### ISSUE TITLE
Quickblox - PrivateChatManager.addPrivateChatManagerListener(this); Is null

### ISSUE THREAD

**Issue by dimitrireef** [QuickBlox/quickblox-android-sdk#101]
privateChatManager.addPrivateChatManagerListener(this); is null when opening a chatbox for the second time from dialog acitvity. A quick workaround was to relogin into the chat and create a new session but the error persist. Can someone help to resolve this issue. While debugging, it was found that QBChatService.getInstance() is initialised but .getPrivateChatManager(); is null.

if(privateChatManager == null){
        privateChatManager =  QBChatService.getInstance().getPrivateChatManager();
        privateChatManager.addPrivateChatManagerListener(this);
    }

The log:

 06-29 10:14:02.335: E/AndroidRuntime(12904): FATAL EXCEPTION: main
    06-29 10:14:02.335: E/AndroidRuntime(12904): java.lang.RuntimeException: Unable to resume activity {com.tchat/com.tchat.quickblox.ChatActivity}: java.lang.NullPointerException
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2828)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2857)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2304)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at android.app.ActivityThread.access$700(ActivityThread.java:154)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at android.os.Handler.dispatchMessage(Handler.java:99)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at android.os.Looper.loop(Looper.java:137)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at android.app.ActivityThread.main(ActivityThread.java:5306)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at java.lang.reflect.Method.invokeNative(Native Method)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at java.lang.reflect.Method.invoke(Method.java:511)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at dalvik.system.NativeStart.main(Native Method)
    06-29 10:14:02.335: E/AndroidRuntime(12904): Caused by: java.lang.NullPointerException
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at com.tchat.quickblox.core.PrivateChatImpl.initManagerIfNeed(PrivateChatImpl.java:54)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at com.tchat.quickblox.core.PrivateChatImpl.<init>(PrivateChatImpl.java:34)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at com.tchat.quickblox.voip.fragment.ChatFragment.initChat(ChatFragment.java:369)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at com.tchat.quickblox.voip.fragment.ChatFragment.onCreateView(ChatFragment.java:106)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at android.app.Fragment.performCreateView(Fragment.java:1699)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:903)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1075)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at android.app.BackStackRecord.run(BackStackRecord.java:682)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1455)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at android.app.Activity.performResume(Activity.java:5344)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2818)
    06-29 10:14:02.335: E/AndroidRuntime(12904):    ... 12 more

**Comment by Simon-Raes** [comment]
I had this happen when I was creating a chat while not logged in yet. Best to build in some extra checks and only create the chat if you're sure you're fully logged in.

**Comment by soulfly** [comment]
This only works after chat login

      privateChatManager = QBChatService.getInstance().getPrivateChatManager();

before chat login the getPrivateChatManager will be returning null always
