### ISSUE TITLE
Hybrid Application: Android error: dex Loader Unable to execute dex: method ID not in [0, 0xffff]: 65536

### ISSUE THREAD

**Issue by SharmilaEsri** [QuickBlox/quickblox-android-sdk#102]
I am developing a hybrid application. Where now currently i am working for android. After i am implementing google sign in, I am calling google play service libraries. I realized that it is calling so much of methods for my application. So it is throwing the below error:
dex Loader Unable to execute dex: method ID not in [0, 0xffff]: 65536

Is there any method to solve this for hybrid application.

i tried the below solutions suggested online:

1) Unchecked private libraries(configured build path). After doing this it is showing: MyApplication has unfortunately stopped.
2) Clean and build the project again and again.

It would be helpful if any of you seeing this problem can suggest something to overcome my problem.

Thanks & Regards,
Sharmila

**Comment by soulfly** [comment]
We split Android SDK some time ago
so now you can use on;y modules you need in your app

http://quickblox.com/developers/Android#Download_Android_SDK
