### ISSUE TITLE
NullPointerException in QBJsonErrorParser

### ISSUE THREAD

**Issue by Simon-Raes** [QuickBlox/quickblox-android-sdk#103]
Occasionally my Android app will crash because of a NullPointerException in the QuickBlox SDK. Checking Fabric, I can see that the crash occurs in the QBJsonErrorParser.parseError() method. 

    com.quickblox.core.parser.QBJsonErrorParser.parseError (QBJsonErrorParser.java:43)
    com.quickblox.core.result.RestResult.processResponse (RestResult.java:84)
    com.quickblox.core.result.RestResult.setResponse (RestResult.java:66)
    com.quickblox.core.parser.QBJsonParser.parse (QBJsonParser.java:76)
    com.quickblox.core.query.Query$VersionEntityCallback.completedWithResponse (Query.java:324)
    com.quickblox.core.query.Query.completedWithResponse (Query.java:250)
    com.quickblox.core.server.HttpRequestRunnable$1.handleMessage (HttpRequestRunnable.java:43)
    android.os.Handler.dispatchMessage (Handler.java:102)
    android.os.Looper.loop (Looper.java:149)
    android.app.ActivityThread.main (ActivityThread.java:5061)
    java.lang.reflect.Method.invokeNative (Method.java)
    dalvik.system.NativeStart.main (NativeStart.java)

Possibly related; at one point I saw this output in my logs, but the app did not seem to crash at that point.

     === REQUEST ==== e160888a-7ab7-4758-9200-c55bc1155232 ===
        REQUEST
        GET https://api.quickblox.com/users.json
        HEADERS
        QuickBlox-REST-API-Version=0.1.1
        QB-SDK=Android 2.2.2
        QB-Token=420f0274651b798c9771606fb131cfa1951e4f6e
        PARAMETERS
        page=0
        per_page=10000
        INLINE
        GET https://api.quickblox.com/users.json?page=0&per_page=10000

     *** RESPONSE *** e160888a-7ab7-4758-9200-c55bc1155232 ***
        STATUS : 502
        HEADERS
        Connection=keep-alive
        Content-Length=173
        Content-Type=text/html
        Date=Fri, 19 Jun 2015 18:00:00 GMT
        Server=nginx/1.0.15
        BODY
        '<html>
        <head><title>502 Bad Gateway</title></head>
        <body bgcolor="white">
        <center><h1>502 Bad Gateway</h1></center>
        <hr><center>nginx/1.0.15</center>
        </body>
        </html>
        '
    06-19 20:00:00.797  32117-32117/com.me.myapp D/QBASDK﹕ Problem has occurred during parsing errors

**Comment by Simon-Raes** [comment]
I found a device/situation where I can reliably reproduce this crash. It happens as soon as I launch my app on a Samsung Galaxy Nexus. The QuickBlox login/session call is immediately started and the app instantly crashes with the following log output.

    06-29 15:54:38.212  11667-11667/com.me.myapp D/QBASDK﹕ =========================================================
    === REQUEST ==== f449d339-fa94-4c13-9886-3508560110eb ===
      REQUEST
       POST https://api.quickblox.com/session.json
       HEADERS
       QuickBlox-REST-API-Version=0.1.1
       QB-SDK=Android 2.2.2
       PARAMETERS
       application_id=[app_id]
       auth_key=[key]
       nonce=346398195
       timestamp=1435586078
       user[login]=[login_here]
       user[password]=[password_here]
       signature=[signature]
       INLINE
       POST https://api.quickblox.com/session.json?application_id=22874&auth_key=eb3a7ydOwfO9Snr&nonce=346398195&timestamp=1435586078&user[login]=[login_here]&user[password]=[password_here]


    06-29 15:54:39.415  11667-11667/com.me.myapp D/QBASDK﹕ *********************************************************
    *** RESPONSE *** f449d339-fa94-4c13-9886-3508560110eb ***
        STATUS : 401
        HEADERS
        Access-Control-Allow-Origin=*
        Cache-Control=no-cache
        Connection=keep-alive
        Content-Type=application/json; charset=utf-8
        Date=Mon, 29 Jun 2015 13:54:38 GMT
        QuickBlox-REST-API-Version=0.1.1
        Server=nginx/1.0.15
        Status=401 Unauthorized
        Transfer-Encoding=chunked
        X-Rack-Cache=invalidate, pass
        X-Request-Id=d678fdb369e956dae462bf36a9bc3ca0
        X-Runtime=0.015044
        X-UA-Compatible=IE=Edge,chrome=1
        BODY
    '{"errors":["Unauthorized"]}'


    06-29 15:54:40.228  11667-11667/com.myapp.me E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.myapp.me, PID: 11667
    java.lang.NullPointerException
            at com.quickblox.core.parser.QBJsonErrorParser.parseError(QBJsonErrorParser.java:43)
            at com.quickblox.core.result.RestResult.processResponse(RestResult.java:84)
            at com.quickblox.core.result.RestResult.setResponse(RestResult.java:66)
            at com.quickblox.core.parser.QBJsonParser.parse(QBJsonParser.java:76)
            at com.quickblox.core.query.Query$VersionEntityCallback.completedWithResponse(Query.java:324)
            at com.quickblox.core.query.Query.completedWithResponse(Query.java:250)
            at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(HttpRequestRunnable.java:43)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5141)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by soulfly** [comment]
per_page is 100 max

can you replace 10000 with 100 and try again

**Comment by Simon-Raes** [comment]
I've replaced the 10000 with 100, but the crash still occurs.

**Comment by soulfly** [comment]
This is fixed in https://github.com/QuickBlox/quickblox-android-sdk/tree/development

will be merged to master soon

**Comment by FisnikIbishi** [comment]
This crash is still happening on 2020
