### ISSUE TITLE
Can't figure out what's the password for a user created using "createSessionUsingSocialProvider"

### ISSUE THREAD

**Issue by eyaldar** [QuickBlox/quickblox-android-sdk#109]
Hi, i'm trying to create a user using createSessionUsingSocialProvider and then using this user to login to QBChatService instance.
but no matter what password I try, I keep getting SASLErrorExcpetion about the details being wrong.

How do you get the password for an social provider user?

P.S

already tried the suggested method here:
http://quickblox.com/developers/Chat#Password

**Comment by soulfly** [comment]
Did you try this?

try {
    user.setPassword(BaseService.getBaseService().getToken());
}catch(BaseServiceException e) {
    e.printStackTrace();  
    // means you have not created a session before 
}

**Comment by eyaldar** [comment]
I tried this method but I keep getting an error about the user or password being wrong.

**Comment by soulfly** [comment]
ok, then please post all code

**Comment by varioous** [comment]
For me above solution worked. But i think that should be fixed or documented.
