### ISSUE TITLE
Does Quick Blox supports one to many (group) video and audio calling facility for android

### ISSUE THREAD

**Issue by kondalaraot** [QuickBlox/quickblox-android-sdk#110]
Hi ,

Does the current version of QuickBlox android SDK supports group audio 
and video calling facility with out any issues as i was able to run the 
test demos with one to one audio/video calling from 
sample-videochat-webrtc-new sample app .

When i am adding support for group video/audio crashing at times and issues in 
JNI libraries seems

can you please let me know whether this QuickBlox android SDK support 
group audio/video calling smoothly?

Thanks,
Kondal

**Comment by soulfly** [comment]
This is under development, will be in our next release
