### ISSUE TITLE
Exception - com.quickblox.core.exception.QBResponseException:

### ISSUE THREAD

**Issue by vinaytumbemane** [QuickBlox/quickblox-android-sdk#111]
com.quickblox.core.exception.QBResponseException: The resource wasn't found,Entity you are looking for was not found. --- dialogId = 558d5b46535c12fdae005343, messageId = 55cc5ee765ea08d7b2400e33

Any one faced this problem

**Comment by soulfly** [comment]
It means you don't have a dialog with id= 558d5b46535c12fdae005343 or a message with id= 55cc5ee765ea08d7b2400e33

so the backend returned http 404 status not found

**Comment by vikashrathore081** [comment]
facing the same issue. Any update

**Comment by QB-nikolay-zolotarov** [comment]
@vikashrathore081 Hello, let's continue the conversation here:
https://github.com/QuickBlox/quickblox-android-sdk/issues/780
