### ISSUE TITLE
Send only audio and Receive audio&video during call

### ISSUE THREAD

**Issue by vinaytumbemane** [QuickBlox/quickblox-android-sdk#112]
When I make a voice call to friend, I want my system to receive both audio and video from my friend. Is it possible to Make such call?
If possible what changes I need to do?
Please any one help me to do this.

**Comment by soulfly** [comment]
which sample are you talking about?

**Comment by vinaytumbemane** [comment]
Q-municate > contacts > friends details > video call
I built this using quickblox-android-sdk.

**Comment by soulfly** [comment]
http://quickblox.com/developers/Sample-webrtc-android#Disable_.2F_enable_audio_stream

http://quickblox.com/developers/Sample-webrtc-android#Disable_.2F_enable_video_stream

you can play with audio/video streams

**Comment by vinaytumbemane** [comment]
Thanks and Regards for the link...
Vinayak
