### ISSUE TITLE
Notice between old and new messages - Android

### ISSUE THREAD

**Issue by dudadayan** [QuickBlox/quickblox-android-sdk#114]
Whenever I'm logging in to QB service, I'm receiving all the messages that were sent to me while QB client was "offline".
All the old messages arrived with <delay> tag, as you can see in the log:
```
D/SMACK﹕ RCV (2): <message type="chat" to="xxxxxxxx-xxxxx@chat.quickblox.com" xmlns="jabber:client" from="xxxxxx-xxxx@chat.quickblox.com/xxxxxxxxxx-quickblox-xxxxx"><composing xmlns="http://jabber.org/protocol/chatstates"/>
<delay from="chat.quickblox.com" xmlns="urn:xmpp:delay" stamp="2015-09-13T06:46:15.465Z">Offline Storage - chat.quickblox.com</delay>
</message>
```

The problem is that i can't get to this <delay> tag and tell it's an old message.
Is there a way to noticed if messages are old?

**Comment by soulfly** [comment]
Try SDK 2.3.1

http://quickblox.com/developers/Android#Framework_changelog

There is QBChatMessage.isDelayed() method

**Comment by dudadayan** [comment]
Thanks for the quick reply, but what about the "typing" messages, currently I can't notice between the new and the old?

Can I disabled the option to save "typing" messages while the user is offline?

**Comment by soulfly** [comment]
yes, will do check this on the backend side

**Comment by dudadayan** [comment]
Thanks!

**Comment by soulfly** [comment]
Deployed, now it should work as you expect
