### ISSUE TITLE
Android studio gradle build dependencies for Quickblox sdk?

### ISSUE THREAD

**Issue by ch-muhammad-adil** [QuickBlox/quickblox-android-sdk#119]
Any way to add gradle build dependencies to integrate quickblox sdk for android studio ? actually I want to integrate your sdk in my project.

**Comment by ch-muhammad-adil** [comment]
Any single line ? 
Instead of doing all this 

compile files('libs/quickblox-android-sdk-chat-2.2.2.jar')
    compile files('libs/quickblox-android-sdk-content-2.2.2.jar')
    compile files('libs/quickblox-android-sdk-core-2.2.2.jar')
    compile files('libs/quickblox-android-sdk-customobjects-2.2.2.jar')
    compile files('libs/quickblox-android-sdk-location-2.2.2.jar')
    compile files('libs/quickblox-android-sdk-messages-2.2.2.jar')
    compile files('libs/quickblox-android-sdk-ratings-2.2.2.jar')
    compile files('libs/quickblox-android-sdk-videochat-2.2.2.jar')
    compile files('libs/quickblox-android-sdk-videochat-webrtc-2.2.2.jar')

**Comment by ch-muhammad-adil** [comment]
I want to integrate chating, video chating and push notifications.

**Comment by soulfly** [comment]
This is a right solution and it works

compile files('libs/quickblox-android-sdk-chat-2.2.2.jar')
compile files('libs/quickblox-android-sdk-content-2.2.2.jar')
compile files('libs/quickblox-android-sdk-core-2.2.2.jar')
compile files('libs/quickblox-android-sdk-customobjects-2.2.2.jar')
compile files('libs/quickblox-android-sdk-location-2.2.2.jar')
compile files('libs/quickblox-android-sdk-messages-2.2.2.jar')
compile files('libs/quickblox-android-sdk-ratings-2.2.2.jar')
compile files('libs/quickblox-android-sdk-videochat-2.2.2.jar')
compile files('libs/quickblox-android-sdk-videochat-webrtc-2.2.2.jar')

More info you can find on our code samples

https://github.com/QuickBlox/quickblox-android-sdk

**Comment by ch-muhammad-adil** [comment]
Too much work but it will be great if you add your sdk in gradle build system.

**Comment by soulfly** [comment]
You mean Maven repository?

**Comment by ch-muhammad-adil** [comment]
yes to public maven repo. compiling it through maven repository will be
easier for developer. Don't you think so ?

Regards,
Muhammad Adil

**Comment by AppHero2** [comment]
@ch-muhammad-adil 
This is reference for  you with this https://github.com/QuickBlox/quickblox-android-sdk
 https://stackoverflow.com/questions/47642490/android-studio-3-0-failed-to-transform-file-gson-2-2-4-jar-to-match-attribu/47800779#47800779
