### ISSUE TITLE
org.apache.http.conn.HttpHostConnectException

### ISSUE THREAD

**Issue by arturEm** [QuickBlox/quickblox-android-sdk#121]
Device is connected to the hotspot (WiFi) and ethernet cable is detached. So, device is connected to the wifi without internet connection.
I send request to api.quickblox.com and Quickblox Android SDK handles exception without giving me an information about that.

Is it possible to handle the exception (below)? Because I'm not able to know that sth went wrong.

Exception:
org.apache.http.conn.HttpHostConnectException: Connection to https://api.quickblox.com refused
....
com.quickblox.core.server.HttpExecutor.execute(HttpExecutor.java:29)
com.quickblox.core.server.HttpRequestRunnable.run(HttpRequestRunnable.java:54)

**Comment by soulfly** [comment]
Hi, 

could you please post your code, will double check 
in general this should work as you expect

**Comment by arturEm** [comment]
> QBDialog dialog = new QBDialog();
>       dialog.setName(name);
>        dialog.setType(QBDialogType.GROUP);
>        dialog.setOccupantsIds(occupantIdsList);
>
>        QBGroupChatManager groupChatManager = QBChatService.getInstance().getGroupChatManager();
        groupChatManager.createDialog(dialog, new QBEntityCallbackImpl<QBDialog>() {
            @Override
            public void onSuccess(QBDialog dialog, Bundle args) {
              
>            }
>
>            @Override
>            public void onError(List<String> errors) {
>                Log.d("dialog error " + errors);
                
>            }
>        });

SDK handles exception but onError is not called.

**Comment by soulfly** [comment]
Thanks, 
I have created an issue in our tracking system, 
will get back to you once we have more information

**Comment by soulfly** [comment]
Fixed on 2.5 SDK version
