### ISSUE TITLE
"Exception: Expected a string but was BEGIN_OBJECT" when retrieving coordinate points

### ISSUE THREAD

**Issue by regmoraes** [QuickBlox/quickblox-android-sdk#122]
I'm trying to retrieve the coordinate points of a Location type data that was stored as a custom parameter of a QBDialog. Here's how I'm creating the dialogues:

   ```java
    final String myLocation = Double.toString(locationManager.getLastLocation().getLatitude())+","+
            Double.toString(locationManager.getLastLocation().getLongitude());

        Map<String,String> customParameters = new HashMap<>();
        customParameters.put("data[class_name]", "JsRoom");
        customParameters.put("data[room_location]", myLocation);

        final QBDialog qbDialog = new QBDialog();
        qbDialog.setName("Test");
        qbDialog.setType(QBDialogType.GROUP);
        qbDialog.setData(customParameters);

        QBChatService.getInstance().getGroupChatManager().createDialog(qbDialog,
                new QBEntityCallbackImpl<QBDialog>() {   /*...*/   }
```        

This is how I'm retrieving the saved dialogues:

```java
Double myLocation[] = {locationManager.getLastLocation().getLatitude(),
                locationManager.getLastLocation().getLongitude()};

        final QBRequestGetBuilder requestBuilder = new QBRequestGetBuilder();
        requestBuilder.setPagesLimit(5);
        requestBuilder.near("data[room_location]",myLocation,NEARBY_ROOMS_DISTANCE);

        QBChatService.getChatDialogs(QBDialogType.GROUP, requestBuilder,
                new QBEntityCallbackImpl<ArrayList<QBDialog>>() {     /* ... */    }
```

When the `QBChatService.getChatDialogs()` method is called, I receive this **RESPONSE BODY**:

```json
'{"total_entries":1,"skip":0,"limit":5,"items":[{"_id":"5648a40aa0eb47b1fd00037e","created_at":"2015-11-15T15:26:02Z","data":{"_qb_location":{"type":"Point","coordinates":[-22.7193467,-42.6158365]},"class_name":"JsRoom"},"last_message":null,"last_message_date_sent":null,"last_message_user_id":null,"name":"Test","occupants_ids":[6810171],"photo":null,"silent_ids":[],"type":2,"updated_at":"2015-11-15T15:26:02Z","user_id":6810171,"xmpp_room_jid":"28632_5648a40aa0eb47b1fd00037e@muc.chat.quickblox.com","unread_messages_count":0}]}'
```
The problem is that right after receive this response, the "onError()" method of the request is called and throws this Exception:

```java
"[java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 142]"
```
How can I avoid this Exception and retrieve the coordinate points?

**Comment by soulfly** [comment]
Hi there, thanks for reporting this, 
I have created an issue in our tracking system, 
will get back to you once we have more information

**Comment by regmoraes** [comment]
No solutions yet?

**Comment by soulfly** [comment]
The fix will be a part of our next release

**Comment by regmoraes** [comment]
I updated the SDK to 2.5.1 and the issue has been solved! But now I'm having another problem: When I try to retrieve the Location data from the Dialog, it always returns null. Here's what I'm doing:

**Creating the dialog and set a location custom data**

    List<Double> myLocation = new ArrayList<>();
        myLocation.add(locationManager.getLastLocation().getLatitude());
        myLocation.add(locationManager.getLastLocation().getLongitude());

        QBDialogCustomData data = new QBDialogCustomData("JsRoom");
        data.putLocation("room_location", myLocation);

        //TODO change generated room name and add other users
        final QBDialog qbDialog = new QBDialog();
        qbDialog.setName("Test");
        qbDialog.setType(QBDialogType.GROUP);
        qbDialog.setCustomData(data);

        QBChatService.getInstance().getGroupChatManager().createDialog(qbDialog,
                new QBEntityCallback<QBDialog>() {/* ... */}

**Retrieving the dialogs**

    Double myLocation[] = {mLastLocation.getLatitude(), mLastLocation.getLongitude()};

        final QBRequestGetBuilder requestBuilder = new QBRequestGetBuilder();
        requestBuilder.setLimit(10);
        requestBuilder.near("data[room_location]", myLocation, NEARBY_ROOMS_DISTANCE);

        QBChatService.getChatDialogs(QBDialogType.GROUP, requestBuilder,
                new QBEntityCallback<ArrayList<QBDialog>>() {/* ... */}

When the QBChatService.getChatDialogs() method is called, I'm receiving this RESPONSE BODY:

    '{"total_entries":1,"skip":0,"limit":10,"items":[{"_id":"56e19ddea0eb4763010000ab","created_at":"2016-03-10T16:16:30Z","data":{"_qb_location":{"type":"Point","coordinates":[-22.5021777,-41.9247733]},"class_name":"JsRoom"},"last_message":null,"last_message_date_sent":null,"last_message_user_id":null,"name":"Test","occupants_ids":[10710573],"photo":null,"silent_ids":[],"type":2,"updated_at":"2016-03-10T16:16:30Z","user_id":10710573,"xmpp_room_jid":"28632_56e19ddea0eb4763010000ab@muc.chat.quickblox.com","unread_messages_count":0}]}'

**Getting the location data in the retrieved dialogs**

    List<Double> roomLocation;

        for (QBDialog room : rooms) {

            roomLocation = room.getCustomData().getLocation("room_location");

            mGoogleMap.addMarker(new MarkerOptions()
                    .position(new LatLng(roomLocation.get(0),roomLocation.get(1)))
                    .snippet(Integer.toString(room.getOccupants().size()))
                    .title(room.getName()))
                    .setIcon(BitmapDescriptorFactory.defaultMarker(BitmapDescriptorFactory.HUE_AZURE));
        }


When executing `roomLocation = room.getCustomData().getLocation("room_location");` I'm getting this error: 

**java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference**

This error there's something to do with the fact that the location is been stored as **_qb_location** and not as **room_location** ?

**Comment by regmoraes** [comment]
As this issue was solved, I'll close it and open another one specific to these new errors.
