### ISSUE TITLE
quickblox-android-sdk-videochat-webrtc-2.4: java.lang.NoSuchMethodError: No static method registerComplexPropertyParser

### ISSUE THREAD

**Issue by deeprathod** [QuickBlox/quickblox-android-sdk#124]
java.lang.NoSuchMethodError: No static method registerComplexPropertyParser(Ljava/lang/String;Lcom/quickblox/chat/propertyparsers/MessagePropertyParser;)V in class Lcom/quickblox/chat/model/QBChatMessageExtension; or its super classes (declaration of 'com.quickblox.chat.model.QBChatMessageExtension' appears in /data/app/xxx.xxx.xxx-2/base.apk)

**Comment by deeprathod** [comment]
@soulfly  any help ? i am stuck here from 5 days. I am unaware whats the issue here.
![screen shot 2015-12-26 at 12 39 40 pm](https://cloud.githubusercontent.com/assets/5393673/12005495/cd984058-abcd-11e5-93d9-dafb78b439a6.png)

**Comment by deeprathod** [comment]
Hello, 

The below screenshot contains the error message, it arises at QBRTCSession. I guess its some library issue. However i even tried using 2.5 jar version however its throwing me the same error. @soulfly Please if you can help me with the same. 

![screen shot 2015-12-26 at 12 42 19 pm](https://cloud.githubusercontent.com/assets/5393673/12005502/2ca7b4de-abce-11e5-9f32-560bcbd70d81.png)

**Comment by soulfly** [comment]
Hi there, 

do you use the same version of all jars?

**Comment by deeprathod** [comment]
HI @soulfly  

merry xmas, no i am not using all the JAR's of same version. @soulfly Should i use all the jars of same version that is 2.4 ?

Thank You

**Comment by deeprathod** [comment]
![screen shot 2015-12-28 at 2 28 28 pm](https://cloud.githubusercontent.com/assets/5393673/12016344/a432df72-ad6f-11e5-85a2-b4ddb4a17f30.png)
Here are the list of dependencies which i am using.

**Comment by soulfly** [comment]
hey @deeprathod , merry xmas too!

Yes, you should use the same version of all jars in one project

**Comment by deeprathod** [comment]
@soulfly  

Thanks, let me try the same and update you :) Thanks a lot.

**Comment by deeprathod** [comment]
@soulfly  

It worked. Thanks a lot. :+1:
