### ISSUE TITLE
Effectively track message dilevery and read status

### ISSUE THREAD

**Issue by laylizzlle** [QuickBlox/quickblox-android-sdk#125]
I want to track the delivery and read status of my chat messages and the methods you have provided in your samples doesn't seem to work for me.
1.) Inside the onCreate method in my ChatActivity

    messageStatusesManager = QBChatService.getInstance().getMessageStatusesManager();
        messageStatusListener = new QBMessageStatusListener() {
            @Override
            public void processMessageDelivered(String messageId, String dialogId, Integer userId) {
                Log.v("NorrisTestQB","delivered messageid "+messageId+" dialogid "+dialogId+" userid "+userId);
            }

            @Override
            public void processMessageRead(String messageId, String dialogId, Integer userId) {
                Log.v("NorrisTestQB","read messageid "+messageId+" dialogid "+dialogId+" userid "+userId);
            }
        };
        messageStatusesManager.addMessageStatusListener(messageStatusListener);

2.)Calling this method after a successful login:

    public void initMessageStatusManagerAndListener(){
        messageStatusesManager = chatService.getMessageStatusesManager();

        messageStatusListener = new QBMessageStatusListener() {
            @Override
            public void processMessageDelivered(String messageId, String dialogId, Integer userId) {
                Log.v("Norristestdilevered","message delivered: "+context.getClass().getSimpleName()+"  " + messageId + " to user " + userId
                        + ". DialogId: " + dialogId);
            }

            @Override
            public void processMessageRead(String messageId, String dialogId, Integer userId) {
                Log.v("Norristestread", "message read: " + messageId + " to user " + userId
                        + ". DialogId: " + dialogId);
            }
        };

Any form of help will be really grateful.

**Comment by soulfly** [comment]
That's correct

can you show how you send messages

**Comment by laylizzlle** [comment]
For some reason it's started working again.....Thank you

**Comment by gagan50** [comment]
QBChatMessage msg = new QBChatMessage();
            msg.setBody("Hello");
            msg.setSenderId(qbChatDialog.getUserId());
            msg.setRecipientId(Integer.valueOf(userModel.getId()));

            msg.setProperty("save_to_history", "1");
            msg.setDateSent(System.currentTimeMillis() / 1000);
            msg.setSaveToHistory(true);
            msg.setMarkable(true);

            boolean sendToDialog = true; 
            QBRestChatService.createMessage(msg, sendToDialog).performAsync(new QBEntityCallback<QBChatMessage>() {
                @Override
                public void onSuccess(QBChatMessage message, Bundle bundle) {
                    Log.e("messageonSuccess>>", message.getId() + "" + message.getSmackMessage());

                  
                }

                @Override
                public void onError(QBResponseException e) {
                    Log.e("onError", e.getHttpStatusCode() + " " + e.getMessage());
                }
            });








please let me know how can i get read status

**Comment by hamzagrepruby** [comment]
How do I use the listener to change the layouts in the adapter when the message has been delivered or read ?
