### ISSUE TITLE
owner delete group dialog

### ISSUE THREAD

**Issue by qzaqza1818** [QuickBlox/quickblox-android-sdk#128]
I had search through your API documentation and I found that pass force=1 to delete a dialog completely. There is no example for android. May I ask you what is the solution?

**Comment by soulfly** [comment]
This will be available in our upcoming release 2.5 next week

**Comment by qzaqza1818** [comment]
Thank you. May I know where to find out what changes and updates such as functions become deprecate for 2.5?

**Comment by soulfly** [comment]
You will find in here

https://quickblox.com/developers/Android#Framework_changelog

also track our blog https://quickblox.com/blog

**Comment by qzaqza1818** [comment]
thank you
