### ISSUE TITLE
Store dialogue and chat messages in local database for offline 

### ISSUE THREAD

**Issue by chiragdigi** [QuickBlox/quickblox-android-sdk#129]
I want to store dialogue and chat message and history in my device local database.
How can i achieve this? can QB provide any inbuilt class or method to store in local memory and retrieve form it?

**Comment by soulfly** [comment]
We  don't have it right now out of the box

You can build it by yourself using SQL Databases guide
http://developer.android.com/training/basics/data-storage/databases.html

Also there is more ready but maybe harder to reuse way - Q-municate src code
https://github.com/QuickBlox/q-municate-android/tree/master/Q-municate_core/src/main/java/com/quickblox/q_municate_core/db

**Comment by moonandroid** [comment]
If i'll store in SQLite then how to display whole offline conversion at chat screen ?

**Comment by RomanPronin** [comment]
As says above look at [Q-mun](https://quickblox.com/developers/Q-municate)
Long time inactivity

**Comment by rishabhtech1994** [comment]
Hello, 
Can anyone help me regarding the QuickBlox local Database storage procedure as Q-municate is a bit difficult to decode. 
Or if QuickBlox provide any local storage facilities for Android????
If any one is into it please try to help
