### ISSUE TITLE
Screen Sharing or Image sending over VideoChat instead using Camera

### ISSUE THREAD

**Issue by cirorizzo** [QuickBlox/quickblox-android-sdk#130]
I didn't find any reference to have screen sharing or sending any other streaming over VideoChat in Android like in iOS SDK.  Is there any other way to have this feature or having QBRTCCameraCapture or QRBTCScreenCapture on Android SDK?

**Comment by soulfly** [comment]
This is in our roadmap to integrate Screen Sharing feature.
ETA is 1st quarter of 2016.

**Comment by rkumawat** [comment]
Hi Soulfly, I am also want this screen sharing feature. Can you please let me know when sharing screen feature will be available in android SDK. So I can plan my application release accordingly.

**Comment by amankajaria** [comment]
Hi Soulfly, has the screen sharing feature been implemented for Android ? We need it asap. Thanks.

**Comment by antoescu** [comment]
Hi @soulfly, any update on this topic? We would like to have same functionality on Android than we have on iOS. Thanks!

**Comment by vfite** [comment]
Hi there. 
ETA for Screen Sharing is the last quarter of 2016.

**Comment by vfite** [comment]
Hi there.
Screen sharing is available from 3.3.0 version.
Have a look sample-video-chat and doc: http://quickblox.com/developers/Sample-webrtc-android#Screen_sharing
