### ISSUE TITLE
Cannot login to chat service in devices like micromax(Android V4.2,V4.4,V5.0),Sony C4(V4.4),Honor Holly(V4.4) etc...

### ISSUE THREAD

**Issue by testabrj** [QuickBlox/quickblox-android-sdk#136]
When I try to login to quickblox chat service(with my own quickblox credentials) code in the above devices, after login to quickblox, chat service login attempt is showing  "getting result from proxy >>>" and failed always in Micromax devices saying "connection failed, check your internet connection(eventhough I am connected!)" and is showing just "exception", "quitting","bye" messages in other devices.Even I have tried with quickblox own sample code with my credentials(Not working in the above mentioned devices.

However, It is working fine and I have implemented group and private chat in devices like motog2(V5.0) and Redmi note 4g(V4.4).All the devices we have logged in to Google play services.Let me know what could be the issue.

**Comment by soulfly** [comment]
Can you post the full log from that device from Android Studio 

Also, can you check the 5222 port of chat.quickblox.com from that device - available or not

**Comment by testabrj** [comment]
you're right, I think the port 5222 is not available, In this case what should I do, how can I enable this programmatically?

**Comment by soulfly** [comment]
Can you list which ports are opened OR blocked in your network?

**Comment by testabrj** [comment]
As of now what I know is No ports are blocked in my network, which means all the ports are opened let me know if you still need the list of open ports?

**Comment by testabrj** [comment]
I tried this reading another issue posted here, like "telnet chat.quickblox.com 5222" and its giving me Trying 54.175.230.12...
Connected to chat.quickblox.com, so now I am wondering whether this is issue related to port. Any hints would be great!

**Comment by tatanka987** [comment]
Closed for long inactivity.
