### ISSUE TITLE
Send push notification to all members of a public group chat

### ISSUE THREAD

**Issue by laylizzlle** [QuickBlox/quickblox-android-sdk#137]
Was doing some digging and found out getOccupants don't work with public group chat because its created dynamically. My app has public chat rooms and was wondering how to send push notifications to all the member who has joined the group when someone posts a message.Thank you.

**Comment by soulfly** [comment]
you can list online users in group chat
http://quickblox.com/developers/Android_XMPP_Chat_Sample#Get_online_users

and then send a push to them
http://quickblox.com/developers/SimpleSample-messages_users-android

**Comment by laylizzlle** [comment]
thanks
