### ISSUE TITLE
Gradle Build problem

### ISSUE THREAD

**Issue by Lordwales** [QuickBlox/quickblox-android-sdk#141]
All the sample chats produce **Error:No cached version listing for io.fabric.tools:gradle:1.+ available for offline mode.** and when i unchecked the offline mode and build with default gradle wrapper,gradle build gets stucked at  "refreshing sample chat gradle project'.Please can anyone help me out here. @soulfly

**Comment by ingerul93** [comment]
This problem is from your gradle files.

**Comment by soulfly** [comment]
I guess it's resolved, so closing it
