### ISSUE TITLE
Grayscale image

### ISSUE THREAD

**Issue by ingerul93** [QuickBlox/quickblox-android-sdk#143]
![screenshot 3](https://cloud.githubusercontent.com/assets/8235301/13291173/68506e4c-db1f-11e5-89a3-a77f906476e8.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/8235301/13291174/68571bf2-db1f-11e5-92f9-faabe9e3fb2a.png)

Captured image is grayscale on my device. This problem seems to appear on 2.3,2.4 and 2.5 sdk version(on older version i can't test). My android version is 4.0.4. Why? How can I fix this?

**Comment by vfite** [comment]
Is this issue reproduced on our sample? Could you specify your devices and steps? It it remote video or your own ? Provide please logs during call & capturing image.

**Comment by ingerul93** [comment]
Yes is reproduced in your sample. My device is Moverio BT-2000. This happens in my view.

**Comment by ingerul93** [comment]
here is a logcat : http://pastebin.com/3nsBerna

**Comment by Souhayeb** [comment]
Any solution ? My device is Moverio BT-2000 too

**Comment by ingerul93** [comment]
@Souhayeb Do you have an Android device with 4.0.4?

**Comment by Souhayeb** [comment]
Yes it's the Moverio BT-200

**Comment by ingerul93** [comment]
Another than Moverio devices.

**Comment by Souhayeb** [comment]
yes and it's a oneplus and it's work fine with it

**Comment by ingerul93** [comment]
ok. Are the images colored?

**Comment by Souhayeb** [comment]
yes

**Comment by ingerul93** [comment]
I don't have other devices to test. I was thinking the problem is android version. Now it's clear for me. The problem is QB SDK. Maybe the libjingle library can be the problem.

**Comment by Souhayeb** [comment]
for me i was thinking that maybe it's the Moverick camera problem, i tried every possible configuration for the camera and still the same problem

**Comment by ingerul93** [comment]
I understood. Maybe the camera is poor quality.

**Comment by Souhayeb** [comment]
@ingerul93 we need to use NV21 Imageformat instead of YV12 Imageformat to make the camera work normally,  but i don't know how

**Comment by ingerul93** [comment]
I don't think so. The Moverio's camera is the problem.

**Comment by ingerul93** [comment]
So...solution? :\

**Comment by Souhayeb** [comment]
i' didn't find any solution yet for that problem, i decide to wait for the moverio bt 300 which has a better camera and android version 5.1

**Comment by ingerul93** [comment]
ok. understood. i don't know what to say but moverio released this glasses with some problem. i think the bt 300 will be the same with this models.

**Comment by Souhayeb** [comment]
yes i have already tested the bt 2000 same problem, quickblox need also to update their sdk and provide more video codec

**Comment by ingerul93** [comment]
i hope this.

**Comment by ingerul93** [comment]
@vfite some good news?

**Comment by Vol-i** [comment]
Any news from that issue?

**Comment by alexanderkoqb** [comment]
Hi @ingerul93,
Since it's been a while and if you're still being experiencing troubles with the newer SDK versions,  you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
