### ISSUE TITLE
Best video call configuration

### ISSUE THREAD

**Issue by norrisboat** [QuickBlox/quickblox-android-sdk#145]
Am using the sample webrtc to test the video call on quickblox and the video quality wasn't all that clear. I later realized there are some settings and changed the resolution to HD(1280 \* 720) and didn't see any improvement. Is there something else i have to do to make the videos clearer? I want the best quality in my app and was wondering how to make this happen.

**Comment by pelipetsaa** [comment]
Hello @laylizzlle !
How you changed the resolution to HD(1280 * 720)?
Did you set width and hight for preview?
            intent.putExtra(CallActivity.EXTRA_VIDEO_WIDTH, videoWidth);
            intent.putExtra(CallActivity.EXTRA_VIDEO_HEIGHT, videoHeight);

**Comment by laylizzlle** [comment]
@pelipetsaa 
    
    for (QBRTCMediaConfig.VideoQuality quality : QBRTCMediaConfig.VideoQuality.values()) {
            if (quality.ordinal() == resolutionItem) {
                QBRTCMediaConfig.setVideoHeight(quality.height);
                QBRTCMediaConfig.setVideoWidth(quality.width);

            }
        }

    /**
        * resolution item values
        * Default = -1
        * HD (1280 x 720) = 0
        * VGA (640 x 480) = 1
        * QVGA (320 x 240) = 2 
    */

**Comment by alexanderkoqb** [comment]
Hey!
Since it's been a while and if you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Bset!
