### ISSUE TITLE
Show image in the chat adapter

### ISSUE THREAD

**Issue by darkovski88** [QuickBlox/quickblox-android-sdk#147]
Hello,
this is not actually a issue, but im strugling to add the option of sharing images in the ChatAdapter in sample chat. My question is is there a sample of ChatAdapter for sharing photos(images) inside of the chat? 

Thanks

**Comment by l3lackjack** [comment]
Please answer.

**Comment by RomanPronin** [comment]
For sharing images use message with [attachment](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Send_and_receive_a_message_with_attachment)
