### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by Souhayeb** [QuickBlox/quickblox-android-sdk#148]
I receive a black and white image with video chat
anyone has ever had this problem?

**Comment by ingerul93** [comment]
I have same problem. Issue #143

**Comment by alexanderkoqb** [comment]
Hi @Souhayeb Souhayeb
Since it's been a while and if you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
