### ISSUE TITLE
Any chat message listener

### ISSUE THREAD

**Issue by marta-rodriguez** [QuickBlox/quickblox-android-sdk#149]
Hi,

I have almost integrated quickblox inside my app but I need to receive new messages while the user is navigating in my app but outside any chat, for example, if the user is in the chat list screen and it receives a new message I need to show the new message in the screen like any other messaging app. How can set a listener to receive any message?

My iOS coworker has implemented the QBChatDelegate for private chats and he has a "for" to join each group chat to be able to receive new messages.
I don't think that joining each chat is the correct way to achieve this. I think that it should be more effective way.

Here the iOS code example.

```
extension ListConversationsQuickBloxRepository: QBChatDelegate {
    func chatDidReceiveMessage(message: QBChatMessage) {
        self.proceesNewMessage(message)
    }

    func chatRoomDidReceiveMessage(message: QBChatMessage, fromDialogID dialogID: String) {
        self.proceesNewMessage(message)
    }

    func chatDidConnect() {
        for dialog in self.dialogs {
            if dialog.isJoined() == false {
                dialog.joinWithCompletionBlock({ (error: NSError?) -> Void in
                    if error != nil {
                        NSLog("%@", (error?.description)!)
                    }
                })
            }

        }
    }
}
```

Thanks!

**Comment by tatanka987** [comment]
Use latest version of QuickBlox Android SDK https://quickblox.com/developers/Android
Closed for long inactivity.
