### ISSUE TITLE
How to get Best Video Quality with QB SDK (2.5)?

### ISSUE THREAD

**Issue by gstream** [QuickBlox/quickblox-android-sdk#151]
I want to get best video quality for our enterprise app.
But current video quality is not great (seems okay).
How can I do it ?

**Comment by katiatereshchenkova** [comment]
Hi! 
Our SDK provides the next Media configuration -  http://quickblox.com/developers/Sample-webrtc-android#Media_configuration 
How to use it you can see here -  https://github.com/QuickBlox/quickblox-android-sdk/tree / master / sample-videochat-webrtc

**Comment by laylizzlle** [comment]
But which of the configurations give the best quality

**Comment by gstream** [comment]
I have same question with laylizzlle.
Which of the configurations gives the best quality?

**Comment by gstream** [comment]
I have good video quality between same OS (ios-ios, android-android).
But not so good when make video call between different os (ios-android, android-ios).

Is there any solution?

**Comment by gstream** [comment]
@parvinderatpercept ,  What issues did you face with integrating Quickblox?

**Comment by parvinderatpercept** [comment]
@gstream : not getting where to start n all ,please if you could guide something ,I would be very thankful to you

**Comment by laylizzlle** [comment]
@parvinderatpercept where to start concerting webrtc or quickblox in general

**Comment by alexanderkoqb** [comment]
Hi again @gstream 
Closing the ticket as old.
If you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
