### ISSUE TITLE
Errors when saving and retrieving Location, Latitude and Longitude, as a Custom Parameters of the QBDialog 

### ISSUE THREAD

**Issue by regmoraes** [QuickBlox/quickblox-android-sdk#152]
I'm getting two erros in two different scenarios

1. I created a Custom Object ( with the Quickblox Dashboard ) with **class_name** _JsRoom_ and **field** _room_location_ of type **Location**. When I create a location ( List<Double> with latitude and longitude) in my app and save it to a QBDialog as a Custom Parameter using the `data.putLocation("room_location", location)` the location data is saved to the dialog custom parameters with field name **_qb_location** ( wich have two objects: type and coordinates), so when I try to get the location data back by calling the `room.getCustomData().getLocation("room_location")`, it always returns me null . 

2.I created a Custom Object ( with the Quickblox Dashboard ) with **class_name** _JsRoom_ and **field** _room_location_ of type **Array String** . When I create a location ( List<Double> with latitude and longitude) in my app and save it to a QBDialog as a Custom Parameter using the `data.putLocation(location)` the location data are saved correctly but when I try to get the location data back by calling the `room.getCustomData().getLocation("room_location")`, I get a                                                            **java.lang.NumberFormatException: Invalid double: "[-22.5021873"**  error. This error also occur if, instead of an Array of String, I use an Array of Float.

**Comment by regmoraes** [comment]
I changed the _room_location_ type to **String** at the Quickblox Dashboard, and now I'm getting this error when trying to get the location values by calling `room.getCustomData().getLocation("room_location")`:

    java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
         at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
         at java.util.ArrayList.set(ArrayList.java:481)
         at com.quickblox.core.model.QBBaseCustomObject.getLocation(QBBaseCustomObject.java:291)

Maybe it's something wrong with the Quickblox SDK during creation of the Array that returns the location values.

**Comment by katiatereshchenkova** [comment]
We've fixed this issue. It will be in the next release next week

**Comment by regmoraes** [comment]
Thanks @katiatereshchenkova !

**Comment by soulfly** [comment]
It's fixed now on the backend

**Comment by regmoraes** [comment]
When the fix will be released?
