### ISSUE TITLE
message not receiving while using SetProperty()

### ISSUE THREAD

**Issue by ahmadmiraj** [QuickBlox/quickblox-android-sdk#153]
I am trying to send some parameters with chat using set property . when i use to set property and send the message, message not received to the other device. when i remove the set property message successfully delivered to other device. Help me out what i am doing wrong and do i have to integrate other things to to receive data ??

**Comment by soulfly** [comment]
please provide your code how you do it and what parameters you send

**Comment by ahmadmiraj** [comment]
okay here is my code !

**Comment by ahmadmiraj** [comment]
QBChatMessage chatMessage = new QBChatMessage();
                    chatMessage.setBody("Camera");
                    chatMessage.setMarkable(true);
                    chatMessage.setProperty(PROPERTY_SAVE_TO_HISTORY, "1");
                    chatMessage.setDateSent(new Date().getTime() / 1000);
chatMessage.setProperty("MessageType","1");
chat.sendMessage(chatMessage);

and message is not received in this message

@Override
    public void processMessage(QBPrivateChat chat, QBChatMessage message) {
        Log.w(TAG, "new incoming message: " + message);
        Log.e("recieving message", message.getId() + " ");
//        FragmentChatDetails.qbChatMessages.add(message);
//        FragmentChatDetails.adapter.notifyDataSetChanged();
//        FragmentChatDetails.listView.setSelection(FragmentChatDetails.adapter.getCount()-1);
        chatActivity.ShowMessage(message);
        if(message.isMarkable()){
            try {
                privateChat.readMessage(message);
            } catch (XMPPException e) {

            } catch (SmackException.NotConnectedException e) {

            }
        }
    }

**Comment by soulfly** [comment]
Is it about "MessageType" property?

**Comment by ahmadmiraj** [comment]
i have set MessageType, Url, Latlong and some other tags in setProperty for a message.

Date: Fri, 1 Apr 2016 04:24:37 -0700

**Comment by tatanka987** [comment]
Use latest version of QuickBlox Android SDK https://quickblox.com/developers/Android
Closed for long inactivity.
