### ISSUE TITLE
PUSH notifications delivery issue

### ISSUE THREAD

**Issue by ppilip** [QuickBlox/quickblox-android-sdk#154]
Hi,

I've got an issue with the PUSH notifications. Here's what's happening:
- I register two devices:
*registration_id_1* = APA91bF00Aox8HXsK....
*registration_id_2* = APA91bH7qWBZ0aWg....

- I send PUSH from DEVICE_1 to DEVICE_2 but no push is received.
- I check the push QUEUE log in admin panel, there i find push status SENT with this message in pop-up dialog: 
**GCM (Android Push) Delivered: 0, failed: 0
Event log
...queued 1 notifications**

- when I download detailed log, inside I find this:

```
{
  "notification": {
    "registration_ids": [
      "APA91bH7qWBZ0aWg..."
           ],
    "delay_while_idle": false,
    "data": {
      "message": "{\"alert\":\"Whatever"
    },
    "time_to_live": 86400
  },
  "log": [
    {
      "device_token": null,
      "created_at": "2016-03-15T03:17:01Z",
      "delivered_at": null,
      "failed_at": null,
      "error_code": null,
      "error_description": null
    }
  ]
}
```

Could someone demystify for me what am I doing wrong here?

Thanks.

**Comment by RomanPronin** [comment]
Hi, you may to check the next:  GCM_SENDER_ID in Android application. It should match GCM certificate and number of Google Api project. 
Refer to this http://quickblox.com/developers/SimpleSample-messages_users-android#Setup_GCM . Next please check if the subscription is for the user you send push to Admin panel -> Push Notifications - >  Subscriptions. You may also check it for specific user Admin panel -> Users - > "your" user  ->   Just below  the "Tags" is the list of subscriptions. And at last you can to send push from Admin Panel - > Push notifications - > Send.  http://quickblox.com/developers/SimpleSample-messages_users-android#Send_Push_Notifications_from_Admin_panel. Good Luck!

**Comment by vinayjoglekar** [comment]
@RomanPronin I am facing same issue. Checked reference you have provided.Users are getting subscribed. Can you please help me to solve it?

**Comment by Faizan2112** [comment]
same issue here .. in subscription tab i have two members in table .. i am recicving notification from fcm console but not from qbconsloe

**Comment by pumatus** [comment]
我真是服了，写出来的demo通知都不能正常接收消息，
