### ISSUE TITLE
UserID in Object QbDialog = null

### ISSUE THREAD

**Issue by tuanhs66** [QuickBlox/quickblox-android-sdk#155]
Dear,

I want to add, delete User and edit information in Group-Dialog but in the field UserID(in Object Dialog QB) returns null. Can not know who is administrator ==> return message: "{"errors":["You don't have appropriate permissions to perform this operation"]}".

P/s: Please help me this problem.
Thanks!

**Comment by tatanka987** [comment]
Use latest version of QuickBlox Android SDK https://quickblox.com/developers/Android
Closed for long inactivity.
