### ISSUE TITLE
After onLocalVideoTrackReceive method fire happens Fatal signal 6

### ISSUE THREAD

**Issue by AlexandroKurchenko** [QuickBlox/quickblox-android-sdk#156]
Hi , after some time testing i am find som terrible issue Fatal Signal 6 (SIGABRT), code -6 in tid 8288 (Thread-14723), this is very bad and must be fixed ASAP, i hope.)
Its happens when i am  accept new call from LG nexus 4  on Samsung galaxy S4. 
here is error code:
`03-21 16:53:02.596 6766-8282/com.wonderslab.camcrush E/VideoCallFragment: onLocalVideoTrackReceive{name=Frank Connecticut, filter=empty, gender=Male, birthday=08/08/1960, likes=3, id=facebook-106272806425690}
03-21 16:53:02.596 6766-8282/com.wonderslab.camcrush I/RTCGLVideoView: obtainVideoRenderer
03-21 16:53:02.596 6766-8282/com.wonderslab.camcrush I/RTCGLVideoView: obtainMainVideoRenderer
03-21 16:53:02.596 6766-8301/com.wonderslab.camcrush D/AppRTCAudioManager: Android SDK: 21, Release: 5.0.1, Brand: samsung, Device: ja3g, Id: LRX22C, Hardware: universal5410, Manufacturer: samsung, Model: GT-I9500, Product: ja3gxx
03-21 16:53:02.621 6766-8343/com.wonderslab.camcrush W/CameraBase: An error occurred while connecting to camera: 1
03-21 16:53:02.626 6766-8289/com.wonderslab.camcrush D/RTCClient.QBPeerChannel.PCObserver:: onRenegotiationNeeded
03-21 16:53:02.636 6766-8343/com.wonderslab.camcrush E/VideoCapturerAndroid: startCapture failed
                                                                             java.lang.RuntimeException: Fail to connect to camera service
                                                                                 at android.hardware.Camera.<init>(Camera.java:545)
                                                                                 at android.hardware.Camera.open(Camera.java:385)
                                                                                 at org.webrtc.VideoCapturerAndroid.startCaptureOnCameraThread(VideoCapturerAndroid.java:491)
                                                                                 at org.webrtc.VideoCapturerAndroid.access$800(VideoCapturerAndroid.java:75)
                                                                                 at org.webrtc.VideoCapturerAndroid$4.run(VideoCapturerAndroid.java:477)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:145)
                                                                                 at org.webrtc.VideoCapturerAndroid$CameraThread.run(VideoCapturerAndroid.java:444)
03-21 16:53:02.636 6766-8343/com.wonderslab.camcrush D/VideoCapturerAndroid: stopCaptureOnCameraThread
03-21 16:53:02.661 6766-8289/com.wonderslab.camcrush D/RTCClient.QBPeerChannel.PCObserver:: onSignalingChange to HAVE_REMOTE_OFFER
03-21 16:53:02.666 6766-8289/com.wonderslab.camcrush D/RTCClient.QBPeerChannel.PCObserver:: onAddStream
03-21 16:53:02.666 6766-8289/com.wonderslab.camcrush D/RTCClient.LooperExecutor: Request Looper execute.
03-21 16:53:02.666 6766-8289/com.wonderslab.camcrush D/RTCClient.LooperExecutor: POST.Run on thread:14721 for QBPeerChannel
03-21 16:53:02.671 6766-8289/com.wonderslab.camcrush D/RTCClient.QBPeerChannel.SDPObserver:: onSetSuccess
03-21 16:53:02.671 6766-8289/com.wonderslab.camcrush D/RTCClient.LooperExecutor: Request Looper execute.
03-21 16:53:02.671 6766-8289/com.wonderslab.camcrush D/RTCClient.LooperExecutor: POST.Run on thread:14721 for QBPeerChannel
03-21 16:53:02.671 6766-8287/com.wonderslab.camcrush D/RTCClient.QBPeerChannel.PCObserver:: set remote stream TO remote renderer 
03-21 16:53:02.671 6766-8287/com.wonderslab.camcrush D/RTCClient.QBRTCSession: onRemoteVideoTrackReceive for opponent 10915983
03-21 16:53:02.671 6766-8287/com.wonderslab.camcrush D/RTCClient.LooperExecutor: Request Looper execute.
03-21 16:53:02.671 6766-8287/com.wonderslab.camcrush D/RTCClient.LooperExecutor: POST.Run on thread:14718 for QBRTCClient
03-21 16:53:02.671 6766-8282/com.wonderslab.camcrush E/VideoCallFragment: remoteVideoView is com.quickblox.videochat.webrtc.view.RTCGLVideoView{db0cd84 V.E..... ........ 0,0-1080,1845 #7f0f0130 app:id/remoteView}
03-21 16:53:02.671 6766-8282/com.wonderslab.camcrush I/RTCGLVideoView: obtainVideoRenderer
03-21 16:53:02.671 6766-8282/com.wonderslab.camcrush I/RTCGLVideoView: obtainMainVideoRenderer
03-21 16:53:02.671 6766-8287/com.wonderslab.camcrush D/RTCClient.QBPeerChannel.SDPObserver:: Remote SDP set successfully
03-21 16:53:02.671 6766-8287/com.wonderslab.camcrush D/RTCClient.QBPeerChannel: createAnswer for opponent 10915983
03-21 16:53:02.671 6766-8287/com.wonderslab.camcrush D/RTCClient.LooperExecutor: Request Looper execute.
03-21 16:53:02.671 6766-8287/com.wonderslab.camcrush D/RTCClient.LooperExecutor: EXECUTE.Run on thread:14721 for QBPeerChannel
03-21 16:53:02.671 6766-8289/com.wonderslab.camcrush D/RTCClient.QBPeerChannel.PCObserver:: onRenegotiationNeeded
03-21 16:53:02.676 6766-8289/com.wonderslab.camcrush D/RTCClient.QBPeerChannel.SDPObserver:: SDP successfully created 
03-21 16:53:02.676 6766-8289/com.wonderslab.camcrush D/RTCClient.RTCMediaUtils: generateLocalDescription:  audioCodec=ISAC
03-21 16:53:02.676 6766-8289/com.wonderslab.camcrush D/RTCClient.RTCMediaUtils: Found ISAC rtpmap 103, prefer at m=audio 9 RTP/SAVPF 103 111 9 102 0 8 106 105 13 127 126
03-21 16:53:02.676 6766-8289/com.wonderslab.camcrush D/RTCClient.RTCMediaUtils: Change media description: m=audio 9 RTP/SAVPF 103 111 9 102 0 8 106 105 13 127 126
03-21 16:53:02.676 6766-8289/com.wonderslab.camcrush D/RTCClient.LooperExecutor: Request Looper execute.
03-21 16:53:02.676 6766-8289/com.wonderslab.camcrush D/RTCClient.LooperExecutor: POST.Run on thread:14721 for QBPeerChannel
03-21 16:53:02.691 6766-8289/com.wonderslab.camcrush D/RTCClient.QBPeerChannel.PCObserver:: onSignalingChange to STABLE
03-21 16:53:02.691 6766-8288/com.wonderslab.camcrush D/AudioTrackJni: InitPlayout@[tid=8288]
03-21 16:53:02.691 6766-8288/com.wonderslab.camcrush D/WebRtcAudioTrack: InitPlayout(sampleRate=48000, channels=1)
03-21 16:53:02.691 6766-8288/com.wonderslab.camcrush D/WebRtcAudioTrack: byteBuffer.capacity: 960
03-21 16:53:02.711 6766-8288/com.wonderslab.camcrush E/art: No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeCacheDirectBufferAddress(java.nio.ByteBuffer, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeCacheDirectBufferAddress and Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeCacheDirectBufferAddress__Ljava_nio_ByteBuffer_2J)
03-21 16:53:02.711 6766-8288/com.wonderslab.camcrush W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeCacheDirectBufferAddress(java.nio.ByteBuffer, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeCacheDirectBufferAddress and Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeCacheDirectBufferAddress__Ljava_nio_ByteBuffer_2J)
03-21 16:53:02.711 6766-8288/com.wonderslab.camcrush W/System.err:     at org.webrtc.voiceengine.WebRtcAudioTrack.nativeCacheDirectBufferAddress(Native Method)
03-21 16:53:02.711 6766-8288/com.wonderslab.camcrush W/System.err:     at org.webrtc.voiceengine.WebRtcAudioTrack.InitPlayout(WebRtcAudioTrack.java:158)
03-21 16:53:02.716 6766-8288/com.wonderslab.camcrush A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 8288 (Thread-14723)
03-21 16:53:05.846 6766-6766/com.wonderslab.camcrush I/Choreographer: Skipped 183 frames!  The application may be doing too much work on its main thread.`

**Comment by Ygauraw** [comment]
Same issue with me.

**Comment by AlexandroKurchenko** [comment]
After some test time i am change my Web-rtc engine to ooVoo and now use it. link to oovoo github.com/oovoodev

**Comment by vfite** [comment]
Please use latest sdk 
https://quickblox.com/developers/Android#Framework_changelog
