### ISSUE TITLE
Chat View from a notification

### ISSUE THREAD

**Issue by Rhefew** [QuickBlox/quickblox-android-sdk#157]
Hello!

I'm having the following issue when implementing a 1-1 chat.

We implemented the whole sdk, the whole flush is working fine when it comes to:
- Login
- Dialogs
- Chat details

the problem is when we need to go from a push notification to a Chat Detail directly (app closed, no background process running). After a lot of fight, I'm doubting about the main implementation of the Login Process to be able to get QBDialog and QBUser successfully. If my app is not running, I need to:
- Create a session
- Login to Chat Service
- Get Chat Dialogs
- Get the Dialog user (used after this to show custom data from user)

I'm currently having issues to get all of these objects while logging in (actually with the callback onSuccess), because I have too much async methods running nested.

Can you help me with a generic approach? I'm driving nuts right now,

Thank you in advance!

**Comment by Rhefew** [comment]
In addition to this, I want to ask you about the right path, because in the Simple example included in the documentation, you implement your inner class, not the sdk itself, and it has some differences when it comes to replicate the functionality.

**Comment by rafa0809** [comment]
Hi! Are you having any exception? Or simply you are worrying about the code complexity due to the callbacks?

**Comment by tatanka987** [comment]
Use latest version of QuickBlox Android SDK https://quickblox.com/developers/Android
Closed for long inactivity.
