### ISSUE TITLE
Not getting processMessageSent callback

### ISSUE THREAD

**Issue by sagaroct** [QuickBlox/quickblox-android-sdk#158]
Not getting processMessageSent callback after message being sent from sender to the receiver.
I have added listener as privateChat.addMessageSentListener(this) in the class which implements QBMessageSentListener<QBPrivateChat>.
What is the work around to get processMessageSent callback.
[PrivateChatHelper.java.tar.gz](https://github.com/QuickBlox/quickblox-android-sdk-releases/files/197490/PrivateChatHelper.java.tar.gz)

**Comment by tatanka987** [comment]
Use latest version of QuickBlox Android SDK https://quickblox.com/developers/Android
Closed for long inactivity.
