### ISSUE TITLE
Crash from XMPP

### ISSUE THREAD

**Issue by Hemant0601** [QuickBlox/quickblox-android-sdk#166]
Hi whenever my login finishes I always get a crash. I cant event find from where exactly its crashing.

Please check:
Here are my logs

CK: SENT (0): <auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='PLAIN'>ADExNTU2Mjc4LTM1ODg2AG9yYWhpXzM2OTM1</auth>
04-12 14:36:37.244 20099-20392/com.softdew.orahi D/SMACK: RECV (0): <success xmlns="urn:ietf:params:xml:ns:xmpp-sasl"/>
04-12 14:36:37.246 20099-20391/com.softdew.orahi D/SMACK: SENT (0): <stream:stream xmlns='jabber:client' to='chat.quickblox.com' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' id='d22e89ff-4f18-47a0-b7a6-3d897cd5a180' xml:lang='en'>
04-12 14:36:37.544 20099-20392/com.softdew.orahi D/SMACK: RECV (0): <iq type="set" to="11556278-35886@chat.quickblox.com/d22e89ff-4f18-47a0-b7a6-3d897cd5a180" id="rsttig2248" xmlns="jabber:client"><query xmlns="jabber:iq:roster" ver="9b6986fb132edd56e09d5b4a36e0e570"><item jid="NaN-35886@chat.quickblox.com" subscription="remove"/></query></iq><iq type="set" to="11556278-35886@chat.quickblox.com/d22e89ff-4f18-47a0-b7a6-3d897cd5a180" id="rsttig2250" xmlns="jabber:client"><query xmlns="jabber:iq:roster" ver="9b6986fb132edd56e09d5b4a36e0e570"><item jid="NaN-35886@chat.quickblox.com" subscription="remove"/></query></iq><iq type="set" to="11556278-35886@chat.quickblox.com/d22e89ff-4f18-47a0-b7a6-3d897cd5a180" id="rsttig2252" xmlns="jabber:client"><query xmlns="jabber:iq:roster" ver="9b6986fb132edd56e09d5b4a36e0e570"><item jid="NaN-35886@chat.quickblox.com" subscription="remove"/></query></iq><iq type="set" to="11556278-35886@chat.quickblox.com/d22e89ff-4f18-47a0-b7a6-3d897cd5a180" id="rsttig2254" xmlns="jabber:client"><query xmlns="jabber:iq:roster" ver="9b6986fb132edd56e09d5b4a36e0e570"><item jid="NaN-35886@chat.quickblox.com" subscription="remove"/></query></iq><iq type="set" to="11556278-35886@chat.quickblox.com/d22e89ff-4f18-47a0-b7a6-3d897cd5a180" id="rsttig2256" xmlns="jabber:client"><query xmlns="jabber:iq:roster" ver="9b6986fb132edd56e09d5b4a36e0e570"><item jid="11601990-35886@chat.quickblox.com" subscription="remove"/></query></iq><iq type="set" to="11556278-35886@chat
04-12 14:36:37.550 20099-20392/com.softdew.orahi D/SMACK: RECV (0): .quickblox.com/d22e89ff-4f18-47a0-b7a6-3d897cd5a180" id="rsttig2258" xmlns="jabber:client"><query xmlns="jabber:iq:roster" ver="9b6986fb132edd56e09d5b4a36e0e570"><item jid="NaN-35886@chat.quickblox.com" subscription="remove"/></query></iq><iq type="set" to="11556278-35886@chat.quickblox.com/d22e89ff-4f18-47a0-b7a6-3d897cd5a180" id="rsttig2260" xmlns="jabber:client"><query xmlns="jabber:iq:roster" ver="9b6986fb132edd56e09d5b4a36e0e570"><item jid="11268303-35886@chat.quickblox.com" subscription="remove"/></query></iq>
04-12 14:36:37.555 20099-20460/com.softdew.orahi W/dalvikvm: threadid=26: thread exiting with uncaught exception (group=0x41c13d40)
04-12 14:36:37.557 20099-20461/com.softdew.orahi W/dalvikvm: threadid=27: thread exiting with uncaught exception (group=0x41c13d40)
04-12 14:36:37.557 20099-20460/com.softdew.orahi E/AndroidRuntime: FATAL EXCEPTION: Smack-Single Threaded Executor 0 (0)
                                                                   Process: com.softdew.orahi, PID: 20099
                                                                   java.lang.NullPointerException
                                                                       at org.jxmpp.util.XmppStringUtils.parseBareJid(XmppStringUtils.java:124)
                                                                       at org.jivesoftware.smack.roster.Roster$RosterPushListener.handleIQRequest(Roster.java:1404)
                                                                       at org.jivesoftware.smack.AbstractXMPPConnection$2.run(AbstractXMPPConnection.java:1060)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:841)
04-12 14:36:37.557 20099-20461/com.softdew.orahi I/Process: Sending signal. PID: 20099 SIG: 9

**Comment by Hemant0601** [comment]
@katiatereshchenkova any update on this issue

**Comment by soulfly** [comment]
what is your app id?

**Comment by Hemant0601** [comment]
App Id 35886

**Comment by Hemant0601** [comment]
@soulfly any update??

**Comment by Hemant0601** [comment]
https://community.igniterealtime.org/thread/56726 if it can help

**Comment by Hemant0601** [comment]
@soulfly any update on this. More log:
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(int)' on a null object reference
       at org.jxmpp.util.XmppStringUtils.parseBareJid(XmppStringUtils.java:124)
       at org.jivesoftware.smack.roster.Roster$RosterPushListener.handleIQRequest(Roster.java:1404)
       at org.jivesoftware.smack.AbstractXMPPConnection$2.run(AbstractXMPPConnection.java:1060)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by Hemant0601** [comment]
@soulfly @alisandr Any update on this issue. I am getting this more and more now, my app users are getting low. Please help its of high priority..
Thanks

**Comment by bgunduz55** [comment]
As your log said, java.lang.String.indexOf(int) has a null object reference. So , indexof() function that you used in your code has a null reference. Check the variable in that function...

**Comment by Hemant0601** [comment]
@bgunduz55 its not my class, its a class in Quickblox SDK jar file. I am not able to change anything in that as Quickblox doesnt provide any github code for whole package.

**Comment by bgunduz55** [comment]
But. if you send a null reference to that class, then you could see the error. I meant that. I recommend you to check the class references, or variables that could null...

**Comment by pletom** [comment]
I had similar problems (with NPE in Roster). 
My fix was to create subclass of XMPPTCPConnection class, use that subclassed connection and in constructors set user variable to "";

```
public class ChatXMPPTCPConnection extends XMPPTCPConnection {
    public ChatXMPPTCPConnection(XMPPTCPConnectionConfiguration config) {
        super(config);
        user = "";
    }

    public ChatXMPPTCPConnection(CharSequence jid, String password) {
        super(jid, password);
        user = "";
    }

    public ChatXMPPTCPConnection(CharSequence username, String password, String serviceName) {
        super(username, password, serviceName);
        user = "";
    }
}
```

**Comment by Hemant0601** [comment]
@pletom Thanks for your comment but I am using Quickblox over here and XMPPTCPConnection class is not in my scope. Its private , staying in .aar file of Quickblox. I cant change untill QB provide me anything for this.

**Comment by vfite** [comment]
@Hemant0601 You get NPE in roster because Roster can't retrieve user's login from connection. It indicates you haven't logged into chat.or after relogin you are using roster referenced to previous connection. In this case after each logout you should retrieve roster object via QBChatService.getInstance().getRoster.
In other case provide us steps to reproduce this issue or try to reproduce it on our chat-sample.

**Comment by Hemant0601** [comment]
@vfite I have checked that I am logged into before using roster, but lemme check the thing you mentioned about using previous reference of login. By the way how could I check if the reference is from previous login.

**Comment by vfite** [comment]
As for " reference is from previous login" I mean that case:
 - you login into chat QBChatService.getInstance().login()
 - get roster and save it: roster = QBChatService.getInstance().getRoster().
- logout - QBChatService.getInstance().logout
- login again QBChatService.getInstance().login()
 - and here using reference "roster" retrieved from first login.
In this case you should reset roster after relogin:
  roster = QBChatService.getInstance().getRoster().

**Comment by Hemant0601** [comment]
@vfite I am not using QBChatService.getInstance().logout but I might be making a new connection, also I was using QBChatService.getInstance().getRoster() only when it was "null", not every time. So might be this was causing all the issue. Anyways I have implemented this, lemme see if it triggers again. It would be a great help if it works and thanks for pointing out the right issue here.

**Comment by Hemant0601** [comment]
@vfite I tried the solution but in vain. Same issue happened again for me. Any other solution?

**Comment by vfite** [comment]
@Hemant0601 provide exact steps and code snippet to reproduce this issue as we can't observe it in normal case. Which version of quickblox sdk a u using ?

**Comment by Hemant0601** [comment]
@vfite I dont know the code will reproduce it or not, but I am sharing whatever I am doing, my QB SDK version is 2.6.

`
//to create session 
public void recreateSession() {

       

        String qbID = AppController.getQBID();

        if (qbID == null
                || TextUtils.isEmpty(qbID) || qbID.equalsIgnoreCase("")) {
            return;
        }

        String userId = AppController.getQBID();
        if (userId.equalsIgnoreCase("orahi_")) {
            Log.v(TAG, "Suspending QB connection creation as user is not logged in");
            return;
        }

        Log.v(TAG, "QB connected status " + ChatService.isConnected());

        final QBUser user = getSelfQBUSerObj();

        if (!Util.haveNetworkConnection(AppController.getInstance())) {
            return;
        } else if (!AppController.getUserProfile().isLoginStatus()) {
            return;
        } else if (!AppController.getUserProfile().isQbSignUpStatus()) {
            return;
        } else if (ChatService.isConnected()) {
            startBasicSetUpQB();
            return;
        }


        if (!creatingSession) {
            creatingSession = true;
            sessionActive = false;
            this.onStartSessionRecreation();

            try {

                final BaseWorkerThread mWorkerThread = new BaseWorkerThread("QBSession");

                Runnable task = new Runnable() {
                    @Override
                    public void run() {

                        // Restoring Chat session
                        //Todo changed chatservice to qbchatservice
                        ChatService.getInstance().login(user, new QBEntityCallback<Void>() {
                            @Override
                            public void onSuccess(Void result, Bundle bundle) {
                                mWorkerThread.quit();
                                creatingSession = false;
                                if (AppController.getUserProfile() != null) {
                                    AppController.getUserProfile().setQbSignUpStatus(true);
                                    AppController.getUserProfile().save();
                                }
                                Log.d(TAG, "Chat login onSuccess for ");
                                sessionActive = true;
                                startBasicSetUpQB();
                                

                            }

                            @Override
                            public void onError(final QBResponseException errors) {
                                mWorkerThread.quit();

                                creatingSession = false;
                                Log.d(TAG, "Chat login onError: " + errors);

                                if (errors.getMessage().contains("already")) {
                                    OrahiBaseActivity.this.onFinishSessionRecreation(true);
                                    startBasicSetUpQB();
                                } else {

                                
                                    recreateSession();
                                   
                                }

                            }
                        });

                    }
                };
                mWorkerThread.start();
                mWorkerThread.prepareHandler();
                mWorkerThread.postTask(task);

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }
}


//using  to get roster
public QBRoster getRoster() {
        try {


            chatRosterObj = QBChatService.getInstance().getRoster(QBRoster.SubscriptionMode.mutual, subscriptionListener);
            if (chatRosterObj != null) {
                chatRosterObj.addRosterListener(rosterListener);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        return chatRosterObj;
    }

//subscription listener
  QBSubscriptionListener subscriptionListener = new QBSubscriptionListener() {
        @Override
        public void subscriptionRequested(int userId) {
            try {
                if (ChatService.isConnected()) {
                    getRoster().confirmSubscription(userId);
                }
            } catch (SmackException.NotConnectedException e) {

            } catch (SmackException.NotLoggedInException e) {

            } catch (XMPPException e) {

            } catch (SmackException.NoResponseException e) {

            } catch (Exception e) {

            }
        }
    };
` 
This is what I am doing to create a session and whenever I need roster I call the above mentioned method. My app crashes with the log that I mentioned on the top of thread after my app have created a connection. There is no specific trigger code or time that I could find which is causing this.

**Comment by Hemant0601** [comment]
@vfite @soulfly @olegflo Any solution for this. My app rating is going down just because of this. Please help its urgent.

**Comment by Hemant0601** [comment]
@vfite @soulfly @olegflo 
The following trace , its even after updating to 3.0,
11-10 22:10:20.502 13674-17010/com.company.app W/Roster: Roster not loaded while processing presence stanza
11-10 22:10:20.510 13674-16899/com.company.app D/SMACK: RECV (0): <presence id="09Krk-954" from="14333659-35886@chat.quickblox.com" to="12075543-35886@chat.quickblox.com" type="subscribe" xmlns="jabber:client"><delay from="chat.quickblox.com" stamp="2016-11-10T15:50:44.797Z" xmlns="urn:xmpp:delay">Offline Storage - chat.quickblox.com</delay></presence>
11-10 22:10:20.513 13674-17063/com.company.app W/Roster: Roster not loaded while processing presence stanza
11-10 22:10:20.532 13674-16899/com.company.app D/SMACK: RECV (0): <presence id="Zofeq-576" from="19196350-35886@chat.quickblox.com" to="12075543-35886@chat.quickblox.com" type="subscribe" xmlns="jabber:client"><delay from="chat.quickblox.com" stamp="2016-11-10T16:32:11.536Z" xmlns="urn:xmpp:delay">Offline Storage - chat.quickblox.com</delay></presence>
11-10 22:10:20.534 13674-16899/com.company.app D/SMACK: RECV (0): <presence id="09Krk-21896" from="14333659-35886@chat.quickblox.com" to="12075543-35886@chat.quickblox.com" type="subscribe" xmlns="jabber:client"><delay from="chat.quickblox.com" stamp="2016-11-10T16:40:12.210Z" xmlns="urn:xmpp:delay">Offline Storage - chat.quickblox.com</delay></presence>
11-10 22:10:20.534 13674-17063/com.company.app W/Roster: Roster not loaded while processing presence stanza
11-10 22:10:20.535 13674-16899/com.company.app D/SMACK: RECV (0): <iq type="result" xmlns="jabber:client" id="v8pN9-1" to="12075543-35886@chat.quickblox.com/android_00000000-0f12-653f-7a5d-fb333b5d3e0c"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>12075543-35886@chat.quickblox.com/android_00000000-0f12-653f-7a5d-fb333b5d3e0c</jid></bind></iq>
11-10 22:10:20.535 13674-17063/com.company.app W/Roster: Roster not loaded while processing presence stanza
11-10 22:10:20.537 13674-16898/com.company.app D/SMACK: SENT (0): <iq id='v8pN9-112' type='set'><session xmlns='urn:ietf:params:xml:ns:xmpp-session'/></iq>
                                                          
                                                          --------- beginning of crash
11-10 22:10:20.667 13674-17010/com.company.app E/AndroidRuntime: FATAL EXCEPTION: Smack-Single Threaded Executor 0 (0)
                                                                   Process: com.company.app, PID: 13674
                                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(int)' on a null object reference
                                                                       at org.jxmpp.util.XmppStringUtils.parseBareJid(XmppStringUtils.java:124)
                                                                       at org.jivesoftware.smack.roster.Roster$RosterPushListener.handleIQRequest(Roster.java:1404)
                                                                       at org.jivesoftware.smack.AbstractXMPPConnection$2.run(AbstractXMPPConnection.java:1060)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)
11-10 22:10:20.671 13674-17010/com.company.app E/AbstractTracker: Can't create handler inside thread that has not called Looper.prepare()
11-10 22:10:20.672 13674-17010/com.company.app D/AppTracker: App Event: crash
11-10 22:10:20.676 13674-17010/com.company.app E/AbstractTracker: mTrackerAsyncQueryHandler is null
11-10 22:10:20.715 13674-13674/com.company.app I/CompBaseActivity: OnPause
11-10 22:10:20.735 13674-13674/com.company.app I/RideFragment: Location fetching stopped
11-

**Comment by alexanderkoqb** [comment]
Hey @Hemant0601 
Since it's been a while and if you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
