### ISSUE TITLE
Total unread messages count request

### ISSUE THREAD

**Issue by marta-rodriguez** [QuickBlox/quickblox-android-sdk#167]
I have seen that in the iOS sdk and the API I can get the total unread messages count, but I couldn't find a way to do the same with the Android SDK. Is there a way to achieve this?

http://stackoverflow.com/questions/36569272/quickblox-android-total-unread-messages-count-request

**Comment by jagatappv** [comment]
+1

**Comment by soulfly** [comment]
Expect to have it in our upcoming release

Will also share with your a snapshot version today

**Comment by marta-rodriguez** [comment]
Perfect! Thanks!

**Comment by jagatappv** [comment]
@soulfly 
thanks for the support

Please inform me once snapshot version is ready.
also mentions the steps to access this snapshot version.

Thanks

**Comment by soulfly** [comment]
To get just a total of unread:


            QBChatService.getTotalUnreadMessagesCount(null, new QBEntityCallback<Integer>() {
                @Override
                public void onSuccess(Integer total, Bundle params) {
                    Log.i(TAG, "total unread messages: " + total);
                }

                @Override
                public void onError(QBResponseException responseException) {
                }
            });

You also can get an info about unread messages per dialogs:

            Set<String> dialogsIds = new HashSet<String>() {{
                add("56f3fac3a0eb4786ae00003f"); add("56f3f546a28f9affc0000033");
            }};

            QBChatService.getTotalUnreadMessagesCount(dialogsIds, new QBEntityCallback<Integer>() {
                @Override
                public void onSuccess(Integer total, Bundle params) {
                    Log.i(TAG, "total unread messages: " + total);
                    Log.i(TAG, "dialog Unread1: " + params.getInt("56f3fac3a0eb4786ae00003f"));
                    Log.i(TAG, "dialog Unread2: " + params.getInt("56f3f546a28f9affc0000033"));
                }

                @Override
                public void onError(QBResponseException responseException) {
                }
            });

**Comment by soulfly** [comment]
And a link to artifacts 

https://sdk.quickblox.com/android/artifacts/artifacts_unread_total.zip

**Comment by jagatappv** [comment]
Thanks a lot

**Comment by soulfly** [comment]
Let us know if you have any questions with this

**Comment by soulfly** [comment]
Released with Android SDK 2.5.2
http://quickblox.com/developers/Android#Framework_changelog

**Comment by jagatappv** [comment]
I think library has been upgraded.
Can you post new work around for getting total unread msg counts?

Thanks

**Comment by jatin-lakhani** [comment]
+1
@jagatappv  Yes, you're right.

**Comment by vfite** [comment]
hi there. Guys, why you don't use documentation?
https://quickblox.com/developers/Android_XMPP_Chat_Sample#Guide:_Getting_Started_with_Chat_API

**Comment by jagatappv** [comment]
@vfite 
Didn't found method that returns all the unread message count.

**Comment by latixinc** [comment]
```
Set<String> dialogIds = new HashSet<String>();
String groupChatId = groupChat.getDialogId();
System.out.println("GroupChat Id: "+groupChatId);
dialogIds.add(groupChatId);
QBRestChatService.getTotalUnreadMessagesCount(dialogIds,null).performAsync(new QBEntityCallback<Integer>() {
 @Override
public void onSuccess(Integer integer, Bundle bundle) {
                                                        
 }

@Override
 public void onError(QBResponseException e) {

}
 });
```

I use that method in the latest library to get total unread messages but it always returns 0. what do i do. once the user close the groupchat all his info is cleared. Even notification does not work.
Please i will need reply urgently. If possible i will need a personal tutor on quickblox because the library is not clear at all.

**Comment by githubmss** [comment]
I am getting issue with unread count 

Here is my code flow :- 

`package com.mss.backup.fragment;

import android.databinding.DataBindingUtil;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.mss.backup.R;
import com.mss.backup.ViewModel.ConversationViewModel;
import com.mss.backup.databinding.FragmentConversationBinding;
import com.mss.backup.managers.DialogsManager;
import com.quickblox.chat.QBIncomingMessagesManager;
import com.quickblox.chat.QBSystemMessagesManager;
import com.quickblox.chat.exception.QBChatException;
import com.quickblox.chat.listeners.QBChatDialogMessageListener;
import com.quickblox.chat.listeners.QBSystemMessageListener;
import com.quickblox.chat.model.QBChatDialog;
import com.quickblox.chat.model.QBChatMessage;

import java.util.Observable;
import java.util.Observer;


public class ConversationFragment extends Fragment implements Observer, DialogsManager.ManagingDialogsCallbacks {
    ConversationViewModel conversationViewModel;
    FragmentConversationBinding binding;
    private static final int REQUEST_SELECT_PEOPLE = 174;
    private static final int REQUEST_DIALOG_ID_FOR_UPDATE = 165;
    QBChatDialogMessageListener allDialogsMessagesListener;
    SystemMessagesListener systemMessagesListener;
    QBSystemMessagesManager systemMessagesManager;
    QBIncomingMessagesManager incomingMessagesManager;
    private DialogsManager dialogsManager;

    public ConversationFragment() {
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        binding = DataBindingUtil.inflate(inflater, R.layout.fragment_conversation, container, false);
        getActivity().getWindow().setBackgroundDrawableResource(R.drawable.bg_img);
        View view = binding.getRoot();
        systemMessagesListener = new SystemMessagesListener();
        dialogsManager = new DialogsManager();

        return view;
    }

    private void setUpModel() {
        conversationViewModel = new ConversationViewModel(getActivity(), binding);
        binding.setConversationViewModel(conversationViewModel);
        setUpObserver(conversationViewModel);
    }


    private void setUpObserver(ConversationViewModel observer) {
        observer.addObserver(this);
    }

    public void update(Observable observable, Object o) {
       

    }

    @Override
    public void onDestroy() {
        super.onDestroy();

    }

    @Override
    public void onResume() {
        super.onResume();
        setUpModel();
    }

    @Override
    public void onPause() {
        super.onPause();
        unregisterQbChatListeners();
    }


    public void unregisterQbChatListeners() {
        if (incomingMessagesManager != null) {
            incomingMessagesManager.removeDialogMessageListrener(allDialogsMessagesListener);
        }

        if (systemMessagesManager != null) {
            systemMessagesManager.removeSystemMessageListener(systemMessagesListener);
        }
        dialogsManager.removeManagingDialogsCallbackListener(this);
    }

    @Override
    public void onDialogCreated(QBChatDialog chatDialog) {
    }

    @Override
    public void onDialogUpdated(String chatDialog) {

    }

    @Override
    public void onNewDialogLoaded(QBChatDialog chatDialog) {

    }

    private class SystemMessagesListener implements QBSystemMessageListener {
        @Override
        public void processMessage(final QBChatMessage qbChatMessage) {
            dialogsManager.onSystemMessageReceived(qbChatMessage);
        }

        @Override
        public void processError(QBChatException e, QBChatMessage qbChatMessage) {

        }
    }


}
`


My Fragment View Model :- 

`package com.mss.backup.ViewModel;

import android.app.Activity;
import android.content.Context;
import android.os.Bundle;
import android.support.v7.view.ActionMode;
import android.view.View;
import android.widget.AdapterView;
import android.widget.Toast;

import com.mss.backup.Utils.chat.ChatHelper;
import com.mss.backup.Utils.qb.QbChatDialogMessageListenerImp;
import com.mss.backup.Utils.qb.QbDialogHolder;
import com.mss.backup.View.acitvities.ChatActivity;
import com.mss.backup.View.adapter.DialogsAdapter;
import com.mss.backup.databinding.FragmentConversationBinding;
import com.mss.backup.managers.DialogsManager;
import com.orangegangsters.github.swipyrefreshlayout.library.SwipyRefreshLayout;
import com.orangegangsters.github.swipyrefreshlayout.library.SwipyRefreshLayoutDirection;
import com.quickblox.chat.QBChatService;
import com.quickblox.chat.QBIncomingMessagesManager;
import com.quickblox.chat.QBSystemMessagesManager;
import com.quickblox.chat.exception.QBChatException;
import com.quickblox.chat.listeners.QBChatDialogMessageListener;
import com.quickblox.chat.listeners.QBSystemMessageListener;
import com.quickblox.chat.model.QBChatDialog;
import com.quickblox.chat.model.QBChatMessage;
import com.quickblox.core.QBEntityCallback;
import com.quickblox.core.exception.QBResponseException;
import com.quickblox.core.request.QBRequestGetBuilder;
import com.quickblox.users.model.QBUser;

import java.util.ArrayList;
import java.util.Observable;


public class ConversationViewModel extends Observable implements DialogsManager.ManagingDialogsCallbacks {
    private static final int REQUEST_SELECT_PEOPLE = 174;
    private static final int REQUEST_DIALOG_ID_FOR_UPDATE = 165;
    public Context mContext;
    FragmentConversationBinding binding;
    private ActionMode currentActionMode;
    public QBRequestGetBuilder requestBuilder;
    private int skipRecords = 0;
    private DialogsAdapter dialogsAdapter;
    private QBChatDialogMessageListener allDialogsMessagesListener;
    private SystemMessagesListener systemMessagesListener;
    private QBSystemMessagesManager systemMessagesManager;
    private QBIncomingMessagesManager incomingMessagesManager;
    private DialogsManager dialogsManager;
    private QBUser currentUser;

    public ConversationViewModel(Context mContext, FragmentConversationBinding binding) {
        this.mContext = mContext;
        this.binding = binding;
        initUI();
    }

    public void initUI() {
        allDialogsMessagesListener = new AllDialogsMessageListener();
        systemMessagesListener = new SystemMessagesListener();
        dialogsManager = new DialogsManager();
        currentUser = ChatHelper.getCurrentUser();
        initList();
        registerQbChatListeners();
        if (QbDialogHolder.getInstance().getDialogs().size() > 0) {
            loadDialogsFromQb(true, true);
        } else {
            loadDialogsFromQb(false, true);
        }
    }

    public void initList() {
        dialogsAdapter = new DialogsAdapter(mContext, new ArrayList<>(QbDialogHolder.getInstance().getDialogs().values()));
        binding.listDialogsChats.setAdapter(dialogsAdapter);
        binding.listDialogsChats.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                QBChatDialog selectedDialog = (QBChatDialog) parent.getItemAtPosition(position);
                if (currentActionMode == null) {
                    ChatActivity.startForResult(((Activity) mContext), REQUEST_DIALOG_ID_FOR_UPDATE, selectedDialog);
                } else {
                    dialogsAdapter.toggleSelection(selectedDialog);
                }
            }
        });
        binding.listDialogsChats.setOnItemLongClickListener(new AdapterView.OnItemLongClickListener() {
            @Override
            public boolean onItemLongClick(AdapterView<?> parent, View view, int position, long id) {
                QBChatDialog selectedDialog = (QBChatDialog) parent.getItemAtPosition(position);
                dialogsAdapter.selectItem(selectedDialog);
                return true;
            }
        });
        requestBuilder = new QBRequestGetBuilder();

        binding.swipyRefreshLayout.setOnRefreshListener(new SwipyRefreshLayout.OnRefreshListener() {
            @Override
            public void onRefresh(SwipyRefreshLayoutDirection direction) {
                requestBuilder.setSkip(skipRecords += ChatHelper.DIALOG_ITEMS_PER_PAGE);
                loadDialogsFromQb(true, false);
            }
        });
    }


    @Override
    public void onDialogCreated(QBChatDialog chatDialog) {
        updateDialogsAdapter();
    }

    @Override
    public void onDialogUpdated(String chatDialog) {
        updateDialogsAdapter();
    }

    @Override
    public void onNewDialogLoaded(QBChatDialog chatDialog) {
        updateDialogsAdapter();
    }


    private void registerQbChatListeners() {
        incomingMessagesManager = QBChatService.getInstance().getIncomingMessagesManager();
        systemMessagesManager = QBChatService.getInstance().getSystemMessagesManager();

        if (incomingMessagesManager != null) {
            incomingMessagesManager.addDialogMessageListener(allDialogsMessagesListener != null
                    ? allDialogsMessagesListener : new AllDialogsMessageListener());
        }

        if (systemMessagesManager != null) {
            systemMessagesManager.addSystemMessageListener(systemMessagesListener != null
                    ? systemMessagesListener : new SystemMessagesListener());
        }

        dialogsManager.addManagingDialogsCallbackListener(this);
    }


    private class SystemMessagesListener implements QBSystemMessageListener {
        @Override
        public void processMessage(final QBChatMessage qbChatMessage) {
            dialogsManager.onSystemMessageReceived(qbChatMessage);
        }

        @Override
        public void processError(QBChatException e, QBChatMessage qbChatMessage) {

        }
    }

    private class AllDialogsMessageListener extends QbChatDialogMessageListenerImp {
        @Override
        public void processMessage(final String dialogId, final QBChatMessage qbChatMessage, Integer senderId) {
            if (!senderId.equals(ChatHelper.getCurrentUser().getId())) {
                dialogsManager.onGlobalMessageReceived(dialogId, qbChatMessage);
            }
        }
    }

    public void updateDialogsAdapter() {
        dialogsAdapter.updateList(new ArrayList<>(QbDialogHolder.getInstance().getDialogs().values()));
    }

    public void loadDialogsFromQb(final boolean silentUpdate, final boolean clearDialogHolder) {
        if (!silentUpdate) {
            binding.progressDialogs.setVisibility(View.VISIBLE);
        }

        ChatHelper.getInstance().getDialogs(requestBuilder, new QBEntityCallback<ArrayList<QBChatDialog>>() {
            @Override
            public void onSuccess(ArrayList<QBChatDialog> dialogs, Bundle bundle) {
                binding.progressDialogs.setVisibility(View.GONE);
                binding.swipyRefreshLayout.setRefreshing(false);
                if (clearDialogHolder) {
                    QbDialogHolder.getInstance().clear();
                }
                QbDialogHolder.getInstance().addDialogs(dialogs);
                updateDialogsAdapter();
            }

            @Override
            public void onError(QBResponseException e) {
                binding.progressDialogs.setVisibility(View.GONE);
                binding.swipyRefreshLayout.setRefreshing(false);
                Toast.makeText(mContext, e.getMessage(), Toast.LENGTH_SHORT).show();
            }
        });
    }
}
`

when ever i send one msg from my chat window it gives me unread count of 4 and with next msg it just get doubled and so on , but once i refresh the screen count issue get resolved.

Can any body let me know what i am doing worng 

it's my first time with quickblox

Any help would be highly appreciated , i really need some suggestions here , i have deadline with me for this task 

your support can ease my pain.

Thanks

**Comment by githubmss** [comment]
Any one there ? i need your suggestion here sir .
