### ISSUE TITLE
Notifications  delivery issue (17 minute delay)

### ISSUE THREAD

**Issue by Aento** [QuickBlox/quickblox-android-sdk#169]
As you see in the log we get huge delay between create and deliver time.
    "notification": {
        "registration_ids": ["APA91bE8qhoxPDLA2eTk1Pe2aaPw2lHy9IPeO...",
                "APA91bGuqCR7NPvcuPivy7Use6q6Bo5ebfp4Y6era..",
        "APA91bH5tGptGgz25iRQqXfVoFQ2_rwO8GJ3IJNw9Zx5UIHurVWt6mZWbBzfm.",
        "APA91bHdBM7xv7sqJ_JnUqLhscJXCAHJfzEaf10Awmz0g6b..",
        "APA91bElhSoY5GeS6Fscmz4sl7PRKYiWKg92ru8_Vu7YSxrWOOLfSs61IaK..",
        "APA91bHSy25qsjFofELuP3f52U6eYWowErcoRvpV93gyvUzlPNY4..,
        "APA91bH-pltLYyr2N9IwOTbGPX_dcKaNrvYi2F5e4qRF742izcXJelVq8V..,
        "delay_while_idle": false,
        "data": {
            "message": "Stas Karas: test 2",
            "dialog_id": "565c1ffba28f9a12d0000192",
            "user_id": "5514027",
            "badge": "1",
            "collapse_key": "event6502293"
        },
        "priority": "high",
        "time_to_live": 86400
    },
    "log": [{
        "device_token": null,
        "created_at": "2016-04-14T10:31:05Z",
        "delivered_at": "2016-04-14T10:48:30Z",
        "failed_at": null,
        "error_code": null,
        "error_description": null
    }]
}

The other notifications has not yet been sent after a 30 minutes.

**Comment by RomanPronin** [comment]
Now it's all ok.
