### ISSUE TITLE
Getting Owner of a Dialog

### ISSUE THREAD

**Issue by fgoni** [QuickBlox/quickblox-android-sdk#17]
I can't seem to find a way of knowing who owns a Dialog.
XMPP allows you to know and change the Owner of a given XMPP MUC, and I'm guessing that's what QuickBlox uses at a lower level, but there's no method to access it in the API.
I recall somewhere in QuickBlox site saying that you would add more info to the getRoomInfo method but that method is gone in Chat 2.0
Using Dialogs in conjunction with CustomObjects just to enable Owners seems like a lot of overhead for something that we should have access to already (when querying for Dialogs).

**Comment by raghuarvapally1** [comment]
Is it possible to change dialog owner to other group participants? when he leaves from dialog?

Example: I created dialog with three participant (1,2.3), I created with 1....after creation 1 left from dialog. then is it possible to assign dialog ownership to second participant.

**Comment by soulfly** [comment]
No, it's not possible at this stage

you have to review your logic
