### ISSUE TITLE
can not add member to group - You don't have appropriate permissions to perform this operation

### ISSUE THREAD

**Issue by estysherman** [QuickBlox/quickblox-android-sdk#170]
in adding member to group in quickblox android i get: You don't have appropriate permissions to perform this operation.

private boolean UpdateDialogGroupQBUsers(int userId) {
        QBRequestUpdateBuilder requestBuilder = new QBRequestUpdateBuilder();
        requestBuilder.push("occupants_ids", userId); // add another users
        QBChatService.getInstance().getGroupChatManager().updateDialog(QBDialog, requestBuilder,           new QBEntityCallback<QBDialog>() {
            @Override
            public void onSuccess(QBDialog dialog, Bundle args) {
                Log.d("addMember", "success");
                isSuccess = true;
            }
            @Override
            public void onError(QBResponseException e) {
                Log.d("addMember",e.toString());
                isSuccess = false;
            }
        });
        return isSuccess;
    }
}

**Comment by Hemant0601** [comment]
@estysherman sometime the error response are not clear. So I would recommend you to create a seperate class to create group and try adding user manually from code.
please note: when the user who created group is removed from the group this error occurs. I faced the same. And I will recommend one more thing, dont add users all in one by this method, because even if it add the users u will get error saying "You dont have permission...". So try adding users one by one.

**Comment by ChaitraKavya** [comment]
Update your QB SDK to 2.6 and use this method it will work, you need to pass dialog, requestbuilder and callback 

QBRequestUpdateBuilder qbRequestBuilder = new QBRequestUpdateBuilder();
  qbRequestBuilder.pushAll("occupants_ids", QbDialogUtils.getUserIds(addedUsers));
        
QBChatService.getInstance().getGroupChatManager().updateDialog(qbDialog, qbRequestBuilder,
                new QBEntityCallback<QBDialog>() {
                    @Override
                    public void onSuccess(QBDialog qbDialog, Bundle bundle) {
                  
                    }

                    @Override
                    public void onError(QBResponseException e) {
                        e.printStackTrace();
                    }
                });

**Comment by vfite** [comment]
Guys, refer to http://quickblox.com/developers/Chat#Update_dialog for your errors.
You can use QBDialogRequestBuilder to simplify your work: http://quickblox.com/developers/Android_XMPP_Chat_Sample#Update_group_dialog.

**Comment by alexanderkoqb** [comment]
Hey @estysherman 
Since it's been a while and if you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
