### ISSUE TITLE
How to handle message when the app is in foreground.

### ISSUE THREAD

**Issue by mikeRozen** [QuickBlox/quickblox-android-sdk#172]
When the app is in foreground no notification arrive.
Can you please show/forward me to sample code how to configure some sort of listener to handle a new  message when app is in foreground?
Thanks.

**Comment by soulfly** [comment]
About what notifications are you talking about? Push Notifications?

**Comment by mikeRozen** [comment]
**soulfly**
I will split my question.(The initial question was regarding A)
A.  When the app in the foreground (on IOS I receive it by listening to the channel/delegate let me know when message arrive)  what will inform the app on arrival of new message ?
B. Sometimes Push notifications come with delay.

**Comment by tatanka987** [comment]
Closed for long inactivity
