### ISSUE TITLE
how can i get dialog by dialogId

### ISSUE THREAD

**Issue by estysherman** [QuickBlox/quickblox-android-sdk#174]
When I get into group I want to get her dialog
How do I get the dialog by dialogId?

**Comment by soulfly** [comment]
Use Dialogs filters

http://quickblox.com/developers/Android_XMPP_Chat_Sample#Filters

for example, 

    requestBuilder.addRule("_id", QueryRule.EQ, "...");

**Comment by estysherman** [comment]
Thanks for the response,
But what function do I send the requestBuilder?
