### ISSUE TITLE
Problem with QBChatManager

### ISSUE THREAD

**Issue by bvscd** [QuickBlox/quickblox-android-sdk#177]
We are trying to use your chat service, and have got issue with chat login in case when network connection is slow. In the code snippet below we often get an exception

**Comment by bvscd** [comment]
QBUser qbUser = new QBUser(settings.getUsername(), settings.getPassword());
                try {
                    QBSession qbSession = QBAuth.getSession();
                    qbUser.setId(qbSession.getUserId());
                }
                catch (QBResponseException e) {
                    QBSession qbSession = QBAuth.createSession(qbUser);
                    qbUser.setId(qbSession.getUserId());
                }
                QBChatService qbChatService = QBChatService.getInstance();
                try {
                    qbChatService.logout();
                }
                catch (Exception e)
                { }
                qbChatService.login(qbUser);

Following exception is thrown on last line

No response received within reply timeout. Timeout was 5000ms (~5s). Used filter: No filter used or filter was 'null'.
SynchronizationPoint.java in checkForResponse at line 253application
SynchronizationPoint.java in checkIfSuccessOrWait at line 146application
SynchronizationPoint.java in checkIfSuccessOrWaitOrThrow at line 125application
XMPPTCPConnection.java in connectInternal at line 850application
AbstractXMPPConnection.java in connect at line 364application
QBChatService.java in connect at line 167application
QBChatService.java in login at line 334application
QBChatService.java in login at line 289application
Backend.java in login at line 2040application

So it looks like QBAuth connection is ok, but QBChatService connection is broken.
Can you give good suggestion how to handle the case properly?

**Comment by vfite** [comment]
Use QBChatService.setDefaultPacketReplyTimeout to increase waiting time as described in doc:https://quickblox.com/developers/Android_XMPP_Chat_Sample#Prepare_Chat_service
