### ISSUE TITLE
Audio Call Not Able to receive : WebRTC Video Engine Error.

### ISSUE THREAD

**Issue by AyushiBShah** [QuickBlox/quickblox-android-sdk#182]
**Environment details**
Android 2.5 quickblox SDK

At times I am getting below error when receiving incoming call :
java.lang.NoClassDefFoundError: org/webrtc/voiceengine/BuildInfo
org.webrtc.PeerConnectionFactory.initializeAndroidGlobals(Native Method)

@soulfly @Sergey-Fedunets  Please look into above issue I am running out of time

**Comment by RomanPronin** [comment]
[Latest version sdk](https://quickblox.com/developers/Android) with webrtc new features.
