### ISSUE TITLE
sample-videochat-webrtc

### ISSUE THREAD

**Issue by mitendraanand** [QuickBlox/quickblox-android-sdk#183]
Unable to make audio calls.

Steps to reproduce.
1. Running on emulator after building the sample code in Android Studio.
2. App launches fine.
3. ee the users list. 1-9 Users
4. Login as one of the user
5. Then make call to another user who has logged on some other laptop/emulator with different user.
6. Make audio call.
7. Call goes to that user.
8. He/She receives it. Time starts.
9. No audio/voice is heard but.
10. Call gets disconnected

Please advise

**Comment by RomanPronin** [comment]
See our latest [video chat sample](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-webrtc) with fixes and new features.
