### ISSUE TITLE
Error code 422 (Error when login, check test users login and password)

### ISSUE THREAD

**Issue by omamapk** [QuickBlox/quickblox-android-sdk#19]
Hi,

i have created app  on quickblox. users are created successfully but when i try to  creates session with : QBAuth.createSession(login, password, new QBCreateSessionCallback(password));
 with some users it throws erros code 422. what could be the reason. 

I have imported github sample video chat app.

**Comment by amitsharmahimcs** [comment]
what the correct code

**Comment by sms81** [comment]
i had downloaded the webrtc video chat sample and changed the app id,key and secret to match my application and when running the app the users re created but when choosing one of them Error when login, check test users login and password appears

**Comment by JobsJr** [comment]
I am still getting the same error :401,Error when login, check test users login and password even after replacing APP ID,AUTH KEY & SECRET.Can you please resolve this??

**Comment by jsiva001** [comment]
i am still getting issues same as what you have got it..  can u give me solution for that?
