### ISSUE TITLE
Message sent to wrong recipient

### ISSUE THREAD

**Issue by Hemant0601** [QuickBlox/quickblox-android-sdk#190]
Hi,
Since QB doesn't give a mechanism where I get all the incoming messages from SMACK(as that I am aware of), I have to join a groupchat or everytime create a new object and connection for private chat. So to work around this, I programatically created a connection for all the dialogs in background, so that when that chat is open the messages are received there, and if not the messages are redirected to my logs so that I show an internal push notification to the user.
Now after this, I am getting a very weird issue, whenever i chat it works normal, but after few min or sometime just one min, whenever i send a message it either send it to self or send it to some random person listed in my QB application.

<message to='12234589-35886@chat.quickblox.com' id='5729dc6ce9bbf2f6734cca0a' type='chat'><body>hiii</body><markable xmlns='urn:xmpp:chat-markers:0'/><extraParams xmlns='jabber:client'><dialog_id>5728a0aea28f9a66a7000084</dialog_id><recipient_id>12075130</recipient_id><sender_id>12075543</sender_id><message_id>5729dc6ce9bbf2f6734cca0a</message_id><date_sent>1462361196</date_sent><save_to_history>1</save_to_history></extraParams></message>

to check i added recipient Id as property, if you look in the stanza the recipient ID is "12075130" different and actual to   "12234589" is different.  

And sometime it happens like the to field is same as sender like  <message to='12075130-35886 ......
when my sender id is also same.

Please tell if you have any solution for this, I am stucked for quite a long..
help would be appreciated.

**Comment by Hemant0601** [comment]
@soulfly any update on this issue?

**Comment by soulfly** [comment]
Not sure that I understand this issue

Could you show some code to better understand this issue

**Comment by Hemant0601** [comment]
@soulfly I have made few changes to achieve notification for incoming messages even when I am not on ChatActivity.. so for that my privateChatconnection class is as:
`package com.softdew.orahi.service;


import com.quickblox.chat.QBChatService;
import com.quickblox.chat.QBGroupChat;
import com.quickblox.chat.QBPrivateChat;
import com.quickblox.chat.QBPrivateChatManager;
import com.quickblox.chat.listeners.QBPrivateChatManagerListener;
import com.quickblox.chat.model.QBChatMessage;
import com.quickblox.chat.model.QBDialog;
import com.softdew.orahi.CustomLogger.Log;
import com.softdew.orahi.activity.OrahiBaseActivity;
import com.softdew.orahi.chat.core.Chat;
import com.softdew.orahi.models.qb.MyQBMessages;
import com.softdew.orahi.utilities.Constants;

import org.jivesoftware.smack.SmackException;
import org.jivesoftware.smack.XMPPException;


public class PrivateChatConnectionCentral extends OrahiBaseActivity implements Chat, QBPrivateChatManagerListener {
    private static final String TAG = "PrivateChatConnCentral";

    private OrahiBaseActivity orahiBaseActivity;
    private QBDialog qbDialog;

    private QBPrivateChatManager privateChatManager;
    private QBPrivateChat privateChat;

    @Override
    public QBPrivateChat getPrivateChat() {
        return privateChat;
    }

    @Override
    public QBGroupChat getGroupChat() {
        return null;
    }


    public PrivateChatConnectionCentral(OrahiBaseActivity orahiBaseActivity, Integer opponentID, QBDialog qbDialog) {
        try {

            this.orahiBaseActivity = orahiBaseActivity;
            this.qbDialog = qbDialog;
            initManagerIfNeed();

            if (privateChatManager != null) {
                privateChat = privateChatManager.getChat(opponentID);
                if (privateChat == null) {
                    privateChat = privateChatManager.createChat(opponentID, messageListenerPrivate);
                } else {
                    Constants.registeredForListeners.add(qbDialog.getDialogId());
                    privateChat.addMessageListener(messageListenerPrivate);
                    privateChat.addMessageSentListener(privateMessageSentListener);

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void initManagerIfNeed() {
        try {
            if (privateChatManager == null) {
                privateChatManager = QBChatService.getInstance().getPrivateChatManager();
                privateChatManager.addPrivateChatManagerListener(this);
            }
        } catch (Exception e) {
            //showShortToast("Some error occured. Please try again later");
        }
    }

    @Override
    public void sendMessage(QBChatMessage message) throws XMPPException, SmackException.NotConnectedException {
        try {
            if (privateChat != null) {
                privateChat.sendMessage(message);
                MyQBMessages.saveQbMessage(message, Constants.RECEIPTS.SENT);

            } else {
                Constants.privateChatObjectMap.remove(qbDialog.getDialogId());

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void release() {

    }

    @Override
    public void chatCreated(QBPrivateChat incomingPrivateChat, boolean createdLocally) {
        if (!createdLocally) {
            Constants.registeredForListeners.add(qbDialog.getDialogId());
            privateChat = incomingPrivateChat;
            privateChat.addMessageListener(messageListenerPrivate);
            privateChat.addMessageSentListener(privateMessageSentListener);
        }

        Log.w(TAG, "private shadow chat created: " + incomingPrivateChat.getParticipant() + ", createdLocally:" + createdLocally);
    }


    @Override
    protected String getTag() {
        return null;
    }

    @Override
    public void findViewById() {

    }

    @Override
    public void reloadRequest() {

    }
}
`
now when I send message which is using this code 
`try {
            int qbidInt = 0;
            try {
                String qbid = OrahiPreferences.loadMap(OrahiPreferences.QB_USER).get("id");
                qbidInt = Integer.parseInt(qbid);
            } catch (Exception e) {
                e.printStackTrace();
            }

            QBChatMessage chatMessage = new QBChatMessage();
            chatMessage.setBody(messageText);
            if (messageText.contains(Constants.API_KEY)) {
                chatMessage.setProperty(PROPERTY_SAVE_TO_HISTORY, "0");

            } else {
                chatMessage.setProperty(PROPERTY_SAVE_TO_HISTORY, "1");
            }
            chatMessage.setDateSent(new Date().getTime() / 1000);
            chatMessage.setProperty("message_id", chatMessage.getId());
            chatMessage.setDialogId(dialog.getDialogId());
            if (qbidInt > 0) {
                chatMessage.setSenderId(qbidInt);
                chatMessage.setProperty("sender_id", qbidInt + "");
            }
            chatMessage.setMarkable(true);

            try {
                if (chat != null && Util.haveNetworkConnection(AppController.getInstance())) {
                    if (dialog.getType() == QBDialogType.PRIVATE) {
                        //Integer opponentID = ActivityUtils.getOpponentIDForPrivateDialog(dialog);
                        //chatMessage.setProperty("opponent_id", opponentID + "");

                        chatMessage.setRecipientId(ActivityUtils.getPrivateRecipientID(dialog));
                        chatMessage.setProperty("recipient_id", ActivityUtils.getPrivateRecipientID(dialog) + "");

                        showMessage(chatMessage, true, Constants.RECEIPTS.PENDING);
                    } else {
                        showMessage(chatMessage, true, Constants.RECEIPTS.PENDING);
                    }

                    chat.sendMessage(chatMessage);


                } else {
                    initChat();
                    showMessage(chatMessage, true, Constants.RECEIPTS.PENDING);
                }

                messageEditText.setText("");

                updateAdapter();
                //sendQBPushNotification(dialog, messageText);

            } catch (XMPPException e) {
                Log.e(TAG, "failed to send a message", e);
            } catch (SmackException sme) {
                Log.e(TAG, "failed to send a message", sme);
            }


            if (chat == null) {

                if (!Util.haveNetworkConnection(AppController.getInstance())) {
                    Toast.makeText(ChatActivity.this, "Please check your internet connection", Toast.LENGTH_SHORT).show();

                } else {

                    //Toast.makeText(ChatActivity.this, "Please wait. Connecting...", Toast.LENGTH_SHORT).show();
                }
                recreateSession();
                createChatObjectIFNotExists();

            }
        } catch (Exception e) {
            e.printStackTrace();
        }`

my message is sent to wrong recipient that is some random QBUSER from my account only.. 

Tell me if you need anymore code...

**Comment by Hemant0601** [comment]
@soulfly Please respond its urgent, I have a PRO account now but still no help. Please provide update on this and other few issues mentioned by me.
