### ISSUE TITLE
QBChatService.getChatDialogs returns an error: Token is required.

### ISSUE THREAD

**Issue by estysherman** [QuickBlox/quickblox-android-sdk#194]
On createChatDialog() function ,
I call QBChatService.getChatDialogs(...).
I got an error: com.quickblox.core.exception.QBResponseException: Token is required.
What does it mean? what is the error?

### private void createChatDialog() {
        QBRequestGetBuilder requestBuilder = new QBRequestGetBuilder();
        requestBuilder.setLimit(100);
        requestBuilder.addRule("_id", QueryRule.EQ, mGroup.getNvQBDialogId());

      QBChatService.getChatDialogs(QBDialogType.GROUP, requestBuilder, new      QBEntityCallback<ArrayList<QBDialog>>() {
            @Override
            public void onSuccess(ArrayList<QBDialog> dialogs, Bundle args) {
                int totalEntries = args.getInt("total_entries");
                QBDialog dialog = dialogs.get(0);
                mAddMembersCustomViewBtn.setQBDialog(dialog);
                mChatView.startChat(mUserInGroup, QBDialogType.GROUP, dialog, mGroup.getNvGroupName(), GroupChatFragment.getInstance(), mGroup.getiGroupId());

            }

            @Override
            public void onError(QBResponseException errors) {
                Log.e("createChatDialog","Error");
            }
        });
###    }

what could be the problem?

**Comment by soulfly** [comment]
Duplicate https://github.com/QuickBlox/quickblox-android-sdk/issues/195
