### ISSUE TITLE
QBChatService.getChatDialogs returns an error: Token is required.

### ISSUE THREAD

**Issue by estysherman** [QuickBlox/quickblox-android-sdk#195]
On createChatDialog() function ,
I call QBChatService.getChatDialogs(...).
I got an error: com.quickblox.core.exception.QBResponseException: Token is required.
What does it mean? what is the error?

private void createChatDialog() {

    QBRequestGetBuilder requestBuilder = new QBRequestGetBuilder();
    requestBuilder.setLimit(100);
    requestBuilder.addRule("_id", QueryRule.EQ, mGroup.getNvQBDialogId());

  QBChatService.getChatDialogs(QBDialogType.GROUP, requestBuilder, new      QBEntityCallback<ArrayList<QBDialog>>() {
        @Override
        public void onSuccess(ArrayList<QBDialog> dialogs, Bundle args) {
            int totalEntries = args.getInt("total_entries");
            QBDialog dialog = dialogs.get(0);
            mAddMembersCustomViewBtn.setQBDialog(dialog);
            mChatView.startChat(mUserInGroup, QBDialogType.GROUP, dialog, mGroup.getNvGroupName(), GroupChatFragment.getInstance(), mGroup.getiGroupId());

        }

        @Override
        public void onError(QBResponseException errors) {
            Log.e("createChatDialog","Error");
        }
    });
}

what could be the problem?

**Comment by soulfly** [comment]
You have to create a session and login as user in order to retrieve your chat dialogs

Read more here http://quickblox.com/developers/Android#A_couple_of_words_about_Authentication_and_Authorization

**Comment by estysherman** [comment]
hi,
thank you for your help.
I checked what you wrote.
QBAuth.createSession(...) is Success.
and chatService.login(...) is Success too.
what could be the problem?

**Comment by soulfly** [comment]
You have to call for GET dialogs inside 'onSuccess' callback method because all operations are async

**Comment by estysherman** [comment]
I did not understand what you meant.
 'onSuccess' callback of chatService.login(...)?

**Comment by soulfly** [comment]
```
// Login
QBUsers.signIn(user, new QBEntityCallback<QBUser>() {
    @Override
    public void onSuccess(QBUser user, Bundle args) {
        // success
        // QBChatService.getChatDialogs(...
    }
 
    @Override
    public void onError(QBResponseException error) {
        // error
    }
});
```

**Comment by estysherman** [comment]
I will try it, thank meantime.
