### ISSUE TITLE
com.quickblox.core.exception.QBResponseException: Authentication failed, check user's ID and password

### ISSUE THREAD

**Issue by parthivikky** [QuickBlox/quickblox-android-sdk#196]
I am getting this error. Please help me to fix it. 

I am getting user id and password from the user and created session for the user. The session was successfully created. I was trying QBChatService.login inside of session's onSuccess. But I am getting this error when QBChatService login.

**Comment by yolapop** [comment]
How did you resolve this?

**Comment by edwinlemmon** [comment]
I think i'm facting this issue too.. Any help?

**Comment by RomanPronin** [comment]
Hi, as stated in the exception, check whether you set valid password and ID for your user. Also you can set userID like this: after QBAuth.createSession(user) in onSuccess(QBSession session, Bundle args) set user.setId(session.getUserId()); and then do QBChatService.getInstance().login(user);
