### ISSUE TITLE
On Group Chat a new user can not be able to join exisitng Group.

### ISSUE THREAD

**Issue by satyaki1988** [QuickBlox/quickblox-android-sdk#20]
QBDialog dialogToUpdate = new QBDialog();
dialogToUpdate.setDialogId("dialog_id");
QBCustomObjectUpdateBuilder requestBuilder = new QBCustomObjectUpdateBuilder();
requestBuilder.push("occupants_ids", 1720008);

QBChatService.getInstance().getGroupChatManager().updateDialog(dialogToUpdate, requestBuilder, new QBEntityCallbackImpl<QBDialog>() 
        {
             @Override
             public void onSuccess(QBDialog dialog, Bundle args) 
             {
                 Log.d("Dialog Update details", "dialog: " + dialog);
             }
             @Override
             public void onError(List<String> errors) 
             {
                  AlertDialog.Builder dialog = new AlertDialog.Builder(JoinGroupActivity.this);
                  dialog.setMessage("dialog creation errors: " + errors).create().show();
             }
         });

But it gives the result  '{"errors":["You don't have appropriate permissions to perform this operation"]}'

**Comment by Hemant0601** [comment]
You don't have appropriate permissions to perform this operation.
I am always getting above permission while adding members to group dialog.(PUBLIC).
First time it works fine , but second time it starts giving me this error. I am adding and removing from the same account which created the dialog.
Please help, I am using following method for it.

QBRequestUpdateBuilder requestBuilder = new QBRequestUpdateBuilder();
requestBuilder.push("occupants_ids", values);

        QBGroupChatManager groupChatManager = QBChatService.getInstance().getGroupChatManager();

        groupChatManager.updateDialog(qbDialog, requestBuilder, new QBEntityCallback<QBDialog>() {
            @Override
            public void onSuccess(QBDialog qbDialog, Bundle bundle) {
                Log.v(TAG, "user added successfully");
            }

            @Override
            public void onError(QBResponseException e) {
                Log.v(TAG, "user added failed" + e.getMessage());

            }
        });
For Removing : QBRequestUpdateBuilder requestBuilder = new QBRequestUpdateBuilder();
// requestBuilder.push("occupants_ids", 378); // add another users

    requestBuilder.pullAll("occupants_ids", values); // Remove yourself (user with ID 22)

    QBGroupChatManager groupChatManager = QBChatService.getInstance().getGroupChatManager();
    groupChatManager.updateDialog(qbDialog, requestBuilder, new QBEntityCallback<QBDialog>() {
        @Override
        public void onSuccess(QBDialog qbDialog, Bundle bundle) {
            Log.v(TAG, "Removing success");
        }

        @Override
        public void onError(QBResponseException e) {
            Log.v(TAG, "Removing Failure"+e.getMessage());

        }
    });

**Comment by YogeshSeralia** [comment]
I am using the same code provided in sample of android chat code to join the group which i have created  by this code : 

```
currentChatRoom.join(history, new QBEntityCallbackImpl() {
            @Override
            public void onSuccess() {
                log("join Room success");

                // add listeners
                currentChatRoom.addMessageListener(groupChatQBMessageListener);
            }

            @Override
            public void onError(final List list) {
                log("join Room error: " + list);
            }
        });
```

I am not getting entered in either of `onSuccess()` and `onError()` ,control flow just goes bypassing callback methods.
