### ISSUE TITLE
Quickblox android javascript QBRTCClientSessionCallbacks » and « QBRTCSessionConnectionCallbacks

### ISSUE THREAD

**Issue by YoussefBha** [QuickBlox/quickblox-android-sdk#201]
Some Issues with Java interfaces of Quickblox « QBRTCClientSessionCallbacks » and « QBRTCSessionConnectionCallbacks ».

Web SDK JS Quickblox Native Android : Once the call is started from a web page with JavaScript SDK to an Android application, the user connected with Android application get notified, in case of accepting, the connection is established well. However, if the call is hanged up by any user, the session in the Android application doesn’t get released and can’t make new call or receive call any more. Function onSessionClosed from QBRTCClientSessionCallbacks interface is not called.

Native Android Web SDK JS Quickblox. No problems, session released correctly.

**Comment by RomanPronin** [comment]
Check latest version [SDK](https://quickblox.com/developers/Android) with new fixes and features in Webrtc functionality.
