### ISSUE TITLE
How to extract local video stream (camera) in quickblox Android?

### ISSUE THREAD

**Issue by dindinii** [QuickBlox/quickblox-android-sdk#209]
How to take a picture from camera while video chatting by using quickbloxsdk?

How to capture particular frame in local video view(from local camera) while on video chat and convert into a bitmap in quickblox android sdk 2.5.1?

In video chat I have one button,Once user click the button I have to get the picture from camera(local video view - RTCGLVideoView). Camera is already in use so can't able to take picture without preview.

**Comment by RomanPronin** [comment]
Look at [doc](https://quickblox.com/developers/Sample-webrtc-android#Obtain_video_tracks_via_QBRTCClientVideoTracksCallbacks_interface), so you should add QBRTCClientVideoTracksCallbacks to get video tracks. Add VideoRenderer to video track via videoTrack.addRenderer.
For getting frame extend video view - QBRTCSurfaceView and override method renderFrame.
