### ISSUE TITLE
Can we make custom group chat using Custom Objects?

### ISSUE THREAD

**Issue by satyaki1988** [QuickBlox/quickblox-android-sdk#21]
I would like to make group chat which have the following features:
1) Any user can create a group chat
2) If any user would like to join this group then they just put the group code and join this group.
3) After that only those member chat with each other
4) Any user can leave any time from this group.
5) Only admin has access to delete the group, block any person 

So, how can I achive this goal through your android 2.o beat version code, because all the study documentation are based on old version.

**Comment by soulfly** [comment]
This is doable via standard QuickBlox Chat API

http://quickblox.com/developers/Android_XMPP_Chat_Sample
