### ISSUE TITLE
Message sent listener not working for QBPrivateChat 

### ISSUE THREAD

**Issue by Hemant0601** [QuickBlox/quickblox-android-sdk#215]
Message sent listener not working for Private Chat, its working fine and smooth for Group Chat but not for private chat. I have my listener in my base activity...

`final public QBMessageSentListener<QBPrivateChat> privateMessageSentListener = new QBMessageSentListener<QBPrivateChat>() {
        @Override
        public void processMessageSent(QBPrivateChat qbPrivateChat, QBChatMessage qbChatMessage) {
            Log.w(TAG, "Private Message sent successfull " + qbChatMessage.getBody());
            NewMessageSentObserver.processPrivateMessageSent(qbPrivateChat, qbChatMessage);

        }

        @Override
        public void processMessageFailed(QBPrivateChat qbPrivateChat, QBChatMessage qbChatMessage) {
            Log.w(TAG, "Private Message sending failed " + qbChatMessage.getBody());
            NewMessageSentObserver.processPrivateMessageFailed(qbPrivateChat, qbChatMessage);

        }
    };`

Also my private chat connection class as follows
`public class PrivateChatConnectionCentral extends OrahiBaseActivity implements Chat, QBPrivateChatManagerListener {
    private static final String TAG = "PrivateChatConnCentral";
    private OrahiBaseActivity orahiBaseActivity;
    private QBDialog qbDialog;

    private QBPrivateChatManager privateChatManager;
    private QBPrivateChat privateChat;

    @Override
    public QBPrivateChat getPrivateChat() {
        return privateChat;
    }

    @Override
    public QBGroupChat getGroupChat() {
        return null;
    }

    public PrivateChatConnectionCentral(OrahiBaseActivity orahiBaseActivity, Integer opponentID, QBDialog qbDialog) {
        try {

            this.orahiBaseActivity = orahiBaseActivity;
            this.qbDialog = qbDialog;
            initManagerIfNeed();

            if (privateChatManager != null) {
                privateChat = privateChatManager.getChat(opponentID);
                if (privateChat == null) {
                    privateChat = privateChatManager.createChat(opponentID, messageListenerPrivate);
                } else {
                    Constants.registeredForListeners.add(qbDialog.getDialogId());
                    privateChat.addMessageListener(messageListenerPrivate);
                    privateChat.addMessageSentListener(privateMessageSentListener);

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void initManagerIfNeed() {
        try {
            if (privateChatManager == null) {
                privateChatManager = QBChatService.getInstance().getPrivateChatManager();
                privateChatManager.addPrivateChatManagerListener(this);
            }
        } catch (Exception e) {
            //showShortToast("Some error occured. Please try again later");
        }
    }

    @Override
    public void sendMessage(QBChatMessage message) throws XMPPException, SmackException.NotConnectedException {
        try {
            if (privateChat != null) {
                privateChat.sendMessage(message);
                MyQBMessages.saveQbMessage(message, Constants.RECEIPTS.SENT);

            } else {
                Constants.privateChatObjectMap.remove(qbDialog.getDialogId());

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void release() {

    }

    @Override
    public void chatCreated(QBPrivateChat incomingPrivateChat, boolean createdLocally) {
        if (!createdLocally) {
            Constants.registeredForListeners.add(qbDialog.getDialogId());
            privateChat = incomingPrivateChat;
            privateChat.addMessageListener(messageListenerPrivate);
            privateChat.addMessageSentListener(privateMessageSentListener);
        }

        Log.w(TAG, "private shadow chat created: " + incomingPrivateChat.getParticipant() + ", createdLocally:" + createdLocally);
    }

    @Override
    protected String getTag() {
        return null;
    }

    @Override
    public void findViewById() {

    }

    @Override
    public void reloadRequest() {

    }
}`

**Comment by Hemant0601** [comment]
@soulfly Please respond its urgent, I have a PRO account now but still no help. Please provide update on this and other few issues mentioned by me.

**Comment by guffyWave** [comment]
Even I am facing the same issue.But you may be interested in the following listener 

        QBMessageStatusListener   messageStatusListener = new QBMessageStatusListener() {
            @Override
            public void processMessageDelivered(final String messageId, String dialogId, Integer userId) {
                Log.d(TAG, "processMessageDelivered: Message DELIVERED : message ID " + messageId);
            }

            @Override
            public void processMessageRead(final String messageId, String dialogId, Integer userId) {
                Log.d(TAG, "processMessageRead: Message READ : message ID " + messageId);
            }
        };
        messageStatusesManager.addMessageStatusListener(messageStatusListener);

Please also check  mesage sent status by
        
          try{
                //blah blah
                 yourchatservice.sendMessage(chatMessage);
          } catch (XMPPException e) {
            Log.e(TAG, "Failed to send a message", e);
          } catch (SmackException sme) {
              Log.e(TAG, "Failed to send a message", sme);
           } catch (Exception e) {
              Log.e(TAG, "Failed to send a message", e);
          }


My objective was resolved by above as I do have SENT,DELIVERED and READ status.

**Comment by tatanka987** [comment]
hello @guffyWave, for work message sent listener your must use stream management, for it need call chatService.setUseStreamManagement(true); before login to the chat, details by [link](http://quickblox.com/developers/Android_XMPP_Chat_Sample#Sent_status )

**Comment by turkovsky** [comment]
I have the similar problem
fun observeIncomingMessages(dialog: QBChatDialog? = null): Flowable<ObservableMessage> {
        return Flowable.create({ emitter ->
            val listener = object : QBChatDialogMessageListener {
                override fun processMessage(dialogId: String, message: QBChatMessage, senderId: Int) {
                    emitter.onNext(Triple(dialogId, message, senderId))
                    toLog("processMessage ${message.body} -> ${message.id}")
                }

                override fun processError(dialogId: String, error: QBChatException?, message: QBChatMessage, senderId: Int) {
                    emitter.onError(error ?: UnknownException())
                }
            }
            val action: Action =
                    if (dialog == null) {
                        chatService.incomingMessagesManager.addDialogMessageListener(listener)
                        Action { chatService.incomingMessagesManager.removeDialogMessageListrener(listener) }
                    } else {
                        dialog.addMessageListener(listener)
                        Action { dialog.removeMessageListrener(listener) }
                    }
            emitter.setDisposable(Disposables.fromAction(action))
        }, BUFFER)
    }

Listener doesn't work when type of dialog is PRIVATE.
With GROUP works correctly

**Comment by RomanPronin** [comment]
@turkovsky, here are some explanations, QBChatDialogMessageListener serves to listen for messages.
QBMessageStatusListener serves to listen delivered/read the status of the message.

**Comment by turkovsky** [comment]
I'm about QBChatDialogMessageListener
It works only with GROUP dialog, not with PRIVATE dialog

**Comment by Hemant0601** [comment]
@turkovsky I would suggest you build your own chat rather than relying on QB, I faced a major issues with QB services, issue exist in QB jar and there is no way you can fix and QB charges even for that.
Use MQTT with ChatUI, it will be hell easier.
