### ISSUE TITLE
Sample videochat - distorted video stream

### ISSUE THREAD

**Issue by AustrianDudes** [QuickBlox/quickblox-android-sdk#217]
I have installed the sample video chat app on several Android devices. On my Samsung Tab A running Android 5.0.2 the incoming video streams are showing up distorted after about 20-30 seconds: 

![device-2016-06-06-100222](https://cloud.githubusercontent.com/assets/6713344/15815622/94e8d41c-2bce-11e6-85c6-8a4691fa467d.png)

I have gone through the logs an figured out that a "decoder format changed" message is logged simultaneously with the video getting messed up:

06-06 10:00:09.779 31260-6050/com.quickblox.sample.groupchatwebrtc D/MediaCodecVideoDecoder: Decoder format changed: {image-data=java.nio.ByteArrayBuffer[position=0,limit=80,capacity=80], mime=video/raw, crop-top=0, crop-right=639, slice-height=480, color-format=19, height=480, width=640, what=1869968451, crop-bottom=479, crop-left=0, stride=640}

06-06 10:00:33.499 31260-6050/com.quickblox.sample.groupchatwebrtc D/MediaCodecVideoDecoder: Decoder format changed: {image-data=java.nio.ByteArrayBuffer[position=0,limit=80,capacity=80], mime=video/raw, crop-top=0, crop-right=479, slice-height=384, color-format=19, height=360, width=480, what=1869968451, crop-bottom=359, crop-left=0, stride=512}

Has anybody experienced a similar issue and can provide me with some ideas on how to resolve this issue?

**Comment by AustrianDudes** [comment]
I just found an issue which could be related to this: 
https://bugs.chromium.org/p/webrtc/issues/detail?id=4787

**Comment by vfite** [comment]
Could you change video resolution to one of listed in settings ?

**Comment by AustrianDudes** [comment]
I found a workaround for this issue. By deactivating the hardware acceleration for videos, the distorted video stopped to appearing during the chat.

QBRTCMediaConfig.setVideoHWAcceleration(false);
