### ISSUE TITLE
How to take screenshot of video call in quickblox android sdk 2.5.2?(access camera)

### ISSUE THREAD

**Issue by dinodroid** [QuickBlox/quickblox-android-sdk#218]
how to extract local media stream from the session in order to work with the local video(camera). I would like to extract the video/frames from the session (the local videostream) to further process (save image as bitmap) or how to take a screenshot of RTCGLVideoView(camera view)?

**Comment by RomanPronin** [comment]
Use our latest version [SDK](https://quickblox.com/developers/Android#Framework_changelog). 
Also look at [doc](https://quickblox.com/developers/Sample-webrtc-android#Obtain_video_tracks_via_QBRTCClientVideoTracksCallbacks_interface), so you should add QBRTCClientVideoTracksCallbacks to get video tracks. Add VideoRenderer to video track via videoTrack.addRenderer.
For getting frame extend video view - QBRTCSurfaceView and override method renderFrame.

**Comment by priteshimp** [comment]
I got the frame but not seeing any option/code to convert it to bitmap anyhow,
 @Override
    public void renderFrame(VideoRenderer.I420Frame frame) {
        super.renderFrame(frame);      
    }

**Comment by RomanPronin** [comment]
Hi, @priteshimp. To get bitmap you can register a callback to be invoked when a new video frame has been received, addFrameListener(EglRenderer.FrameListener listener, float scale). For example in onLocalVideoTrackReceive():
```java
public void onLocalVideoTrackReceive(QBRTCSession qbrtcSession, final QBRTCVideoTrack videoTrack) {
...
        localVideoView.addFrameListener(new EglRenderer.FrameListener() {
            @Override
            public void onFrame(Bitmap bitmap) {
                Log.d(TAG, "onFrame bitmap= " + bitmap);
            }
        }, 1f);
}
```
