### ISSUE TITLE
Error: cannot find symbol method getTotalUnreadMessagesCount(Set<String>,<anonymous QBEntityCallback<Integer>>)

### ISSUE THREAD

**Issue by ChaitraKavya** [QuickBlox/quickblox-android-sdk#226]
I'm trying to get total unread message count form QuickBlox earlier i was using qbsdk 2.5 and now i updated qbsdk to 2.5.2 now gradle build is failing with this error

**Comment by tatanka987** [comment]
you should use this method like this QBChatService.getTotalUnreadMessagesCount(dialogIDs, callback);

**Comment by ChaitraKavya** [comment]
QBChatService.getTotalUnreadMessagesCount(dialogsIds, new QBEntityCallback<Integer>() {
            @Override
            public void onSuccess(Integer integer, Bundle bundle) {
                Log.i("TAG", "total unread messages: " + bundle);
                Log.i("TAG", "dialog Unread: " + bundle);
            }

            @Override
            public void onError(QBResponseException e) {
                e.printStackTrace();
            }
        });

This is how i'm using when i try to run the app compilation fails with this error

**Comment by tatanka987** [comment]
please review our documentation by QuickBlox Android SDK https://sdk.quickblox.com/android/  and provide us full log from Android Studio with this error
