### ISSUE TITLE
QBMessageSentListener/QBMessageStatustListener is not called in gorup chat for android

### ISSUE THREAD

**Issue by ChaitraKavya** [QuickBlox/quickblox-android-sdk#231]

**Comment by guffyWave** [comment]
Even I am facing the same issue.But you may be interested in following listener 

   QBMessageStatusListener   messageStatusListener = new QBMessageStatusListener() {
            @Override
            public void processMessageDelivered(final String messageId, String dialogId, Integer userId) {
                Log.d(TAG, "processMessageDelivered: Message DELIVERED : message ID " + messageId);
            }

            @Override
            public void processMessageRead(final String messageId, String dialogId, Integer userId) {
                Log.d(TAG, "processMessageRead: Message READ : message ID " + messageId);
            }
        };
        messageStatusesManager.addMessageStatusListener(messageStatusListener);
Please also check  mesage sent status by
     try{
             //blah blah
              yourchatservice.sendMessage(chatMessage);
       } catch (XMPPException e) {
            Log.e(TAG, "Failed to send a message", e);
        } catch (SmackException sme) {
            Log.e(TAG, "Failed to send a message", sme);
        } catch (Exception e) {
            Log.e(TAG, "Failed to send a message", e);
        }


My objective was resolved by above as I do have SENT,DELIVERED,READ status.

**Comment by tatanka987** [comment]
hello @guffyWave,  for mark messages as read, messages's receiver must call method groupChat.readMessage(chatMessage), more details by [link ](http://quickblox.com/developers/Android_XMPP_Chat_Sample#Read_status) (this code actual and for group chats)

**Comment by tatanka987** [comment]
Close. Long time inactivity.

**Comment by imvikasrai** [comment]
i m also  facing the same issue in one to one chat  i also tried with groupChat.readMessage(chatMessage) but it didnt work fine..in callback of processMessageRead i got different ids not the send message id..
