### ISSUE TITLE
when updating user information tags become empty

### ISSUE THREAD

**Issue by Asimkahn** [QuickBlox/quickblox-android-sdk#233]
when i am updating user information like status, image etc. tag become empty at admin panel.
According to new quick blox 2.6 sdk documentation
"Fixed QBUsers.updateUser query. To delete tags from user put empty StringifyArrayList to QBUser.setTags method. If you put null then tags won't be changed."

after reading this i am setting setTag(null) but tag column still become empty.

**Comment by pelipetsaa** [comment]
Is this issue still actual?
