### ISSUE TITLE
Broadcasting message to all users not working 

### ISSUE THREAD

**Issue by dilipvinu** [QuickBlox/quickblox-android-sdk#239]
The [QuickBlox docs](http://quickblox.com/developers/SimpleSample-messages_users-android) say I can create one user which will have all device ids associated with it and send a push to that user to send a broadcast. However the push is only sent to the first device the user signed in on. I tried sending push from both QuickBlox dashboard and through Android SDK. The GCM registration is fine on other devices, I've verified that by sending push to those devices from [here](http://apns-gcm.bryantan.info/). Is this feature not available yet?

Push subscribed this way

```
    QBSubscription subscription = new QBSubscription(QBNotificationChannel.GCM);
    subscription.setEnvironment(QBEnvironment.PRODUCTION);
    String deviceId = DeviceId.getDeviceId(context);
    subscription.setDeviceUdid(deviceId);
    subscription.setRegistrationID(gcmRegistrationId);

    QBPushNotifications.createSubscription(subscription, new QBEntityCallback<ArrayList<QBSubscription>>() {
        @Override
        public void onSuccess(ArrayList<QBSubscription> qbSubscriptions, Bundle bundle) {
            Log.i(Consts.TAG, "Push subscribed");
        }

        @Override
        public void onError(QBResponseException e) {
            Log.w(Consts.TAG, "Push not subscribed");
        }
    });
```

**Comment by pelipetsaa** [comment]
Is this issue still actual?

**Comment by pelipetsaa** [comment]
Close. long time inactivity
