### ISSUE TITLE
How can I delete a user completely?

### ISSUE THREAD

**Issue by estysherman** [QuickBlox/quickblox-android-sdk#241]
Including his dialogs.
I want to delete a user (not me, other user) from dashboard by Android code.

I try to delete user:

> QBUsers.deleteUser(qbUserId, new QBEntityCallback<Void>() {
>             @Override
>             public void onSuccess(Void aVoid, Bundle bundle) {
>                 callback.doAfterTask(true);
>             }
> 
> ```
>         @Override
>         public void onError(QBResponseException e) {
>             callback.doAfterTask(false);
>         }
>     });
> ```

but I get exception:  base You are not owner of this object.
any one can help?

**Comment by vinaywadhwa** [comment]
same problem

**Comment by tatanka987** [comment]
User can delete only himself.
