### ISSUE TITLE
An existing user in group chat is unable to add other user

### ISSUE THREAD

**Issue by neel-trantor** [QuickBlox/quickblox-android-sdk#242]
QBRequestUpdateBuilder requestBuilder = new QBRequestUpdateBuilder();

```
                    requestBuilder.pushAll("occupants_ids", usersIds);
```

QBDialog dialog = new QBDialog();
dialog.setType(QBDialogType.GROUP);
dialog.setName("My Group");

QBChatService.getInstance().getGroupChatManager().updateDialog(dialog, requestBuilder, new QBEntityCallback<QBDialog>() {
                        @Override
                        public void onSuccess(QBDialog dialog, Bundle args) {

```
                    }

                    @Override
                    public void onError(QBResponseException errors) {



                    }
                });
```

But I am getting "You don't have appropriate permissions to perform this operation" error

Please help me on this.

**Comment by pelipetsaa** [comment]
Please read documentation
https://quickblox.com/developers/Android_XMPP_Chat_Sample
Update group dialog
