### ISSUE TITLE
Maintain session active

### ISSUE THREAD

**Issue by vihangptl** [QuickBlox/quickblox-android-sdk#244]
Hello,

Can any one give me solution about how to keep user logged in and getting messages when app is background or kill?
How I will keep-alive user's session token so i can get messages and notifications?

**Comment by Emeritus-androiddev1** [comment]
Did you find a solution to this?

**Comment by vihangptl** [comment]
No

**Comment by vihangptl** [comment]
in case you find solution, please post here.

**Comment by tatanka987** [comment]
hello, for getting notifications in background you can use QuickBlox push notifications, details by link http://quickblox.com/developers/SimpleSample-messages_users-android or http://quickblox.com/developers/Android_XMPP_Chat_Sample#Push_notifications_to_the_offline_users  for this need realize logout functions if app move to background and login functions if app move foreground.   Or you can use class Service of Android, you can move chat login functions and managing of dialogs to Service (but this method not optimal).

**Comment by vfite** [comment]
Closed as for inactivity

**Comment by haris15** [comment]
do you find any solution ?
if yes please help me
