### ISSUE TITLE
Android sdk doesnt ignore invalid session when simultaneous call on web and android app

### ISSUE THREAD

**Issue by arpit87** [QuickBlox/quickblox-android-sdk#247]
I have implemented video call on website and android app. Same call when comes to both web and app and is accepted from web then android app crashes because null session to which it tries to attach icecandidates. The javascript sdk ignore invalid session.

07-14 19:01:09.595 13888-15858/in.yolohealth.yolo_doctorapp_android D/QBASDK﹕ Receive Video signal ' call', from User: 4068269, sessionId: b493b16d-089c-4834-84b1-3bf95c2029d3
07-14 19:01:09.595 13888-15858/in.yolohealth.yolo_doctorapp_android D/RTCClient.﹕ Call offer message received from4068269
07-14 19:01:09.595 13888-15858/in.yolohealth.yolo_doctorapp_android D/RTCClient.LooperExecutor﹕ Request Looper execute.
07-14 19:01:09.595 13888-15858/in.yolohealth.yolo_doctorapp_android D/RTCClient.LooperExecutor﹕ POST.Run on thread:6404 for QBRTCClient
07-14 19:01:09.595 13888-13940/in.yolohealth.yolo_doctorapp_android D/SMACK﹕ SENT (0): 
07-14 19:01:09.596 13888-13933/in.yolohealth.yolo_doctorapp_android D/RTCClient.﹕ Session b493b16d-089c-4834-84b1-3bf95c2029d3 exists
07-14 19:01:09.596 13888-13933/in.yolohealth.yolo_doctorapp_android D/RTCClient.QBRTCSession﹕ procRemoteOfferSDP from 4068269
07-14 19:01:13.283 13888-13941/in.yolohealth.yolo_doctorapp_android D/SMACK﹕ RECV (0): b493b16d-089c-4834-84b1-3bf95c2029d314068269103837580audiocandidate:1910078557 1 udp 2122260223 192.168.1.121 50320 typ host generation 00audiocandidate:1910078557 2 udp 2122260222 192.168.1.121 58132 typ host generation 01videocandidate:1910078557 1 udp 2122260223 192.168.1.121 43659 typ host generation 01videocandidate:1910078557 2 udp 2122260222 192.168.1.121 37584 typ host generation 00audiocandidate:4036066025 2 udp 1686052606 124.155.240.29 58132 typ srflx raddr 192.168.1.121 rport 58132 generation 01videocandidate:4036066025 1 udp 1686052607 124.155.240.29 43659 typ srflx raddr 192.168.1.121 rport 43659 generation 01videocandidate:4036066025 2 udp 1686052606 124.155.240.29 37584 typ srflx raddr 192.168.1.121 rport 37584 generation 00audiocandidate:4036066025 1 udp 1686052607 124.155.240.29 50320 typ srflx raddr 192.168.1.121 rport 50320 generation 00audiocandidate:1062895789 1 tcp 1518280447 192.168.1.121 0 typ host tcptype active generation 00audiocandidate:1062895789 2 tcp 1518280446 192.168.1.121 0 typ host tcptype active generation 01videocandidate:1062895789 1 tcp 1518280447 192.168.1.121 0 typ host tcptype active generation 01videocandidate:1062895789 2 tcp 1518280446 192.168.1.121 0 typ host tcptype active generation 00audiocandidate:2661402798 1 udp 41885439 52.76.115.253 59577 typ relay raddr 124.155.240.29 rport 50320 generation 01videocandidate:243536930 2 udp 41885438 52.76.27.81 50637 typ relay raddr 124.155.240.29 rport 37584 generation 00audiocandidate:243536930 2 udp 41885438 52.76.27.81 61231 typ relay raddr 124.155.240.29 rport 58132 generation 01videocandidate:2661402798 1 udp 41885439 52.76.115.253 49508 typ relay raddr 124.155.240.29 rport 43659 generation 01videocandidate:2661402798 2 udp 25108222 52.76.115.253 59182 typ relay raddr 124.155.240.29 rport 37885 generation 00audiocandidate:243536930 1 udp 25108223 52.76.27.81 44631 typ relay raddr 124.155.240.29 rport 37882
07-14 19:01:13.289 13888-13972/in.yolohealth.yolo_doctorapp_android D/QBASDK﹕ Receive Video signal ' iceCandidates', from User: 4068269, sessionId: b493b16d-089c-4834-84b1-3bf95c2029d3
07-14 19:01:13.290 13888-13940/in.yolohealth.yolo_doctorapp_android D/SMACK﹕ SENT (0): 
07-14 19:01:13.290 13888-13972/in.yolohealth.yolo_doctorapp_android D/RTCClient.﹕ onReceiveIceCandidatesFromUser 4068269, session=b493b16d-089c-4834-84b1-3bf95c2029d3
07-14 19:01:13.290 13888-13972/in.yolohealth.yolo_doctorapp_android D/RTCClient.LooperExecutor﹕ Request Looper execute.
07-14 19:01:13.290 13888-13972/in.yolohealth.yolo_doctorapp_android D/RTCClient.LooperExecutor﹕ POST.Run on thread:6404 for QBRTCClient
07-14 19:01:13.290 13888-13933/in.yolohealth.yolo_doctorapp_android D/RTCClient.QBRTCSession﹕ process ice candidates from 4068269
07-14 19:01:13.290 13888-13933/in.yolohealth.yolo_doctorapp_android D/RTCClient.QBPeerChannel﹕ Set iceCandidates in count of: 32
07-14 19:01:13.290 13888-13933/in.yolohealth.yolo_doctorapp_android D/RTCClient.LooperExecutor﹕ Request Looper execute.
07-14 19:01:13.290 13888-13933/in.yolohealth.yolo_doctorapp_android D/RTCClient.LooperExecutor﹕ POST.Run on thread:6436 for QBPeerChannel
07-14 19:01:13.291 13888-15861/in.yolohealth.yolo_doctorapp_android E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-6436
Process: in.yolohealth.yolo_doctorapp_android, PID: 13888
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.webrtc.PeerConnection.addIceCandidate(org.webrtc.IceCandidate)' on a null object reference
at com.quickblox.videochat.webrtc.QBPeerChannel$8.run(QBPeerChannel.java:394)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at com.quickblox.videochat.webrtc.LooperExecutor.run(LooperExecutor.java:73)

**Comment by priyankapc** [comment]
Hi @arpit87  

Does your app working properly on mobile devices ? I means if the app in background does it able to receive call ?

Thanks,
Priyanka

**Comment by RomanPronin** [comment]
Look at our updated [video chat sample](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-webrtc).
