### ISSUE TITLE
Error:SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

### ISSUE THREAD

**Issue by phamminhvu** [QuickBlox/quickblox-android-sdk#252]
_Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)_

**Environment details**
_(Operating system, browser information, SDK version)_

Android SDK

**Did this work before?**

**Expected behavior**

**Actual behavior**
I tried to run the sample on Android Studio. But I alway got this issue. I can not build
**Logs**
_(please, use github [gist](https://gist.github.com/))_

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by RomanPronin** [comment]
It works fine. Besides, there are a lot of new feature, just have a try [samples](https://github.com/QuickBlox/quickblox-android-sdk)
