### ISSUE TITLE
Add Group calling to existing project[Didn't find class]

### ISSUE THREAD

**Issue by jaikikani** [QuickBlox/quickblox-android-sdk#256]
How to add group calling in the existing project? My existing project contains video chat library 2.4.1. So, i am trying to update and add the group calling functionality.
My existing q-municate project working fine one on one video call and audio  call.
And i am updating library and try to make group calling. So class not found error occur below my stackstrace.

 Didn't find class "org.webrtc.VideoCapturerAndroid$NativeObserver" on path: DexPathList[[zip file "/data/app/com.demo.call-1/base.apk"],nativeLibraryDirectories=[/data/app/com.demo.call-1/lib/arm, /vendor/lib, /system/lib]]

**Comment by RomanPronin** [comment]
You should add native libraries - libjingle_peerconnection_so.so files. Have a look at our sample http://quickblox.com/developers/Sample-webrtc-android

**Comment by vfite** [comment]
Closed as for long inactivity
