### ISSUE TITLE
How to record video and audio call in android ? 

### ISSUE THREAD

**Issue by mayank250004** [QuickBlox/quickblox-android-sdk#257]
i want to record calls using android Sdk . 

any developers have any idea then please tell me

**Comment by pelipetsaa** [comment]
Quickblox SDK does not support these features yet. 
You can do it yourself using the documentation
https://quickblox.com/developers/Sample-webrtc-android
Obtain video tracks via QBRTCClientVideoTracksCallbacks interface
Obtain audio tracks

**Comment by pelipetsaa** [comment]
Is this issue still actual?

**Comment by pelipetsaa** [comment]
Close. long time inactivity

**Comment by vasupujy** [comment]
Hi @pelipetsaa  We have facing same issue in Android. We are trying to like this but how can we videoframe into Mp4 vide we are integrating like this.
``
private void fillVideoView(int userId, QBRTCSurfaceView videoView, QBRTCVideoTrack videoTrack,
                               boolean remoteRenderer) {
//
        videoTrack.setEnabled(true);


        videoTrack.addRenderer(new VideoRenderer(i420Frame -> {
            videoView.renderFrame(i420Frame);

        }));
        if (userId != 0) {
            getVideoTrackMap().put(userId, videoTrack);
        }
        if (!remoteRenderer) {
            updateVideoView(videoView, isCurrentCameraFront);
        }
        Log.d(TAG, (remoteRenderer ? "remote" : "local") + " Track is rendering");
    }

please help me if you can how can i record a frame and convert into video.
Thanks in Advance.
