### ISSUE TITLE
Problems with lags and echoes in calls including an Android device

### ISSUE THREAD

**Issue by pzoechner** [QuickBlox/quickblox-android-sdk#26]
Are there any plans to solve the audio problems with calls including an Android device?
I'm experiencing issues of major lags on Android devices as well as metally echoes from an Android device to the other user.
In the iOS-Logs we can see that the audio is obviously be taken care of: Error: "Bad audio data, length x".

Would be great if something similar will be implemented in the Android SDK :-)

**Comment by soulfly** [comment]
New Video calling SDKs are available here 
http://quickblox.com/developers/VideoChat#SDK_.26_code_samples
