### ISSUE TITLE
Offline 1-1 Chat PushNotifications

### ISSUE THREAD

**Issue by harshadaasai** [QuickBlox/quickblox-android-sdk#261]
Hi,

Can anyone please help me out for private chat (1-1 Chat)offline notification.

a. When user is offline, user is not able to receive private chat push Notification and also does not get added in Queue.

But for public_group chat it works.

**Comment by harshadaasai** [comment]
Sorry forgot to mention above issue is for Android.

**Comment by RomanPronin** [comment]
Android provides 'true' background mode but the better way to handle correctly chat offline messages is to do 'Chat logout' when app goes to background and does 'Chat login' when app goes to foreground.
