### ISSUE TITLE
Can I get all  the groups dialogs for user

### ISSUE THREAD

**Issue by estysherman** [QuickBlox/quickblox-android-sdk#263]
I want to get all the groups dialogs,
for specific user, by ID.
how can i do that?

please help.

**Comment by tatanka987** [comment]
you can get only dialogs associated with current user. Server will return all dialogs where current user id is in occupants_ids field OR if type=1(PUBLIC_GROUP). To detect current user id server uses session token.

**Comment by RomanPronin** [comment]
Long time inactivity
