### ISSUE TITLE
Twitter Digits wrong example code / not working

### ISSUE THREAD

**Issue by moritzm** [QuickBlox/quickblox-android-sdk#267]
I am trying to get Twitter Digits login working. The login via Twitter Digits is working so far, but i can not login to Quickblox, because the documentation in https://quickblox.com/developers/SimpleSample-users-android#Signing_In_with_Twitter_Digits is using not existing code. It uses the method `QBUsers.signInUsingTwitterDigits()` which does not exist in the class `QBUsers`.
I am using the Q-Municate source code https://github.com/QuickBlox/q-municate-android.

Any ideas? Is the SDK more up-to-date then the app?

**Comment by pelipetsaa** [comment]
The Twitter Digits was added in the SDK v2.5.
Is the issue still actual?
