### ISSUE TITLE
Update Group Name not working

### ISSUE THREAD

**Issue by Jiten-Medic** [QuickBlox/quickblox-android-sdk#269]
**Environment details**
_(Operating system : Android, SDK version : 2.5.2)_

Hi @QuickBlox-team ,

I am updating the Group Dialog Name, but it throws an error

com.quickblox.core.exception.QBResponseException: You don't have appropriate permissions to perform this operation
ErrorCode : 403

Please suggest on this.

Thanks

**Comment by vfite** [comment]
pls refer to documentation http://quickblox.com/developers/Chat#Update_dialog

**Comment by vfite** [comment]
Closed as for inactivity
