### ISSUE TITLE
QuickBlox 2.0 lib has a problem at the time of load chat history, gives wrong date & time

### ISSUE THREAD

**Issue by satyaki1988** [QuickBlox/quickblox-android-sdk#27]
A problem on loadChatHistory() method on your given sample-chat application (Android) . At the time of loading old chat , it will show wrong date and time, it always show 1970-01-17 02:33:34 ,but at the time of chatting it shows exact date and time.
![device-2014-11-03-181044](https://cloud.githubusercontent.com/assets/9411966/4895203/420ec336-63e4-11e4-97e1-6e997b531811.png)

**Comment by itziksamara** [comment]
is this problem fixed i still get the same issue with API 2.1?

**Comment by soulfly** [comment]
Fixed, close ticket

**Comment by imTefa** [comment]
Hi, is this problem really fixed ?!!, I am using 3.3.0 version.
it returns 01/18/1970 from this line of code
`android.text.format.DateFormat.format("MM/dd/yyy", item.getQbChatDialog().getLastMessageDateSent()).toString();`

**Comment by RomanPronin** [comment]
Hi @imTefa, pay attention getLastMessageDateSent() returns seconds, not milliseconds.

**Comment by imTefa** [comment]
@RomanPronin  thank you.
