### ISSUE TITLE
Rosters are not reloaded for new user login - Android

### ISSUE THREAD

**Issue by Jiten-Medic** [QuickBlox/quickblox-android-sdk#270]
**Environment details**
_(Operating system : Android, browser information : na, SDK version : 2.5.2)_

**Did this work before?**
1) Login the user, roster get loaded with correct information.
2) Logout using the QBUsers.signOut method.
3) Login with different user.
4) Rosters has the list of previously logged-in user, and not re-loaded for the logged-in user.

**Expected behavior**
Rosters should re-loaded for the current login user and should refresh for each login.

**Actual behavior**
Previously logged in users roster still showing after log out and loggedin with other user.

**Steps to reproduce the behavior**
1. login with user A.
2. check the rosters.
3. Logout the user and login with user B.
4. Check the rosters. Previous user roster will be shown.

**Comment by tatanka987** [comment]
hello Jiten-Medic, roster is a chat's function, but method QBUsers.signOut performs logout **from REST** (not from chat), for logout **from chat** you need call QBChatService.getInstance().logout()

**Comment by Jiten-Medic** [comment]
Hi

Yes i am doing the same and pasting my code as below :
-------
ChatHelper.getInstance().logout(new QBEntityCallback<Void>() {
                    @Override
                    public void onSuccess(Void aVoid, Bundle bundle) {

                        QBUsers.signOut(new QBEntityCallback<Void>() {
                            @Override
                            public void onSuccess(Void aVoid, Bundle bundle) {
                                LoginActivity.start(getActivity(), false);
                                getActivity().finish();

                            }

                            @Override
                            public void onError(QBResponseException e) {
                            }
                        });
                    }
-----

But still i am getting the old user Rosters while logged-in with different user.
Also if we call QBChatService.getInstance().logout() is there any need to call the
QBUsers.signOut() method ? or it will be handled automatically.

Currently QBUsers.signOut() never returns the callback result.

Please also let me know how to reset / reload the Rosters with the current user or clear them manually
at the time of the logout.

----- Another Issue ----
While getting the rosters of a fresh user, if i accept the incoming friend request. The roster still shows the status of that user as - RosterPacket.ItemType.from

I am reading the rosters as : 
roster = QBChatService.getInstance().getRoster(QBRoster.SubscriptionMode.mutual,
                new SubscriptionListener());

Please resolve these issues i am having so that i can apply these basic operations, which are
now much delayed.

Thanks

**Comment by Jiten-Medic** [comment]
Or Please let me know the way to update the user roster while accept / reject the request in QB app.
Currently roster doesn't updated with the latest action performed.

Please let me know, as these issues / ways are now way to critical.

Thanks

**Comment by tatanka987** [comment]
Use our latest version [SDK](https://quickblox.com/developers/Android )
