### ISSUE TITLE
Every thing is working fine but one thing is the width of the message comes from the other user is long.....how to reduce the size of the width comes from the user......my android studio  version is 23.......plz help me.......

### ISSUE THREAD

**Issue by purushottam34** [QuickBlox/quickblox-android-sdk#273]
_Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)_

**Environment details**
_(Operating system, browser information, SDK version)_

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
_(please, use github [gist](https://gist.github.com/))_

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by tatanka987** [comment]
hello @purushottam34, please add details about your issue (steps to reproduce and logs if need)

**Comment by parvinderatpercept** [comment]
Can u please let me know how to set up this

**Comment by tatanka987** [comment]
If I correctly understood your issue, new QuickBlox lib [ChatMessagesAdapter for Android](https://github.com/QuickBlox/ChatMessagesAdapter-android) will help you with your problem.
