### ISSUE TITLE
Error code 422 : client error

### ISSUE THREAD

**Issue by AnkitSS77** [QuickBlox/quickblox-android-sdk#274]
[QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: client error (422)" UserInfo=0x175b3030 {com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x175e1710> { URL: https://api.quickblox.com/events.json } { status code: 422, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 45;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Sat, 20 Aug 2016 09:00:42 GMT";
    "QB-Token-ExpirationDate" = "2016-08-20 10:56:59 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    Status = "422 Unprocessable Entity";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = a99335a1ac7b56a3b8bbe7ecd177c10d;
    "X-Runtime" = "0.300226";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
} }, NSErrorFailingURLKey=https://api.quickblox.com/events.json, NSLocalizedDescription=Request failed: client error (422), com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a5b22 4e6f206f 6e652063 616e2072 65636569 76652074 6865206d 65737361 6765225d 7d>}

**Comment by RomanPronin** [comment]
Hi. How did you get this response? Show us full request for this.

**Comment by vfite** [comment]
Closed as for long inactivity
