### ISSUE TITLE
QBSession.startSessionWithDetails not getting  any response

### ISSUE THREAD

**Issue by AnkitSS77** [QuickBlox/quickblox-android-sdk#276]
I am using the my server to generate the token & by using that token i want to start session using following method
QBSession.currentSession().startSessionWithDetails(session)
        {

```
        let updatedSession = QBASession.init()
        session.token = "new token"
        QBSession.currentSession().startSessionWithDetails(updatedSession)
         self.performSegueWithIdentifier("chat", sender: self)
    }
```

but i am not able to get any response not even any logs and the block is no get execute

**Comment by vfite** [comment]
Doesn't relate to android
