### ISSUE TITLE
NoClassDefFoundError when try to run sample-chat

### ISSUE THREAD

**Issue by trietbui85** [QuickBlox/quickblox-android-sdk#28]
After downloading Quickblox sample, I import `sample-chat` project, add required library projects (`android-support-v7-appcompat` and `pull-to-refresh`) as well as JARs (quickblox-android-sdk-chat-2.0.jar and quickblox-android-sdk-core-2.0.jar) as guide from http://quickblox.com/developers/Android_XMPP_Chat_Sample#Eclipse_IDE

I see project can be compiled successful without error. However when run app, right after enter Splash, I receive many warnings first

> 11-04 21:37:16.665: E/dalvikvm(9198): Could not find class 'com.quickblox.users.model.QBUser', referenced from method com.quickblox.sample.chat.ApplicationSingleton.addDialogsUsers
> 11-04 21:37:16.665: W/dalvikvm(9198): VFY: unable to resolve check-cast 1281 (Lcom/quickblox/users/model/QBUser;) in Lcom/quickblox/sample/chat/ApplicationSingleton;
> 11-04 21:37:16.670: W/dalvikvm(9198): VFY: unable to find class referenced in signature (Lcom/quickblox/users/model/QBUser;)
> 11-04 21:37:16.670: W/dalvikvm(9198): VFY: unable to find class referenced in signature (Lcom/quickblox/chat/model/QBDialog;)
> 11-04 21:37:16.670: I/dalvikvm(9198): Could not find method com.quickblox.chat.model.QBDialog.getOccupants, referenced from method com.quickblox.sample.chat.ApplicationSingleton.getOpponentIDForPrivateDialog
> 11-04 21:37:16.670: W/dalvikvm(9198): VFY: unable to resolve virtual method 9782: Lcom/quickblox/chat/model/QBDialog;.getOccupants ()Ljava/util/ArrayList;
> 11-04 21:37:16.670: W/dalvikvm(9198): VFY: unable to find class referenced in signature (Lcom/quickblox/users/model/QBUser;)
> 11-04 21:37:16.670: E/dalvikvm(9198): Could not find class 'com.quickblox.users.model.QBUser', referenced from method com.quickblox.sample.chat.ApplicationSingleton.setDialogsUsers
> 11-04 21:37:16.670: W/dalvikvm(9198): VFY: unable to resolve check-cast 1281 (Lcom/quickblox/users/model/QBUser;) in Lcom/quickblox/sample/chat/ApplicationSingleton;
> 11-04 21:37:16.675: I/dalvikvm(9198): Could not find method com.quickblox.chat.QBChatService.setDebugEnabled, referenced from method com.quickblox.sample.chat.ui.activities.SplashActivity.onCreate
> 11-04 21:37:16.675: W/dalvikvm(9198): VFY: unable to resolve static method 9757: Lcom/quickblox/chat/QBChatService;.setDebugEnabled (Z)V

then crash with errors:

> 11-04 21:37:16.940: E/AndroidRuntime(9198): FATAL EXCEPTION: main
> 11-04 21:37:16.940: E/AndroidRuntime(9198): java.lang.NoClassDefFoundError: com.quickblox.chat.QBChatService
> 11-04 21:37:16.940: E/AndroidRuntime(9198):     at com.quickblox.sample.chat.ui.activities.SplashActivity.onCreate(SplashActivity.java:41)
> 11-04 21:37:16.940: E/AndroidRuntime(9198):     at android.app.Activity.performCreate(Activity.java:5133)
> 11-04 21:37:16.940: E/AndroidRuntime(9198):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
> 11-04 21:37:16.940: E/AndroidRuntime(9198):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2293)
> 11-04 21:37:16.940: E/AndroidRuntime(9198):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
> 11-04 21:37:16.940: E/AndroidRuntime(9198):     at android.app.ActivityThread.access$600(ActivityThread.java:153)
> 11-04 21:37:16.940: E/AndroidRuntime(9198):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269)

Any suggest how to fix it?

**Comment by amitsharmahimcs** [comment]
@soulfly i have completley dun all these things but got error  

java.lang.NoClassDefFoundError: com.quickblox.chat.QBChatService
at com.quickblox.sample.chat.ui.activities.SplashActivity.onCreate(SplashActivity.java:41)

**Comment by anumighty** [comment]
I have added all libraries as others said earlier, but i still have error in the com.sample.chat.pushnotifications package. It says GoogleCloudMessaging cannot resolve to a type.
Thanks for your quick responce

**Comment by anumighty** [comment]
I have added all libraries as others said earlier, but i still have error in the com.sample.chat.pushnotifications package. It says GoogleCloudMessaging cannot resolve to a type.
Thanks for your quick responce

**Comment by soulfly** [comment]
The GoogleCloudMessaging class is in com.google.android.gms.gcm.GoogleCloudMessaging, which is part of the Google Play Services.

You'll need to download the Play Services through the SDK manager and then add that to your project as well.

http://developer.android.com/google/play-services/setup.html

**Comment by anumighty** [comment]
I really appreciate your quick responce. Thanks.
com.google.android.gms.gcm.GoogleCloudMessaging is in my m2repository folder. Also I have installed the google play services through my SDK manager. I have imported Google Play Services and I have added it as a library to my project.
what else do you suggest could cause the error GoogleCloudMessaging?
The target for my project is API 18.
Thanks for the quick response.

**Comment by anumighty** [comment]
This will help you in helping me solve my error. I am using Eclipse, not Android Studio

**Comment by anumighty** [comment]
Yes, I got it resolved now! Thanks
But it still shows 2 errors, QBMessages and QBEnvironment cannot be resolved.
Expecting your quick response. Thanks ahead

**Comment by anumighty** [comment]
Yes, I got it resolved now! Thanks
But it still shows 2 errors, QBMessages and QBEnvironment cannot be
resolved.
Expecting your quick response. Thanks ahead

**Comment by anumighty** [comment]
I expect your early response. really in the midst of the work and i need to get it done. Thanks

**Comment by soulfly** [comment]
QBMessages and QBEnvironment are a part of QB SDK

did you import them in your file?

**Comment by anumighty** [comment]
Yes I have added the QB SDK as you said. Now no more error. The sample installs on emulator, but crashes at launch, QBSetting class cannot be found. How do i correct this?
Thanks for your reply.

**Comment by soulfly** [comment]
can you post a log

**Comment by krishnangit** [comment]
Even am getting the same error, log as follows

06-25 11:25:19.769: E/AndroidRuntime(1740): FATAL EXCEPTION: main
06-25 11:25:19.769: E/AndroidRuntime(1740): java.lang.NoClassDefFoundError: com.quickblox.core.QBSettings
06-25 11:25:19.769: E/AndroidRuntime(1740): 	at com.quickblox.q_municate.App.initApplication(App.java:43)
06-25 11:25:19.769: E/AndroidRuntime(1740): 	at com.quickblox.q_municate.App.onCreate(App.java:27)
06-25 11:25:19.769: E/AndroidRuntime(1740): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
06-25 11:25:19.769: E/AndroidRuntime(1740): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391)
06-25 11:25:19.769: E/AndroidRuntime(1740): 	at android.app.ActivityThread.access$1300(ActivityThread.java:141)
06-25 11:25:19.769: E/AndroidRuntime(1740): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
06-25 11:25:19.769: E/AndroidRuntime(1740): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-25 11:25:19.769: E/AndroidRuntime(1740): 	at android.os.Looper.loop(Looper.java:137)
06-25 11:25:19.769: E/AndroidRuntime(1740): 	at android.app.ActivityThread.main(ActivityThread.java:5039)
06-25 11:25:19.769: E/AndroidRuntime(1740): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-25 11:25:19.769: E/AndroidRuntime(1740): 	at java.lang.reflect.Method.invoke(Method.java:511)
06-25 11:25:19.769: E/AndroidRuntime(1740): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
06-25 11:25:19.769: E/AndroidRuntime(1740): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
06-25 11:25:19.769: E/AndroidRuntime(1740): 	at dalvik.system.NativeStart.main(Native Method)
