### ISSUE TITLE
Unauthorised error shown while logging into chat in quickblox.

### ISSUE THREAD

**Issue by samarth220194** [QuickBlox/quickblox-android-sdk#283]
My chat is showing unauthorised error while logging in.

09-01 16:55:16.938 14535-14535/com.baniaclothing.rang D/QBASDK: *********************************************************
                                                                **\* RESPONSE **\* d9214225-fa47-41d4-947a-c44d08701594 ***
                                                                STATUS : 401 
                                                                HEADERS
                                                                    X-Runtime=0.032609
                                                                    Cache-Control=no-cache
                                                                    X-Rack-Cache=invalidate, pass
                                                                    QuickBlox-REST-API-Version=0.1.1
                                                                    X-UA-Compatible=IE=Edge,chrome=1
                                                                    QB-Token-ExpirationDate=2016-09-01 13:25:17 UTC
                                                                    Status=401 Unauthorized
                                                                    X-Request-Id=435569107199dcc3d8550004b5b57674
                                                                    X-Android-Response-Source=NETWORK 401
                                                                    Connection=Close
                                                                    X-Android-Sent-Millis=1472729115344
                                                                    Content-Type=application/json; charset=utf-8
                                                                    Date=Thu, 01 Sep 2016 11:25:17 GMT
                                                                    Server=openresty/1.9.15.1
                                                                    Content-Length=27
                                                                    X-Android-Received-Millis=1472729116926
                                                                    Access-Control-Allow-Origin=*
                                                                BODY
                                                                    '{"errors":["Unauthorized"]}'

When i login to chat it shows unauthorised error.I referred to [https://github.com/QuickBlox/quickblox-android-sdk/issues/59](this) link ,it said that the user login and password is wrong .I wanted to ask where should i change the user login and password.

**Comment by samarth220194** [comment]
standard login+password authentication: use same password 
What does same password means here ??

**Comment by RomanPronin** [comment]
Hello, samarth220194. Same password means password which you created for your user. Here is link http://quickblox.com/developers/Android_XMPP_Chat_Sample#Login_to_Chat, do like in this example.

**Comment by samarth220194** [comment]
Hello,RomanPronin .I implemented the following way to login into the chat .Here is my part of the code.Will you please have a look and tell me the error.

`
        private void initQuickBlox()
{
                          ActivityLifecycle.init(this);
                          QBSettings.getInstance().init(getApplicationContext(), APP_ID, AUTH_KEY, AUTH_SECRET);
                           QBSettings.getInstance().setAccountKey(ACCOUNT_KEY);

        QBChatService.ConfigurationBuilder chatServiceConfigurationBuilder = new QBChatService.ConfigurationBuilder();
        chatServiceConfigurationBuilder.setSocketTimeout(60); //Sets chat socket's read timeout in seconds
        chatServiceConfigurationBuilder.setKeepAlive(true); //Sets connection socket's keepAlive option.
        QBChatService.setConfigurationBuilder(chatServiceConfigurationBuilder);

        QBAuth.createSession(new QBEntityCallback<QBSession>() {

            @Override
            public void onSuccess(QBSession session, Bundle params) {
                Log.e("DEBUG","session created: "+session.getToken());
                QBUser user=SharedPreferencesUtil.getMyUser();
                if(!TextUtils.isEmpty(user.getEmail())) {
                    createQuickBloxUserSession(user);
                }
            }

            @Override
            public void onError(QBResponseException errors) {
                Log.e("DEBUG","cannot create session "+errors.getMessage());
            }
        });
    }
      public void createQuickBloxUserSession(final QBUser user){
                 QBAuth.createSession(user,new QBEntityCallback<QBSession>() {

            @Override
            public void onSuccess(QBSession session, Bundle params) {
                SharedPreferencesUtil.save(AppConstants.USER_CREATED,true);
                if (googlePlayServicesHelper.checkPlayServicesAvailable()) {
                    if(TextUtils.isEmpty(googlePlayServicesHelper.getGcmRegIdFromPreferences().trim())) {
                        googlePlayServicesHelper.registerForGcm(Consts.GCM_SENDER_ID);
                    }
//                    sendPush();
                }
                Log.e("DEBUG","session created "+session.getToken());
            }

            @Override
            public void onError(QBResponseException errors) {
                Log.e("DEBUG","cannot create session "+errors.getMessage());
                if (errors.getMessage() != null && errors.getMessage().equals("Unauthorized")) {
                    QBUsers.signUp(user, new QBEntityCallback<QBUser>() {
                        @Override
                        public void onSuccess(QBUser user, Bundle args) {
                            // success
                            Log.e("DEBUG", "Account created ");
                            user.setPassword(SharedPreferencesUtil.getMyPassword());
                            createQuickBloxUserSession(user);
                        }

                        @Override
                        public void onError(QBResponseException error) {
                            // error
                            Log.e("DEBUG", "Cannot create Account " + error.getMessage());
                        }
                    });
                }
            }
        });
    }`

**Here is my SharedpreferencesUtil.java code** 
`package com.baniaclothing.rang.quickblox.utils;

import com.baniaclothing.rang.AppConstants;
import com.quickblox.users.model.QBUser;

public class SharedPreferencesUtil {
    private static final String QB_USER_ID = "qb_user_id";
    private static final String QB_USER_LOGIN = "qb_user_login";
    private static final String QB_USER_PASSWORD = "qb_user_password";
    private static final String QB_USER_FULL_NAME = "qb_user_full_name";
    private static final String RANG_USER_ID = "rang_user_id";
    private static final String RANG_USER_PASSWORD = "rang_user_password";
    private static final String RANG_ADMIN_USER_ID = "rang_admin_user_id";
    private static final String RANG_ADMIN_ID = "rang_admin_id";
    private static final String RANG_ADMIN_PASSWORD = "rang_admin_password";


    public static void saveQbUser(QBUser qbUser) {
        SharedPrefsHelper helper = SharedPrefsHelper.getInstance();
        helper.save(QB_USER_ID, qbUser.getId());
        helper.save(QB_USER_LOGIN, qbUser.getLogin());
        helper.save(QB_USER_PASSWORD, qbUser.getPassword());
        helper.save(QB_USER_FULL_NAME, qbUser.getFullName());
    }


    public static void save(String key, Object value) {
        SharedPrefsHelper helper = SharedPrefsHelper.getInstance();
        helper.save(key, value);
    }

    public static void removeQbUser() {
        SharedPrefsHelper helper = SharedPrefsHelper.getInstance();
        helper.delete(QB_USER_ID);
        helper.delete(QB_USER_LOGIN);
        helper.delete(QB_USER_PASSWORD);
        helper.delete(QB_USER_FULL_NAME);
    }

    public static boolean hasQbUser() {
        SharedPrefsHelper helper = SharedPrefsHelper.getInstance();
        return helper.has(QB_USER_LOGIN) && helper.has(QB_USER_PASSWORD);
    }

    public static QBUser getQbUser() {
        SharedPrefsHelper helper = SharedPrefsHelper.getInstance();

        if (hasQbUser()) {
            Integer id = helper.get(QB_USER_ID);
            String login = helper.get(QB_USER_LOGIN);
            String password = helper.get(QB_USER_PASSWORD);
            String fullName = helper.get(QB_USER_FULL_NAME);

            QBUser user = new QBUser(login, password);
            user.setId(id);
            user.setFullName(fullName);
            return user;
        } else {
            return null;
        }
    }

    public static void saveMyUser(String userName, String password) {
        SharedPrefsHelper helper = SharedPrefsHelper.getInstance();
        helper.save(RANG_USER_ID, userName);
        helper.save(RANG_USER_PASSWORD, password);
    }

    public static void saveAdmin(String userName, String password,int id) {
        SharedPrefsHelper helper = SharedPrefsHelper.getInstance();
        helper.save(RANG_ADMIN_USER_ID, userName);
        helper.save(RANG_ADMIN_PASSWORD, password);
        helper.save(RANG_ADMIN_ID, id);
    }

    public static QBUser getMyUser() {
        if(AppConstants.IS_ADMIN) {
            return getAdminUser();
        }
        SharedPrefsHelper helper = SharedPrefsHelper.getInstance();
        QBUser qbUser =  new QBUser((String)helper.get(RANG_USER_ID),(String)helper.get(RANG_USER_PASSWORD));
        qbUser.setEmail((String) helper.get(AppConstants.USER_EMAIL));
        qbUser.setFullName((String) helper.get(AppConstants.USER_NAME));
        qbUser.setPhone((String) helper.get(AppConstants.USER_PHONE));
        return qbUser;
    }

    public static String getMyPassword(){
        SharedPrefsHelper helper = SharedPrefsHelper.getInstance();
        return  (String)helper.get(RANG_USER_PASSWORD);
    }

    public static QBUser getAdminUser(){
        SharedPrefsHelper helper = SharedPrefsHelper.getInstance();
        QBUser admin = new QBUser((String)helper.get(RANG_ADMIN_USER_ID),(String)helper.get(RANG_ADMIN_PASSWORD));
        admin.setId((int)helper.get(RANG_ADMIN_ID));
        return admin;
    }

    public static <T> T get(String key,Object defaultVal) {
        SharedPrefsHelper helper = SharedPrefsHelper.getInstance();
        return (T) helper.get(key,defaultVal);
    }
}
`

**Comment by samarth220194** [comment]
One more thing i would like to ask.Will i create a common paasword for all users to login or the user will login through his./her own password??

**Comment by RomanPronin** [comment]
To update an Application session to a User session you have to login to QuickBlox: QBUsers.signIn.  Look [here](http://quickblox.com/developers/Android#A_couple_of_words_about_Authentication_and_Authorization) 
 Also you must set qbUser.setPassword("password"); when you make QBChatService.getInstance().login.
P.S. You can create common password, but we don't advise do that in your app.

**Comment by samarth220194** [comment]
Bro i created a button to go to the chat .When i click on the button i passed an intent to the LoginActivity.java .Here is my LoginActivity.java file and a MyshopApplication.java file .Please have a look a it.I have filled the credentials in the myshopapplication.java file in my project .It is left blank here for security.
[Desktop.zip](https://github.com/QuickBlox/quickblox-android-sdk/files/456012/Desktop.zip)

**Comment by samarth220194** [comment]
[ChatHelper.zip](https://github.com/QuickBlox/quickblox-android-sdk/files/456434/ChatHelper.zip)
This file is also helpful so please have a loot at it

**Comment by samarth220194** [comment]
09-06 16:22:59.892 4528-4528/com.baniaclothing.rang I/token: token:6433ac04a5e921cb62bc8870bf63640969df86ec
09-06 16:22:59.892 4528-4528/com.baniaclothing.rang V/BaseActivity: wasAppRestored = false
09-06 16:22:59.892 4528-4528/com.baniaclothing.rang V/BaseActivity: isQbSessionActive = true
09-06 16:22:59.898 4528-4528/com.baniaclothing.rang D/LoginActivity: Need to recreate chat session
09-06 16:23:00.040 4528-4528/com.baniaclothing.rang D/Request build:: application_id=43390&auth_key=SNK-xc5t8u4VBP8&nonce=1037023029&timestamp=1473159180&user[login]=359301053278395&user[password]=610bccd47331ed14e4a2a39f8955ca2e
09-06 16:23:00.040 4528-4528/com.baniaclothing.rang D/QBASDK: =========================================================
                                                              === REQUEST ==== d868276e-acfb-434c-a1c6-abac6b613c64 ===
                                                              REQUEST
                                                                  POST https://api.quickblox.com/session.json
                                                              HEADERS
                                                                  QuickBlox-REST-API-Version=0.1.1
                                                                  QB-SDK=Android 2.6
                                                                  QB-Token=6433ac04a5e921cb62bc8870bf63640969df86ec
                                                              PARAMETERS
                                                                  application_id=43390
                                                                  auth_key=SNK-xc5t8u4VBP8
                                                                  nonce=1037023029
                                                                  timestamp=1473159180
                                                                  user[login]=359301053278395
                                                                  user[password]=610bccd47331ed14e4a2a39f8955ca2e
                                                                  signature=bd78c7cdf703cf5d190249c3af9285d99e1ef84e
                                                              INLINE
                                                                  POST https://api.quickblox.com/session.json?application_id=43390&auth_key=SNK-xc5t8u4VBP8&nonce=1037023029&timestamp=1473159180&user[login]=359301053278395&user[password]=610bccd47331ed14e4a2a39f8955ca2e&signature=bd78c7cdf703cf5d190249c3af9285d99e1ef84e
09-06 16:23:00.294 4528-4528/com.baniaclothing.rang I/Choreographer: Skipped 46 frames!  The application may be doing too much work on its main thread.
09-06 16:23:20.500 4528-4528/com.baniaclothing.rang D/QBASDK: *********************************************************
                                                              *** RESPONSE *** d868276e-acfb-434c-a1c6-abac6b613c64 ***
                                                              STATUS : 201 
                                                              HEADERS
                                                                  X-Runtime=0.066415
                                                                  Cache-Control=max-age=0, private, must-revalidate
                                                                  X-Rack-Cache=invalidate, pass
                                                                  QuickBlox-REST-API-Version=0.1.1
                                                                  X-UA-Compatible=IE=Edge,chrome=1
                                                                  QB-Token-ExpirationDate=2016-09-06 12:53:20 UTC
                                                                  Status=201 Created
                                                                  X-Request-Id=e3885dcaba0d8a4fc9bc5cb6e4976d78
                                                                  X-Android-Response-Source=NETWORK 201
                                                                  Connection=Close
                                                                  X-Android-Sent-Millis=1473159196514
                                                                  Content-Type=application/json; charset=utf-8
                                                                  Date=Tue, 06 Sep 2016 10:53:20 GMT
                                                                  Server=openresty/1.9.15.1
                                                                  ETag="f5a4014886b52d6d766528786af973cf"
                                                                  Content-Length=271
                                                                  Strict-Transport-Security=max-age=15768000;
                                                                  X-Android-Received-Millis=1473159200487
                                                                  Access-Control-Allow-Origin=*
                                                              BODY
                                                                  '{"session":{"_id":"57cea01fa0eb47b1d8000016","application_id":43390,"created_at":"2016-09-06T10:53:19Z","device_id":0,"nonce":1037023029,"token":"6a921a2688f0866e66220412ebc1b3328a8a1737","ts":1473159180,"updated_at":"2016-09-06T10:53:20Z","user_id":17355822,"id":62389}}'
09-06 16:23:20.519 4528-4528/com.baniaclothing.rang I/id: id:17355822
09-06 16:23:20.591 4528-5805/com.baniaclothing.rang D/QBASDK: Connecting to chat: chat.quickblox.com
09-06 16:23:24.446 4528-5805/com.baniaclothing.rang D/QBASDK: Setting socket keepAlive :true
09-06 16:23:24.447 4528-5805/com.baniaclothing.rang D/QBASDK: Setting socket timeout :60000
09-06 16:23:37.514 4528-6052/com.baniaclothing.rang D/SMACK: SENT (0): <stream:stream xmlns='jabber:client' to='chat.quickblox.com' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>
09-06 16:23:41.747 4528-6053/com.baniaclothing.rang D/SMACK: RECV (0): <?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='chat.quickblox.com' id='cd49539b-07ed-4924-b7fa-1d99917ebf14' version='1.0' xml:lang='en'>
09-06 16:23:42.568 4528-4528/com.baniaclothing.rang W/LoginActivity: Chat login onError(): com.quickblox.core.exception.QBResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). Used filter: No filter used or filter was 'null'.
09-06 16:23:45.211 4528-6053/com.baniaclothing.rang D/SMACK: RECV (0): <stream:features><sm xmlns="urn:xmpp:sm:3"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>ANONYMOUS</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression></stream:features>
09-06 16:23:53.767 4528-4528/com.baniaclothing.rang D/Request build:: application_id=43390&auth_key=SNK-xc5t8u4VBP8&nonce=1110233396&timestamp=1473159233&user[login]=359301053278395&user[password]=610bccd47331ed14e4a2a39f8955ca2e
09-06 16:23:53.768 4528-4528/com.baniaclothing.rang D/QBASDK: =========================================================
                                                              === REQUEST ==== 0f32d589-d013-4ec5-9b6d-e9b8960ec724 ===
                                                              REQUEST
                                                                  POST https://api.quickblox.com/session.json
                                                              HEADERS
                                                                  QuickBlox-REST-API-Version=0.1.1
                                                                  QB-SDK=Android 2.6
                                                                  QB-Token=6a921a2688f0866e66220412ebc1b3328a8a1737
                                                              PARAMETERS
                                                                  application_id=43390
                                                                  auth_key=SNK-xc5t8u4VBP8
                                                                  nonce=1110233396
                                                                  timestamp=1473159233
                                                                  user[login]=359301053278395
                                                                  user[password]=610bccd47331ed14e4a2a39f8955ca2e
                                                                  signature=9ba658ba1bccde07a894ab793d78393171d23f8c
                                                              INLINE
                                                                  POST https://api.quickblox.com/session.json?application_id=43390&auth_key=SNK-xc5t8u4VBP8&nonce=1110233396&timestamp=1473159233&user[login]=359301053278395&user[password]=610bccd47331ed14e4a2a39f8955ca2e&signature=9ba658ba1bccde07a894ab793d78393171d23f8c
09-06 16:24:45.225 4528-6053/com.baniaclothing.rang W/AbstractXMPPConnection: Connection closed with error
                                                                              java.net.SocketTimeoutException
                                                                                  at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
                                                                                  at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
                                                                                  at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                                                  at java.io.InputStreamReader.read(InputStreamReader.java:231)
                                                                                  at java.io.BufferedReader.read(BufferedReader.java:325)
                                                                                  at org.jivesoftware.smack.util.ObservableReader.read(ObservableReader.java:41)
                                                                                  at org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1515)
                                                                                  at org.kxml2.io.KXmlParser.peekType(KXmlParser.java:992)
                                                                                  at org.kxml2.io.KXmlParser.next(KXmlParser.java:349)
                                                                                  at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
                                                                                  at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1169)
                                                                                  at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:948)
                                                                                  at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:963)
                                                                                  at java.lang.Thread.run(Thread.java:818)


I am getting the above error while running the chat.What might be the reason for it .??

**Comment by RomanPronin** [comment]
As for SocketTimeoutException, you can increase this timeout QBChatService.setDefaultPacketReplyTimeout(15000);

**Comment by samarth220194** [comment]
**=== REQUEST ==== acbb36da-a0d4-481a-beb0-85d516654327 ===
                                                            REQUEST
                                                                GET https://api.quickblox.com/users.json
                                                            HEADERS
                                                                QuickBlox-REST-API-Version=0.1.1
                                                                QB-SDK=Android 2.6
                                                                QB-Token=9ab1bbddfa370d8b5e42f7eabad9ba159a7d7db6
                                                            PARAMETERS
                                                                page=1
                                                                per_page=0
                                                                filter[]=number id in null
                                                            INLINE
                                                                GET https://api.quickblox.com/users.json?page=1&per_page=0&filter[]=number+id+in+null
09-06 17:30:00.307 763-763/com.baniaclothing.rang D/QBASDK: *********************************************************
                                                            *** RESPONSE *** acbb36da-a0d4-481a-beb0-85d516654327 ***
                                                            STATUS : 200 
                                                            HEADERS
                                                                X-Runtime=0.020377
                                                                Cache-Control=max-age=0, private, must-revalidate
                                                                X-Rack-Cache=miss
                                                                QuickBlox-REST-API-Version=0.1.1
                                                                X-UA-Compatible=IE=Edge,chrome=1
                                                                QB-Token-ExpirationDate=2016-09-06 13:59:43 UTC
                                                                Status=200 OK
                                                                X-Request-Id=0d5360b0274af7e4feda6f0d8cb02c51
                                                                X-Android-Response-Source=NETWORK 200
                                                                Connection=Close
                                                                X-Android-Sent-Millis=1473163198809
                                                                Content-Type=application/json; charset=utf-8
                                                                Date=Tue, 06 Sep 2016 12:00:00 GMT
                                                                Server=openresty/1.9.15.1
                                                                ETag="ddf4c0e0dc6fd9511428e0cfd001ecf8"
                                                                Content-Length=60
                                                                Strict-Transport-Security=max-age=15768000;
                                                                X-Android-Received-Millis=1473163200299
                                                                Access-Control-Allow-Origin=*
                                                            BODY
                                                                '{"current_page":1,"per_page":1,"total_entries":0,"items":[]}'
09-06 17:30:23.559 763-1981/com.baniaclothing.rang D/QBASDK: StanzaSender run 
09-06 17:30:23.560 763-2009/com.baniaclothing.rang D/SMACK: SENT (0): <presence id='M16Ec-9'></presence>
09-06 17:30:23.560 763-2009/com.baniaclothing.rang D/SMACK: SENT (0): <r xmlns='urn:xmpp:sm:3'/>
09-06 17:30:24.759 763-2010/com.baniaclothing.rang D/SMACK: RECV (0): <a xmlns='urn:xmpp:sm:3' h='3'/>
09-06 17:30:25.694 763-2010/com.baniaclothing.rang D/SMACK: RECV (0): <presence id="M16Ec-9" xmlns="jabber:client" to="17355822-43390@chat.quickblox.com" from="17355822-43390@chat.quickblox.com/android_00000000-61a2-6506-ffff-ffffb8bd3ddd"/><r xmlns='urn:xmpp:sm:3' />
09-06 17:30:25.695 763-2009/com.baniaclothing.rang D/SMACK: SENT (0): <a xmlns='urn:xmpp:sm:3' h='3'/>**

Getting the above log in android monitor.Is there any error in the Request??
**GET https://api.quickblox.com/users.json?page=1&per_page=0&filter[]=number+id+in+null**

**Comment by RomanPronin** [comment]
Looks like you need to set "Allow to retrieve a list of users" in your admin panel - Overview - Settings.

**Comment by samarth220194** [comment]
Ok so should i make the changes in the quickblox website by logging in ??

**Comment by samarth220194** [comment]
I will make the desired changes and then tell you.

**Comment by samarth220194** [comment]
I have already checked ""Allow to retrieve a list of users" in admin panel.But it is not working

**Comment by RomanPronin** [comment]
Long time inactivity.

**Comment by dipakkadamdpk** [comment]
Hi    RomanPronin /samarth220194   i am facing the same issue, while login to chat,  I am unable to understand which password i have to set. Even i set the login password still its get the same issue   ERROR CODE 201

**Comment by RomanPronin** [comment]
Hello @dipakkadamdpk, qbUser must have ID and Password (qbUser.setPassword(), qbUser.setId()) before doing chatService.login(qbUser).
Also, I strongly advise you to look at our [sample-chat](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-chat) for better understanding how QB API chat works.

**Comment by sushillyn** [comment]
Keep Getting   STATUS : 400  error when i try to signup:

    *** RESPONSE *** 6038ede1-65a6-4b9e-9645-4ef732fcea09 ***
    STATUS : 400 
    HEADERS
        x-request-id=FngnSoCch9K2Rd0EQYTi
        X-Android-Selected-Protocol=http/1.1
        Server=nginx
        Connection=close
        X-Android-Response-Source=NETWORK 400
        X-Android-Sent-Millis=1619087266707
        cache-control=max-age=0, private, must-revalidate
        Content-Length=102
        X-Android-Received-Millis=1619087267285
        Date=Thu, 22 Apr 2021 10:27:46 GMT
        Content-Type=application/json; charset=utf-8
    BODY
        '{"code":null,"message":"Content-type: application/x-www-form-urlencoded; charset=UTF-8 not supported"}'

I don't know why I am getting this error I tried everything, a few days back it's working now suddenly I am getting this.
