### ISSUE TITLE
Screen Sharing or Image sending over VideoChat instead using Camera

### ISSUE THREAD

**Issue by antoescu** [QuickBlox/quickblox-android-sdk#285]
According to https://github.com/QuickBlox/quickblox-android-sdk/issues/130#issuecomment-170466174 this should have been added by the first quarter of 2016, but haven't been an update yet about it. We would like to have this functionality in both iOS and Android version of our app. Any news about it? Thanks!

**Comment by RomanPronin** [comment]
In version 3.3.0 added "Screen sharing" feature.
