### ISSUE TITLE
Classes not found after updating to 2.6.1 

### ISSUE THREAD

**Issue by CRUDTechnolgoy** [QuickBlox/quickblox-android-sdk#291]
Hi i was using 2.4.0 version of your sdk. all thing working fine but now i want to use group audio & video call so i need to upgrade it 2.6.1 when i put dependency to build.gradle it sync perfectly but classes is not resolve.  please provide me solution i have tried all thing delete .gradle from project & root directory delete .iml file but still show "cannot resolve symbol"

**Comment by RomanPronin** [comment]
Hi @CRUDTechnolgoy. To solve dependency errors look at this [guide](https://github.com/QuickBlox/quickblox-android-sdk#android-studio-issues).

**Comment by CRUDTechnolgoy** [comment]
@RomanPronin  i tried this not working than i use 2.6. but the application is crashed on call activity... and also give me error o isRead() method can't resolve..

**Comment by RomanPronin** [comment]
Carefully look this link  https://quickblox.com/developers/Android#How_to:_add_SDK_to_IDE_and_connect_to_the_cloud for correct adding sdk via gradle script.
Note, for including transitive dependencies you should add dependency on particular sdk module - " compile("com.quickblox:quickblox-android-sdk-chat:2.6.1")" 
not just to resource ("aar" or "jar") - compile("com.quickblox:quickblox-android-sdk-chat:2.6.1@aar"). In addition don't forget update jni libs.
