### ISSUE TITLE
Transform CustomObject Inputstream to bitmap on Quickblox

### ISSUE THREAD

**Issue by ignasirv** [QuickBlox/quickblox-android-sdk#292]
I am trying to download an image from quickblox backend but I don't know ho to transform the recieved inputstream to a bitmap. Here my code:

QBCustomObjectsFiles.downloadFile(co, "fieldName", new QBEntityCallback<InputStream>(){
        @Override
        public void onSuccess(InputStream result, Bundle params) 
        {
            Bitmap bm= BitmapFactory.decodeStream(result);
            if (bm!=null) 
            {
                job.foto = bm;
            }
            else
            {
                App.getInstance().log("ERROR");
            }
        }
The output error is DECORDER-->DECODER ERROR

**Comment by tatanka987** [comment]
hi @ignasirv please provide your log from starting loading file to getting error

**Comment by ignasirv** [comment]
D/skia: ---- read threw an exception 
D/skia: --- decoder->decode returned false 


The result.tostream() is: com.quickblox.core.request.ProgressHttpEntityWrapper$Progres‌​sFilterInputStream@c‌​913d95

**Comment by tatanka987** [comment]
looks like you upload incorrect image, we tested this case on test and it works fine
