### ISSUE TITLE
1.How to get current logged in users quickblox id? 2.how to effectively hang up video call audio and video??

### ISSUE THREAD

**Issue by xpressmobtech** [QuickBlox/quickblox-android-sdk#293]
1.How to get current logged in users quickblox id?
 2.how to effectively hang up video call audio and video??

**Comment by tatanka987** [comment]
Hi @xpressmobtech,  
1. For getting current logged in user to QuickBlox server need call QBAuth.getSession().getUserId();  if you want to get id of user logged to the chat you should call QBChatService.getInstance().getUser().getId();
2. Please specify your question, what functions you need?
