### ISSUE TITLE
onOpponentVideoDataReceive & onOpponentAudioDataReceive are not called for VideoChat in Android

### ISSUE THREAD

**Issue by NilaySheth** [QuickBlox/quickblox-android-sdk#30]
Hi, I am working on Eclipse and building the app for video chat on it instead of studio. Now I made the entire code work in eclipse by view this: http://quickblox.com/developers/Sample-videochat-android . But when implemented, everything worked fine except that onOpponentVideoDataReceive & onOpponentAudioDataReceive were not called. I can make a Call and receive it too, but cannot see opponent's part of video from my app. I also copied the "libilbc-codec.so" to "\libs\armeabi\" path and included Native support too.

Can you please suggest me any solution as I cannot change IDE to Studio in my app and am kind of stuck in Eclipse. Please help me out on this part.

**Comment by soulfly** [comment]
Try our latest version of Android WebRTC

 http://quickblox.com/developers/Sample-videochat-android
