### ISSUE TITLE
user can not update group chat dialog's custom data

### ISSUE THREAD

**Issue by anniehita** [QuickBlox/quickblox-android-sdk#301]
Hello
I have 1 question and 1 issue:
Question : I have a dialog of type 2 and I want all members to be able to update custom data, is it possible or just the dialog owner is able to do that?

Issue : even as the dialog owner I am not allowed to update custom data of my dialog
this is the code I am using

```
QBDialogCustomData customData = dialog.getCustomData(); 
QBDialogRequestBuilder requestBuilder = new QBDialogRequestBuilder();

editDialog.setName(groupNameEditText.getText().toString());
editDialog.setPhoto(photo);

ArrayList<Integer> acceptedList = (ArrayList<Integer>) customData.get("accepted");
acceptedList.add(user.getId());
customData.put("accepted",acceptedList);
QBGroupChatManager groupChatManager = QBChatService.getInstance().getGroupChatManager();

 groupChatManager.updateDialog(dialog, requestBuilder, new QBEntityCallback<QBDialog>() {

@Override
  public void onSuccess(QBDialog dialog, Bundle bundle) {
            }
@Override
 public void onError(QBResponseException e) {

            }
        });
```

 neither owner nor members, could not update custom data of the group dialog Type 2.

**Comment by anniehita** [comment]
Could someone please help me with this?

**Comment by RomanPronin** [comment]
Make sure that you are updating correct dialog (editDialog). If you still get error, provide us logs with request and response.

**Comment by anniehita** [comment]
D/QBASDK: =========================================================
          === REQUEST ==== d0b0dd73-1184-41c9-8753-4d8cd9c6be82 ===
          REQUEST
              GET https://api.quickblox.com/chat/Message.json
          HEADERS
              QuickBlox-REST-API-Version=0.1.1
              QB-SDK=Android 2.6.1
              QB-Token=d0a8a8f8c88888edd8888fff5225ff822200afa6
          PARAMETERS
              limit=200
              chat_dialog_id=57e2b7e6a28f9a24ba000019
          INLINE
              GET https://api.quickblox.com/chat/Message.json?limit=200&chat_dialog_id=57e2b7e6a28f9a24ba000019

D/dalvikvm: GC_FOR_ALLOC freed 2276K, 25% free 20796K/27520K, paused 53ms, total 65ms
D/dalvikvm: GC_FOR_ALLOC freed 1179K, 27% free 20269K/27520K, paused 46ms, total 47ms
W/f: Suppressed StrictMode policy violation: StrictModeDiskReadViolation
W/f: Suppressed StrictMode policy violation: StrictModeDiskWriteViolation
D/dalvikvm: GC_FOR_ALLOC freed 425K, 27% free 20333K/27520K, paused 53ms, total 53ms
D/QBASDK: *********************************************************
          *** RESPONSE *** d0b0dd73-1184-41c9-8753-4d8cd9c6be82 ***
          STATUS : 200 
          HEADERS
              QuickBlox-REST-API-Version=0.1.1
              X-Runtime=0.036653
              ETag="dc6e14d86efae42293a0bd70a29400b2"
              Content-Length=383
              X-UA-Compatible=IE=Edge,chrome=1
              X-Request-Id=8f8aff0c092c5e7c87bc8f9370cd8d39
              X-Rack-Cache=miss
              Connection=Close
              X-Android-Response-Source=CONDITIONAL_CACHE 200
              Server=openresty/1.9.15.1
              QB-Token-ExpirationDate=2016-10-18 18:24:39 UTC
              Cache-Control=max-age=0, private, must-revalidate
              Status=200 OK
              Strict-Transport-Security=max-age=15768000;
              X-Android-Selected-Transport=http/1.1
              Date=Tue, 18 Oct 2016 16:31:46 GMT
              Access-Control-Allow-Origin=*
              X-Android-Received-Millis=1476808306283
              Content-Type=application/json; charset=utf-8
              X-Android-Sent-Millis=1476808306044
          BODY
              '{"skip":0,"limit":200,"items":[{"_id":"57f7a9e874d8f914a8de7d16","attachments":[],"avatar":"null","chat_dialog_id":"57e2b7e6a28f9a24ba000019","created_at":"2016-10-07T13:58:00Z","date_sent":1475848680,"delivered_ids":[17429227],"message":"alo","read_ids":[17429227],"recipient_id":null,"senderDisplayName":"Tester","sender_id":17429227,"updated_at":"2016-10-07T13:58:00Z","read":0}]}'

---++++
D/QBASDK: =========================================================
          === REQUEST ==== d1e179d8-8c0a-45a7-a83b-e1150b846fcb ===
          REQUEST
              PUT https://api.quickblox.com/chat/Dialog/57e2b7e6a28f9a24ba000019.json
          HEADERS
              QuickBlox-REST-API-Version=0.1.1
              QB-SDK=Android 2.6.1
              QB-Token=d0a8a8f8c88888edd8888fff5225ff822200afa6
          PARAMETERS
              name=gal out oit
              photo=null
              spotPlaceID=ChIJ1Zj3u0QayUwRwjoylEnYkNE
              data[accepted]=[17487343,17429227]
              scope=2
              spotURL=http://www.vargas.ca/
              location=-73.5674397,45.5015312
              spotName=Vargas Steakhouse & Sushi
              spotAddress=690 Boulevard René-Lévesque O, Montréal, QC H3B 4A5, Canada
              date=2016-08-30T10:18:00Z
              spotPhone=+1 514-875-4545
          INLINE
              PUT https://api.quickblox.com/chat/Dialog/57e2b7e6a28f9a24ba000019.json?name=gal+out+oit&photo=null&spotPlaceID=ChIJ1Zj3u0QayUwRwjoylEnYkNE&data[accepted]=%5B17487343%2C17429227%5D&scope=2&spotURL=http%3A%2F%2Fwww.vargas.ca%2F&location=-73.5674397%2C45.5015312&spotName=Vargas+Steakhouse+%26+Sushi&spotAddress=690+Boulevard+Ren%C3%A9-L%C3%A9vesque+O%2C+Montr%C3%A9al%2C+QC+H3B+4A5%2C+Canada&date=2016-08-30T10%3A18%3A00Z&spotPhone=%2B1+514-875-4545
D/QBASDK: *********************************************************
          *** RESPONSE *** d1e179d8-8c0a-45a7-a83b-e1150b846fcb ***
          STATUS : 200 
          HEADERS
              QuickBlox-REST-API-Version=0.1.1
              X-Runtime=0.047283
              ETag="a3d56a82e66070cbff50a4530b522283"
              Content-Length=767
              X-UA-Compatible=IE=Edge,chrome=1
              X-Request-Id=e8b9cc9e0b3f980a28eea4b411c85099
              X-Rack-Cache=invalidate, pass
              Connection=Close
              X-Android-Response-Source=NETWORK 200
              Server=openresty/1.9.15.1
              QB-Token-ExpirationDate=2016-10-18 18:24:39 UTC
              Cache-Control=max-age=0, private, must-revalidate
              Status=200 OK
              Strict-Transport-Security=max-age=15768000;
              X-Android-Selected-Transport=http/1.1
              Date=Tue, 18 Oct 2016 16:38:07 GMT
              Access-Control-Allow-Origin=*
              X-Android-Received-Millis=1476808687688
              Content-Type=application/json; charset=utf-8
              X-Android-Sent-Millis=1476808687569
          BODY
              '{"_id":"57e2b7e6a28f9a24ba000019","created_at":"2016-09-21T16:40:06Z","data":{"date":"2016-08-30T10:18:00Z","scope":2,"spotAddress":"690 Boulevard René-Lévesque O, Montréal, QC H3B 4A5, Canada","accepted":[17487343],"spotPhone":"+1 514-875-4545","spotName":"Vargas Steakhouse & Sushi","spotPlaceID":"ChIJ1Zj3u0QayUwRwjoylEnYkNE","spotURL":"http://www.vargas.ca/","class_name":"GPPlanDetailsInfo","location":[-73.5674397,45.501531199999995]},"last_message":"alo","last_message_date_sent":1475848680,"last_message_user_id":17429227,"name":"gal out oit","occupants_ids":[17487343,17429227],"photo":"null","type":2,"updated_at":"2016-10-07T13:58:00Z","user_id":17487343,"xmpp_room_jid":"44966_57e2b7e6a28f9a24ba000019@muc.chat.quickblox.com","unread_messages_count":0}'
D/QBASDK: =========================================================
          === REQUEST ==== 0fc59a59-bbef-42f5-b23b-34a595cfa4c5 ===
          REQUEST
              GET https://api.quickblox.com/chat/Message.json
          HEADERS
              QuickBlox-REST-API-Version=0.1.1
              QB-SDK=Android 2.6.1
              QB-Token=d0a8a9f8c79190edd4453dce5225ff822200afa6
          PARAMETERS
              limit=200
              chat_dialog_id=57e2b7e6a28f9a24ba000019
          INLINE
              GET https://api.quickblox.com/chat/Message.json?limit=200&chat_dialog_id=57e2b7e6a28f9a24ba000019
D/dalvikvm: GC_FOR_ALLOC freed 4384K, 25% free 21327K/28108K, paused 87ms, total 94ms
D/QBASDK: *********************************************************
          *** RESPONSE *** 0fc59a59-bbef-42f5-b23b-34a595cfa4c5 ***
          STATUS : 200 
          HEADERS
              QuickBlox-REST-API-Version=0.1.1
              X-Runtime=0.015827
              ETag="dc6e14d86efae42293a0bd70a29400b2"
              Content-Length=383
              X-UA-Compatible=IE=Edge,chrome=1
              X-Request-Id=fbc60858b52521ff39d1ad30eeb2d44a
              X-Rack-Cache=miss
              Connection=Close
              X-Android-Response-Source=CONDITIONAL_CACHE 200
              Server=openresty/1.9.15.1
              QB-Token-ExpirationDate=2016-10-18 18:24:39 UTC
              Cache-Control=max-age=0, private, must-revalidate
              Status=200 OK
              Strict-Transport-Security=max-age=15768000;
              X-Android-Selected-Transport=http/1.1
              Date=Tue, 18 Oct 2016 16:38:08 GMT
              Access-Control-Allow-Origin=*
              X-Android-Received-Millis=1476808688157
              Content-Type=application/json; charset=utf-8
              X-Android-Sent-Millis=1476808688069
          BODY
              '{"skip":0,"limit":200,"items":[{"_id":"57f7a9e874d8f914a8de7d16","attachments":[],"avatar":"null","chat_dialog_id":"57e2b7e6a28f9a24ba000019","created_at":"2016-10-07T13:58:00Z","date_sent":1475848680,"delivered_ids":[17429227],"message":"alo","read_ids":[17429227],"recipient_id":null,"senderDisplayName":"Tester","sender_id":17429227,"updated_at":"2016-10-07T13:58:00Z","read":0}]}'

**Comment by RomanPronin** [comment]
You can do the next, create new dialog, create QBDialogCustomData with CustomObjects class name in constructor and put some values just like this:
QBDialogCustomData data = new QBDialogCustomData("Advert"); // class name
data.putString("title", "Magic Beans"); // field 'title'
data.putInteger("advert_id", 5665); // field 'advert_id'
newDialog.setCustomData(data);
... create newDialog.
Then, try to update this dialog like you did it before.

**Comment by adzharkahar** [comment]
im using restful api for quickblox, and i seem to be facing the same problems as anniehita. I created the dialog first with the custom parameters and its working. here is the result of the dialog creation: 

{{
  "_id": "58856f32a0eb47d47e000031",
  "created_at": "2017-01-23T02:49:22Z",
  "data": {
    "customerImageURL": " ",
    "customerName": "customer2",
    "merchantPhone": "{\"0168956193\"=>nil}",
    "merchantEmail": "honglok@agmostudio.com",
    "merchantShopName": "Honglok",
    "merchantImageURL": "https://bmo.blob.core.windows.net/u00029/01759e9b-d500-4148-b9db-e01da5643b1d.Jpeg",
    "class_name": "user"
  },
  "last_message": "uy",
  "last_message_date_sent": 1485140907,
  "last_message_user_id": 22972344,
  "name": "Honglok",
  "occupants_ids": [
    22972344,
    23092002
  ],
  "photo": null,
  "type": 3,
  "updated_at": "2017-01-23T03:08:28Z",
  "user_id": 23092002,
  "xmpp_room_jid": null,
  "unread_messages_count": null
}}

the error happens when im trying to update the custom parameters, i followed the sample from http://quickblox.com/developers/Chat#Update_custom_parameters but the custom parameters doesnt seem to be updating. Please advise on how i could solve this

**Comment by jeantanzj** [comment]
Whoever lands here in search of an answer, the type of the dialog created has to be '1' or '2', not '3' (for private).
Then you can update the name of your dialog.

If you are trying to add custom data, be sure to create its schema in your admin console first, then use something like .setClassName in your code to refer to that schema you created.

**Comment by alexanderkoqb** [comment]
Hey @anniehita 
Since it's been a while and if you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
