### ISSUE TITLE
Not Showing my local video and remote video view on caller side

### ISSUE THREAD

**Issue by CRUDTechnolgoy** [QuickBlox/quickblox-android-sdk#304]
Hello i am implement this https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-webrtc on new project but i am not able to get my video or remote videos at sender side but able to view at receiver side..

**Comment by tatanka987** [comment]
hello @CRUDTechnolgoy, looks like you not added video track listener before starting call, see [this link](http://quickblox.com/developers/Sample-webrtc-android#Prepare_your_activity_class_to_audio.2Fvideo_calls)
