### ISSUE TITLE
push notification to all users who is located in your radius

### ISSUE THREAD

**Issue by bayanruby** [QuickBlox/quickblox-android-sdk#306]
Hi admin! Tell me please. 

"You can create or update geodata with sending a push notification to all users who is located in your radius."

Everyone who is Check-in users?

Or you monitor all GPS users?

---

на русском

У вас есть вот такая фича

"You can create or update geodata with sending a push notification to all users who is located in your radius."

Можно отправлять Чекин с текстом и он в радиусе отправит пуш всем кто рядом находится.

У меня вопрос, он отправит всем пользователям кто рядом находится?

Вы мониторите каждого юзера где он сейчас находится?"

**Comment by vfite** [comment]
Hi.
We don't monitor users. 
This Push is delivered  to users who create geodata via https://quickblox.com/developers/Location#Create_geodata.
To keep geadata in actual state users have to update it  https://quickblox.com/developers/Location#Update_geodata.

**Comment by bayanruby** [comment]
"Create geodata with the location-push
You can create or update geodata with sending a push notification to all users who is located in your radius."

Who will get the push notification?

**Comment by tatanka987** [comment]
long time inactivity
