### ISSUE TITLE
Need to integrate video call module without including XMPP part.

### ISSUE THREAD

**Issue by A86S** [QuickBlox/quickblox-android-sdk#310]
I have already implemented xmpp (smack 4.1) chat module in my android app but now i want to integrate Only Video Module from quick-blox and when i am integrating the video module i am getting error like this : 

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.

> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/jivesoftware/smack/android/AndroidSmackInitializer.class

can we exclude the xmpp part from quick blox or i need to rewrite the chat part with quickblox.

**Comment by tatanka987** [comment]
hello @A86S, you can use Smack library from QuickBlox Android SDK

**Comment by A86S** [comment]
@tatanka987  Yes i did this but some classes are missing in quick blox smack library like 
org.jivesoftware.smackx.receipts.DeliveryReceipt and more smackx classes.

**Comment by A86S** [comment]
@tatanka987 if i want to include some classes from org.igniterealtime.smack:smack-extensions how can i do that?

**Comment by tatanka987** [comment]
can try to export external smack lib and exclude all modules, then try include only missing modules, it will to help you
