### ISSUE TITLE
How to link jniLibs to cordova project.

### ISSUE THREAD

**Issue by williamtran1988** [QuickBlox/quickblox-android-sdk#313]
Hi All,

I am building a cordova application with Android quickblox version 3.0. I used gradle script as below:

repositories {
    maven {
        url "https://github.com/QuickBlox/quickblox-android-sdk-releases/raw/master/"
    }
}
dependencies {
   compile("com.quickblox:quickblox-android-sdk-chat:3.0")
   compile("com.quickblox:quickblox-android-sdk-core:3.0")
   compile("com.quickblox:quickblox-android-sdk-messages:3.0")
   compile("com.quickblox:quickblox-android-sdk-videochat-webrtc:3.0")
   compile("com.quickblox:quickblox-android-sdk-extensions:3.0")
}

we also have Build grable script which is generated by Cordova. This is android structure in cordova project defined:

android {
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }
    }

How is about native libs (jniLibs). Where can i put this libs to in cordova project?

Thanks.

**Comment by tatanka987** [comment]
import like usual android project
