### ISSUE TITLE
Integration with Javascript API

### ISSUE THREAD

**Issue by vinaywadhwa** [QuickBlox/quickblox-android-sdk#314]
I was actually working with the samples provided here - android, web. 

When i run these two and sign in to the same chat rooms from both web and mobile - the user signing in from web don't show up in mobile and vice versa. 

However, mobile users show up to other mobiles users & web users show up to other web users. I validated the ICE settings. 

Eg: if i create user vinay in chatroom vinaywadhwa in mobile, create user vinay2 in chatroom vinaywadhwa in web, the api "user by tags"( https://api.quickblox.com/users/by_tags.json?tags=vinaywadhwa)  should return both users from both mobile & web right? they dont

**Comment by tatanka987** [comment]
long time inactivity

**Comment by vinaywadhwa** [comment]
Although i am not using this library anymore, the inactivity was due to no-reply from Quickblox :-)

**Comment by RomanPronin** [comment]
Sorry for a long time not answering.

**Comment by koolll** [comment]
did you get any solution about this?

**Comment by RomanPronin** [comment]
Hi @koolll, if you have some problem you can create new issue with description.
