### ISSUE TITLE
Does any one have an example of the QBRTCSurfaceView being implemented?

### ISSUE THREAD

**Issue by xpressmobtech** [QuickBlox/quickblox-android-sdk#316]
Does any one have an example of the QBRTCSurfaceView being implemented in the sample android webrtc project ? I just can't seem to get it working correctly.

**Comment by RomanPronin** [comment]
Hello @xpressmobtech, you can find QBRTCSurfaceView implementation in sample-videochat-webrtc by this [link](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-webrtc) (VideoConversationFragment)

**Comment by tatanka987** [comment]
long time inactivity
