### ISSUE TITLE
Push: No one can receive the message

### ISSUE THREAD

**Issue by bayanruby** [QuickBlox/quickblox-android-sdk#318]
При отправке пуш уведомления выдает ошибку:
com.quickblox.core.exception.QBResponseException: No one can receive the message

http://take.ms/SBLaP

**Comment by vfite** [comment]
Hi there. Pls use english for writing issues.
Meaning of error exactly matches error from request. "No one can receive the message"  means you sent push to user who doesn't have subscriptions.

**Comment by bayanruby** [comment]
Hello guys.

I get exception when try sending push notification:
com.quickblox.core.exception.QBResponseException: No one can receive the message
But I have two users subscribed for push notifications. 
Why?
Code for subscribtion: 
http://take.ms/l3kYU

Code for send notification:
http://take.ms/LUwKJ

**Comment by roudunyy** [comment]
did you find the answer of this question, I got the same problem.

**Comment by tatanka987** [comment]
hi all, we recommend use new feature from QuickBlox Android SDK  - Auto subscription on Push Notifications since version 3.2.0. You can manage user's subscriptions in your admin panel.  If you gets any errors, please provide us full logs.

**Comment by vfite** [comment]
Closed as for inactivity

**Comment by manojkraftly** [comment]
Getting same error in iOS
Please check code

let event = QBMEvent()
                            event.notificationType = QBMNotificationType.push
                            //event.pushType = QBMPushType.GCM
                            event.usersIDs = otherUserId
                            event.message = trimmedString!
                            QBRequest.createEvent(event, successBlock: { (response, events) in
                                print(response)
                            }, errorBlock: { (error) in
                                print(error)
                            })

Response:-
error: Request failed: client error (422)
reasons: {
    errors =     (
        "No one can receive the message"
    );
}
[QBResponse], status: 422

**Comment by tatanka987** [comment]
please check subscription for user otherUserId in admin panel. Additionally check ENVIRONMENT for event and for user's subscription, they should be same.

**Comment by manojkraftly** [comment]
Yes i checked subscription for all user & ENVIRONMENT is same for both but
its nots working fine for me i need to call two different function for iOS
- Android, iOS - iOS. push will work with same function, can you please
send me line of code then i will compare with my code.

**Comment by tatanka987** [comment]
please follow iOS documentation how to send universal push. For next check try send push from admin panel. Then try remove subscription in admin panel for user otherUserId and recreate it again. You also can check subscription for user otherUserId if try send for it universal push from android device. Please collect all logs from iOS devise (request and response for create event) and from android device (request and response for create subscription) and post here.

**Comment by manojkraftly** [comment]
I followed iOS documentation, there every one getting issue to understand
document there not mentioned how can i push iOS - Android, i am reading
document from last week but not getting solution & i checked more developer
community fourm there i did not get any solution.

**Comment by tatanka987** [comment]
I wait requested logs. You can ask iOS team how to create universal push [here](https://github.com/QuickBlox/quickblox-ios-sdk).
