### ISSUE TITLE
Not able to Login to Quickblox chat ????

### ISSUE THREAD

**Issue by samarth220194** [QuickBlox/quickblox-android-sdk#319]
My quickblox chat was working before .I did not made any changes to the code but ,now I am getting the following Logcat while i am logging to quickblox chat and it is showing a blank screen while logging .

`10-26 22:15:37.485 29763-29763/com.baniaclothing.rang W/System.err: com.quickblox.core.exception.QBResponseException: No response received within reply timeout. Timeout was 15000ms (~15s). Used filter: No filter used or filter was 'null'.
10-26 22:15:37.491 29763-29763/com.baniaclothing.rang W/System.err:     at com.quickblox.chat.QBChatService$1.performInAsync(QBChatService.java:408)
10-26 22:15:37.491 29763-29763/com.baniaclothing.rang W/System.err:     at com.quickblox.chat.utils.ThreadTask.run(ThreadTask.java:15)
10-26 22:15:37.491 29763-29763/com.baniaclothing.rang W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
10-26 22:15:37.491 29763-29763/com.baniaclothing.rang W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-26 22:15:37.491 29763-29763/com.baniaclothing.rang W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
10-26 22:15:37.491 29763-29763/com.baniaclothing.rang W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
10-26 22:15:37.491 29763-29763/com.baniaclothing.rang W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-26 22:15:37.491 29763-29763/com.baniaclothing.rang W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-26 22:15:37.491 29763-29763/com.baniaclothing.rang W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-26 22:15:37.491 29763-29763/com.baniaclothing.rang W/System.err: Caused by: org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 15000ms (~15s). Used filter: No filter used or filter was 'null'.
10-26 22:15:37.492 29763-29763/com.baniaclothing.rang W/System.err:     at org.jivesoftware.smack.SASLAuthentication.authenticate(SASLAuthentication.java:250)
10-26 22:15:37.492 29763-29763/com.baniaclothing.rang W/System.err:     at org.jivesoftware.smack.tcp.XMPPTCPConnection.loginNonAnonymously(XMPPTCPConnection.java:374)
10-26 22:15:37.492 29763-29763/com.baniaclothing.rang W/System.err:     at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:456)
10-26 22:15:37.492 29763-29763/com.baniaclothing.rang W/System.err:     at com.quickblox.chat.QBChatService.login(QBChatService.java:350)
10-26 22:15:37.492 29763-29763/com.baniaclothing.rang W/System.err:     at com.quickblox.chat.QBChatService$1.performInAsync(QBChatService.java:393)`

**Comment by anniehita** [comment]
I received the same issue here as well

**Comment by anniehita** [comment]
According their website it is because of the maintenance, it will be fixed soon
http://quickblox.com/blog/maintenance-on-shared-instance-on-october-26th-wednesday/

**Comment by tatanka987** [comment]
long time inactivity
