### ISSUE TITLE
QB requests ridiculous permissions in manifest

### ISSUE THREAD

**Issue by davidwood99** [QuickBlox/quickblox-android-sdk#322]
hey guys, 
when i upload android app to play store, it says I'm requesting 14 permissions, including flashlight!!

A search in android studio shows it's in the generated quickblox package files in the merged manifest.

Note they are NOT in my project manifest.

1) how do I find these permissions in the actual QB package? (I've looked at every file)

2) How do I remove them?

Thanks

David (newbie)

**Comment by guimellon** [comment]
Hi David!
Had the same problem and it made my supported devices drop by around 4k (my app was available on 11k devices and then dropped to around 6.5k because of that).

I found a way to remove these strange permissions but kind of "overriding" them.
The thing that makes the difference is the 'tools:node="remove"' added on the uses-feature.

Below is what I added to my manifest:

<uses-feature
        android:name="android.hardware.camera"
        android:required="false"
        tools:node="remove" />
    <uses-feature
        android:name="android.hardware.camera.autofocus"
        android:required="false"
        tools:node="remove" />
    <uses-feature
        android:name="android.hardware.camera.flash"
        android:required="false"
        tools:node="remove" />

    <uses-feature
        android:name="android.permission.CAMERA"
        android:required="false"
        tools:node="remove" />
    <uses-feature
        android:name="android.permission.FLASHLIGHT"
        android:required="false"
        tools:node="remove" />
    <uses-feature
        android:name="android.hardware.FLASHLIGHT"
        android:required="false"
        tools:node="remove" />
    <uses-feature
        android:name="android.hardware.microphone"
        android:required="false"
        tools:node="remove" />

Sorry for not providing a reference for it :/ Found it in a StackOverflow thread months ago after being searching for weeks and couldn't find it in my History right now.

Hope it helps you!

**Comment by tatanka987** [comment]
close. long time inactivity

**Comment by aslamca** [comment]
Hi,
Modifying your solution:

 <uses-feature  android:name="android.hardware.camera.flash" android:required="false" tools:node="remove" />
    <uses-feature  android:name="android.hardware.camera" android:required="false" tools:node="remove" />
    <uses-feature  android:name="android.hardware.camera.autofocus" android:required="false" tools:node="remove" />
    <uses-feature  android:name="android.hardware.MICROPHONE" android:required="false" tools:node="remove" />

    <uses-permission android:name="android.permission.CAMERA" tools:node="remove" />
    <uses-permission android:name="android.permission.FLASHLIGHT" tools:node="remove" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" tools:node="remove" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" tools:node="remove" />

**Comment by aslamca** [comment]
This worked for me: [Permissions.txt](https://github.com/QuickBlox/quickblox-android-sdk/files/875508/Permissions.txt)
