### ISSUE TITLE
Chat connection after plan upgrade.

### ISSUE THREAD

**Issue by sashacomn** [QuickBlox/quickblox-android-sdk#323]
Hi, i want to ask, if i will purchase advanced or pro plan on quickblox, will it make chat connection time smaller?

**Comment by tatanka987** [comment]
hello @sashacomn, QuickBlox has greatly optimized chat connection in our QB SDKs. But you should pay your attention to the fact that both ‘Advanced’ and ‘PRO’ plans refer to accounts on Shared Cloud. Being shared means that a number of other accounts are placed there. Thus, the performance of one’s application, connection to chat, speed of API requests will always depend on overall amount of traffic on shared cloud. Putting it simply, if one of accounts on Shared instance is getting hit with a lot of traffic, the performance of your account can suffer.
Another option is Enterprise plans. It means that a client has his Dedicated instance and chat connection and etc won’t depend on traffic generated by other apps.
Please refer to FAQs to learn more http://quickblox.com/plans/  about QB plans and their peculiarities.

**Comment by tatanka987** [comment]
long time inactivity
