### ISSUE TITLE
Block the user even after bloking user goes offline

### ISSUE THREAD

**Issue by ArchanaGowda** [QuickBlox/quickblox-android-sdk#326]
Need to block the user using privacy list. Privacy list works fine when both the users are online. But it won't work if the blocking user goes offline. When the blocking user goes offline the blocked user can still send a message. I don't want to send a message once block is allowed.

Here is the code I used to block the user.
private void blockUser() {
QBPrivacyList list = new QBPrivacyList();
list.setName("public");
list.setActiveList(true);
ArrayList<QBPrivacyListItem> items = new ArrayList<>();
QBPrivacyListItem item1 = new QBPrivacyListItem();
item1.setAllow(false);
item1.setType(QBPrivacyListItem.Type.USER_ID);
item1.setValueForType(String.valueOf(qbChatDialog.getRecipientId()));
item1.setMutualBlock(true);
items.add(item1);
list.setItems(items);

try {
privacyListsManager.setPrivacyList(list);
privacyListsManager.setPrivacyListAsDefault("public");
blockedSuccess = true;
isBlocked = false;
} catch (SmackException.NotConnectedException | XMPPException.XMPPErrorException | SmackException.NoResponseException e) {
Log.e(TAG,"Failed to block: "+ e);
}
}

**I don't want to send a message once block is allowed**

**Now its allowing the user to chat even mutual block is enabled**

**Comment by RomanPronin** [comment]
Actually privacy list works regardless of the user status. We have some updates in [privacy list docs](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Privacy_lists)

**Comment by RomanPronin** [comment]
Long time inactivity
