### ISSUE TITLE
getting wrong private or public image url

### ISSUE THREAD

**Issue by Hafiz-Waleed-Hussain** [QuickBlox/quickblox-android-sdk#327]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*
Android, 2.6

**Did this work before?**
Yes

**Expected behavior**
Currently we shifted from free account to Enterprise account. So Quickblox already shifted to our Amazon server. Now I am getting wrong urls of image files. Original urls if I check on QB portal I am getting on amazon servers but on application I am getting to api endpoint. which is not working. 
Like:

Image url I am getting is : https://apiqb.icarasia.com/blobs/e7a082c3585645fb86e1b36b2216014200

On portal:
https://s3-ap-southeast-1.amazonaws.com/qb-icarasia-s3/e7a082c3585645fb86e1b36b2216014200

**Actual behavior**
 Should give me below url 
https://s3-ap-southeast-1.amazonaws.com/qb-icarasia-s3/e7a082c3585645fb86e1b36b2216014200

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by RomanPronin** [comment]
Hello @Hafiz-Waleed-Hussain, give us log how you uploaded this file (REQUEST - RESPONSE).

**Comment by Hafiz-Waleed-Hussain** [comment]
Hi Guys below is my code.


        QBContent.uploadFileTask(file, true, null, new QBEntityCallback<QBFile>() {
            @Override
            public void onSuccess(QBFile qbFile, Bundle bundle) {
                callback.onSuccess(qbFile);
            }

            @Override
            public void onError(QBResponseException e) {
                callback.onError(e);
            }
        }, progressCallback);

**Comment by RomanPronin** [comment]
Ok, and log please, with requests and responses after performing QBContent.uploadFileTask

**Comment by RomanPronin** [comment]
Long time inactivity.
