### ISSUE TITLE
QBRTCSurfaceView not working after taking picture during video call

### ISSUE THREAD

**Issue by A86S** [QuickBlox/quickblox-android-sdk#328]
I have faced this issue while i am open device camera during video call and while i am come back to my video call screen the QBRTCSurfaceView stop working. 

I am using quicblox quickblox-android-sdk-videochat-webrtc-3.0

**Comment by RomanPronin** [comment]
Please, use latest version [sdk](https://quickblox.com/developers/Android#Download_Android_SDK)
