### ISSUE TITLE
Continously getting old messages

### ISSUE THREAD

**Issue by Hemant0601** [QuickBlox/quickblox-android-sdk#330]
In my smack logs I am getting lot of messages like this, its like 100 logs per 5 sec.

<presence id="8XJ7c-26957" from="35886_581388c7a28f9a2226000054@muc.chat.quickblox.com/15922255" to="15922255-35886@chat.quickblox.com/android_00000000-1af9-0c20-ffff-ffffa6ac9afa_00000000-1af9-0c20-ffff-ffffa6ac9afa" xmlns="jabber:client"><x xmlns="http://jabber.org/protocol/muc#user"><item affiliation="admin" jid="15922255-35886@chat.quickblox.com/android_00000000-1af9-0c20-ffff-ffffa6ac9afa_00000000-1af9-0c20-ffff-ffffa6ac9afa" role="moderator" nick="15922255"/><status code="110"/></x></presence>

Similarly ,

under my msg listener QBChatDialogMessageListener

I am getting lot of messages which are from same dialog but with old date_sent value, those are like 20 msg of same body per sec. Any help would be appreciated.

**Comment by tatanka987** [comment]
hi @Hemant0601, that type of dialogs do you use? If you use QBDialogType.GROUP and run join to dialog without setting parameter discussionHistory.setMaxStanzas(0); you will get all old messages.

**Comment by Hemant0601** [comment]
@tatanka987 so if I join a group using discussionHistory.setMaxStanzas(0); then I wont get old messages? can u give details on the object from which discussionHistory is created.

**Comment by tatanka987** [comment]
For getting old messages you can use REST request ([details](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Retrieve_list_of_messages)). You can configure some parameters for getting needed messages.

**Comment by vfite** [comment]
Closed for long inactivity
