### ISSUE TITLE
Unable to login into QuickBlox.

### ISSUE THREAD

**Issue by KianCh** [QuickBlox/quickblox-android-sdk#332]
I am unable to login into the quickblox from morning onwards . Yesterday It was working fine,But morning onwards it was not working. Below is the Snippet of the code.  

ChatHelper.getInstance().login(qbUser, new QBEntityCallback<Void>() {
            @Override
            public void onSuccess(Void result, Bundle bundle) { 
            }
            @Override
            public void onError(QBResponseException e) {
            }
        });

**Comment by ksrpraneeth** [comment]
i tried to run sample code provided in website
its not working

**Comment by ksrpraneeth** [comment]
Apparently there is a issue from quickblox side
http://quickblox.com/blog/shared-instance-chat-performance-degradation/

**Comment by KianCh** [comment]
Thanks praneeth.
