### ISSUE TITLE
Unable to get unread count and chat data,dialog messages. 

### ISSUE THREAD

**Issue by KoustuvGanguly** [QuickBlox/quickblox-android-sdk#335]
**Environment details**
Android,API 16 to 24

**Did this work before?**
Yes before the shared cluster failure it was working perfectly.

**Expected behavior**
It should return the unread count and should load the chat history as per expectation.

**Actual behavior**
It`s always returning unread count as ZERO. and no chat history when i am loading dialog messages.  
Also when ever I am creating a qb dialog instance by passing the dialog id as string(which is not null) in constructor it is throwing qbdialog.tostring() null pointer exception.

**Logs**
XMPP [END OF DIALOG], server closed the connection prematurely. 

sometimes no exception it comes in success block in call back with zero unread count or zero length qbmessage arraylist(though i had chat in that group chat dialog).  

**Steps to reproduce the behavior**

Try to fetch the unread count using group chat dialog id or try to fetch dialog messages using the group chat dialog id. 

**Any others comments?**
Please give info to subscribers of shared or enterprize instances before this kind of disaster.Otherwise,those who are using this for building commercial apps they get in trouble, looses clients.Eventually looses trust n patience on QB.

**Comment by tatanka987** [comment]
Try [latest version](https://quickblox.com/developers/Android) of QuickBlox Android SDK
