### ISSUE TITLE
Unable to send or retrieve chat messages while initiating group chat

### ISSUE THREAD

**Issue by KianCh** [QuickBlox/quickblox-android-sdk#336]
**Environment details :**

Android SDK 15+

**Did this work before?**

It was working fine earlier. Unable to send or retrieve the chat from 25th November 2016

**Type of Chat :**

Group Chat

**Expected Behavior :**

Chat should be updated into the chat dialog as and when the chat message sent and should return the chat history on load.

**Actual Behavior :**

While sending the chat message, the message is adding to the chat adapter, but not really getting updated to the quickblox server. When we logged in and checked from quickblox server we are not able to see the messages which we sent latest. Also we are not able to see any kind of errors or exceptions while sending the message. When we are doing private chat we found no issue. This is happening for group chat. 

**Logs :**

Not able to see any kind of error logs for the scenario. Please find the below log from chat creation to load chat history

11-28 12:52:00.341 14586-20133/yqlabs.com.smeapp V/FA: Activity paused, time: 149003605
11-28 12:52:00.351 14586-14586/yqlabs.com.smeapp V/FA: onActivityCreated
11-28 12:52:00.361 14586-14586/yqlabs.com.smeapp V/BaseActivity: wasAppRestored = false
11-28 12:52:00.361 14586-14586/yqlabs.com.smeapp V/BaseActivity: isQbSessionActive = true
11-28 12:52:00.385 14586-14586/yqlabs.com.smeapp V/ChatHelper: onCreate ChatActivity on Thread ID = 1
11-28 12:52:00.389 14586-20133/yqlabs.com.smeapp V/FA: Activity resumed, time: 149003659
11-28 12:52:00.389 14586-14586/yqlabs.com.smeapp D/tag: slider exce-->Attempt to invoke virtual method 'boolean android.support.v4.widget.DrawerLayout.isDrawerOpen(android.view.View)' on a null object reference
11-28 12:52:00.398 14586-15038/yqlabs.com.smeapp D/SMACK: SENT (0): <presence to='44858_5834479aa28f9a98450000c6@muc.chat.quickblox.com/20536906' id='VZNjh-36' type='unavailable'></presence>
11-28 12:52:00.399 14586-15038/yqlabs.com.smeapp D/SMACK: SENT (0): <r xmlns='urn:xmpp:sm:3'/>
11-28 12:52:00.400 14586-15038/yqlabs.com.smeapp D/SMACK: SENT (0): <presence to='44858_5834479aa28f9a98450000c6@muc.chat.quickblox.com/20536906' id='VZNjh-37'><x xmlns='http://jabber.org/protocol/muc'><history maxstanzas='0'/></x></presence>
11-28 12:52:00.401 14586-15038/yqlabs.com.smeapp D/SMACK: SENT (0): <r xmlns='urn:xmpp:sm:3'/>
11-28 12:52:00.761 14586-15039/yqlabs.com.smeapp D/SMACK: RECV (0): <a xmlns='urn:xmpp:sm:3' h='9'/>
11-28 12:52:00.762 14586-15039/yqlabs.com.smeapp D/SMACK: RECV (0): <presence xmlns="jabber:client" type="unavailable" id="VZNjh-36" from="44858_5834479aa28f9a98450000c6@muc.chat.quickblox.com/20536906" to="20536906-44858@chat.quickblox.com/android_00000000-26ed-cb8a-ffff-ffff9011c01a"><x xmlns="http://jabber.org/protocol/muc#user"><item affiliation="admin" role="moderator" nick="20536906" jid="20536906-44858@chat.quickblox.com/android_00000000-26ed-cb8a-ffff-ffff9011c01a"/><status code="110"/></x></presence>
11-28 12:52:00.763 14586-15039/yqlabs.com.smeapp D/SMACK: RECV (0): <r xmlns='urn:xmpp:sm:3' />
11-28 12:52:00.764 14586-15038/yqlabs.com.smeapp D/SMACK: SENT (0): <a xmlns='urn:xmpp:sm:3' h='21'/>
11-28 12:52:00.777 14586-14586/yqlabs.com.smeapp D/QBASDK: =========================================================
                                                           === REQUEST ==== 564beb07-afc8-4c09-9300-ef3395574893 ===
                                                           REQUEST
                                                               GET https://api.quickblox.com/chat/Message.json
                                                           HEADERS
                                                               QuickBlox-REST-API-Version=0.1.1
                                                               QB-SDK=Android 3.0
                                                               QB-Token=71a710baf7ff9d128e1d1ef291ba576d4c00af3a
                                                           PARAMETERS
                                                               sort_desc=date_sent
                                                               limit=50
                                                               chat_dialog_id=5834479aa28f9a98450000c6
                                                           INLINE
                                                               GET https://api.quickblox.com/chat/Message.json?sort_desc=date_sent&limit=50&chat_dialog_id=5834479aa28f9a98450000c6
11-28 12:52:01.150 14586-15039/yqlabs.com.smeapp D/SMACK: RECV (0): <a xmlns='urn:xmpp:sm:3' h='10'/>
11-28 12:52:01.161 14586-15039/yqlabs.com.smeapp D/SMACK: RECV (0): <presence xmlns="jabber:client" id="VZNjh-37" from="44858_5834479aa28f9a98450000c6@muc.chat.quickblox.com/20536906" to="20536906-44858@chat.quickblox.com/android_00000000-26ed-cb8a-ffff-ffff9011c01a"><x xmlns="http://jabber.org/protocol/muc#user"><item affiliation="admin" role="moderator" nick="20536906" jid="20536906-44858@chat.quickblox.com/android_00000000-26ed-cb8a-ffff-ffff9011c01a"/><status code="110"/></x></presence>
11-28 12:52:01.163 14586-15039/yqlabs.com.smeapp D/SMACK: RECV (0): <r xmlns='urn:xmpp:sm:3' />
11-28 12:52:01.164 14586-15038/yqlabs.com.smeapp D/SMACK: SENT (0): <a xmlns='urn:xmpp:sm:3' h='22'/>
11-28 12:52:02.193 14586-14586/yqlabs.com.smeapp D/QBASDK: *********************************************************
                                                           *** RESPONSE *** 564beb07-afc8-4c09-9300-ef3395574893 ***
                                                           STATUS : 200 
                                                           HEADERS
                                                               X-Runtime=0.017838
                                                               Cache-Control=max-age=0, private, must-revalidate
                                                               X-Rack-Cache=miss
                                                               QuickBlox-REST-API-Version=0.1.1
                                                               X-UA-Compatible=IE=Edge,chrome=1
                                                               QB-Token-ExpirationDate=2016-11-28 09:16:16 UTC
                                                               Status=200 OK
                                                               X-Request-Id=c6b9a7b39e1e395bdb1a3da09d831e5e
                                                               X-Android-Response-Source=NETWORK 200
                                                               Connection=Close
                                                               X-Android-Sent-Millis=1480317721468
                                                               Content-Type=application/json; charset=utf-8
                                                               Date=Mon, 28 Nov 2016 07:22:01 GMT
                                                               Server=openresty/1.9.15.1
                                                               ETag="d82fcebcd0d568a824456c8c6214ed85"
                                                               Content-Length=2063
                                                               Strict-Transport-Security=max-age=15768000;
                                                               X-Android-Received-Millis=1480317722175
                                                               Access-Control-Allow-Origin=*
                                                           BODY
                                                               '{"skip":0,"limit":50,"items":[{"_id":"583692793760dda22847d458","attachments":[],"chat_dialog_id":"5834479aa28f9a98450000c6","created_at":"2016-11-24T07:10:49Z","date_sent":1479971449,"delivered_ids":[20536906],"dialog_id":"5834479aa28f9a98450000c6","message":"hi","read_ids":[20536906],"recipient_id":null,"sender_id":20536906,"updated_at":"2016-11-24T07:10:49Z","read":0},{"_id":"5834487bb2937efc050041ae","attachments":[],"chat_dialog_id":"5834479aa28f9a98450000c6","created_at":"2016-11-22T13:30:35Z","date_sent":1479821435,"delivered_ids":[20619485],"message":"Hcjjcj","read_ids":[20619485,20536906],"recipient_id":null,"sender_id":20619485,"updated_at":"2016-11-22T13:31:20Z","read":0},{"_id":"5834484db2937efc050041ac","attachments":[{"id":"6465482","url":"https://api.quickblox.com/blobs/d26ba01193e0402199c954a411102fed00.json","type":"photo"}],"chat_dialog_id":"5834479aa28f9a98450000c6","created_at":"2016-11-22T13:29:49Z","date_sent":1479821389,"delivered_ids":[20619485],"message":null,"read_ids":[20619485,20536906],"recipient_id":null,"sender_id":20619485,"updated_at":"2016-11-22T13:30:08Z","read":0},{"_id":"583447c9b2937efc050041aa","attachments":[],"chat_dialog_id":"5834479aa28f9a98450000c6","created_at":"2016-11-22T13:27:37Z","date_sent":1479821257,"delivered_ids":[20619485],"message":"Hi","read_ids":[20619485,20536906],"recipient_id":null,"sender_id":20619485,"updated_at":"2016-11-22T13:28:53Z","read":0},{"_id":"583447aa79192741090041aa","attachments":[],"chat_dialog_id":"5834479aa28f9a98450000c6","created_at":"2016-11-22T13:27:06Z","date_sent":1479821226,"delivered_ids":[20536906],"message":"Hello","read_ids":[20536906,20619485],"recipient_id":null,"sender_id":20536906,"updated_at":"2016-11-22T13:27:32Z","read":0},{"_id":"583447a679192741090041a8","attachments":[],"chat_dialog_id":"5834479aa28f9a98450000c6","created_at":"2016-11-22T13:27:02Z","date_sent":1479821222,"delivered_ids":[20536906],"message":"Hi","read_ids":[20536906,20619485],"recipient_id":null,"sender_id":20536906,"updated_at":"2016-11-22T13:27:32Z","read":0}]}'
11-28 12:52:02.237 14586-14586/yqlabs.com.smeapp D/QBASDK: =========================================================
                                                           === REQUEST ==== 1f0c7f13-db8a-4760-9a44-9d2b0fd0688d ===
                                                           REQUEST
                                                               GET https://api.quickblox.com/users.json
                                                           HEADERS
                                                               QuickBlox-REST-API-Version=0.1.1
                                                               QB-SDK=Android 3.0
                                                               QB-Token=71a710baf7ff9d128e1d1ef291ba576d4c00af3a
                                                           PARAMETERS
                                                               page=1
                                                               per_page=2
                                                               filter[]=number id in 20619485,20536906
                                                           INLINE
                                                               GET https://api.quickblox.com/users.json?page=1&per_page=2&filter[]=number+id+in+20619485%2C20536906
11-28 12:52:03.645 14586-14586/yqlabs.com.smeapp D/QBASDK: *********************************************************
                                                           *** RESPONSE *** 1f0c7f13-db8a-4760-9a44-9d2b0fd0688d ***
                                                           STATUS : 200 
                                                           HEADERS
                                                               X-Runtime=0.045865
                                                               Cache-Control=max-age=0, private, must-revalidate
                                                               X-Rack-Cache=miss
                                                               QuickBlox-REST-API-Version=0.1.1
                                                               X-UA-Compatible=IE=Edge,chrome=1
                                                               QB-Token-ExpirationDate=2016-11-28 09:16:16 UTC
                                                               Status=200 OK
                                                               X-Request-Id=3f00854545536763e8d9ef216fef338b
                                                               X-Android-Response-Source=NETWORK 200
                                                               Connection=Close
                                                               X-Android-Sent-Millis=1480317722895
                                                               Content-Type=application/json; charset=utf-8
                                                               Date=Mon, 28 Nov 2016 07:22:02 GMT
                                                               Server=openresty/1.9.15.1
                                                               ETag="c82dd862bfa8ff8c99eda3feddc3d2f1"
                                                               Content-Length=886
                                                               Strict-Transport-Security=max-age=15768000;
                                                               X-Android-Received-Millis=1480317723628
                                                               Access-Control-Allow-Origin=*
                                                           BODY
                                                               '{"current_page":1,"per_page":2,"total_entries":2,"items":[{"user":{"id":20536906,"owner_id":56098,"full_name":"Deepthi","email":"deepthi.apptester@gmail.com","login":"deepthi.apptester@gmail.com","phone":null,"website":null,"created_at":"2016-11-16T14:17:42Z","updated_at":"2016-11-28T06:34:03Z","last_request_at":"2016-11-28T07:17:37Z","external_user_id":null,"facebook_id":null,"twitter_id":null,"blob_id":null,"custom_data":null,"twitter_digits_id":null,"user_tags":null}},{"user":{"id":20619485,"owner_id":56098,"full_name":null,"email":"shaen@abinbevsample.com","login":"shaen@abinbevsample.com","phone":null,"website":null,"created_at":"2016-11-18T08:43:30Z","updated_at":"2016-11-24T06:35:20Z","last_request_at":"2016-11-26T10:06:46Z","external_user_id":87654323,"facebook_id":null,"twitter_id":null,"blob_id":null,"custom_data":null,"twitter_digits_id":null,"user_tags":null}}]}'
11-28 12:53:08.759 14586-15038/yqlabs.com.smeapp D/SMACK: SENT (0): <message to='44858_5834479aa28f9a98450000c6@muc.chat.quickblox.com' id='583bdb5ceed6639551406a16' type='groupchat'><body>ghff</body><markable xmlns='urn:xmpp:chat-markers:0'/><extraParams xmlns='jabber:client'><dialog_id>5834479aa28f9a98450000c6</dialog_id><date_sent>1480317788</date_sent><save_to_history>1</save_to_history></extraParams></message>
11-28 12:53:08.759 14586-15038/yqlabs.com.smeapp D/SMACK: SENT (0): <r xmlns='urn:xmpp:sm:3'/>
11-28 12:53:09.144 14586-15039/yqlabs.com.smeapp D/SMACK: RECV (0): <a xmlns='urn:xmpp:sm:3' h='11'/>
11-28 12:53:09.146 14586-15039/yqlabs.com.smeapp D/SMACK: RECV (0): <message xmlns="jabber:client" type="groupchat" id="583bdb5ceed6639551406a16" from="44858_5834479aa28f9a98450000c6@muc.chat.quickblox.com/20536906" to="20536906-44858@chat.quickblox.com/android_00000000-26ed-cb8a-ffff-ffff9011c01a"><body>ghff</body><markable xmlns="urn:xmpp:chat-markers:0"/><extraParams xmlns="jabber:client"><dialog_id>5834479aa28f9a98450000c6</dialog_id><date_sent>1480317788</date_sent><save_to_history>1</save_to_history></extraParams><delay xmlns="urn:xmpp:delay" stamp="2016-11-28T07:23:08Z"/></message>
11-28 12:53:09.150 14586-15039/yqlabs.com.smeapp D/SMACK: RECV (0): <r xmlns='urn:xmpp:sm:3' />
11-28 12:53:09.150 14586-15038/yqlabs.com.smeapp D/SMACK: SENT (0): <a xmlns='urn:xmpp:sm:3' h='24'/>

**Steps to reproduce the behavior :**

Opening chat dialog is not showing the chat messages after 24.11.2016.

**Comment by syam82** [comment]
Same issue

**Comment by RomanPronin** [comment]
It were some problems with shared server side [info link](http://quickblox.com/blog/shared-instance-chat-performance-degradation/) Now it is all ok.
