### ISSUE TITLE
Displaying quickbloxid in groupchat title

### ISSUE THREAD

**Issue by gowthamidommeti** [QuickBlox/quickblox-android-sdk#337]
After creating the group chat if we click on Add user to chat and come back to group chat it is adding quickblox id of the login user in group chat title.PLease help me to resolve the issue.
![screenshot_2016-11-30-11-00-05 1](https://cloud.githubusercontent.com/assets/24225438/20740844/51096802-b6ec-11e6-83dd-4292f2cedab1.png)

**Comment by tatanka987** [comment]
hello @gowthamidommeti looks like you added user, which doesn't have full name, in chat sample we downloads all users by tag from QuickBlox server before adding their to dialog.
