### ISSUE TITLE
QuickBlox SDK 3.2.0 ERROR: Authentication failed, check user's ID and password

### ISSUE THREAD

**Issue by guimellon** [QuickBlox/quickblox-android-sdk#342]
Since I upgraded to SDK 3.2.0, I started getting this error on my Android App for several users when trying to signin using QBUsers.signIn(user):

`com.quickblox.core.exception.QBResponseException: Authentication failed, check user's ID and password`

The problem is that it doesn't happen when using my website. I can login in and authenticate perfectly using the same login and password.

Is this something related to the new SDK? 

This issue didn't use to happen on the previous versions of the SDK and quickblox is a fundamental part of my app.

**Comment by RomanPronin** [comment]
Hello @guimellon , this exception throws if you try to do QBChatService.getInstance().login(user); not QBUsers.signIn(user). So, check that you set user ID - user.setId(),  before login to chat.

**Comment by guimellon** [comment]
Yeah, you're totally right @RomanPronin ! Sorry about that.
The problem is that it wasn't happening at all when using the previous versions of the SDK. And since I upgraded it to 3.2.0 it started happening frequently.

**Comment by histone** [comment]
Same problem with here on android.

**Comment by yalematta** [comment]
Did anyone find a solution? We are getting the same error!

**Comment by alexanderkoqb** [comment]
Hey @guimellon 
Since it's been a while and if you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
