### ISSUE TITLE
can any one explain privacy settings was unable to block  person it must include all of the desired items (i.e., not a "delta").if possible small example 

### ISSUE THREAD

**Issue by bharatkumaremani** [QuickBlox/quickblox-android-sdk#345]
is there any sample example for privacy block and unblock

**Comment by gowthamidommeti** [comment]
I also have same problem

**Comment by RomanPronin** [comment]
Hi, there. You can find all info with examples about Privacy list [here](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Privacy_lists). As for expression it must include all of the desired items, it means when you want to update list, you should add all opponents you want to to be blocked in list, not only new ones.

**Comment by RomanPronin** [comment]
Long time inactivity
