### ISSUE TITLE
 how to add group name for the group chat.

### ISSUE THREAD

**Issue by gowthamidommeti** [QuickBlox/quickblox-android-sdk#348]
please any one tell me how to set group name to the group chat . instead of displaying user names. 
Please help me resolve this issue.

**Comment by tatanka987** [comment]
hello @gowthamidommeti you can use this [guide](http://quickblox.com/developers/Android_XMPP_Chat_Sample#Update_group_dialog) for updating group dialog's name but without settings parameter QBDialogRequestBuilder (you can set it as null)
