### ISSUE TITLE
Dialog.initForChat() crashes application

### ISSUE THREAD

**Issue by ubarua123** [QuickBlox/quickblox-android-sdk#349]
According to the [documentation](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Chat_in_private_dialog) if we need to create a `dialog` from `senderId`, we can do the following
```
QBChatDialog opponentDialog = new QBChatDialog();
 ArrayList<Integer> occupantIds = new ArrayList<>();
 occupantIds.add(message.getSenderId());
 opponentDialog.setOccupantsIds(occupantIds);
 
//init Dialog for chatting
 opponentDialog.initForChat(dialogId, QBDialogType.PRIVATE, chatService);
```

**Or even do this:**
`DialogUtils.buildPrivateDialog(senderId);`

The above statement also does the same thing as mentioned in the beginning.

Now,
The line `opponentDialog.initForChat(dialogId, QBDialogType.PRIVATE, chatService);` **crashes** the application because internally it tries to fetch `this.getRecipientId().intValue()` on line `231` in the class `QBChatDialog.java` of the SDK, which _always_ returns -1 since there's only 1 value in the occupantId list.

Either I am missing some step or this is a bug or the documentation needs to be updated.
Can anybody tell me what to do here?

**Comment by vfite** [comment]
Hi there. First of all specify pls sdk version.
As for your issue you should be logged in before doing initForChat, because it uses logged user into chat. Also check you set not your own logged user into occupantIds field for dialog.
