### ISSUE TITLE
Deleting Private Chat Dialog

### ISSUE THREAD

**Issue by ltburruel** [QuickBlox/quickblox-android-sdk#35]
Is there a way to delete a Private Chat Dialog?  

I am using Android SDK 2.0 QBPrivateChatManager deleteDialog and getting a 200 response.
After doing that and making this request GET https://api.quickblox.com/chat/Dialog.json
The Dialog that I deleted is not in the response which is good 
However, when I start a chat with the same user that was in the Dialog I deleted, all the old chat messages reappear.  

Any help with this issue would be greatly appreciated.  Thanks

**Comment by Shahjahan786** [comment]
I'm using sdk 3.5.0 but still it happens to me
