### ISSUE TITLE
Authentication failed, check user's ID and password (3.2.0)

### ISSUE THREAD

**Issue by histone** [QuickBlox/quickblox-android-sdk#350]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*Android, 3.2.0

**Did this work before?**
yes on 3.0

**Expected behavior**
should log in to chat.

**Actual behavior**
 QBUsers.signIn(qbUser).performAsync(new QBEntityCallback<QBUser>() {
                @Override
                public void onSuccess(QBUser user, Bundle bundle) {
                    // success
                }

                @Override
                public void onError(QBResponseException e) {
               // error
                }
After tha login to chat 
QBChatService.getInstance().login(qbUser1, new QBEntityCallback<QBUser>() {
                    @Override
                    public void onSuccess(QBUser qbUser, Bundle bundle) {
                        // success
                    }

                    @Override
                    public void onError(QBResponseException errors) {
                       // on error
                    }
                });
**Logs**
in loginto chat on error : Authentication failed, check user's ID and password 
and error code -1
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by tatanka987** [comment]
hello @histone check qbUser1's id and password before login to the chat

**Comment by histone** [comment]
I have checked and it's corrected.

**Comment by pelipetsaa** [comment]
you must set a password for the qbUser1 from the qbUser
qbUser1.setPassword(qbUser.getPassword());
QBChatService.getInstance().login(qbUser1, new QBEntityCallback() {
...

**Comment by azlandoctor2u** [comment]
@histone Have you resolve this issue? I am facing the same issue here. I'm using version 3.3.0.

**Comment by histone** [comment]
@pelipetsaa yes, I have set the password too before login to chat.

**Comment by histone** [comment]
@azlandoctor2u  Not resolve yet, and Quickblox team not responding about it.:)

**Comment by tatanka987** [comment]
@histone please provide us logs from start creating REST session to getting this error. QB logs and chat logs must be enabled: 
QBSettings.getInstance().setLogLevel(LogLevel.DEBUG);
QBChatService.setDebugEnabled(true);

**Comment by histone** [comment]
@tatanka987, Resolved after updated the sdk from 3.2.0 to 3.3.0

But here is an other error for FCM

**Comment by tatanka987** [comment]
@histone please create new issue with problem with FCM.
