### ISSUE TITLE
notification is not getting for individual user

### ISSUE THREAD

**Issue by gowthamidommeti** [QuickBlox/quickblox-android-sdk#351]
Hi ..

I installed the latest code . In this i can get the notifiactions for the group chatting But iam unable to get notification for individual. Please help me to resolve this issue.

**Comment by RomanPronin** [comment]
hello @gowthamidommeti. Do you use auto subscription to push notification [feature](https://quickblox.com/developers/SimpleSample-messages_users-android#Setup_Push_Notifications_SDK_3.2_-_Auto_subscription)? Also look carefully at [sample chat](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-chat).

**Comment by alexanderkoqb** [comment]
Hey @gowthamidommeti 
Since it's been a while and if you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
