### ISSUE TITLE
Notification issues!

### ISSUE THREAD

**Issue by Shahgupta0007** [QuickBlox/quickblox-android-sdk#352]
using SDK 3.2 and FCM for notifications.

1) From the docs:

**Add empty current_key settings into your google-services.json file for your package name:
"api_key": [
        {
          "current_key": ""
        }
      ],**

can anyone please explain why do we need to have empty current_key? 

2) We have successfully integrated quickblox notifications in our app but there are some issues when we send notifications from firebase console.  If app is open(logged into chat service) then we receive notifications without any content(seems like service extending QBFcmPushListenerService processes it). And when app is in background(logged out of chat service) we receive notifications with content but with default notification icon.

It would be really helpful if anyone can tell us what we are missing?

**Comment by RomanPronin** [comment]
If you generated google-services.json in firebase console, current_key is already defined, so you needn't set empty current_key. You need set this, if you use GCM google-services.json.
As for notification icon it is possible issue with Lollipop ([link](http://stackoverflow.com/questions/28387602/notification-bar-icon-turns-white-in-android-5-lollipop)) Also, you can override method onMessageReceived(String var1, Bundle var2) from QBGcmPushListenerService, and do your own logic for received messages.

**Comment by Shahgupta0007** [comment]
@RomanPronin  Thanks! Really appreciated.

Oh Okay! We will keep the generated key then.

Actually We have already overridden onMessageReceived method and everything is working fine for quickblox notifications. But we are having trouble with notifications that are sent from Firebase console. When user is logged into chat service then Firebase notifications are received without content(just the icon and header). And when user is logged out of chat service then they receive notification with content but the icon is not the one defined in onMessageReceived method.

Can you help us understand this behavior? Let me know if you need more info.

**Comment by RomanPronin** [comment]
Look, if you send notification from Firebase console, in onMessageReceived(RemoteMessage remoteMessage) try to get message content from Notification. Something like this:

        String message;
        if (remoteMessage.getNotification() != null) {
            message = remoteMessage.getNotification().getBody();
        } else {
            message = (String) data.get("message");
        }
        showNotification(message);

**Comment by Shahgupta0007** [comment]
This works perfectly when the app is in foreground.. but onMessageReceived is not called when app is in background.

After little bit of search I found that there are two types of notifications in Firebase
 - display-messages - These notifications call onMessageReceived only when app is in foreground.
 - data-messages - These notifications call onMessageReceived even when app is in background.

Since I was sending firebase notifications from console(which only sends display-messages), onMessageReceived was not called in background.

Source : https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages


@RomanPronin Thanks a lot for your help!

**Comment by Shahgupta0007** [comment]
As the message says "Notification has been added to queue" doesn't mean that notification is delivered successfully. Please check logs to see if that notification was delivered or not. 

In case you don't know where to find logs, follow these steps:

 - Go to "queue" section inside push notification.
 - Under the column "status" click on sent status.
 - there you have your logs to see the status of your notification.

 If your message wast not delivered than check your GCM API key you had provided in the Quickblox console. Make sure you put Google Server Key there.

Also in order to receive a push notification, you must be logged out of chat service.

**Comment by Najneen22** [comment]
Thank you Shagupta.

Now notifications are working fine. I was sending wrong registrationId to createSubscription() method. Now I am sending registration token as a registrationId, getting from Firebase in onTokenRefresh() method and receiving notification in onMessageReceived().

**Comment by Shahgupta0007** [comment]
@Najneen22 There is no need to create subscription if you are using SDK 3.2. 

From the docs:
**Since version 3.2 android SDK provides new feature - auto subscription to push notification out of the box. It means you don’t need bother how to get GCM or FCM token, create QBPushNotifications.createSubscription and what to do with received data in your code anymore.**

**Comment by Najneen22** [comment]
@Shahgupta0007 

Previously I have not added subscription method to code, but in subscription tab on Quickblox dashboard, it was not showing any user as subscribed and not able to get push notification also. 
It seems auto subscription was not working. Any idea why?

I am facing another problem, **when app is not in background, chat notifications are receiving** but when **app is in foreground or in background I am not receiving any notification**. Can you guys help me ?
