### ISSUE TITLE
push notifications were not obtaining for an individual user

### ISSUE THREAD

**Issue by bharatkumaremani** [QuickBlox/quickblox-android-sdk#353]
**In latest SDK I was able to get push notifications for group messages but for individual users, these notifications are not obtaining can anyone please tell me how to get push notification for individual users**

**Comment by Shahgupta0007** [comment]
I have recently implemented on push notifications for private 1-1 chat in Quickblox, for most part they are very easy to setup(especially FCM).

Just follow this documentation : http://quickblox.com/developers/SimpleSample-messages_users-android

**Comment by RomanPronin** [comment]
Long time inactivity.
