### ISSUE TITLE
How to get total unread messages in the latest release.

### ISSUE THREAD

**Issue by latixinc** [QuickBlox/quickblox-android-sdk#355]
```
Set<String> dialogIds = new HashSet<String>();
String groupChatId = groupChat.getDialogId();
System.out.println("GroupChat Id: "+groupChatId);
dialogIds.add(groupChatId);
QBRestChatService.getTotalUnreadMessagesCount(dialogIds,null).performAsync(new QBEntityCallback<Integer>() {
 @Override
public void onSuccess(Integer integer, Bundle bundle) {
                                                        
 }

@Override
 public void onError(QBResponseException e) {

}
 });
```
I use that method in the latest library to get total unread messages but it always returns 0. what do i do. once the user close the groupchat all his info is cleared. Even notification does not work.
Please i will need reply urgently. If possible i will need a personal tutor on quickblox because the library is not clear at all.

**Comment by kunkhmer** [comment]
Try putting null in Id's and bundle.


Sent from my Samsung device

-------- Original message --------

**Comment by latixinc** [comment]
it also returned 0. Do i have to do a special configuration to the groupchat for it to be able to keep track of users unread messages

**Comment by kunkhmer** [comment]
It should work for all chats. I don't work at quick Blox.  But it works for me for private and group by putting null. Maybe your not refreshing it at the right time?


Sent from my Samsung device

-------- Original message --------

**Comment by latixinc** [comment]
Can you please give me code for creating groupchats.

**Comment by kunkhmer** [comment]
public void createDialogWithSelectedUsers(final List<QBUser> users,
                                              final QBEntityCallback<QBChatDialog> callback) {

        QBRestChatService.createChatDialog(QbDialogUtils.createDialog(users)).performAsync(
                new QbEntityCallbackWrapper<QBChatDialog>(callback) {
                    @Override
                    public void onSuccess(QBChatDialog dialog, Bundle args) {
                        QbDialogHolder.getInstance().addDialog(dialog);
                        QbUsersHolder.getInstance().putUsers(users);
                        super.onSuccess(dialog, args);
                    }
                });
    }

I used the one found in chathelper.java
https://github.com/QuickBlox/quickblox-android-sdk/blob/master/sample-chat/src/main/java/com/quickblox/sample/chat/utils/chat/ChatHelper.java

**Comment by latixinc** [comment]
You used a private groupchat, i am using a public groupchat. In private groupchat are the users permanent?  because i think that is why the unread messages are 0 and the notifications are not sent.
The application am developing is for a school and i do not want anybody to create groupchat, i want the users to join when the application is opened. Does private groupchat allow the users to join without invitation?. Please explain the concept of the private group chat to me.

**Comment by kunkhmer** [comment]
You can modify the QbDialogUtils.createDialog() method to create a public group. I havent used a public group yet so I cant tell you how it works. But private chat group is an invite only so far for me.

**Comment by latixinc** [comment]
But are the users permanent. Like if they go offline will they still be part of the group?

**Comment by kunkhmer** [comment]
Yes. Unless they leave or is deleted. You can also invite individuals into
group chat.

**Comment by latixinc** [comment]
Thanks alot for you help.

**Comment by latixinc** [comment]
I used private groupchat and everything is working fine. Thanks once again
