### ISSUE TITLE
3g/4g connection won't works

### ISSUE THREAD

**Issue by GiacomoSilli** [QuickBlox/quickblox-android-sdk#356]
Hello everyone, I'm using quickblox sdk sample videochat for ios and android.
Working properly using the wifi network.

If I try to use 3g / 4g the device can not connect.

Android log
http://pastebin.com/46QPhnU8

iOS log
http://pastebin.com/BqyxL2kG

iOS using wifi
Android using 3g/4g

What is the problem? Thanks

**Comment by Pro100Andrey** [comment]
Hi @GiacomoSilli, fixed

v2.3.1 - Jan 4, 2017

Fixed TURN/STUN Servers setup. Thanks GiacomoSilli for reporting the issue.
Added missing RTCVideoFrame.h file
