### ISSUE TITLE
Weird connection drop on leaving screen ON for long time

### ISSUE THREAD

**Issue by ubarua123** [QuickBlox/quickblox-android-sdk#357]
As the title mentions. I have enable these settings in QB

`QBChatService.ConfigurationBuilder configurationBuilder = new QBChatService.ConfigurationBuilder();
configurationBuilder
.setSocketTimeout(0)
.setKeepAlive(true)
.setAutojoinEnabled(true)
.setReconnectionAllowed(true);`
I even have this on 

`QBChatService.setDefaultAutoSendPresenceInterval(30);`

**How to reproduce this?**
Open your app, chat for a while and then leave the phone and let the screen be on for a long time.
You won't get any callbacks for disconnection or reconnection. Try sending a message then. 

On the other side, you dont receive push notifications, no incoming message nothing. If you have "save_to_history" ON, then you won't see the message in Quickblox servers.

Smack log gets printed 

`<message to='22470481-49028@chat.quickblox.com' id='58723d21c4548298e1e140ed' type='chat'><body>Gff</body><markable xmlns='urn:xmpp:chat-markers:0'/><extraParams xmlns='jabber:client'><dialog_id>5870acd0a0eb476ff2000011</dialog_id><date_sent>1483881761</date_sent><save_to_history>1</save_to_history></extraParams></message>`

But the other person doesnt receive anyth callback. Anybody face this?

**Comment by tatanka987** [comment]
hello @ubarua123 which version of QuickBlox Android SDK do you use? Can you reproduce this issue on our chat-sample? Can you provide more logs before getting this issue?

**Comment by smartgammadev** [comment]
any news from this error ? we still getting . 1-2 minutes on chat screen and messages not sent.

**Comment by tatanka987** [comment]
@smartgammadev  please provide us full logs from start login to chat to getting this error. Additionally specify version of used QuickBlox Android SDK  and your configurations for  QBTcpConfigurationBuilder (or QBChatService.ConfigurationBuilder).

**Comment by HarryMMR** [comment]
Yes. connections drop after some time. This even happens on sample app too. Snackbar will show up from bottom.

**Comment by alexanderkoqb** [comment]
Hey @ubarua123 
Since it's been a while and if you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
