### ISSUE TITLE
Your meta-data are not set, auto push subscribe unable (SDK 3.2)

### ISSUE THREAD

**Issue by veiz** [QuickBlox/quickblox-android-sdk#358]
I'm following the guide from https://quickblox.com/developers/SimpleSample-messages_users-android#Setup_Push_Notifications_SDK_3.2_-_Auto_subscription, and finally got this message from console.

**D/QBASDK: SubscribeService: Your meta-data are not set, auto push subscribe unable** 

I've double check the meta-data tag from AndroidManifest.xml and pretty sure I've set the right values.
```xml
<meta-data android:name="com.quickblox.messages.TYPE" android:value="FCM" />
<meta-data android:name="com.quickblox.messages.SENDER_ID" android:value="1036940727543" />
<meta-data android:name="com.quickblox.messages.QB_ENVIRONMENT" android:value="DEVELOPMENT" />
```

Any hints?

**Comment by RomanPronin** [comment]
Hello @veiz , pay attention, you must set SENDER_ID value as string resource.
```
<string name="sender_id">1036940727543</string>
...
<meta-data android:name="com.quickblox.messages.SENDER_ID" android:value="@string/sender_id" />
```

**Comment by kirtan-inexture** [comment]
Still doesn't work for me. Same issue..

**Comment by faizanprogrammer** [comment]
RomanPronin  thanks a lot you comment resolved my problem

**Comment by nobeldhar** [comment]
meta data need to be inside application (in case you put it outside).
