### ISSUE TITLE
Error in Sign up SDK version 3.2.0

### ISSUE THREAD

**Issue by naseefcse** [QuickBlox/quickblox-android-sdk#359]
hello, 
I am working with Quickblox sdk. I want to create sign up with only user name and password. I have followed the documentation of SDK 3.2.0 Authentication. But I am facing problem when trying to sign up with user login and password. The **error: 422** shows that user e-mail required. When I set user email in sign up and try to sign in then it wants e-mail confirmation with **error: 422**. Now my Questions are, 
**1) Why it's not possible to sign up with only login and password?**
**2) If I use user e-mail for sign up then is it mandatory to confirm the user e-mail for sign in?**

Please give me those answer as soon as possible.

**Comment by RomanPronin** [comment]
Sure you can sign up only with login and password. Show us log with request to QB for identification problem.

**Comment by vfite** [comment]
Closed for long inactivity
