### ISSUE TITLE
is local and remote stream recording available in quickblox(android sdk)?

### ISSUE THREAD

**Issue by shishram** [QuickBlox/quickblox-android-sdk#360]
let me know if stream recording functionality is available in android Sdk just like we have in Javascript sdk to record the video. if possible then please share a code snippet which can help in implementing this with quickblox.

**Comment by RomanPronin** [comment]
Hello @shishram. We're going to add video recording functionality in SDK at the end of the first quarter of the year.

**Comment by vfite** [comment]
closed as for inactivity
