### ISSUE TITLE
QBChatService.setConfigurationBuilder() has bug, not assigning to member variable

### ISSUE THREAD

**Issue by sincerekamal** [QuickBlox/quickblox-android-sdk#361]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*
Android, SDK Version - 3.3.0

**Did this work before?**
Yes

**Expected behavior**
ConfigurationBuilder object passed should be assigned to this.configurationBuilder 

**Actual behavior**
Assigned back to the same passed variable. configurationBuilder = configurationBuilder;
So whatever the configuration we pass, it's simply waste

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by tatanka987** [comment]
hello @sincerekamal, please provide us code for config configurationBuilder and full log from start login to success login to the chat

**Comment by sincerekamal** [comment]
You don't need a log, please review the code in QBChatService.java
````
    public static void setConfigurationBuilder(QBChatService.ConfigurationBuilder configurationBuilder) {
        if(configurationBuilder != null) {
            configurationBuilder = configurationBuilder;
        }

    }
````

Line no: 246

**Comment by tatanka987** [comment]
@sincerekamal you can see only decompiled code, original code is correct, if you have real issues, please provide us your code with configs and logs as I asked before.
