### ISSUE TITLE
How to get frames from QBRTCCameraVideoCapturer for local and remote surfaceview

### ISSUE THREAD

**Issue by shishram** [QuickBlox/quickblox-android-sdk#364]
To define current capturer use QBMediaStreamManager api :

currentSession.getMediaStreamManager().setVideoCapturer(new QBRTCCameraVideoCapturer(this, null));

this is mentioned in documentation but its not clear how to get frames and convert them to bitmaps, let me know about this thanks in advance!

**Comment by vfite** [comment]
Closed for long inactivity
