### ISSUE TITLE
Create session with existing token

### ISSUE THREAD

**Issue by IlyaPavlovskii** [QuickBlox/quickblox-android-sdk#367]
How can I create User session on Android with token which generated on my server over REST API ?
I use this construction for create new session on the client `QBSessionManager.getInstance().createActiveSession(externalToken, externakExpirationDate);`

But I have some problems with login to QBChatService. I use **externalToken** like password for user :

```java
.flatMap( qbSession -> UserUtils.getUser(userId)
.doOnNext(qbUser -> qbUser.setPassword(BaseService.getBaseService().getToken()))
.flatMap(ChatUtils::loginChatService)
```

Always I have error response:
```javascript
{
  "errors": [
    "Unauthorized"
  ]
}
```

We can't  transfer original user password from own custom server, because it's insecure. How can I use login without original password to QBChatService session ? **BaseService.getBaseService()** it already has deprecated.

**Comment by vfite** [comment]
Hi there. As you noticed BaseService API is deprecated. Use QBSessionManager to get active session and token.

**Comment by IlyaPavlovskii** [comment]
Thanks. It's work.
