### ISSUE TITLE
Block unblock feature in dialog 

### ISSUE THREAD

**Issue by thakurSonu** [QuickBlox/quickblox-android-sdk#369]
Hi, 
I looking for block unblock feature between android and ios. is block unblock feature available in quickblox dialog? I want like whatsp block.

**Comment by RomanPronin** [comment]
If you want to enable or disable communication with other users in a chat you can use [Privacy list](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Privacy_lists).

**Comment by thakurSonu** [comment]
Hi,

I have used below code to create privacy, But still block user able to send message to me.  Can you please share code Snippet for block.

 
 QBPrivacyList list = new QBPrivacyList();
        list.setName("public");
        ArrayList<QBPrivacyListItem> items = new ArrayList<QBPrivacyListItem>();
        QBPrivacyListItem item1 = new QBPrivacyListItem();
        item1.setAllow(false);
        item1.setType(QBPrivacyListItem.Type.USER_ID);
        item1.setValueForType(String.valueOf(recipent_id));
        //item1.setMutualBlock(true);
        items.add(item1);

        list.setItems(items);
        try {
            privacyListsManager.setPrivacyList(list);
        } catch (SmackException.NotConnectedException e) {
            e.printStackTrace();
        } catch (XMPPException.XMPPErrorException e) {
            e.printStackTrace();
        } catch (SmackException.NoResponseException e) {
            e.printStackTrace();
        }

**Comment by thakurSonu** [comment]
finally i resolved my bug thanks

**Comment by RomanPronin** [comment]
Nice to hear that.

**Comment by wowankit23** [comment]
same i m facing what should i do plz reply asap

**Comment by kishorejethava** [comment]
I'm facing same issue like User still send message to blocked user!!
Can please help me?
