### ISSUE TITLE
Error in SignIn After clean App data in ASUS zenfon 3 Max 

### ISSUE THREAD

**Issue by Anindya-Duti-Dhar** [QuickBlox/quickblox-android-sdk#370]
I have installed Sample WebRTC App and create new user and it was fine for the first time, but when I have cleaned the app data and tried to create another new user it was getting sign in error. Have anyone any idea why I'm getting such error with my ASUS Zenfon 3 Max (Marshmallow) device? Please give me a solution as soon as possible.
Thanks in advance.

**Comment by tatanka987** [comment]
hello @Anindya-Duti-Dhar, which error do you gets? It can happen if you try signup new user with login which has already been taken (after first login in your app). In our sample after clean application data starts signup with new user, if server response error, we handle this error and if need starts signin old user, then removes it (on server) and creates new user with entered data. If you don't want remove user you can signin (not signup) old user.

**Comment by Anindya-Duti-Dhar** [comment]
Hello @tatanka987 , thanks for the reply i was just going to close the issue and min while i have got your comment. No problem, i have fixed my issue myself. there was wrong with my Device time zone, after fixing the right time zone in my device then it's all right.
thanks.
