### ISSUE TITLE
How to detect that remote video is paused

### ISSUE THREAD

**Issue by Anindya-Duti-Dhar** [QuickBlox/quickblox-android-sdk#372]
Hello, I just want to implement a custom view instead of showing black screen when opponent user paused or mute his/her video view. Do you have any method or anything idea so that i can detect that the remote video is currently paused or mute? 
please reply me as soon as possible. 
Thanks in advance.

**Comment by tatanka987** [comment]
hello @Anindya-Duti-Dhar, you can realize needed functionality used QB System Notification (more [by link](https://quickblox.com/developers/Android_XMPP_Chat_Sample#System_notifications)). On sender side you can sand system notification with specific parameter, on receiver side you have to listen and parse this notification and run need logic.

**Comment by Anindya-Duti-Dhar** [comment]
@tatanka987 Thanks for another quick reply. It's good idea to send, great. but I thought that you have built in callback for such feature. anyway, thanks for the tips. HappY coding :)

**Comment by Anindya-Duti-Dhar** [comment]
Hello @tatanka987 ,
Thanks a lot for this tips. You save my day. Happy coding :)
