### ISSUE TITLE
how to add a newly register user into already created group

### ISSUE THREAD

**Issue by SushreeR** [QuickBlox/quickblox-android-sdk#373]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by RomanPronin** [comment]
Hi @SushreeR, you can add user to group chat like this ([link](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Update_group_dialog))
```
QBDialogRequestBuilder requestBuilder = new QBDialogRequestBuilder();
requestBuilder.addUsers(378); // add another users
 
QBChatDialog chatDialog = ...; // dialog should contain dialogId
 
QBRestChatService.updateGroupChatDialog(chatDialog, requestBuilder).performAsync(new QBEntityCallback<QBChatDialog>() {
            @Override
            public void onSuccess(QBChatDialog qbChatDialog, Bundle bundle) {
 
            }
 
            @Override
            public void onError(QBResponseException e) {
 
            }
        });
```
