### ISSUE TITLE
Could not Get FCM push notification when App is removed from Recent trey

### ISSUE THREAD

**Issue by Anindya-Duti-Dhar** [QuickBlox/quickblox-android-sdk#374]
Hello @tatanka987  hope you are doing well. recently I have tried to send push to opponent using QBPushNotifications.createEvent(qbEvent).performAsync(null); Method which referred QBPushNotifications.java class. But sometimes  when My App is in background or removed from device recent Apps trey I could not get any push. Would you please tell me that which message type QBPushNotifications.java class send, is it Notification message type or data payload type? 
I need to receive push without delay even my app is in background or not in recent apps trey like facebook, whatsup.

**Comment by tatanka987** [comment]
hello @Anindya-Duti-Dhar, please check your log (from LogCat) for any errors. Subscription created successfully? Request on create event sent successfully? QuickBlox's pushes receive to device as  Data messages. You have to create own service ([like there ](https://github.com/QuickBlox/quickblox-android-sdk/blob/master/sample-core/src/main/java/com/quickblox/sample/core/gcm/CoreGcmPushListenerService.java#L9)) and listen pushes from it. You will get all push notifications in callback 

`protected void sendPushMessage(Map data, String from, String message)` 

You have to create Notification manually and display for user.

If push message was delivered to device in logs you can see lines like these:

02-06 19:39:04.355 21101-22498/com.quickblox.q_municate D/QBASDK: QBFcmPushListenerService: data: {user_id=10479638, badge=1, message=valik11@injoit.com: test message, dialog_id=56e13567a28f9a90f000001b}
02-06 19:39:04.355 21101-22498/com.quickblox.q_municate D/QBASDK: QBFcmPushListenerService: From: 265299067289
02-06 19:39:04.355 21101-22498/com.quickblox.q_municate D/QBASDK: QBFcmPushListenerService: Message: valik11@injoit.com: test message

**Comment by Anindya-Duti-Dhar** [comment]
Hello @tatanka987  thanks for the reply. I'm using FCM not GCM. and I'm sending push through 

public void sendPushMessage(ArrayList<Integer> recipients, String senderName){
String outMessage = senderName
        Log.d("PushOutMessage: ", outMessage);

        // Send Push: create QuickBlox Push Notification Event
        QBEvent qbEvent = new QBEvent();
        qbEvent.setNotificationType(QBNotificationType.PUSH);
        qbEvent.setEnvironment(QBEnvironment.DEVELOPMENT);
        // Generic push - will be delivered to all platforms (Android, iOS, WP, Blackberry..)
        qbEvent.setMessage(outMessage);

        StringifyArrayList<Integer> userIds = new StringifyArrayList<>(recipients);
        qbEvent.setUserIds(userIds);

        QBPushNotifications.createEvent(qbEvent).performAsync(null);
    }

And receiving it in a Class extending FirebaseMessagingService Class using following method

public void onMessageReceived(RemoteMessage remoteMessage)


So what's the problem with this?

**Comment by tatanka987** [comment]
@Anindya-Duti-Dhar in other QuickBlox project used FCM pushes, [there class](https://github.com/QuickBlox/q-municate-android/blob/QMUN-SPRINT-2/Q-municate_app/src/main/java/com/quickblox/q_municate/fcm/FcmPushListenerService.java) for listening pushes and [AndroidManifest.xml](https://github.com/QuickBlox/q-municate-android/blob/QMUN-SPRINT-2/Q-municate_app/src/main/AndroidManifest.xml) with all needed configs. This is [google-services.json](https://github.com/QuickBlox/q-municate-android/blob/QMUN-SPRINT-2/Q-municate_app/google-services.json), downloaded from FireBase developer console. In this project used QuickBlox mechanism autosubscription to pushes. Please, follow this code for fixing your issue.
Note: this is not released code, but FCM pushes works fine.

**Comment by Anindya-Duti-Dhar** [comment]
@tatanka987 thanks for quick solution. I have implemented your all CallBack methods sequentially to create successful user push initialization, push subscription and push sending event, thankfully I have also implemented a service class to receive push like QBFcmPushListenerService class. And I'm getting pushes in my app. but my problem statements are as follow:

1) If my app is in forground ( like it may be when user is staying in my app or he/she just closed my app by pressing back button or home button. that's mean when my app is in my device recent apps tray not killed yet.) But if I kill my app by removing from recent tray i do not get any push whereas the push should be received. Why this is happened? 

2) If I'm not wrong then according to FCM docs, Google says that if we use notification message type push then it will received by client app even app is killed or working background. But it's not happened with data payload type push. 
So would you please tell me that what type of push message is actually sending by Quickblox SDK callBack method? 
If it's not notification message type push then is their any way to send notification message type  push instead of data payload type push from my app to another user?

Thanks in advance.

**Comment by tatanka987** [comment]
@Anindya-Duti-Dhar as I said before

> QuickBlox's pushes receive to device as **Data messages**

in callback  **sendPushMessage(Map data, String from, String message)** you will get all pushes sent from app (create QBEvent request) or from QuickBlox admin panel or offline pushes. If you use QBFcmPushListenerService you get fully control of the push notifications.

**Comment by Anindya-Duti-Dhar** [comment]
Hello @tatanka987 Thanks for your guideline. :)
