### ISSUE TITLE
Videocall adapter

### ISSUE THREAD

**Issue by lordmen99** [QuickBlox/quickblox-android-sdk#375]
Hi all, anyone have one page videocall adapter. share code please if u have do make that

**Comment by pelipetsaa** [comment]
what do you mean by videocall adapter?
you can use source code of the Simple Android WebRTC (VideoChat)
https://quickblox.com/developers/Sample-webrtc-android
or
Q-municate
https://github.com/QuickBlox/q-municate-android

**Comment by lordmen99** [comment]
videocall adapter like chatadapter

**Comment by alexanderkoqb** [comment]
Hey @lordmen99 
Since it's been a while and if you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
