### ISSUE TITLE
How to change message status to unread after reading in group chat?

### ISSUE THREAD

**Issue by KoustuvGanguly** [QuickBlox/quickblox-android-sdk#378]
**Environment details**
Android, SDK 2.5.2

**Expected behavior**
There should be a method to change the status of that message back to unread after reading ,so it comes in unread count  ,such as **_> Mark messages as unread_**  like currently what we have
 **_> Mark messages as read_** .

**Actual behavior**
Once read a message to get some content from custom property of that message, though that message body has not been seen by the user(receiver), receiver wont get the unread count for that unread message(only retrieved to read a custom property to have a custom JSON to do some operation in receivers device). Which is not acceptable. Flexibility should be there.

**Steps to reproduce the behavior**
Fetch an unread message from the receivers end,using getDialogMessage method by passing the dialog id,then read a custom property of that message object.then in another call try to fetch unread count against that dialog id,so as natural we wont get that message as in unread count,so need a status changer from read to unread again , from receivers end/login.

**Any others comments?**
It`s very urgent for me app is live in production.plz respond asap.

**Comment by tatanka987** [comment]
hello @KoustuvGanguly, for getting messages from server without mark as read you have to add parameter to QBRequestGetBuilder, see next code snippet:

        QBRequestGetBuilder messagesRequesGetBuilder = new QBRequestGetBuilder();
       ....
        messagesRequesGetBuilder.addRule("mark_as_read", "", 0);
       ....
        
ArrayList<QBChatMessage> dialogMessagesList = QBChatService.getDialogMessages(dialog, messagesRequesGetBuilder, bundle);

In SDK version 2.5.2 we didn't have methods for updating messages. We added this logic since version 2.6. In version 2.6 you can set unread status for message using next code snippet:

QBMessageUpdateBuilder messageUpdateBuilder = new QBMessageUpdateBuilder();
        messageUpdateBuilder.setRules(new ArrayList<>(Collections.singleton(new GenericQueryRule("read", 0))));

QBChatService.updateMessage(messageId, dialogId, messageUpdateBuilder);

**Comment by KoustuvGanguly** [comment]
First of all thanks for the quick response, 
Now my query is :

> 
> for getting messages from server without mark as read you have to add parameter to QBRequestGetBuilder, see next code snippet:
> 
>     QBRequestGetBuilder messagesRequesGetBuilder = new QBRequestGetBuilder();
>    ....
>     messagesRequesGetBuilder.addRule("mark_as_read", "", 0);
>    ....
> 

Will this work in 2.5.2? 
and by this i am assuming , if i do like this `messagesRequesGetBuilder.addRule("mark_as_read", "", 0);` then after reading a chat message from a group chat dialog also i will get unread count for that particular (read)message . Please confirm.

**Comment by tatanka987** [comment]
yes, this works in 2.5.2 and after getting messages with parameter mark_as_read=0 you will be getting  correct count unread messages.

**Comment by KoustuvGanguly** [comment]
Thank`s a lot for the help.I will check it out.Hope it will work fine.

**Comment by LogicNarendra** [comment]
Hi, Is there any listener to find whether message is delivered and read by opponent user. it will be helpful to know. Thanks

**Comment by tatanka987** [comment]
@LogicNarendra your question not related with current issue. Sure, QuickBlox Android SDK has listener for your purpose, please see documentation [Delivered_status](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Delivered_status) and [Read_status](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Read_status). But keep in mind if your will mark message message as delivered/read via REST (using QBRestChatService.markMessagesAsRead(dialogId, messagesIds).perform()) this listeners not will work. If you want listening message's status realtime, you have mark messages as delivered/read using chat (qbChatDialog.readMessage(qbChatMessage).

P.S. For getting faster answer will create new issue, not write your questions to closed issues.

**Comment by MahadevT** [comment]
Hi, Please can you guide me how to send video file and GIF file in Quickblox chat sdk. It may help to know.

**Comment by tatanka987** [comment]
@MahadevT your question not related with this thread, please create new issue and we will try to help you

> For getting faster answer will create new issue, not write your questions to closed issues.
