### ISSUE TITLE
Custom Object is not showing at dashboard but get object at onSuccess

### ISSUE THREAD

**Issue by DeveloperTele** [QuickBlox/quickblox-android-sdk#379]
**Hi Admin**

I've found unexpected behavior at creating custom objects from Android devices. This is actually working perfect until yesterday.  I found same issue as another closed one.
*[https://github.com/QuickBlox/quickblox-android-sdk/issues/44](44)*

I create this custom object after user registeration is success. Please see my code as below, which was working until yesterday.

        QBCustomObject userDetail = new QBCustomObject("LuveyUserData");
        userDetail.putInteger("ud_gender", maleFemalePosition);
        userDetail.putLocation("ud_location", defLocation);
        userDetail.putBoolean("ud_smoke", udsmoke);
        userDetail.putBoolean("ud_drink", uddrink);
        .
        .
        .
        .
        .

        QBCustomObjects.createObject(userDetail, new QBEntityCallback<QBCustomObject>() {
            @Override
            public void onSuccess(QBCustomObject createdObject, Bundle params) {
                //got created obj
            }

            @Override
            public void onError(QBResponseException errors) {
                //no exception here
            }
        });

I've got "createdObject" at "onSuccess" method. But they cannot see at admin dashboard, even "getObjectsByIds" method return null. Please look into it when you can.

**Comment by RomanPronin** [comment]
Hello @DeveloperTele, we have just tested QBCustomObjects.createObject with latest version SDK and it's all ok. So check your custom object class "LuveyUserData" for the existence of your fields.

**Comment by alexanderkoqb** [comment]
Hey @DeveloperTele 
Since it's been a while and if you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
