### ISSUE TITLE
Minus 3.8k supported devices SDK Quickblox.com

### ISSUE THREAD

**Issue by bayanruby** [QuickBlox/quickblox-android-sdk#380]
I have a question regarding your SDK. When we use it, the number of supported device decreases by 3800.

Is it possible to avoid these losses?

**Comment by tatanka987** [comment]
Which version of QuickBlox Android SDK do you use? If you use quickblox-android-sdk-videochat-webrtc module try add to AndroidManifest.xml of your app next code:

    <uses-feature
        android:name="android.hardware.camera"
        android:required="false"
        tools:node="replace" />
    <uses-feature
        android:name="android.hardware.camera.autofocus"
        android:required="false"
        tools:node="replace" />
    <uses-feature
        android:name="android.hardware.camera.flash"
        android:required="false"
        tools:node="replace" />

for exclude this features as required.

**Comment by bayanruby** [comment]
Thank you!

спасибо!!! заработало все, девайсы появились
