### ISSUE TITLE
Not updating the un readmessage count in DialogsActivity in Android.

### ISSUE THREAD

**Issue by santhosh153** [QuickBlox/quickblox-android-sdk#383]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*
Android 6.0.1

**Did this work before?**
Yes, its worked previously with default Configuration (qb_config.json & sample_config.json) files.

**Expected behavior**
unread message count should be updated automatically.

**Actual behavior**
Not updating the un readmessage count in DialogsActivity in Android.

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**
1. Get the code from  https://github.com/QuickBlox/quickblox-android-sdk.git
2. Import project into android studio
3. Login into quickblox.
4. Create an application in quickblox admin panel.
5. Replace the latest applicaton appId, auth_key, auth_secret &  account_key values in qb_config.json
6. Replace the users_tag & users_password in sample_config.json
7. Install the application in two different devices & login with two different ids.
8. Create chat dialog between these two userIds.
9. Start messaging from first device and in second device move to Chatdialogs screen wait.
10. Unread message will not update automatically in second device.

![chatactivity](https://cloud.githubusercontent.com/assets/6703954/23494300/fb0b6e34-ff37-11e6-9307-efdf537c23fc.png)
![dialogsactivity](https://cloud.githubusercontent.com/assets/6703954/23494301/fb0cd5d0-ff37-11e6-9243-32034cfd9d32.png)

**Any others comments?**

**Comment by tatanka987** [comment]
hello @santhosh153, you have to configure push notifications in admin panel and in sample, because group dialogs updates after receiving pushes from dialogs.

**Comment by santhosh153** [comment]
Do you mean its necessary to configure push notifications for group dialogs? 
But in case of private dialogs  count is getting updated with configuring push notifications.

**Comment by tatanka987** [comment]
Did your resolve your issue after our recommendations?

**Comment by santhosh153** [comment]
The issue resolved
