### ISSUE TITLE
QBRTCSurfaceView Documentation Help

### ISSUE THREAD

**Issue by xpressmobtech** [QuickBlox/quickblox-android-sdk#384]
There is no documentation for the QBRTCSurfaceView installation anywehre on your website,github,or stackoverflow.

please show implementation of a simple one- on - one video call using the QBRTC SurfaceView. 
For example : 
https://github.com/GleasonK/android-webrtc-tutorial

Does  The RTCLVideoView work on devices using Marshmallow or Higher?

Can you use RTCLVideoView even though it's deprecated?

P.S. I saw the Quickblox video call fragment with  QBRTCSurfaceView implemented , and it's a mess that can't possibly help anyone.

**Comment by vfite** [comment]
Hi there. What actually are you looking for?
Have a look at https://quickblox.com/developers/Sample-webrtc-android#QBRTCSurfaceView.

**Comment by xpressmobtech** [comment]
Now this is perfect!
