### ISSUE TITLE
Unable to receive push notifications from quickblox

### ISSUE THREAD

**Issue by Ghouse87** [QuickBlox/quickblox-android-sdk#385]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*
 Android 6.0.1

**Did this work before?**
  Sample given by quickblox is able to receive notification for group chat.

**Expected behavior**
  Changed with my credentials (like account credentials and gcm sender id) in sample given by quickblox should be able to receive notification for group chat.

**Actual behavior**
 Unable to receive notification when changed with my credentials (like account credentials and gcm sender id)
**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**
Get the code from https://github.com/QuickBlox/quickblox-android-sdk.git
Import project into android studio
Login into quickblox.
Create an application in quickblox admin panel.
Replace the latest applicaton appId, auth_key, auth_secret & account_key values in qb_config.json
Replace the users_tag & users_password in sample_config.json
Install the application in two different devices & login with two different ids.
Start messaging from first device and in second device move to Chat dialogs screen wait.
Not able to receive notification.

**Any others comments?**
In logs i get this message  "SubscribeService: Successfully subscribed for QB push messages", but unable to receive any notification on device.

**Comment by tatanka987** [comment]
hello @Ghouse87 please set your sender_id to [string resources](https://github.com/QuickBlox/quickblox-android-sdk/blob/master/sample-chat/src/main/res/values/strings.xml#L71), then remove app from device and install it again

**Comment by ameenmaheen** [comment]
@tatanka987 push Not working even after sender_id moved to resources

**Comment by tatanka987** [comment]
Did you set GCM API key in admin panel? Please see screenshot [how to get GCM API Key](https://gyazo.com/99d69e8bf7c28196cc269539040b87ee)

**Comment by ameenmaheen** [comment]
No just added now its working , thanks for the help
