### ISSUE TITLE
Video chat demo apk is about 26 MB! Already removed unused code :(

### ISSUE THREAD

**Issue by Kishankondhiya** [QuickBlox/quickblox-android-sdk#387]
Video chat demo apk is about 26 MB! Already removed unused code :(

I have run the demo and found larger apk size about 26 MB already removed unused code

**Comment by RomanPronin** [comment]
Hello @Kishankondhiya. For example, you can build a separate build for each individual platform, i.e. separately under arm64-v8a, separately for x86, etc.

**Comment by Kishankondhiya** [comment]
i did not understood what are you talking about @RomanPronin

**Comment by RomanPronin** [comment]
@Kishankondhiya in your project you have the next native libraries for each platform: arm64-v8a, armeabi-v7a, x86, x86_64. Consequently, you have possibility to assemble apk build just with needed libraries. For example, Huawei Nexus 6P has Qualcomm Snapdragon with 810 - arm64-v8a. For more info look [here](https://developer.android.com/ndk/guides/abis.html)
