### ISSUE TITLE
Android: Social signIn: Token is required

### ISSUE THREAD

**Issue by odemolliens** [QuickBlox/quickblox-android-sdk#388]
**Environment details**

Android:
QuickBlox-REST-API-Version=0.1.1
QB-SDK=Android 3.3.0

iOS:
"QB-OS" = "iOS 10.2";
"QB-SDK" = "iOS 2.9.2";

**Did this work before?**
Works in sample (but it's not using social sign in)

**Expected behavior**
QBUsers.signInUsingSocialProvider throw a 200

**Actual behavior**
QBUsers.signInUsingSocialProvider throw a 401 error

**Logs**
[Gist Android with 401](https://gist.github.com/odemolliens/8979729a08302a8da78bbd6a60e6e85f)

![screenshot 2017-03-16 14 34 08](https://cloud.githubusercontent.com/assets/2726958/23999026/4e900568-0a57-11e7-96a2-ed50c38225a8.png)

[Gist iOS with 200](https://gist.github.com/odemolliens/8979729a08302a8da78bbd6a60e6e85f)

![screenshot 2017-03-16 14 35 17](https://cloud.githubusercontent.com/assets/2726958/23999028/50d175aa-0a57-11e7-9f21-af8988ae5e3f.png)

**Code used**
```
QBUsers.signInUsingSocialProvider(QBProvider.FACEBOOK, sessionToken, null).performAsync(new QbEntityCallbackTwoTypeWrapper<QBUser, Void>(new QBEntityCallback<Void>() {
            @Override
            public void onSuccess(Void result, Bundle bundle) {

            }

            @Override
            public void onError(QBResponseException e) {
               
            }
        }) {
            @Override
            public void onSuccess(QBUser qbUser, Bundle args) {
                callback.onSuccess(null, null);
            }
        });
```

I have try to put the token used on iOS and I get the same trouble...

**Comment by odemolliens** [comment]
I would add:

If  QBSettings.getInstance().setAutoCreateSession(false). If it's on true and you get a 401 from server: QuickBlox SDK crash

**Comment by tatanka987** [comment]
if you use QBSettings.getInstance().setAutoCreateSession(false) you have to create session without user before call QBUsers.signInUsingSocialProvider else QBSessionManager will automatically create session without user before call QBUsers.signInUsingSocialProvider.

**Comment by odemolliens** [comment]
Hi @tatanka987.
This is not my main question.

I want to use QBUsers.signInUsingSocialProvider with AutoCreateSession ON.

But I get a 401. Please look my first post

**Comment by tatanka987** [comment]
it should work, I ran tests today and it works fine, try to remove app from device and install again, maybe you have cached information about old session

**Comment by tatanka987** [comment]
@odemolliens additionally provide us full log from start app to getting this error

**Comment by odemolliens** [comment]
Without any change in my code. Without uninstall my application, it works now. Pretty strange right ?

Check request content, everything is filled as requested.
