### ISSUE TITLE
Change dependency from mavel to jar

### ISSUE THREAD

**Issue by Coder-Ashish** [QuickBlox/quickblox-android-sdk#389]
hey i am working on project so in previous version i was used mavel file dependency from jcenter and now i want to change that dependency from mavel to jar i created a jar file an include it in project and jar dependency in gradle but when i compile and run application i gives application error contentiously because thread run in background but instead of that i add mavel dependency then project work successfully...!
can anyone help me..!
thank you

**Comment by tatanka987** [comment]
Why don't you use .aar files for integration QuickBlox Android SDK? Please, provide us more information about errors you've got.

**Comment by Coder-Ashish** [comment]
even by using p2p-core my problem get solved now i just want to know p2p-core is that the open source library available on mavel central

**Comment by alexanderkoqb** [comment]
Hey @Coder-Ashish 
Since it's been a while and if you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
