### ISSUE TITLE
Push: sometime the push is sent to hundred of users

### ISSUE THREAD

**Issue by harding13** [QuickBlox/quickblox-android-sdk#392]
At one moment from my PHP backend i sent two push notifications: one to an user and another to another user (ios or android). 
Randomly, one of these notifications are sent to +500 registered users.
How can i log what is happen?

Until one month ago all it's going good.

**Comment by harding13** [comment]
Ok, found it. 
When a user exists but has no subscription, if i send thru CURL a push to him, QuickBlox sends push to all users of his channel.
So you must know if a user has a subscription before you try to send him a push.

**Comment by soulfly** [comment]
Sergio, could you post your request (parameters), we will check where is the problem

**Comment by harding13** [comment]
`$post_body = http_build_query(array(
            'event[notification_type]' => 'push',
            'event[environment]' => 'production',
            'event[message]' => $text,
            'event[external_user][ids]' => $user_id,
            'event[push_type]' => $push_type
        ));`

this is a typical set of parameters sent to https://api.quickblox.com/events.json

**Comment by soulfly** [comment]
Thanks, 
one thing to check - does it work well when use **event[user][ids]**?

also, are you sure you pass a valid value here **event[external_user][ids]** ? (not something like empty string etc.)

**Comment by harding13** [comment]
I never used event[user][ids] to sent push (in my db i call them qb_id).

I double checked what i sent and i always sent a valid value.

The problem, i repeat, is the subscription. If the user hasn't a subscription and i try to send him a push, i have the problem described above.

**Comment by soulfly** [comment]
Ok we are going to check it

**Comment by SerjQB** [comment]
The problem has been reproduced.

**Comment by alexanderkoqb** [comment]
Hey @harding13 
Since it's been a while and if you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
