### ISSUE TITLE
com.quickblox.core.exception.QBResponseException: Occupants with these IDs do not exist.

### ISSUE THREAD

**Issue by rajputkapil** [QuickBlox/quickblox-android-sdk#393]
Chat was working fine from last 6 months but now from last 4 to 5 days I am getting this error **com.quickblox.core.exception.QBResponseException: Occupants with these IDs do not exist.**  while creating a private chat dialog. Occupant is the owner of chat portal.  I don't know why it is happening now the same code which was working now stops working.

Code 

        privateChatManager = QBChatService.getInstance().getPrivateChatManager();
        privateChatManager.createDialog(7094465, new QBEntityCallback<QBDialog>() {
            @Override
            public void onSuccess(QBDialog dialog, Bundle args) {
                 Log.d(TAG, "onSuccess: ");
            }

            @Override
            public void onError(QBResponseException errors) {
                Log.d(TAG, "onError: ");
            }
        });

**Comment by tatanka987** [comment]
hello there, it happened after updates on backend, now one user can use only from one app, so if user_A was created in app_1 and you try to create dialog in app_2 with user_A you will get error 
"Occupants with these IDs do not exist". QuickBlox warned all customers before by e-mail, in [blog](https://quickblox.com/blog/maintenance-on-shared-instance-on-march-1st-1500-eet-wednesday/) also you could see notification about it in QuickBlox admin panel.
