### ISSUE TITLE
Server ping is unavailable on video call between android and webapp

### ISSUE THREAD

**Issue by Esvux** [QuickBlox/quickblox-android-sdk#394]
**Environment details**
* Android app - SDK v3.0
* Android Studio v2.3
* Target Android SDK 4.4 (API 19 KitKat)
* Javascript app - SDK v2.1.2

**Did this work before?**
Never

**Description**
I'm developing an app (android) to comunicate with another Web app (Html+javascript) for chat and video chat. The app (android & js) have an user with caller role and another user with receiver role (this never change since login); between android-android the app works fine, also js-js; the problem is when caller is run on javascript app and receiver is run on android app, the first call works fine, but after this, chat and video chat brokes, the single error (comparing with android-android logs) is:
`com.quickblox.core.exception.QBResponseException: Server is unavailable`
This exception is throws from PingManager (on `ChatPingAlarmManager.java`)

**Logs**
This is the log produced by the exception using printStackTrace method.

`D/ChatPingAlarmManager: Calling pingServer for connection 
D/SMACK: SENT (0): <iq to='chat.quickblox.com' id='PvM7K-29' type='get'><ping xmlns='urn:xmpp:ping'/></iq>
D/SMACK: RECV (0): <iq type="result" id="PvM7K-29" from="chat.quickblox.com" xmlns="jabber:client" to="23453397-42215@chat.quickblox.com/android_ffffffff-aa20-84bb-ffff-ffffef05ac4a"/>
 com.quickblox.core.exception.QBResponseException: Server is unavailable
     at com.quickblox.chat.QBPingManager$1.performInAsync(QBPingManager.java:73)
     at com.quickblox.chat.utils.ThreadTask.run(ThreadTask.java:15)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)
D/CallService: Ping chat server failed`

**Any others comments?**
I'm basing my code on  `sample-videochat-webrtc`

**Comment by vadimkhmyrovqb** [comment]
Closed due to inactivity.
