### ISSUE TITLE
Unable to filter dialog messages by custom value?

### ISSUE THREAD

**Issue by imTefa** [QuickBlox/quickblox-android-sdk#395]
When I try to fetch dialog messages with a filter the filter doesn't work?
here is my code: 

`ArrayList<QBChatMessage> messages = null;
            QBMessageGetBuilder qbMessageGetBuilder = new QBMessageGetBuilder();
            qbMessageGetBuilder.eq("bookID", customDialog.getBookID());
            qbMessageGetBuilder.sortAsc("date_sent");
            try {
                messages = QBRestChatService.getDialogMessages(qbChatDialog, qbMessageGetBuilder).perform();
            } catch (QBResponseException e) {
                e.printStackTrace();
            }`

the response returns all messages without any filter on bookId value for example:
`{
  "skip": 0,
  "limit": 100,
  "items": [
    {
      "_id": "58f6c9f4a28f9a0c7f000003",
      "attachments": [],
      "bookID": "-Kh9UzvClNyHuwNhLcFV",
      "chat_dialog_id": "58f6bcdea0eb4766d900003c",
      "created_at": "2017-04-19T02:22:44Z",
      //other values
    },
    {
      "_id": "58f6ca12a28f9a08c5000001",
      "attachments": [],
      "bookID": "-KeA1pw5DGMSTg67Pbp0",
      "chat_dialog_id": "58f6bcdea0eb4766d900003c",
      "created_at": "2017-04-19T02:23:15Z",
      //other values
    }
  ]
}`

**Comment by tatanka987** [comment]
hello @imTefa sorry for delayed response, you can filter messages only by filters from [this link ](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Retrieve_list_of_messages)

**Comment by alexanderkoqb** [comment]
Hey @imTefa 
Since it's been a while and if you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
