### ISSUE TITLE
Notification still Comming after leave from group

### ISSUE THREAD

**Issue by jaggi772** [QuickBlox/quickblox-android-sdk#396]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by jaggi772** [comment]
Please help anyone.
I am using same code of Quickblox to leave from group chat and successfully leave from group. But still i am receiving chat notification from same group.

**Comment by RomanPronin** [comment]
Hi, @jaggi772! Pay attention, if your opponent is offline while you sending a message - he will automatically receive push notification. For details look [here](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Push_notifications_to_the_offline_users).

**Comment by jaggi772** [comment]
Hi, @RomanPronin . i am saying notification is coming after i leave group.

**Comment by RomanPronin** [comment]
Receiving notification after leaving group is a normal behavior. You won't receive notification if you remove current dialog for current user.

**Comment by alexanderkoqb** [comment]
Hey @jaggi772 
Since it's been a while and if you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
