### ISSUE TITLE
Migrating from Shared starter instance to Dedicated enterprise(Small) instance setup and changes required in app end

### ISSUE THREAD

**Issue by KoustuvGanguly** [QuickBlox/quickblox-android-sdk#399]
I have developed an enterprise level chatting app on android platform which is live now to users,by using quickblox SDK 2.5.2 in starter tier. I am planning to upgrade to dedicated instance of quickblox (Small). Please let me know the setup procedure and other details including downtime during up scaling of the instance. Also do let me know the changes I need to do in my app and if any other places required.

**if i wanted to migrate what are the changes required?**
In terms of setup procedure and other details including downtime during up scaling of the instance.
 Also do let me know the changes I need to do in my app and if any other places required.

**what will be required things I need to do in case :**
i. I use own server for hosting
ii. I use AWS infrastructure managed by QuickBlox team for hosting

**Comment by vadimkhmyrovqb** [comment]
Closed due to inactivity.
