### ISSUE TITLE
base Forbidden. Need user

### ISSUE THREAD

**Issue by e4basil** [QuickBlox/quickblox-android-sdk#400]
`final QBUser new_user = new QBUser("bas", "12345678");
        QBAuth.createSession(new_user).performAsync(new QBEntityCallback<QBSession>() {
            @Override
            public void onSuccess(QBSession qbSession, Bundle bundle) {
                new_user.setId(qbSession.getUserId());
                Log.d(TAG, "qbSession. Token : " + qbSession.getToken());
                QBUsers.signIn(new_user).performAsync(new QBEntityCallback<QBUser>() {
                    @Override
                    public void onSuccess(QBUser user, Bundle args) {
                        // success
                        Log.d(TAG, "onSuccess: signIn");

                        chatService.login(new_user, new QBEntityCallback() {
                            @Override
                            public void onSuccess(Object o, Bundle bundle) {
                                Log.d(TAG, "onSuccess: chatService");
                                proceedToTheNextActivity();
                            }

                            @Override
                            public void onError(QBResponseException e) {
                                Log.d(TAG, "onError: chatService");
                            }
                        });

                    }

                    @Override
                    public void onError(QBResponseException error) {
                        // error
                        Log.d(TAG, "onError: signIn " + error.getMessage());
                    }
                });
            }

            @Override
            public void onError(QBResponseException e) {
                Log.d(TAG, "onError: qbSession " + e.getMessage());
            }
        });
`

**Environment details**

Operating system - linux,
SDK version 3.3.2 

```
D/QBASDK: SubscribeService: Not subscribed for QB push messagescom.quickblox.core.exception.QBResponseException: base Forbidden. Need user.
05-09 12:08:12.656 11310-12011/com.basil.test.quickbloxchat D/QBASDK: SubscribeService: startSchedulerTask
05-09 12:08:12.656 11310-11310/com.basil.test.quickbloxchat D/App: onSubscriptionError: base Forbidden. Need user.
05-09 12:08:12.692 11310-11310/com.basil.test.quickbloxchat D/QBASDK: SubscribeService: Service onDestroy
```
always getting error like this, cannot use FCM

**Comment by RomanPronin** [comment]
Hi @e4basil, starting from QuickBlox Android SDK 3.2 you don't need to manage session manually, and there is no need to call createSession methods. Just do QBUsers.signIn(qbUser). Here is more [info](https://quickblox.com/developers/Android#SDK_3.2.0_Authentication).
