### ISSUE TITLE
Can't parse the 'date_sent' value null: Invalid double: "null"

### ISSUE THREAD

**Issue by odemolliens** [QuickBlox/quickblox-android-sdk#401]
**Environment details**
*(Operating system, browser information, SDK version)*
SDK Android: 3.3.2
iOS SDK: 2.9.2

**Did this work before?**
Yes

**Expected behavior**
Structured QBChatMessage

**Actual behavior**

When I receive an message from iOS to Android, an error is throwed: `Can't parse the 'date_sent' value null: Invalid double: "null"`

**Logs**
![screenshot 2017-05-10 15 11 50](https://cloud.githubusercontent.com/assets/2726958/25900253/216c6466-3593-11e7-8e64-3625710742f5.png)

![screenshot 2017-05-10 15 11 53](https://cloud.githubusercontent.com/assets/2726958/25900254/2277b1c6-3593-11e7-9d10-ae15bb52b505.png)

**Steps to reproduce the behavior**
Use iOS sample chat
Receive message on Android with sample chat

**Any others comments?**

**Comment by naguchennai** [comment]
I also have same problem if no activty ion feve second then try to send msg it show
Can't parse the 'date_sent' value null: Invalid double: "null"

**Comment by alexanderkoqb** [comment]
Hey @odemolliens 
Since it's been a while and if you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
