### ISSUE TITLE
Chat push notifications not sending proper parameters for offline users

### ISSUE THREAD

**Issue by aldoborrero** [QuickBlox/quickblox-android-sdk#403]
Hi, 

I've configured correctly the alert for receiving offline push notifications. So far, so good, but there's one thing that I'm not receiving correctly (or I'm missing as your documentation creates a lot of confusions as is not correctly updated and organized). [As stated here](https://quickblox.com/developers/Chat#Alerts):

<img width="838" alt="screen shot 2017-05-19 at 19 42 49" src="https://cloud.githubusercontent.com/assets/82811/26259953/aaa4fac4-3ccb-11e7-8e61-6612b59eb54d.png">

These are the parameters I can receive for Android. Currently, what I'm receiving are:

<img width="593" alt="screen shot 2017-05-19 at 19 46 38" src="https://cloud.githubusercontent.com/assets/82811/26260009/e94f82f8-3ccb-11e7-912b-993410c47e97.png">

Which are from key and message key, but there's no key related to "dialog_id", so right now I can't do anything useful to redirect the user to the proper screen (I don't know who is the sender).

But in the documentation is stated that:

<img width="831" alt="screen shot 2017-05-19 at 19 48 33" src="https://cloud.githubusercontent.com/assets/82811/26260078/338cd866-3ccc-11e7-8412-a6d8dbac3f50.png">

This is my current configuration for the alerts:

<img width="1497" alt="screen shot 2017-05-19 at 19 48 10" src="https://cloud.githubusercontent.com/assets/82811/26260093/3f5d8b40-3ccc-11e7-8746-8f7a9831ffb1.png">

What should I do to fix this? (BTW I'm using Firebase option)

**Comment by RomanPronin** [comment]
Hi, @aldoborrero. After receiving push notifications for offline user, aka offline pushes, if you use Firebase option, you should use QBFcmPushListenerService, and in logs you can see payload like this: 
`D/QBASDK: QBFcmPushListenerService: data: {user_id=10714375, message=Tomas: great weather, dialog_id=591eeba7a28f9a5302f10fd2}`
Have you get this log?

**Comment by aldoborrero** [comment]
@RomanPronin I've checked the parameters in QBFcmPushListenerService and is sending it correctly! 

I guess that in documentation should be clearly stated, or at least in:

<img width="655" alt="screen shot 2017-05-22 at 13 33 30" src="https://cloud.githubusercontent.com/assets/82811/26306339/4cb8c0c4-3ef3-11e7-889f-b5053e7d9404.png">

Should be modified to have those parameters by default without having to modify or extend QBFcmPushListenerService by default pretty much like this:

<img width="443" alt="screen shot 2017-05-22 at 13 34 43" src="https://cloud.githubusercontent.com/assets/82811/26306380/758f1b06-3ef3-11e7-9c9b-5084b0fe1d3e.png">

Thanks!
