### ISSUE TITLE
How to send GIF image  in QuickBlox  chat SDK android

### ISSUE THREAD

**Issue by MahadevT** [QuickBlox/quickblox-android-sdk#405]
Please can anyone guide me how to send GIF image in QuickBlox android SDK.

**Comment by tatanka987** [comment]
closed, duplicate [#404](https://github.com/QuickBlox/quickblox-android-sdk/issues/404)

**Comment by MahadevT** [comment]
#404   got solution please guide me for #405

**Comment by tatanka987** [comment]
@MahadevT please specify your question what is difference between #404 and #405?

**Comment by alexanderkoqb** [comment]
Hi @MahadevT 
Since it's been a while and if you're still being experiencing troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
