### ISSUE TITLE
Authentication failed, check user's ID and password

### ISSUE THREAD

**Issue by AlaaZarifa** [QuickBlox/quickblox-android-sdk#409]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*
 _Windows 10 | chrome | 3.3.1_ 

**Did this work before?**
_No_

**Expected behavior**
_to create a session and perform a successful authentication..!_ 

**Actual behavior**

I know that starting from v3.2 creating a session manually isn't required, but doing that resulted in a crash when I initialized the dialog right before I'm about to start a private chat via this method.
`chatDialog.initForChat(chatService);` 
and the cause of the error is` < Recipient ID is null > `
SO.... 
I had to create the session manually, but it shows me OnError whenever I call `QBChatService.getInstance.login(user, ....)`
and this error shows..
`Error chatService :: Authentication failed, check user's ID and password
`
if I tried to make a new dialog while this error still exists, this error shows..
`base Forbidden. Need user.
`
**Logs**
 
https://gist.github.com/AlaaZarifa/c841bf2d1952b578cb6e5307a0d5bca2

**Steps to reproduce the behavior**

Here's the Login method..

```
        final String un = userName.getText().toString();
        final String pw = pass.getText().toString();
        QBUser user = new QBUser(un, pw);

        QBUsers.signIn(user).performAsync(new QBEntityCallback<QBUser>() {
          @Override
          public void onSuccess(QBUser user, Bundle bundle) { 
            Intent i = new Intent(MainActivity.this, ChatDialogsActivity.class);
            i.putExtra("userName", un);
            i.putExtra("pass", pw);
            MainActivity.this.startActivity(i);
          }
          @Override
          public void onError(QBResponseException e) {
          }
        });
```
Here's the session creation  method.. called inside the onCreate of in DialogsActivity

```
    QBChatService chatService = QBChatService.getInstance();
    String username, pass;
    username = getIntent().getStringExtra("userName");
    pass = getIntent().getStringExtra("pass");
    final QBUser user = new QBUser(username, pass);
    Log.i(">>> user : ", username);
    Log.i(">>> pass : ", pass);

    QBAuth.createSession().performAsync(new QBEntityCallback<QBSession>() {
      @Override
      public void onSuccess(QBSession session, Bundle bundle) {
        user.setId(session.getUserId());
        try {
          user.setPassword(QBSessionManager.getInstance().getToken());
          Log.d("Token ", QBSessionManager.getInstance().getToken() + "");
        } catch (Exception e) {
          Log.d(" Set Password E ", e.getMessage() + ""); }
       
                   chatService.login(user, new QBEntityCallback() {
                             @Override
                             public void onSuccess(Object o, Bundle bundle) {
                               Log.i("Success chatService : ", " ");
                             }
                             @Override
                             public void onError(QBResponseException e) {
/* this what gets called x_x */   Log.i("Error chatService : ", e.getMessage() + ""); 
                             }
                           }); }
              
      @Override
      public void onError(QBResponseException e) {
        Log.d(" createSession ", e.getMessage() + "");

      }
    });
```

**Any others comments?**

**Comment by tatanka987** [comment]
hello @AlaaZarifa for initializing chatDialog for chat you have to be logged in to the chat (not to REST). And in second case you got error because you created session without user.

**Comment by AlaaZarifa** [comment]
@tatanka987 what do you mean, I've seen the sample in the project.. this the order that I've noticed:
1. calling `QBUsers.signIn(user)`...
1. then calling `QBAuth.createSession()`..
1. inside the `onSucusses` of the createSession() , I called `chatService.login`..

could check the code, and point where I'm doing wrong, I can really use the help.!

**Comment by tatanka987** [comment]
after success step 1 you have to run step 3, then you can call  chatDialog.initForChat(chatService);

**Comment by AlaaZarifa** [comment]
do you mean like this, 

```
QBUsers.signIn(user).performAsync(new QBEntityCallback<QBUser>() {
          @Override
          public void onSuccess(QBUser user, Bundle bundle) { 
               
                      chatService.login(user, new QBEntityCallback() {
                             @Override
                             public void onSuccess(Object o, Bundle bundle) {
                               Log.i("Success chatService : ", " ");
                             }
                             @Override
                             public void onError(QBResponseException e) {
                             }
                           }); 

            Intent i = new Intent(MainActivity.this, ChatDialogsActivity.class);
            i.putExtra("userName", un);
            i.putExtra("pass", pw);
            MainActivity.this.startActivity(i);
          }
          @Override
          public void onError(QBResponseException e) {
          }
        });
```


I thinkthis will call `onError` for the `chatService.login` since the user isn't set..!?

**Comment by tatanka987** [comment]
yes but before chatService.login(user, new QBEntityCallback() need add user.setPassword(password);

**Comment by AlaaZarifa** [comment]
hmmm, I'll try this and see.. thanx

**Comment by AlaaZarifa** [comment]
thanks a lot man, it worked finally 😃

**Comment by prem34** [comment]
i got an error please help me ..iam using sdk 3.3.5 and using firebase phone autho when i sign in for first time using project id and token it successfully loged to chat ..but after 4 5 hours i never chat to login again untill i clear the cache ... i have tried by set the password of token user id but still it says Authentication failed, check user's ID and password

**Comment by tatanka987** [comment]
@prem34 please create new issue with firebase login problem, attach full log with first success login and attach full log with failed login after 4-5 hours

**Comment by adedotun** [comment]
Hello,please i have a similar isuse as @AlaaZarifa.... The progressdialog keeps running endlessly on loading the chat activity... please here is my code snipet

 QBAuth.createSession().performAsync(new QBEntityCallback<QBSession>() {
            @Override
            public void onSuccess(QBSession qbSession, Bundle bundle) {
                qbUser.setId(qbSession.getUserId());
                try {
                    qbUser.setPassword(BaseService.getBaseService().getToken());
                } catch (BaseServiceException e) {
                    e.printStackTrace();
                }
                QBChatService.getInstance().login(qbUser, new QBEntityCallback() {
                    @Override
                    public void onSuccess(Object o, Bundle bundle) {
                        progressDialog.dismiss();
                    }

                    @Override
                    public void onError(QBResponseException e) {
                        Log.e("ERROR",""+e.getMessage());
                    }
                });
            }

            @Override
            public void onError(QBResponseException e) {
                Log.e("ERROR","+++++HERE++++"+e.getMessage());

            }
        });

**Comment by tatanka987** [comment]
@adedotun you created session without user and try to get user id from it - it is mistake, because that session not contain any user. You need create session with user and in success callback try login to chat.

**Comment by adedotun** [comment]
Please can you show me how,i am kinda new to this pls

**Comment by adedotun** [comment]
here is the full createsession() method

private void createsessionforChats() {
        progressDialog=new ProgressDialog(this);
        progressDialog.setMessage("Please wait...");
        progressDialog.setCanceledOnTouchOutside(false);
        progressDialog.show();

        final String user,pass;
        user=getIntent().getStringExtra("User");
        pass=getIntent().getStringExtra("Password");


        QBUsers.getUsers(null).performAsync(new QBEntityCallback<ArrayList<QBUser>>() {
            @Override
            public void onSuccess(ArrayList<QBUser> qbUserArrayList, Bundle bundle) {
                QBUsersHolder.getInstance().putUsers(qbUserArrayList);
            }

            @Override
            public void onError(QBResponseException e) {

            }
        });

        final QBUser qbUser=new QBUser(user,pass);
        QBAuth.createSession().performAsync(new QBEntityCallback<QBSession>() {
            @Override
            public void onSuccess(QBSession qbSession, Bundle bundle) {
                qbUser.setId(qbSession.getUserId());
                try {
                    qbUser.setPassword(BaseService.getBaseService().getToken());
                } catch (BaseServiceException e) {
                    e.printStackTrace();
                }
                QBChatService.getInstance().login(qbUser, new QBEntityCallback() {
                    @Override
                    public void onSuccess(Object o, Bundle bundle) {
                        progressDialog.dismiss();
                    }

                    @Override
                    public void onError(QBResponseException e) {
                        Log.e("ERROR",""+e.getMessage());
                    }
                });
            }

            @Override
            public void onError(QBResponseException e) {
                Log.e("ERROR","+++++HERE++++"+e.getMessage());

            }
        });
    }

**Comment by adedotun** [comment]
@tatanka987 thanks in advance sir

**Comment by tatanka987** [comment]
below code for creating session and login to chat for your method

```
        QBUser qbUser = new QBUser(user,pass);
        QBUsers.signIn(qbUser).performAsync(new QBEntityCallback<QBUser>() {
            @Override
            public void onSuccess(QBUser resultQbUser, Bundle bundle) {
                resultQbUser.setPassword(pass);

                QBChatService.getInstance().login(resultQbUser, new QBEntityCallback() {
                    @Override
                    public void onSuccess(Object o, Bundle bundle) {
                        progressDialog.dismiss();
                    }

                    @Override
                    public void onError(QBResponseException e) {
                        Log.e("ERROR",""+e.getMessage());
                    }
                });
            }

            @Override
            public void onError(QBResponseException e) {
                Log.e("ERROR","+++++HERE++++"+e.getMessage());

            }
        });
```

**Comment by adedotun** [comment]
Thank you very much
