### ISSUE TITLE
Constantly track the Users offline/online in a Geofence

### ISSUE THREAD

**Issue by JoCodes** [QuickBlox/quickblox-android-sdk#41]
Hi Team,

I m using Quickblox latest version Android API. I m stumbled upon a Use Case where the User Creates   a group with other Users and adds a Geofence for a particular Location ( POI ) . When ever group members are entered or exited the Geofence it should Alert the Group Members . Also , needs to show the other group member's location constantly. 

I was trying to achieve the same with the GoogleClientAPI ( latest PlayServices API ) and GeofecingAPI from Google with the Custom Classes from Quickblox and QBLOcations. But manually trying to achieve this makes constant server updations which makes App heavy.
 Do we have anything specific in Quickblox Android API for constantly knowing the other user's location and to trigger a geofence alert. through API calls? 

Please let me know about the same since that can avoid lots of Background services which monitor and update the current locations . 

Thanks in advance
Jobi

**Comment by tatanka987** [comment]
Closed for long inactivity.
