### ISSUE TITLE
"Connection failed. Please check your internet connection" - when uploading attachment.

### ISSUE THREAD

**Issue by leonardosetiadi** [QuickBlox/quickblox-android-sdk#410]
im using this code for attach image.
```
QBContent.uploadFileTask(file, true, null).performAsync(new QBEntityCallback<QBFile>() {
            @Override
            public void onSuccess(QBFile qbFile, Bundle bundle) {
                // create a message
                QBChatMessage chatMessage = new QBChatMessage();
                chatMessage.setSaveToHistory(true); // Save a message to history

                // attach a photo
                QBAttachment attachment = new QBAttachment("photo");
                attachment.setId(qbFile.getId().toString());
                chatMessage.addAttachment(attachment);

                // send a message
                // ...
            }

            @Override
            public void onError(QBResponseException e) {
                Toast.makeText(ChatingActivity.this, "failed to upload", Toast.LENGTH_SHORT).show();
            }
        });
```

but i always get the error response that said "Connection failed. Please check your internet connection"
```
@Override
public void onError(QBResponseException e) { 
     Toast.makeText(ChatingActivity.this, "failed to upload", Toast.LENGTH_SHORT).show();
}
```

any solution about this?i need help thanks.

**Comment by tatanka987** [comment]
@leonardosetiadi please provide more logs with server request and response before getting this error

**Comment by s1n1e1** [comment]
I am also facing this issue. 

![quickblox](https://user-images.githubusercontent.com/30263580/28318706-5de3266e-6be9-11e7-8f2d-355414d816ab.png)

Please, provide solution for this issue.

**Comment by vadimkhmyrovqb** [comment]
Closed due to inactivity.

**Comment by yevhenYefimov** [comment]
I have the same issue, @leonardosetiadi did u find a solution?

**Comment by QB-nikolay-zolotarov** [comment]
@yevhenYefimov Hello,

This is Nikolay from QuickBlox support.

Please make sure that you use the latest version of the SDK:
https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.15

Also, please try reproducing the issue on our samples:
https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-chat-java
https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-chat-kotlin

If the samples work as expected, you can take them as examples.

Additionally, please try using a different connection.
