### ISSUE TITLE
Getting NullPointer exception when doing QBUser.singnUp in Quickblox3.3.1

### ISSUE THREAD

**Issue by WinnyMathew** [QuickBlox/quickblox-android-sdk#413]
I am doing Signup for quickblox using below method
QBUsers.signUp(user).performAsync(new QBEntityCallback<QBUser>() {
            @Override
            public void onSuccess(QBUser user, Bundle args) {
                // success
                
               
            }

            @Override
            public void onError(QBResponseException error) {
                // error
                if (error.getMessage() != null && error.getMessage().contains("login has already been taken")) {
                    signInUser(user);
                }

            }
        });

In log file request is shown as below
 === REQUEST ==== 3053fa85-4073-4f70-bcc1-bf5bbfc371f6 ===
                                                                     REQUEST
                                                                         POST https://api.quickblox.com/session.json
                                                                     HEADERS
                                                                         QuickBlox-REST-API-Version=0.1.1
                                                                         QB-SDK=Android 3.3.1
                                                                     PARAMETERS
                                                                         application_id=my app id
                                                                         auth_key= 
                                                                         nonce=
                                                                         timestamp=
                                                                   signature= my signature
                                                                     INLINE
                                                                         POST https://api.quickblox.com/session.json?application_id=appid&auth_key=authkey&nonce=&timestamp=1496910805&signature=6

response is also shown as below

*** RESPONSE *** 3053fa85-4073-4f70-bcc1-bf5bbfc371f6 ***
                                                                     STATUS : 201 
                                                                     HEADERS
                                                                         QuickBlox-REST-API-Version=0.1.1
                                                                         X-Runtime=0.038569
                                                                         ETag=W/"93857266cf230b87e087b55af9179848"
                                                                         Content-Length=240
                                                                         X-XSS-Protection=1; mode=block
                                                                         X-Request-Id=8dc696f9-69cf-4b09-864e-71f19feb3265
                                                                         Connection=Close
                                                                         X-Android-Response-Source=NETWORK 201
                                                                         Server=openresty/1.9.15.1
                                                                         X-Content-Type-Options=nosniff
                                                                         QB-Token-ExpirationDate=2017-06-08 10:31:36 UTC
                                                                         Cache-Control=max-age=0, private, must-revalidate
                                                                         X-Frame-Options=SAMEORIGIN
                                                                         Status=201 Created
                                                                         Strict-Transport-Security=max-age=31536000max-age=15768000;
                                                                         X-Android-Selected-Transport=http/1.1
                                                                         Date=Thu, 08 Jun 2017 08:31:36 GMT
                                                                         Access-Control-Allow-Origin=*
                                                                         X-Android-Received-Millis=1496910806821
                                                                         Content-Type=application/json; charset=utf-8
                                                                         X-Android-Sent-Millis=1496910805994
                                                                     BODY
                                                                         '{"session":{"application_id":,"created_at":"2017-06-08T08:31:36Z","id":,"nonce":-,"token":"","ts":1496910805,"updated_at":"2017-06-08T08:31:36Z","user_id":0,"_id":"172"}}'

but after this the onSuccess of QBUsers.signUp(user) is not called.Instead i get this error

java.lang.NullPointerException
06-08 14:03:26.907 26736-26736/ W/System.err:     at java.util.Calendar.setTime(Calendar.java:1183)
06-08 14:03:26.907 26736-26736/com. W/System.err:     at java.text.SimpleDateFormat.formatImpl(SimpleDateFormat.java:518)
06-08 14:03:26.907 26736-26736/com W/System.err:     at java.text.SimpleDateFormat.format(SimpleDateFormat.java:818)
06-08 14:03:26.907 26736-26736/com. W/System.err:     at java.text.DateFormat.format(DateFormat.java:307)
06-08 14:03:26.907 26736-26736/com. W/System.err:     at com.google.gson.DefaultDateTypeAdapter.write(DefaultDateTypeAdapter.java:88)
06-08 14:03:26.907 26736-26736/com. W/System.err:     at com.google.gson.DefaultDateTypeAdapter.write(DefaultDateTypeAdapter.java:40)
06-08 14:03:26.907 26736-26736/com. W/System.err:     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
06-08 14:03:26.907 26736-26736/com. W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
06-08 14:03:26.907 26736-26736/com. W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
06-08 14:03:26.907 26736-26736/com.W/System.err:     at com.google.gson.Gson.toJson(Gson.java:669)
06-08 14:03:26.907 26736-26736/com.W/System.err:     at com.google.gson.Gson.toJson(Gson.java:648)
06-08 14:03:26.907 26736-26736/com.W/System.err:     at com.google.gson.Gson.toJson(Gson.java:603)
06-08 14:03:26.908 26736-26736/com. W/System.err:     at com.google.gson.Gson.toJson(Gson.java:583)
06-08 14:03:26.908 26736-26736/com. W/System.err:     at com.quickblox.auth.session.b.save(Unknown Source)
06-08 14:03:26.908 26736-26736/com. W/System.err:     at com.quickblox.auth.session.QBSessionManager.setActiveSession(Unknown Source)
06-08 14:03:26.908 26736-26736/com. W/System.err:     at com.quickblox.auth.session.QBSessionJsonParser.extractEntity(Unknown Source)
06-08 14:03:26.908 26736-26736/com.W/System.err:     at com.quickblox.auth.session.QBSessionJsonParser.extractEntity(Unknown Source)
06-08 14:03:26.909 26736-26736/com. W/System.err:     at com.quickblox.core.parser.QBJsonParser.parse(Unknown Source)
06-08 14:03:26.909 26736-26736/com. W/System.err:     at com.quickblox.auth.session.Query$VersionEntityCallback.completedWithResponse(Unknown Source)
06-08 14:03:26.909 26736-26736/com.W/System.err:     at com.quickblox.auth.session.Query.completedWithResponse(Unknown Source)
06-08 14:03:26.909 26736-26736/com. W/System.err:     at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(Unknown Source)
06-08 14:03:26.909 26736-26736/com.W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
06-08 14:03:26.909 26736-26736/com. W/System.err:     at android.os.Looper.loop(Looper.java:193)
06-08 14:03:26.909 26736-26736/com. W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5292)
06-08 14:03:26.910 26736-26736/com.W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
06-08 14:03:26.910 26736-26736/com. W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
06-08 14:03:26.910 26736-26736/com. W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
06-08 14:03:26.910 26736-26736/com.W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
06-08 14:03:26.910 26736-26736/com. W/System.err:     at dalvik.system.NativeStart.main(Native Method)
06-08 14:03:26.910 26736-26736/com W/dalvikvm: threadid=1: calling UncaughtExceptionHandler

**Comment by tatanka987** [comment]
@WinnyMathew please see [this issue ](https://github.com/QuickBlox/quickblox-android-sdk-releases/issues/10) I think you have same problem

**Comment by vadimkhmyrovqb** [comment]
Closed due to inactivity.
