### ISSUE TITLE
Chatting issues with group and individual chat message

### ISSUE THREAD

**Issue by ashutoshgohil** [QuickBlox/quickblox-android-sdk#415]
Hi Team,

I have integrated 3.3.1 sdk in Android, for chatting and video calling. When I do testing with iPhone and Android device then many times I do not get last message in one to one chat and group chat. it happens many times when I test with different platform like iPhone v/s Android. 
I have checked sent message in quickblox database and every message sent successfully but my chat window didn't refreshed. My question is :
1. How to refresh manually Chat screen after getting new message ?
2. How to handle drop message which is sent successfully but didn't received ?

Thanks
Ashutosh

**Comment by tatanka987** [comment]
hello @Ashutosh, please provide us logs in time when messages not receive to Android device, additionally check custom parameters in message, they haven't to be blank or empty (you can set there some default values). For more information check our documentation how to [get messages realtime](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Receiving_incoming_messages) or [get messages from server](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Retrieve_list_of_messages)

**Comment by vadimkhmyrovqb** [comment]
Closed due to inactivity.
