### ISSUE TITLE
QuickBlox Login Error :  Connection failed. Please check your internet connection

### ISSUE THREAD

**Issue by himangipatel** [QuickBlox/quickblox-android-sdk#418]
SignUp and SignIn just working fine with almost devices but In some device (samsung gt 18552) its is not wokring.

I tried Sample Chat app which is provided by SDK. Even that is not working in this device

**com.quickblox.core.exception.QBResponseException: Connection failed. Please check your internet connection.**

I am getting above error when trying to login QBUser in some devices(samsung gt 18552).

**QBUsers.signUp is working perfect but when trying to login with same user its gave me Error :  Please check your internet connection.**

> #SignUp code :

requestExecutor.signUpNewUser(newUser, new QBEntityCallback<QBUser>() {
                    @Override
                    public void onSuccess(QBUser result, Bundle params) {
                        updateQuickBloxIdToServer(String.valueOf(result.getId()));
                        loginToChat(newUser);
                    }@Override
                    public void onError(QBResponseException e) {
                        if (e.getHttpStatusCode() == Consts.ERR_LOGIN_ALREADY_TAKEN_HTTP_STATUS) {
                            signInCreatedUser(newUser, true);
                        } else {
                            if (mRegisterView != null) {
                                mRegisterView.hideProgress();
                            }
                            //  getPrefs(AppClass.getInstance()).clearAll();
                            Toast.makeText(AppClass.getInstance(),e.toString(), Toast.LENGTH_SHORT).show();
                        }
                    }
                }
        );

> #Login Code 

 QBUsers.signIn(user).performAsync(new QbEntityCallbackTwoTypeWrapper<QBUser, Void>(callback) {
            @Override
            public void onSuccess(QBUser qbUser, Bundle args) {
                user.setId(qbUser.getId());
                loginToChat(user, new QbEntityCallbackWrapper<>(callback));
            }
        });

Please Help. I am stuck with this weird issue

**Comment by himangipatel** [comment]
> #Request Log

=========================================================
                                                     === REQUEST ==== bf6923bc-08a7-4995-8c72-24fddec45223 ===
                                                     REQUEST
                                                         POST https://api.quickblox.com/login.json
                                                     HEADERS
                                                         QuickBlox-REST-API-Version=0.1.1
                                                         QB-SDK=Android 3.3.1
                                                         QB-Token=f8ac2bb2e24f17c99fe561960abd033f9f00cb8e
                                                     PARAMETERS
                                                         login=test11@gmail.com
                                                         email=test11@gmail.com
                                                         password=123456789
                                                     INLINE
                                                         POST https://api.quickblox.com/login.json?login=test11%40gmail.com&email=test11%40gmail.com&password=123456789


> #OnError Response Log

com.quickblox.core.exception.QBResponseException: Connection failed. Please check your internet connection.

**Comment by himangipatel** [comment]
https://play.google.com/store/apps/details?id=com.quickblox.q_municate&hl=en

I am not able to login with this app in samsung gt 18552 device

**Comment by tatanka987** [comment]
@himangipatel please provide us full log from app start to getting this error and full stacktrace with error

**Comment by himangipatel** [comment]
@tatanka987 

06-16 17:00:50.841 31124-31124/com.bnbjobs D/QBASDK: =========================================================
                                                     === REQUEST ==== 06c376ab-ccdd-44c0-8b91-e411b0f233af ===
                                                     REQUEST
                                                         POST https://api.quickblox.com/login.json
                                                     HEADERS
                                                         QuickBlox-REST-API-Version=0.1.1
                                                         QB-SDK=Android 3.3.1
                                                         QB-Token=5a0149f8a8ca5b94cdcc41d507d1b4c95f00cb8e
                                                     PARAMETERS
                                                         login=test11@gmail.com
                                                         email=test11@gmail.com
                                                         password=123456789
                                                     INLINE
                                                         POST https://api.quickblox.com/login.json?login=test11%40gmail.com&email=test11%40gmail.com&password=123456789
06-16 17:00:52.371 31124-31124/com.bnbjobs D/BJ_LoginPresenter: com.quickblox.core.exception.QBResponseException: Connection failed. Please check your internet connection.
06-16 17:00:52.421 31124-31124/com.bnbjobs D/QBASDK: =========================================================
                                                     === REQUEST ==== bd990c72-bdda-41bc-9d57-190bc383e327 ===
                                                     REQUEST
                                                         POST https://api.quickblox.com/users.json
                                                     HEADERS
                                                         QuickBlox-REST-API-Version=0.1.1
                                                         QB-SDK=Android 3.3.1
                                                         QB-Token=5a0149f8a8ca5b94cdcc41d507d1b4c95f00cb8e
                                                     PARAMETERS
                                                         user[login]=test11@gmail.com
                                                         user[email]=test11@gmail.com
                                                         user[external_user_id]=4
                                                         user[full_name]=test 1him
                                                         user[custom_data]=http://bnb.reviewprototypes.com/uploads/users/4/thumb/pp_1497611228_thumb.png
                                                         user[tag_list]=BNBJob
                                                         user[password]=123456789
                                                     INLINE
                                                         POST https://api.quickblox.com/users.json?user[login]=test11%40gmail.com&user[email]=test11%40gmail.com&user[external_user_id]=4&user[full_name]=test+1him&user[custom_data]=http%3A%2F%2Fbnb.reviewprototypes.com%2Fuploads%2Fusers%2F4%2Fthumb%2Fpp_1497611228_thumb.png&user[tag_list]=BNBJob&user[password]=123456789
06-16 17:00:53.941 31124-1286/com.bnbjobs D/QBASDK: SubscribeTaskManager EXTRA_SUBSCRIBE_TASK
06-16 17:00:53.941 31124-1286/com.bnbjobs D/QBASDK: SubscribeTaskManager onRunTask
06-16 17:00:53.971 31124-31124/com.bnbjobs D/QBASDK: SubscribeService: SubscribeService created
06-16 17:00:53.981 31124-1287/com.bnbjobs D/QBASDK: SubscribeService: onHandleIntent start: register to pushes
06-16 17:00:53.991 31124-1287/com.bnbjobs D/QBASDK: SubscribeService:  get settings from meta-data: typeCM=GCM, senderId=946246511340, qbEnvironment=development
06-16 17:00:53.991 31124-1287/com.bnbjobs D/QBASDK: SubscribeService: Device registered in GCM, regId=c-giF4EZqC4:APA91bHPdvOiyk5gW-n9ROsUnw-7vpmQCmaUvvL8iqdKI7aXyEz3YsadYV7J4wtWKgiGfBEQtJCE1PUgjA2pZidj3qaqfNNPQPdk-22p7xIoGSjtDZBnZVcDMvQh89D54rOpHuqWj2__
06-16 17:00:53.991 31124-1287/com.bnbjobs D/QBASDK: DEVICE_ID = ffffffff-cda1-62f6-ffff-ffffebae35c3
06-16 17:00:54.001 31124-1287/com.bnbjobs D/QBASDK: =========================================================
                                                    === REQUEST ==== 4728951e-424a-4ffc-9ebc-b0b850bdebc8 ===
                                                    REQUEST
                                                        POST https://api.quickblox.com/subscriptions.json
                                                    HEADERS
                                                        QuickBlox-REST-API-Version=0.1.1
                                                        QB-SDK=Android 3.3.1
                                                        QB-Token=5a0149f8a8ca5b94cdcc41d507d1b4c95f00cb8e
                                                    PARAMETERS
                                                        notification_channels=gcm
                                                        push_token[client_identification_sequence]=c-giF4EZqC4:APA91bHPdvOiyk5gW-n9ROsUnw-7vpmQCmaUvvL8iqdKI7aXyEz3YsadYV7J4wtWKgiGfBEQtJCE1PUgjA2pZidj3qaqfNNPQPdk-22p7xIoGSjtDZBnZVcDMvQh89D54rOpHuqWj2__
                                                        device[udid]=ffffffff-cda1-62f6-ffff-ffffebae35c3
                                                        device[platform]=android
                                                        push_token[environment]=development
                                                    INLINE
                                                        POST https://api.quickblox.com/subscriptions.json?notification_channels=gcm&push_token[client_identification_sequence]=c-giF4EZqC4%3AAPA91bHPdvOiyk5gW-n9ROsUnw-7vpmQCmaUvvL8iqdKI7aXyEz3YsadYV7J4wtWKgiGfBEQtJCE1PUgjA2pZidj3qaqfNNPQPdk-22p7xIoGSjtDZBnZVcDMvQh89D54rOpHuqWj2__&device[udid]=ffffffff-cda1-62f6-ffff-ffffebae35c3&device[platform]=android&push_token[environment]=development
06-16 17:00:55.291 31124-1287/com.bnbjobs D/QBASDK: SubscribeService: Not subscribed for QB push messagescom.quickblox.core.exception.QBResponseException: Connection failed. Please check your internet connection.
06-16 17:00:55.311 31124-1287/com.bnbjobs D/QBASDK: SubscribeService: startSchedulerTask
06-16 17:00:55.441 31124-31124/com.bnbjobs D/QBASDK: SubscribeService: Service onDestroy



This is full stacktrace

**Comment by himangipatel** [comment]
06-16 17:00:50.841 31124-31124/com.bnbjobs D/QBASDK: =========================================================
                                                     === REQUEST ==== 06c376ab-ccdd-44c0-8b91-e411b0f233af ===
                                                     REQUEST
                                                         POST https://api.quickblox.com/login.json
                                                     HEADERS
                                                         QuickBlox-REST-API-Version=0.1.1
                                                         QB-SDK=Android 3.3.1
                                                         QB-Token=5a0149f8a8ca5b94cdcc41d507d1b4c95f00cb8e
                                                     PARAMETERS
                                                         login=test11@gmail.com
                                                         email=test11@gmail.com
                                                         password=123456789
                                                     INLINE
                                                         POST https://api.quickblox.com/login.json?login=test11%40gmail.com&email=test11%40gmail.com&password=123456789
06-16 17:00:52.371 31124-31124/com.bnbjobs D/BJ_LoginPresenter: com.quickblox.core.exception.QBResponseException: Connection failed. Please check your internet connection.
06-16 17:00:52.421 31124-31124/com.bnbjobs D/QBASDK: =========================================================
                                                     === REQUEST ==== bd990c72-bdda-41bc-9d57-190bc383e327 ===
                                                     REQUEST
                                                         POST https://api.quickblox.com/users.json
                                                     HEADERS
                                                         QuickBlox-REST-API-Version=0.1.1
                                                         QB-SDK=Android 3.3.1
                                                         QB-Token=5a0149f8a8ca5b94cdcc41d507d1b4c95f00cb8e
                                                     PARAMETERS
                                                         user[login]=test11@gmail.com
                                                         user[email]=test11@gmail.com
                                                         user[external_user_id]=4
                                                         user[full_name]=test 1him
                                                         user[custom_data]=/uploads/users/4/thumb/pp_1497611228_thumb.png
                                                         user[tag_list]=BNBJob
                                                         user[password]=123456789
                                                     INLINE
                                                         POST https://api.quickblox.com/users.json?user[login]=test11%40gmail.com&user[email]=test11%40gmail.com&user[external_user_id]=4&user[full_name]=test+1him&user[custom_data]=http%3A%2F%2Fbnb.reviewprototypes.com%2Fuploads%2Fusers%2F4%2Fthumb%2Fpp_1497611228_thumb.png&user[tag_list]=BNBJob&user[password]=123456789
06-16 17:00:53.941 31124-1286/com.bnbjobs D/QBASDK: SubscribeTaskManager EXTRA_SUBSCRIBE_TASK
06-16 17:00:53.941 31124-1286/com.bnbjobs D/QBASDK: SubscribeTaskManager onRunTask
06-16 17:00:53.971 31124-31124/com.bnbjobs D/QBASDK: SubscribeService: SubscribeService created
06-16 17:00:53.981 31124-1287/com.bnbjobs D/QBASDK: SubscribeService: onHandleIntent start: register to pushes
06-16 17:00:53.991 31124-1287/com.bnbjobs D/QBASDK: SubscribeService:  get settings from meta-data: typeCM=GCM, senderId=946246511340, qbEnvironment=development
06-16 17:00:53.991 31124-1287/com.bnbjobs D/QBASDK: SubscribeService: Device registered in GCM, regId=c-giF4EZqC4:APA91bHPdvOiyk5gW-n9ROsUnw-7vpmQCmaUvvL8iqdKI7aXyEz3YsadYV7J4wtWKgiGfBEQtJCE1PUgjA2pZidj3qaqfNNPQPdk-22p7xIoGSjtDZBnZVcDMvQh89D54rOpHuqWj2__
06-16 17:00:53.991 31124-1287/com.bnbjobs D/QBASDK: DEVICE_ID = ffffffff-cda1-62f6-ffff-ffffebae35c3
06-16 17:00:54.001 31124-1287/com.bnbjobs D/QBASDK: =========================================================
                                                    === REQUEST ==== 4728951e-424a-4ffc-9ebc-b0b850bdebc8 ===
                                                    REQUEST
                                                        POST https://api.quickblox.com/subscriptions.json
                                                    HEADERS
                                                        QuickBlox-REST-API-Version=0.1.1
                                                        QB-SDK=Android 3.3.1
                                                        QB-Token=5a0149f8a8ca5b94cdcc41d507d1b4c95f00cb8e
                                                    PARAMETERS
                                                        notification_channels=gcm
                                                        push_token[client_identification_sequence]=c-giF4EZqC4:APA91bHPdvOiyk5gW-n9ROsUnw-7vpmQCmaUvvL8iqdKI7aXyEz3YsadYV7J4wtWKgiGfBEQtJCE1PUgjA2pZidj3qaqfNNPQPdk-22p7xIoGSjtDZBnZVcDMvQh89D54rOpHuqWj2__
                                                        device[udid]=ffffffff-cda1-62f6-ffff-ffffebae35c3
                                                        device[platform]=android
                                                        push_token[environment]=development
                                                    INLINE
                                                        POST https://api.quickblox.com/subscriptions.json?notification_channels=gcm&push_token[client_identification_sequence]=c-giF4EZqC4%3AAPA91bHPdvOiyk5gW-n9ROsUnw-7vpmQCmaUvvL8iqdKI7aXyEz3YsadYV7J4wtWKgiGfBEQtJCE1PUgjA2pZidj3qaqfNNPQPdk-22p7xIoGSjtDZBnZVcDMvQh89D54rOpHuqWj2__&device[udid]=ffffffff-cda1-62f6-ffff-ffffebae35c3&device[platform]=android&push_token[environment]=development
06-16 17:00:55.291 31124-1287/com.bnbjobs D/QBASDK: SubscribeService: Not subscribed for QB push messagescom.quickblox.core.exception.QBResponseException: Connection failed. Please check your internet connection.
06-16 17:00:55.311 31124-1287/com.bnbjobs D/QBASDK: SubscribeService: startSchedulerTask
06-16 17:00:55.441 31124-31124/com.bnbjobs D/QBASDK: SubscribeService: Service onDestroy

**Comment by tatanka987** [comment]
without responses? you can use [Gist](https://gist.github.com/) for providing logs

**Comment by tatanka987** [comment]
on other devises working fine? please provide information about Android version on your devise

**Comment by himangipatel** [comment]
https://gist.github.com/himangipatel/67e5251432f1590ccf7408b319815c4d

yes its working fine with almost devices.

![device-2017-06-16-171339](https://user-images.githubusercontent.com/19974650/27225308-31c1100a-52b7-11e7-9cde-3d0d9f46c9a7.png)

**Comment by jay2342** [comment]
hey tatanka987  can you help me

**Comment by maximrahlis** [comment]
I have encountered a similar problem, make sure the time on your device is correct..

**Comment by iman2420** [comment]
@jay2342 @tatanka987 does not respond whenever he can not help!!

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customers,

This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-users](https://docs.quickblox.com/docs/android-users)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
