### ISSUE TITLE
Unable to get user status using QBPingManager

### ISSUE THREAD

**Issue by akashmehta** [QuickBlox/quickblox-android-sdk#421]
**Environment details**
*(Operating system, browser information, SDK version)*
using com.quickblox:quickblox-android-sdk-chat:3.3.3 { transitive = true } 

**Did this work before?**
No 

**Expected behavior**
I should get user online status true when user is online according to [doc:](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Ping_a_user)

to satisfy requirement that user A try to call user B at that time A should be able to get availability status of B whether it is online/offline using Ping Manager.
 
**Actual behavior**
i am able to ping server but unable to ping a perticular user.

**Steps to reproduce the behavior**
This is the method which i am using to check user status:
```
public void checkUserOnlineStatus(String mOpponentName) {
        Performer<QBUser> qbUser = QBUsers.getUserByLogin(mOpponentName);
        qbUser.performAsync(new QBEntityCallback<QBUser>() {
            @Override
            public void onSuccess(QBUser qbUser, Bundle bundle) {
                final int mOpponentUserId = qbUser.getId();
                final QBPingManager pingManager = QBChatService.getInstance().getPingManager();
                pingManager.addPingFailedListener(new PingFailedListener() {
                    @Override
                    public void pingFailed() {
                        Log.d(TAG, "pingFailed() called");
                    }
                });
                pingManager.setPingInterval(1);
                pingManager.pingServer(new QBEntityCallback<Void>() {
                    @Override
                    public void onSuccess(Void aVoid, Bundle bundle) {
                        pingManager.pingUser(mOpponentUserId, new QBEntityCallback<Void>() {
                            @Override
                            public void onSuccess(Void aVoid, Bundle bundle) {
                                Log.d(TAG, "onSuccess() called with: aVoid = [" + aVoid + "], bundle = [" + bundle + "]");
                            }

                            @Override
                            public void onError(QBResponseException e) {
                                Log.d(TAG, "onError() called with: e = [" + e + "]");
                                e.printStackTrace();
                            }
                        });

                    }

                    @Override
                    public void onError(QBResponseException e) {
                        Timber.tag(TAG).e("message (ping server): " + e.getMessage() + "\n localized message: " + e.getLocalizedMessage());
                    }
                });


            }

            @Override
            public void onError(QBResponseException e) {
                Timber.tag(TAG).e("Error : " + e.getMessage() + "\n Message :  " + e.getLocalizedMessage());
            }
        });
    }

```
This always returns following log:
onError() called with: e = [com.quickblox.core.exception.QBResponseException: Server is unavailable]
please let me know if any other configuration is needed. 

**Any others comments?**
for more info please visit following link: [stackoverflow](https://stackoverflow.com/questions/44885113/android-how-to-maintain-user-online-offline-status-using-quickblox)

**Comment by tatanka987** [comment]
@akashmehta can you provide us full log from start login to chat to get this error?

**Comment by akashmehta** [comment]
sure @tatanka987 i got following exception while performing ping user:
07-04 15:23:08.206 13905-13905/com.samplechatapp.app W/System.err: com.quickblox.core.exception.QBResponseException: Server is unavailable
07-04 15:23:08.207 13905-13905/com.samplechatapp.app W/System.err:     at com.quickblox.chat.QBChatService$5.run(Unknown Source)
07-04 15:23:08.207 13905-13905/com.samplechatapp.app W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
07-04 15:23:08.207 13905-13905/com.samplechatapp.app W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-04 15:23:08.207 13905-13905/com.samplechatapp.app W/System.err:     at android.os.Looper.loop(Looper.java:148)
07-04 15:23:08.208 13905-13905/com.samplechatapp.app W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
07-04 15:23:08.208 13905-13905/com.samplechatapp.app W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-04 15:23:08.208 13905-13905/com.samplechatapp.app W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-04 15:23:08.208 13905-13905/com.samplechatapp.app W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

and i have attached file that has full log since login to chat.
[quickblox chat logs.docx](https://github.com/QuickBlox/quickblox-android-sdk/files/1121707/quickblox.chat.logs.docx)

**Comment by ShahzaibAli1** [comment]
I am getting the same exception every time even if the user is online.

**Comment by vikasrairajput** [comment]
is anyone find the solution?

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @vikasrairajput 

1. Have you tried to reproduce the reported issue on clear QuickBlox Android sample?
2. What Android SDK version do you use? 
3. Provide the detailed reproducing steps. 
4. Provide a full logs of the issue. 
5. Provide a code snippet to see how this feature is implemented on your side.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customers,

This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-video-calling](https://docs.quickblox.com/docs/android-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#video-calling-samples](https://docs.quickblox.com/docs/code-samples#video-calling-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
