### ISSUE TITLE
Push notification issue

### ISSUE THREAD

**Issue by AnilJha10** [QuickBlox/quickblox-android-sdk#424]
Opponent user never receives push notification on time and whenever he receives it would be something like "You have 0 notification". I'm not using event for every message sent as you suggest after 3.3.0 you have default subscription for Android and I'm using 3.3.2 please help. Thanks!

**Comment by RomanPronin** [comment]
Hi @AnilJha10, if you don't receive pushes after a successful subscription, check the next: 
1. Check certificates for pushes: Admin panel ->Push Notification ->Settings -> APNS, GCM etc.
2. Check subscription :  Admin panel -> Push Notifications - >  Subscriptions. You can check subscription for user:  Admin panel -> Users - > "your" user  ->In the right side below  "Tags" is placed list of the subscriptions. 
3. Send push from Admin Panel - > Push notifications - > Send. http://quickblox.com/developers/SimpleSample-messages_users-android#Send_Push_Notifications_from_Admin_panel

**Comment by RomanPronin** [comment]
Long time inactivity.
