### ISSUE TITLE
VideoTrack serious error on Android 7.0

### ISSUE THREAD

**Issue by whitenoory** [QuickBlox/quickblox-android-sdk#427]
Hi,
We've fixed some issues but we are struggling with using new version of quickblox which is version 3.3.0.
We were making with an application with version 3.2.0 and it had no problems at all. However, when I tried with 3.3.0, local video view freeze when I try to reuse it. 
Lets say I am making a random chatting application. After I am done with current chat, I am connecting with other user. After I connected with another user, other functions working well but only local video view freezes and doesnt work well. And this issue occurs only with android 7.0 version.
Can you tell me how to fix this problem?

[Simple Code]
```
public void onLocalVideoTrackReceive (QBRTCSession a_pSession, QBRTCVideoTrack a_pVideoTrack)
{
        if(m_pLocalVideoTrack != null)
        {
            if(m_pLocalVideoTrack.getRenderer() != null)
            {
                //  There is a problem here.
                m_pLocalVideoTrack.removeRenderer(m_pLocalVideoTrack.getRenderer());
            }
        }
        
        m_pLocalVideoTrack = a_pVideoTrack;
        .....
}

```

**Comment by RomanPronin** [comment]
Hi, @whitenoory. Please, provide full steps to find out the problem. What's happening when you finish first call, do you release CurrentSession or not? And so on. Give us more info.

**Comment by whitenoory** [comment]
Hi,
At first, connect with the opponent by using the function "QBRTCSession.startCall();". After done with video chatting with opponent, call "QBRTCSession.hangup();)" this method to finish the session. At this point, I initialized "CurrentSession" to Null and I tried to connect with other user but I didn't finish the current activity. To connect with other user, I used this function "createNewSessionWithOpponents". and use "startCall" to have video chat with the other user.

The point is, under Android 7.0 version works very well but over Android 7.0 version the LocalVideo freezes. Can you tell me how to fix this problem? Thanks.

**Comment by RomanPronin** [comment]
If you receive onCameraFreezed() or onCameraError() event, or maybe by another event you've got, you can try to reset CameraVideoCapturer:

`
 currentSession.getMediaStreamManager().setVideoCapturer(new QBRTCCameraVideoCapturer(this, null));`

**Comment by RomanPronin** [comment]
Long time inactivity.
