### ISSUE TITLE
Receiving push notifications after signout

### ISSUE THREAD

**Issue by pozharov** [QuickBlox/quickblox-android-sdk#428]
**Environment details**
Quickblox sdk version 3.3.1

**Expected behavior**
Do not receive push notifications after removing user's session using code below

`QBUsers.signOut();`

**Actual behavior**

User receive push notifications

Sign in sample

```
            final QBUser user = new QBUser(qbLogin, qbPass);
            QBUsers.signIn(user).performAsync(new QBEntityCallback<QBUser>() {
                @Override
                public void onSuccess(QBUser qbUser, Bundle bundle) {

                }

                @Override
                public void onError(QBResponseException e) {

                }
            });
```

**Comment by RomanPronin** [comment]
Hi @pozharov, in order to unsubscribe from pushes just call:

`
//you can do it in onSuccess();`
`
SubscribeService.unSubscribeFromPushes(context);
`

**Comment by petergayduchik** [comment]
for me helped this two lines 
```
QBSettings.getInstance().setEnablePushNotification(false);
SubscribeService.unSubscribeFromPushes(HomeActivity.this);
```

**Comment by RomanPronin** [comment]
Resolved.
