### ISSUE TITLE
Not getting the Push notifications

### ISSUE THREAD

**Issue by gowthamidommeti** [QuickBlox/quickblox-android-sdk#430]
Hi,

This is Gowthami. I integrated this code 3 months before. In that time push notifications are working fine. But now am unable to get a push notification. Please help me to resolve this issue.

**Comment by RomanPronin** [comment]
Hi @gowthamidommeti, likely there is some temporary problem in server side, it will be fixed soon.

**Comment by RomanPronin** [comment]
It's all ok now?
