### ISSUE TITLE
Cant set notification to FCM

### ISSUE THREAD

**Issue by petergayduchik** [QuickBlox/quickblox-android-sdk#431]
Hello there. 
Im trying to use qb notifications , but i have problem . 
Im using **sdk 3.3.4** 
reading from this 
[link to quickblox_developers](https://quickblox.com/developers/SimpleSample-messages_users-android)
in documentation i see that we need set QBNotificationChannel for FCM. 
But we can set only GCM  because 
```
public enum QBNotificationChannel {
    GCM("gcm"),
    APNS("apns"),
    APNS_VOIP("apns_voip"),
    EMAIL("email"),
    PULL("pull");

    private String caption;

    private QBNotificationChannel(String caption) {
        this.caption = caption;
    }

    public String toString() {
        return this.caption;
    }

    public String getCaption() {
        return this.caption;
    }

    public void setCaption(String caption) {
        this.caption = caption;
    }
}
```
dont have FCM. Can any explaine what im doing wrong ? 
In quickblox admin panel also i dont see settings for FCM , only for GCM. 
AutoSubscription not working for GCM/FCM. Listener not working.
Please any help ?
Regards, Peter 
p.s. sorry for my bad english

**Comment by RomanPronin** [comment]
Hi, @petergayduchik. You do not need to set QBNotificationChannel manually. Use [Auto subscription mechanism](https://quickblox.com/developers/SimpleSample-messages_users-android#Setup_Push_Notifications_SDK_3.2_-_Auto_subscription). And if you use type FCM, you should set this type in meta-data. Just follow guidelines.

**Comment by petergayduchik** [comment]
@RomanPronin Hey Roman, thank you for u answer, Im trying to make its without QBNotificationChannel. But its not working . Listener not calling. And in admin panel(Quickblox) i dont see new subscriber with FCM. Please if u guys can help . Can u provide some correct code. Its very urgent.

**Comment by RomanPronin** [comment]
All code is correct in guide. Did you set QBFcmPushListenerService and QBFcmPushInstanceIDService in manifest file? Do you get some events from QBPushManager.QBSubscribeListener? @petergayduchik, you should look at [sample](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-pushnotifications) more carefully.

**Comment by petergayduchik** [comment]
@RomanPronin i dont have any events from QBPushManager. Anythings. FCM NOT WORKING!!! thats all. GCM  i can config only for one from two devices. I cant udnderstand why/ Nexus 6.0 not working, Samsung J2 working.
```
<meta-data android:name="com.quickblox.messages.TYPE" android:value="GCM" />
        <meta-data android:name="com.quickblox.messages.SENDER_ID" android:value="@string/sender_id" />
        <meta-data android:name="com.quickblox.messages.QB_ENVIRONMENT" android:value="DEVELOPMENT" />
        <service
            android:name="com.quickblox.messages.services.gcm.QBGcmPushListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>
        <service
            android:name="com.quickblox.messages.services.gcm.QBGcmPushInstanceIDService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.gms.iid.InstanceID" />
            </intent-filter>
        </service>
```
```
QBPushManager.getInstance().addListener(new QBPushManager.QBSubscribeListener() {
            @Override
            public void onSubscriptionCreated() {
                Logger.e("################On subscription Created####################");
            }

            @Override
            public void onSubscriptionError(Exception e, int i) {
                Logger.e("########################On subscription error : "+e.toString());
                e.printStackTrace();
            }

            @Override
            public void onSubscriptionDeleted(boolean b) {
                Logger.e("##########################On subscription deleted ,  status = "+b);
            }
        });
```

all events not call.

**Comment by petergayduchik** [comment]
any help ? AutoSubscribe not working . GCM hand mode also not working .  Subscription going with wrong userId(quickbloxId). If made hand subscribe - in "subscription complete " -> RegistrationID = null.!!

**Comment by petergayduchik** [comment]
unbelievable, no help with sdk. Documentation for android almost broken. Everything always need repaire to work.  Sample apps dont have all classes which need to run.  FCM not working, GCM not working. Subscription always destroyed after first push which not received. Admin panel with ajax errors.

**Comment by RomanPronin** [comment]
Our SDK and samples work fine. So, our recommendation, if in your code something doesn't work, look at the same implementation in quickblox samples. As for pushes GSM implementation sample https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-pushnotifications, and FCM - https://github.com/QuickBlox/q-municate-android

**Comment by petergayduchik** [comment]
why u just not reading what im saying ? auto subscription not working .  normal subscription work only one time per call and push not received. Callbacks not tell me anything.

**Comment by petergayduchik** [comment]
today at morning  auto subscription make correct registration as i think and we get first push. No changes from our side. What happened idk.

**Comment by RomanPronin** [comment]
There was temporarily problem with pushes on shared server, sorry about that.

**Comment by petergayduchik** [comment]
Thank you guys, now all work perfect.  @RomanPronin  thank for answers. We can close this issue.

**Comment by RomanPronin** [comment]
You are welcome.

**Comment by rizwanjillani** [comment]
Android notifications not working

**Comment by rizwanjillani** [comment]
**Android notifications not working**
below is the logs generated on dashboard 

{"notification":{"id":17284994,"badge":null,"device_token":null,"sound":"default","alert":null,"data":{"message":"test","collapse_key":"event25852527"},"expiry":86400,"delivered":false,"delivered_at":null,"failed":true,"failed_at":"2018-09-18T08:44:53+00:00","fail_after":"2018-09-18T09:44:52+00:00","retries":0,"error_code":401,"error_description":"Unable to deliver notification 17284994, received error 401 (Unauthorized, check your App auth_key.)","deliver_after":null,"alert_is_json":null,"app_id":25478,"collapse_key":null,"delay_while_idle":false,"registration_ids":["60772493"],"uri":null,"priority":10,"url_args":null,"category":null,"content_available":false,"mutable_content":false,"notification":null,"type":"Rpush::Client::Redis::Gcm::Notification","event_id":25852527,"event_date":"2018-09-18T08:44:51+00:00"},"log":[{"device_token":null,"delivered_at":null,"failed_at":"2018-09-18T08:44:53+00:00","error_code":401,"error_description":"Unable to deliver notification 17284994, received error 401 (Unauthorized, check your App auth_key.)"}]}

**Comment by dtaparelli** [comment]
Same here! All configurations checked..

**Comment by imran-samed** [comment]
@rizwanjillani  do you found any solution for this
I'm also facing same issue.

**Comment by Krailit** [comment]
Same here I tried to config everything follows the tutorial.
When I send push-notification from the backend I got this log
and the client never received any notification.

> {
  "notification": {
    "id": 38261720,
    "badge": null,
    "device_token": null,
    "sound": "default",
    "alert": null,
    "data": {
      "message": "fffff7",
      "collapse_key": "event35665602"
    },
    "expiry": 86400,
    "delivered": false,
    "delivered_at": null,
    "failed": true,
    "failed_at": "2020-12-16T11:23:11+00:00",
    "fail_after": "2020-12-16T12:23:11+00:00",
    "retries": 0,
    "error_code": 401,
    "error_description": "Unable to deliver notification 38261720, received error 401 (Unauthorized, check your App auth_key.)",
    "deliver_after": null,
    "alert_is_json": null,
    "sound_is_json": null,
    "app_id": 66471,
    "collapse_key": null,
    "delay_while_idle": false,
    "registration_ids": [
      "eAIn61PQ8PE:APA91bEhMQSq2CztyBzIixPiDpxZn_lTNPECoFN0xupGuCU0L67TYkH9ajIWYF14DDWd601WE0p5RAPvz9XgPFJmendv78zbBsAzkh8jmNby6o-Cc2JBfXYxo_Kiq_zxhVD4_ZtyIeP1"
    ],
    "uri": null,
    "priority": 10,
    "url_args": null,
    "category": null,
    "content_available": false,
    "dry_run": false,
    "mutable_content": false,
    "notification": null,
    "thread_id": null,
    "type": "Rpush::Client::Redis::Fcm::Notification",
    "event_id": 35665602,
    "event_date": "2020-12-16T11:23:11+00:00"
  },
  "log": [
    {
      "device_token": null,
      "delivered_at": null,
      "failed_at": "2020-12-16T11:23:11+00:00",
      "error_code": 401,
      "error_description": "Unable to deliver notification 38261720, received error 401 (Unauthorized, check your App auth_key.)"
    }
  ]
}

But it's working fine if I send push notifications directly from firebase API with the same SERVER_KEY between QB and Postman header.

![image](https://user-images.githubusercontent.com/5466911/102344138-0b47cd80-3fce-11eb-8f43-baaf979c29c7.png)
