### ISSUE TITLE
Something wrong with your account key please check it in quickblox admin panel 

### ISSUE THREAD

**Issue by jay2342** [QuickBlox/quickblox-android-sdk#432]
i have a problem when i build apk and emulator starts running after that when i signin or signup this error displays "Something wrong with your account key please check it in quickblox admin panel"

**Comment by RomanPronin** [comment]
Hi @jay2342, did you set your AccountKey like this ? `QBSettings.getInstance().setAccountKey(ACCOUNT_KEY);`
Follow to QuickBlox Dashboard https://admin.quickblox.com/account and copy the AccountKey value.
Also look here https://quickblox.com/developers/Android#Initialize_framework

**Comment by jay2342** [comment]
yes
and my account key also right

**Comment by RomanPronin** [comment]
Instead of set setAccountKey, set endpoints like [here](https://quickblox.com/developers/Android#Endpoints_customization). You can also look at [sample](https://github.com/QuickBlox/quickblox-android-sdk/blob/master/sample-core/src/main/java/com/quickblox/sample/core/CoreApp.java) for proper initCredentials.

**Comment by jay2342** [comment]
Roman can i get your whatsapp number
so i can chat with you quickly to solve my prob

**Comment by RomanPronin** [comment]
Look [here](https://quickblox.com/contact/) to get info about support. I advise you deeply look into quickblox samples, so you can find a lot of useful information there.

**Comment by jay2342** [comment]
Roman just can you solve my prob if i give you my project file

**Comment by jay2342** [comment]
[secondhalfProChat.zip](https://github.com/QuickBlox/quickblox-android-sdk/files/1191117/secondhalfProChat.zip)

**Comment by jay2342** [comment]
[firsthalfProChat.zip](https://github.com/QuickBlox/quickblox-android-sdk/files/1191145/firsthalfProChat.zip)

**Comment by jay2342** [comment]
i didnot uploded build file do you need it

**Comment by jay2342** [comment]
Roman
please help me

**Comment by RomanPronin** [comment]
Listen @jay2342 , if you want to use quickblox API, you should carefully learn it, there is no other way. I say again, look at samples. You'll find all you need. As for your problem, if you are convinced your account key is correct, I already gave you alternative way. Our samples works fine, so сompare your code with the sample. It is not so difficult.

**Comment by jay2342** [comment]
i m using it but you should help with the code

**Comment by RomanPronin** [comment]
Also, I recommend you use SDK version 3.2.0 with [auto session mechanism](https://quickblox.com/developers/Android#SDK_3.2.0_Authentication).

**Comment by djErock** [comment]
Roman, your documentation's syntax is incorrect here:

QBSettings.getInstance().setEndpoints(API_DOMAIN, CHAT_DOMAIN), ServiceZone.PRODUCTION);

**Comment by djErock** [comment]
You have a close parantheses at the end. What opens it? ServiceZone.PRODUCTION);

**Comment by djErock** [comment]
It should be like this:

QBSettings.getInstance().setEndpoints(API_DOMAIN, CHAT_DOMAIN, ServiceZone.PRODUCTION);

**Comment by RomanPronin** [comment]
@djErock, thanks for noticing.

**Comment by jay2342** [comment]
@djErock i have a problem i cnt get user in listview when i start emulator the app runs but it dont shows me the users can you give me solution

**Comment by djErock** [comment]
Do you have an enterprise account? What type of account so you have?

**Comment by djErock** [comment]
Do you have?***

**Comment by jay2342** [comment]
see my problem is i m not getting my users in this listview
![screenshot 18](https://user-images.githubusercontent.com/30625700/29719802-5037be4e-89d5-11e7-9474-edaa035130d6.png)
![screenshot 19](https://user-images.githubusercontent.com/30625700/29719803-503da5a2-89d5-11e7-9ceb-698f919082a2.png)
![screenshot 20](https://user-images.githubusercontent.com/30625700/29719804-504054be-89d5-11e7-9cb6-4e490cb7c2b9.png)
![screenshot 21](https://user-images.githubusercontent.com/30625700/29719805-504a241c-89d5-11e7-9625-b764d06fbb34.png)

**Comment by jay2342** [comment]
here i want my register user to display in this upper photo and its showing that there is no users so help me    and i register many users but one also is not displayed

**Comment by agoransson** [comment]
F.y.i. Setting the endpoints, as @RomanPronin stated, fixed this same error for me.

**Comment by gosemathraj** [comment]
I am getting the same issue. Where to find the End Points. I checked the quickblox admin panel but did not find any.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-setup](https://docs.quickblox.com/docs/android-setup)

Also, please update the SDK to the latest version:
https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/2.17.10

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
