### ISSUE TITLE
Quickblox.Init take to much time (Android)

### ISSUE THREAD

**Issue by petergayduchik** [QuickBlox/quickblox-android-sdk#434]
Hello againe. 
I have a question and maybe you guys can show me how to avoid it.
**Platform Android:
QB sdk 3.3.4**

every time when quickblox made init phase - its take to much time.

code for init 
```
private void initQuickblox() {

        new AsyncTask<Void, Void, Void>() {

            @Override
            protected Void doInBackground(Void... voids) {
                Logger.e("init quickblox ");
                QBSettings.getInstance().init(getApplicationContext(), APP_ID, AUTH_KEY, AUTH_SECRET);
                QBSettings.getInstance().setAccountKey(ACCOUNT_KEY);
                Logger.e("quickblox init = true");
                return null;
            }
        }.execute();
    }
```

in logs i see 
` QBSettings.getInstance().init(getApplicationContext(), APP_ID, AUTH_KEY, AUTH_SECRET);`
this part make my app lagging. So i add it to asynctask. But time for operation takes from 2-3 to 4-7 seconds.  Its possible to avoid it ? make it faster ? We check Ios - there are all ok.
Regards, Peter

update : i see in coreApp same way with init 
[link to CoreApp.java
](https://github.com/QuickBlox/quickblox-android-sdk/blob/master/sample-core/src/main/java/com/quickblox/sample/core/CoreApp.java)

**Comment by petergayduchik** [comment]
no answers :( but problem still here. on Ios everything better.

**Comment by RomanPronin** [comment]
Hello, @petergayduchik, you can set ` QBSettings.getInstance().setStoringMehanism(StoringMechanism.UNSECURED);`
It will be much faster without encryption mechanism. For more info have a look at [Manage session storage](https://quickblox.com/developers/Android#Manage_session_storage)

**Comment by petergayduchik** [comment]
@RomanPronin thank you Roman. Its working.

**Comment by RomanPronin** [comment]
Resolved.
