### ISSUE TITLE
I need total unread message count in my rails app

### ISSUE THREAD

**Issue by SandipBhowmick** [QuickBlox/quickblox-android-sdk#437]
I have prepare 
function unreadMessageCount() {
  var a = QBChatService.getTotalUnreadMessagesCount(null, new QBEntityCallback<Integer>() 
    { 
      @Override public void onSuccess(Integer total, Bundle params) 
      {
        Log.i(TAG, "total unread messages: " + total);
      }

      @Override public void onError(QBResponseException responseException) 
      {}
    });
  }

method in assetes/messages.js but it shown error. Please help me with some solution or document which i can easily understood. My sysyem in Ubuntu 14.04, ruby '2.3.3' and rails '4.2.6'

I got Uncaught SyntaxError: Unexpected token ) in my browser console.

**Comment by tatanka987** [comment]
@SandipBhowmick please specify language which you use for writing and running your app (how are you run Android code in desktop browser). Provide us full log before and during getting this error.

**Comment by SandipBhowmick** [comment]
I want to get total unread message count in my rails project  rails '4.2.6' Ubuntu 14.04, ruby '2.3.3'

**Comment by SandipBhowmick** [comment]
In my project  /app/assets/javascripts/quickblox directory there are some js file named (config.js, connection.js, messages.js, ui_helpers.js etc)

**Comment by tatanka987** [comment]
looks like you need [QuickBlox JavaScript SDK](https://github.com/QuickBlox/quickblox-javascript-sdk). Error Uncaught SyntaxError: Unexpected token says about wrong syntax (maybe you use Java code in JS wrong).

**Comment by SandipBhowmick** [comment]
Thank you for the help :)
