### ISSUE TITLE
How to join a public group by group_id in Java.

### ISSUE THREAD

**Issue by iman2420** [QuickBlox/quickblox-android-sdk#439]
Hello. i want to join users in an` public group `by **group_id** in Java. How to do it?

**Comment by RomanPronin** [comment]
You don't need to add occupants to PUBLIC_GROUP dialog, because all the users from your application will be able to chat in this type dialog.

**Comment by iman2420** [comment]
Newly registered users can not view the public group. So they should be register in the group that already exists, in the background.

**Comment by RomanPronin** [comment]
Actually any users in app, also newly registered can view PUBLIC_GROUP dialog. Maybe you just need to [download dialogs](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Retrieve_dialogs) for this user again.

**Comment by iman2420** [comment]
I use this code to do it:

     `private void loadDialogsFromQb(final boolean silentUpdate, final boolean clearDialogHolder) {
        isProcessingResultInProgress = true;
        if (!silentUpdate) {
            progressBar.setVisibility(View.VISIBLE);
        }

        ChatHelper.getInstance().getDialogs(requestBuilder, new QBEntityCallback<ArrayList<QBChatDialog>>() {
            @Override
            public void onSuccess(final ArrayList<QBChatDialog> dialogs, Bundle bundle) {
                for (QBChatDialog dialog : dialogs) {
                    AppLog.Log(TAG, "loadDialogsFromQb " + dialog.getType() + " / Name: " + dialog.getName());
                }
                QBRestChatService.getChatDialogById("59a00b1fa28f9a022b6a0323").performAsync(new QBEntityCallback<QBChatDialog>() {
                    @Override
                    public void onSuccess(QBChatDialog qbChatDialog, Bundle bundle) {
                        AppLog.Log(TAG, "loadDialogsFromQb getChatDialogById " + qbChatDialog.getType());
                        qbChatDialog.setPhoto("https://qbprod.s3.amazonaws.com/uploads/large_quiz.jpg");
                        dialogs.add(qbChatDialog);
                        isProcessingResultInProgress = false;
                        progressBar.setVisibility(View.GONE);
                        setOnRefreshListener.setRefreshing(false);

                        if (clearDialogHolder) {
                            QbDialogHolder.getInstance().clear();
                        }
                        QbDialogHolder.getInstance().addDialogs(dialogs);
                        updateDialogsAdapter();
                    }

                    @Override
                    public void onError(QBResponseException e) {

                    }
                });

            }

            @Override
            public void onError(QBResponseException e) {
                isProcessingResultInProgress = false;
                progressBar.setVisibility(View.GONE);
                setOnRefreshListener.setRefreshing(false);
                Toast.makeText(DialogsActivity.this, e.getMessage(), Toast.LENGTH_SHORT).show();
            }
        });

    }`
