### ISSUE TITLE
Didn't find class "org.webrtc.Camera1Enumerator"

### ISSUE THREAD

**Issue by UneDB** [QuickBlox/quickblox-android-sdk#443]
**Logs**
[gist](https://gist.github.com/UneDB/2caf48d36db60c5e8d424e0341d7533d/)

Created a project to test quickblox, I'm getting this error on runtime.

I saw this link [https://github.com/QuickBlox/quickblox-android-sdk/issues/287](url) 
JniLibs are updated.
I didnt used for this project proguard.

Any ideas where to look?

**Comment by RomanPronin** [comment]
Hi, @UneDB. You can check you have actually Camera1Enumerator.class or not in Android Studio by Search EveryWhere. Maybe, you should clear gradle cache and restart Studio.

**Comment by UneDB** [comment]
Hi @RomanPronin. No there is no class Camera1Enumerator.class. I found only Camera2Enumerator, also i restarted studio and clered gradle cache.

**Comment by RomanPronin** [comment]
So, this could mean that you have wrong jni libs, look at our [sample](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-webrtc), you can get libs there. Or if you already did it, to make sure that this Camera1Enumerator.class is existed you can check it in videochat sample.

**Comment by UneDB** [comment]
@RomanPronin Thx for help. Solved this by changing videochat-webrtc dependecy to 3.3.1. 
In tutorial here [https://quickblox.com/developers/Sample-webrtc-android#Prepare_your_application_for_Android_SDK](url) version is 2.6.1. Please change it on website, this may confuse other users.

**Comment by RomanPronin** [comment]
Problem is solved.
