### ISSUE TITLE
Problem with Android 8.0

### ISSUE THREAD

**Issue by luisribeiro** [QuickBlox/quickblox-android-sdk#445]
Hi there,
   We're facing a problem with our app in production. When our user has a device with Android 8.0, the qb sdk throws an error that we can't handle. 

```
Fatal Exception: java.lang.IllegalStateException
Not allowed to start service Intent { cmp=****/com.quickblox.messages.services.SubscribeService (has extras) }: app is in background uid UidRecord{2a0ab34 u0a396 TRNB idle procs:1 seq(0,0,0)}
```
**Environment details**
We are using the last SDK version: 3.3.5.
Android version: 8.0

**Did this work before?**
The lower Android versions work.

**Expected behavior**
I want to avoid crashes

**Actual behavior**
The app is crashing.

**Steps to reproduce the behavior**
Just run the app and wait. The app crashes even when it's in background.

**Any others comments?**
<img width="664" alt="captura de tela 2017-09-14 as 11 44 08" src="https://user-images.githubusercontent.com/400173/30437162-50475f74-9944-11e7-8400-d30218bbd659.png">

Thank you!!

**Comment by RomanPronin** [comment]
Hi, @luisribeiro! Thanks for reporting, we will check this and fix in next releases.

**Comment by HarinTrivedi** [comment]
Same issue with me. When app moves to background/ or killed, it shows crash with java.lang.IllegalStateException on O

**Comment by PampaZiya** [comment]
@RomanPronin On which version was this fixed? Or will be fixed? 3.4 still calls:

`Intent intent = new Intent(context, SubscribeService.class);
intent.putExtra("extraSubscribe", true);
context.startService(intent);`

startService throws the IllegalStateException. Will targeting API lvl 25 for now fix the issue ?

**Comment by RomanPronin** [comment]
Hi, @PampaZiya. In current 3.4 release we don't fix this issue yet. But it will be fixed very soon. And yes, if you set your targetSdkVersion to 25 this should help to avoid crash.

**Comment by PampaZiya** [comment]
Hi, @RomanPronin. After I asked my question I found this:

https://developer.android.com/about/versions/oreo/android-8.0-changes.html

Under **Changes for all apps**, **Background execution limits**, it points out that startService will affect all devices no matter which version they target. Are you certain it will avoid the crash ? Thank you !

**Comment by RomanPronin** [comment]
From above docs: Background execution limits - By default, these restrictions only apply to apps that target O. However, users can enable these restrictions for any app from the Settings screen, even if the app has not targetted O.
I've tested app with target 25 and it's all ok. Though, there is a possibility that app can crash. I would not rely on it. @PampaZiya, do you get crash with targeting lower 26?

**Comment by PampaZiya** [comment]
@RomanPronin Targeting lower API seems to help. Thank you. Any estimate date for the fix ?

**Comment by RomanPronin** [comment]
The next version of the SDK will be released in about a month.

**Comment by sacot41** [comment]
We can't lower API in your app, because other library can't work with lower API........ 

When do you plan to release a correction ?

**Comment by tatanka987** [comment]
@sacot41  this issue was fixed in version 3.4.1, now latest version is 3.5.2, did you tested on latest version?

**Comment by sacot41** [comment]
Sorry, my bad, I check the release version number under this repo and not under "https://github.com/QuickBlox/quickblox-android-sdk-releases". 

I going to test the last release, thank you !

**Comment by g-balas** [comment]
Still a problem today....

**Comment by QuickBlox-team** [comment]
This email is confirmation that you are now registered at our helpdesk.

Registered email: reply@reply.github.com
Password: pjljrf4bbs

You can visit the helpdesk to browse articles and contact us at any time: https://assist.quickblox.com/

Thank you for registering!


QuickBlox

Helpdesk: https://assist.quickblox.com/index.php?

**Comment by g-balas** [comment]
Ok i found the solution and understood the problem.

If you use your own notification server to start the background service, be sure to send your notification in "high" priority. This will force to whitelist your app temporary and allows you to start the call service in the background.

**Comment by QuickBlox-team** [comment]
This email is confirmation that you are now registered at our helpdesk.

Registered email: reply@reply.github.com
Password: k863k41nup

You can visit the helpdesk to browse articles and contact us at any time: https://assist.quickblox.com/

Thank you for registering!


QuickBlox

Helpdesk: https://assist.quickblox.com/index.php?

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

Please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
