### ISSUE TITLE
simple video call- cant end call from from calling user unless the call is received by the called user side.

### ISSUE THREAD

**Issue by joydip1990** [QuickBlox/quickblox-android-sdk#45]
QBVideoChatController.getInstance().finishVideoChat(videoChatConfig);

This is not ending the call when call is not accepted by the user.
After the user accept the call the above code is working fine.

**Comment by soulfly** [comment]
Try our latest WebRTC Android SDK version 

 http://quickblox.com/developers/Sample-videochat-android
