### ISSUE TITLE
Unread count not coming correct when return back to listing screen from Chat Room.

### ISSUE THREAD

**Issue by githubmss** [QuickBlox/quickblox-android-sdk#453]
I am using your SDK inside my application , every thing is working fine in my application , i am getting one problem with unread count only. First time it works perfectly fine but once i get entered inside chat room and then come back to it's chat listing page my unread count starts behaving in very wired manner . 

Example :- 
i have installed my application in two devices . when i send message from one (Device A) to other (Device B).The device B will display correct Unread count i.e 1 . Now when i click on chat dialog and get entered inside the chat room (of Device B). and come back to it's listing page and then again try to send message from Device A to device B . This time the unread count comes as 2 but it should be one as i already viewed my previous message. This get more worse if i try to open my chat room again to read the message(Device B) and get back to my listing page(Device B) after reading the message . This time if i  send message from  Device A to Device B, **Then the count came out as "5" just for my one message** this thing is making me sick , i debugged the whole code , it's chatDialog.getUnreadMessageCount() who is returning me count "5" , i don't know why my previous messages are not counted as read messages and why every time i open chat room  one additional number get added up inside the unread count.Please help me out , i am scratching my head from past two days.

Please let me know where i am doing wrong in code .

SDK version using in app :- 

> compile 'com.quickblox:quickblox-android-sdk-chat:3.4'
>     compile 'com.quickblox:quickblox-android-sdk-content:3.4'
>     compile 'com.quickblox:quickblox-android-sdk-extensions:3.4'
>     compile 'com.quickblox:quickblox-android-sdk-customobjects:3.4'

Here is my complete question :-  

https://stackoverflow.com/questions/46363242/count-on-chat-does-not-working-correctly-quickblox

**Comment by tatanka987** [comment]
Did you mark messages as read on chat screen (for example in messages adapter in method onBindViewHolder when view showed for user)? Are you load dialogs again when you back to dialogs screen?  Please provide logs with loading dialogs and with marking messages as read?

**Comment by githubmss** [comment]
Hello sir , Thank you for your reply 

This is what i am doing inside my chatActivityView Model

 public void loadChatHistory() {
        ChatHelper.getInstance().loadChatHistory(qbChatDialog, skipPagination, new QBEntityCallback<ArrayList<QBChatMessage>>() {
            @Override
            public void onSuccess(ArrayList<QBChatMessage> messages, Bundle args) {
                Collections.reverse(messages);
                if (chatAdapter == null) {
                    chatAdapter = new ChatAdapter(mContext, qbChatDialog, messages);
                    chatAdapter.setPaginationHistoryListener(new PaginationHistoryListener() {
                        @Override
                        public void downloadMore() {
                            loadChatHistory();
                        }
                    });
                    chatAdapter.setOnItemInfoExpandedListener(new ChatAdapter.OnItemInfoExpandedListener() {
                        @Override
                        public void onItemInfoExpanded(final int position) {
                            if (isLastItem(position)) {
                                ((Activity) mContext).runOnUiThread(new Runnable() {
                                    @Override
                                    public void run() {
                                        binding.listChat.setSelection(position);
                                    }
                                });
                            } else {
                                binding.listChat.smoothScrollToPosition(position);
                            }
                        }

                        private boolean isLastItem(int position) {
                            return position == chatAdapter.getCount() - 1;
                        }
                    });
                    if (unShownMessages != null && !unShownMessages.isEmpty()) {
                        List<QBChatMessage> chatList = chatAdapter.getList();
                        for (QBChatMessage message : unShownMessages) {
                            if (!chatList.contains(message)) {
                                chatAdapter.add(message);
                            }
                        }
                    }
                    binding.listChat.setAdapter(chatAdapter);
                    binding.listChat.setAreHeadersSticky(false);
                    binding.listChat.setDivider(null);
                } else {
                    chatAdapter.addList(messages);
                    binding.listChat.setSelection(messages.size());
                }
                binding.progressBar.setVisibility(View.GONE);
            }

            @Override
            public void onError(QBResponseException e) {
                binding.progressBar.setVisibility(View.GONE);
                skipPagination -= ChatHelper.CHAT_HISTORY_ITEMS_PER_PAGE;
                Toast.makeText(mContext, e.toString(), Toast.LENGTH_SHORT).show();
            }
        });
        skipPagination += ChatHelper.CHAT_HISTORY_ITEMS_PER_PAGE;

        **QBRestChatService.markMessagesAsRead(qbChatDialog.getDialogId(), null);**

    }

**Comment by tatanka987** [comment]
please provide log from logCat for better understanding your issue, as I asked before

**Comment by githubmss** [comment]
**License Plate Successfully added**:-

`{"_id":"59d20eb8a0eb473264ba08e5","_parent_id":null,"carColor":"Black","carType":"BMW","created_at":1506938552,"disableQuickMessage":"NO","licenseNumber":"RADHIKA","stateName":"California ","state_code":"CA","updated_at":1506938552,"user_id":34120159,"permissions":{"read":{"access":"open"},"update":{"access":"owner"},"delete":{"access":"owner"}}}`


**Sending message to License plate GUR** :-

`{"class_name":"LicensePlates","skip":0,"limit":100,"items":[{"_id":"59d20f1da28f9a6b3760961d","_parent_id":null,"carColor":"Red","carType":"Audi","created_at":1506938653,"disableQuickMessage":"NO","licenseNumber":"GUR","stateName":"California ","state_code":"CA","updated_at":1506938653,"user_id":34120626}]}`

**People involved inside chat room** :-

`{"current_page":1,"per_page":3,"total_entries":2,"items":[{"user":{"id":34120159,"owner_id":66308,"full_name":"radhika","email":"radhika@gmail.com","login":null,"phone":null,"website":null,"created_at":"2017-10-02T09:45:40Z","updated_at":"2017-10-02T09:45:40Z","last_request_at":"2017-10-02T09:57:41Z","external_user_id":null,"facebook_id":null,"twitter_id":null,"blob_id":null,"custom_data":null,"twitter_digits_id":null,"user_tags":null}},{"user":{"id":34120626,"owner_id":66308,"full_name":"Gur","email":"gur@gmail.com","login":null,"phone":null,"website":null,"created_at":"2017-10-02T09:51:45Z","updated_at":"2017-10-02T09:51:45Z","last_request_at":"2017-10-02T09:51:46Z","external_user_id":null,"facebook_id":null,"twitter_id":null,"blob_id":null,"custom_data":null,"twitter_digits_id":null,"user_tags":null}}]}`

**When I Open The Chat Room** :-

> 10-02 15:41:42.837 30553-30553/com.mss.backup D/QBASDK: *********************************************************
>                                                         *** RESPONSE *** f16d8355-91f4-4b62-8852-d67053953c2c ***
>                                                         STATUS : 200 
>                                                         HEADERS
>                                                             X-Runtime=0.040425
>                                                             Cache-Control=max-age=0, private, must-revalidate
>                                                             QuickBlox-REST-API-Version=0.1.1
>                                                             X-Android-Selected-Protocol=http/1.1
>                                                             Set-Cookie=_mkra_ctxt=09531b84a45a9b1d49f680c1ab7d1963--200; path=/; max-age=5; HttpOnly; secure
>                                                             QB-Token-ExpirationDate=2017-10-02 11:57:41 +0000
>                                                             Status=200 OK
>                                                             X-Request-Id=b684e754-ab54-47a4-b6ea-ed28d0086197
>                                                             X-Android-Response-Source=NETWORK 200
>                                                             Connection=Close
>                                                             X-Android-Sent-Millis=1506939102405
>                                                             Content-Type=application/json; charset=utf-8
>                                                             Date=Mon, 02 Oct 2017 10:11:45 GMT
>                                                             X-Content-Type-Options=nosniff
>                                                             Server=openresty/1.9.15.1
>                                                             ETag=W/"8d8ee8b26885250646b211294fa59109"
>                                                             Content-Length=1041
>                                                             Strict-Transport-Security=max-age=31536000max-age=15768000;
>                                                             X-XSS-Protection=1; mode=block
>                                                             X-Frame-Options=SAMEORIGIN
>                                                             X-Android-Received-Millis=1506939102834
>                                                             Access-Control-Allow-Origin=*
>                                                         BODY
> 

                                                            `'{"skip":0,"limit":50,"items":[{"_id":"59d210caff8ef9f2156de47d","attachments":[],"chat_dialog_id":"59d21039a28f9a69846096ed","created_at":"2017-10-02T10:11:22Z","date_sent":1506939082,"delivered_ids":[34120626,34120159],"message":"Hello","read_ids":[34120626],"recipient_id":34120159,"sender_id":34120626,"updated_at":"2017-10-02T10:11:23Z","read":1},{"_id":"59d210acff8ef9f2156de47a","attachments":[],"chat_dialog_id":"59d21039a28f9a69846096ed","created_at":"2017-10-02T10:10:53Z","date_sent":1506939052,"delivered_ids":[34120626,34120159],"message":"Hii","read_ids":[34120626],"recipient_id":34120159,"sender_id":34120626,"updated_at":"2017-10-02T10:10:53Z","read":1},{"_id":"59d21037ac2bc966001e9585","attachments":[],"chat_dialog_id":"59d21039a28f9a69846096ed","created_at":"2017-10-02T10:08:58Z","date_sent":1506938935,"delivered_ids":[34120159,34120626],"message":"You are parked in my spot im going to tow you","read_ids":[34120159,34120626],"recipient_id":34120626,"sender_id":34120159,"updated_at":"2017-10-02T10:11:24Z","read":1}]}'`




> 10-02 15:41:44.491 30553-30553/com.mss.backup D/QBASDK: *********************************************************
>                                                         *** RESPONSE *** 708f0e97-2a52-44be-9573-3e521333c966 ***
>                                                         STATUS : 200 
>                                                        
>                                                         BODY

                                                            `'{"current_page":1,"per_page":2,"total_entries":2,"items":[{"user":{"id":34120159,"owner_id":66308,"full_name":"radhika","email":"radhika@gmail.com","login":null,"phone":null,"website":null,"created_at":"2017-10-02T09:45:40Z","updated_at":"2017-10-02T09:45:40Z","last_request_at":"2017-10-02T09:57:41Z","external_user_id":null,"facebook_id":null,"twitter_id":null,"blob_id":null,"custom_data":null,"twitter_digits_id":null,"user_tags":null}},{"user":{"id":34120626,"owner_id":66308,"full_name":"Gur","email":"gur@gmail.com","login":null,"phone":null,"website":null,"created_at":"2017-10-02T09:51:45Z","updated_at":"2017-10-02T10:10:33Z","last_request_at":"2017-10-02T10:10:33Z","external_user_id":null,"facebook_id":null,"twitter_id":null,"blob_id":null,"custom_data":null,"twitter_digits_id":null,"user_tags":null}}]}'`


10-02 15:41:46.120 30553-30553/com.mss.backup D/QBASDK: *********************************************************
                                                        *** RESPONSE *** 2fae7913-3433-44f6-83dc-99dfbf5b1bb5 ***
                                                        STATUS : 200 
                                                      
                                                        BODY
                                                            '{"skip":50,"limit":50,"items":[]}'



**Got this when i come back to me chat listing page** :-

> 10-02 15:44:54.844 30553-30553/com.mss.backup D/QBASDK: *********************************************************
>                                                         *** RESPONSE *** d5585244-e0c5-41d0-9f56-b3b7e66f4a1e ***
>                                                         STATUS : 200 
> 
>                                                        
>                                                         BODY

                                                           ` '{"total_entries":1,"skip":0,"limit":100,"items":[{"_id":"59d21039a28f9a69846096ed","created_at":"2017-10-02T10:08:57Z","last_message":"Hello","last_message_date_sent":1506939082,"last_message_user_id":34120626,"name":"Gur","occupants_ids":[34120159,34120626],"photo":null,"type":3,"updated_at":"2017-10-02T10:11:22Z","user_id":34120159,"xmpp_room_jid":null,"unread_messages_count":0}]}'`


> 10-02 15:44:54.859 30553-30553/com.mss.backup D/QBASDK: =========================================================
>                                                         === REQUEST ==== be4dd804-1d5f-468c-90d8-c4fce4149f36 ===
>                                                         REQUEST
>                                                             GET https://api.quickblox.com/users.json
>                                                         HEADERS
>                                                             QuickBlox-REST-API-Version=0.1.1
>                                                             QB-SDK=Android 3.3.1
>                                                             QB-Token=c3e8c143e54915b230d104db26e64d33b600cdd0
>                                                         PARAMETERS
>                                                             page=1
>                                                             per_page=3
>                                                             filter[]=number id in 34120159,34120626,34120626
>                                                         INLINE
>                                                             GET https://api.quickblox.com/users.json?page=1&per_page=3&filter[]=number+id+in+34120159%2C34120626%2C34120626
> 10-02 15:44:54.862 30553-30553/com.mss.backup D/QBASDK: *********************************************************
>                                                         *** RESPONSE *** 312d5342-22e9-4318-b39d-590f3c7f0f2a ***
>                                                         STATUS : 200 
>                                                     
>                                                         BODY

                                                            `'{"total_entries":1,"skip":0,"limit":100,"items":[{"_id":"59d21039a28f9a69846096ed","created_at":"2017-10-02T10:08:57Z","last_message":"Hello","last_message_date_sent":1506939082,"last_message_user_id":34120626,"name":"Gur","occupants_ids":[34120159,34120626],"photo":null,"type":3,"updated_at":"2017-10-02T10:11:22Z","user_id":34120159,"xmpp_room_jid":null,"unread_messages_count":0}]}'`


```
10-02 15:44:54.876 30553-30553/com.mss.backup D/QBASDK: =========================================================
                                                        === REQUEST ==== 2cc99193-5ac1-466d-ad95-02f397f9e383 ===
                                                        REQUEST
                                                            GET https://api.quickblox.com/users.json
                                                        HEADERS
                                                            QuickBlox-REST-API-Version=0.1.1
                                                            QB-SDK=Android 3.3.1
                                                            QB-Token=c3e8c143e54915b230d104db26e64d33b600cdd0
                                                        PARAMETERS
                                                            page=1
                                                            per_page=3
                                                            filter[]=number id in 34120159,34120626,34120626
                                                        INLINE
                                                            GET https://api.quickblox.com/users.json?page=1&per_page=3&filter[]=number+id+in+34120159%2C34120626%2C34120626
10-02 15:44:56.241 199-815/? D/audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback
10-02 15:44:56.242 199-815/? D/audio_hw_primary: disable_snd_device: snd_device(2: speaker)
10-02 15:44:56.495 30553-30553/com.mss.backup D/QBASDK: *********************************************************
                                                        *** RESPONSE *** 2cc99193-5ac1-466d-ad95-02f397f9e383 ***
                                                        STATUS : 200 
```
                                                        
                                                        BODY
                                                           ` '{"current_page":1,"per_page":3,"total_entries":2,"items":[{"user":{"id":34120159,"owner_id":66308,"full_name":"radhika","email":"radhika@gmail.com","login":null,"phone":null,"website":null,"created_at":"2017-10-02T09:45:40Z","updated_at":"2017-10-02T10:14:57Z","last_request_at":"2017-10-02T10:14:57Z","external_user_id":null,"facebook_id":null,"twitter_id":null,"blob_id":null,"custom_data":null,"twitter_digits_id":null,"user_tags":null}},{"user":{"id":34120626,"owner_id":66308,"full_name":"Gur","email":"gur@gmail.com","login":null,"phone":null,"website":null,"created_at":"2017-10-02T09:51:45Z","updated_at":"2017-10-02T10:10:33Z","last_request_at":"2017-10-02T10:10:33Z","external_user_id":null,"facebook_id":null,"twitter_id":null,"blob_id":null,"custom_data":null,"twitter_digits_id":null,"user_tags":null}}]}'`

**Comment by githubmss** [comment]
Issue Solved , I Problem was with unregisterQbChatListeners(); call 
So i just put it under 

```
binding.listDialogsChats.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                QBChatDialog selectedDialog = (QBChatDialog) parent.getItemAtPosition(position);
                if (currentActionMode == null) {
                    unregisterQbChatListeners();
                    ChatActivity.startForResult(((Activity) mContext), REQUEST_DIALOG_ID_FOR_UPDATE, selectedDialog);
                } else {
                    dialogsAdapter.toggleSelection(selectedDialog);
                }
            }
        });
```

This solves my problem.
