### ISSUE TITLE
Multiple errors when running sample-videochat-webrtc

### ISSUE THREAD

**Issue by atiberius** [QuickBlox/quickblox-android-sdk#457]
I am trying to run the sample-videochat-webrtc from quickblox sdk version "3.4", as per instructions from https://github.com/QuickBlox/quickblox-android-sdk/blob/master/README.md
on a OnePlus One with Android 6.0, but I am receiving many errors.

"Error:(68, 8) error: CallActivity is not abstract and does not override abstract method onConnectionClosedForUser(BaseSession,Integer) in QBRTCSessionStateCallback" for CallActivity.

Steps to reproduce:
1. git clone https://github.com/QuickBlox/quickblox-android-sdk
2. Android Studio 2.3.3: New > Import Project > ... quickblox-android-sdk
3. edit values on sample-videochat-webrtc/assets/qb_config.json
4. wait to build, build successful
5. select target sample-videochat-webrtc, click Run

These errors appear:

Information:Gradle tasks [:sample-videochat-webrtc:assembleDevDebug]
/Users/.../quickblox-android-sdk/sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/activities/CallActivity.java
Error:(68, 8) error: CallActivity is not abstract and does not override abstract method onConnectionClosedForUser(BaseSession,Integer) in QBRTCSessionStateCallback
Error:(309, 18) error: cannot find symbol method setCameraErrorHendler(<anonymous CameraEventsHandler>)
Error:(543, 5) error: method does not override or implement a method from a supertype
Error:(553, 5) error: method does not override or implement a method from a supertype
Error:(590, 5) error: method does not override or implement a method from a supertype
/.../quickblox-android-sdk/sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/fragments/BaseConversationFragment.java
Error:(143, 72) error: cannot find symbol variable QB_RTC_SESSION_ACTIVE
/.../quickblox-android-sdk/sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/fragments/VideoConversationFragment.java
Error:(63, 8) error: VideoConversationFragment is not abstract and does not override abstract method onRemoteVideoTrackReceive(BaseSession,QBRTCVideoTrack,Integer) in QBRTCClientVideoTracksCallbacks
Error:(246, 72) error: cannot find symbol variable QB_RTC_SESSION_ACTIVE
Error:(470, 5) error: method does not override or implement a method from a supertype
Error:(483, 5) error: method does not override or implement a method from a supertype
Error:(736, 5) error: method does not override or implement a method from a supertype
Error:(743, 5) error: method does not override or implement a method from a supertype
Error:(753, 5) error: method does not override or implement a method from a supertype
Error:Execution failed for task ':sample-videochat-webrtc:compileDevDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by huynx** [comment]
I change dependencies of sample-videochat-webrtc to:
compile "com.quickblox:quickblox-android-sdk-videochat-webrtc:3.3.0"

build success

**Comment by RomanPronin** [comment]
Hello, there! We've updated samples to sdk version 3.4. So, it works fine now.

**Comment by atiberius** [comment]
Now it worked. Thanks a lot!
