### ISSUE TITLE
Incoming Message Receiver from any user - Quickblox android sdk

### ISSUE THREAD

**Issue by vandanaagile** [QuickBlox/quickblox-android-sdk#46]
Hi , 
I am getting messages when i am in chat dialog , How can i get incoming messages from any user in case of whenever i am in the application , 
I would like to notify app user that you have received a new message . 
Please let me know

**Comment by rishabhtech1994** [comment]
Hi @vandanaagile. Can you please help me with this issue. How have you solved this issue. A small help would be appreciated.

Thank you
