### ISSUE TITLE
Unable to set group dialog photo to empty.

### ISSUE THREAD

**Issue by diaz9557** [QuickBlox/quickblox-android-sdk#460]
I am using Qb Sdk 3.3.1 . Everything working fine . When i am updating Group dialog photo to blank or null its not updating . But Updating new photo with url works well . It's not accepting a blank String so how i will remove the group icon. In my chat module there is option to remove Group dialog image. I have Updated the the dialog using SDK and using Api as well but both are resulting same . Please resolve this Issue.

**Comment by RomanPronin** [comment]
Hi, @diaz9557. For now, you can't set blank String to photo field to update dialog. We can offer the next: you can set photo field, let's say, as "empty" and check it or you can set url with image stub instead of unwanted image.

**Comment by diaz9557** [comment]
Yeah Thats what i am doing . But Don't you think it should accept the blank. Thx for quick reply. Closing the issue .
