### ISSUE TITLE
How to update Quickblox SDK in my Current Project? A lot of Conflicts occurring 

### ISSUE THREAD

**Issue by sheikhrashid** [QuickBlox/quickblox-android-sdk#468]
I have my client's Project with **Quickblox SDK version 2.2.5**. Now I want to update the **SDK with version 3.4**. I am using .jar Libraries in Android Studio Project.

I removed the **2.2.5** libraries and added **3.4** libraries successfully.The problem is after adding 3.4, a lot of conflicts occur in the whole Project.

**For Example:**
- in SDK 2.2.5 (there is QBDialog class)
- but in SDK 3.4 (it is named with QBChatDialog)

I was thinking after adding 3.4, all the classes would be updated according to 3.4. But it is not happening.

**Comment by tatanka987** [comment]
Below presented main differences 2.x and 3.x versions:
Chat.
In new version to work with chat you only need to download dialog, previously there were additional managers for these purposes
https://quickblox.com/developers/Android_XMPP_Chat_Sample#Chatting_in_dialog
In case you take dialog from local storage you need to init it first to be able to use chat functions. In new versions you can set one listener for all dialogs:  https://quickblox.com/developers/Android_XMPP_Chat_Sample#Receiving_incoming_messages
Such functionality is not available in old versions

Session management.
 https://quickblox.com/developers/Android#SDK_3.2.0_Authentication
There is no need to manage session manually now - after previous session is ended new one is created automatically with the parameters of old one. 

Push notification auto subscription
By default it is enabled, however you can disable it if you wish
https://quickblox.com/developers/SimpleSample-messages_users-android#Setup_Push_Notifications_SDK_3.2_-_Auto_subscription

Calls.
Updated jni-libs, which can be downloaded from https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-webrtc/src/main/jniLibs

Some helpful links:
https://quickblox.com/developers/Android#Android_SDK_Transition_guide_from_version_2.x_to_3.0_version
https://quickblox.com/developers/Android#SDK_3.2.0_Authentication
https://quickblox.com/developers/Android#QuickBlox_android_SDK_and_Rxjava.2FRxAndroid

**Comment by sheikhrashid** [comment]
I need to know, how can I update my current project with the latest SDK?

**Comment by tatanka987** [comment]
Usually update from 2.x to 3.x version is major update. And only you know your project and used functions. I provided some helpful information to help you search solution for your issue.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

Please check the latest version of the SDK:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
