### ISSUE TITLE
Unable to get push notification

### ISSUE THREAD

**Issue by Sharanjeet** [QuickBlox/quickblox-android-sdk#472]
Whenever i am trying to send the message from one user to another, then i am unable to get the push notification.
Getting error:
QBASDK: Can't parse the 'date_sent' value null: Invalid double: "null"

**Comment by Sharanjeet** [comment]
QBASDK: Can't parse the 'date_sent' value null: Invalid double: "null"

**Comment by naguchennai** [comment]
QBASDK: Can't parse the 'date_sent' value null: Invalid double: "null"\
same error

**Comment by RomanPronin** [comment]
Hi, guys. "Can't parse the 'date_sent' value null: Invalid double: "null""  is a debug log, and it doesn't affect to sending or receiving messages. This is not an error at all.

**Comment by alexanderkoqb** [comment]
Sup @Sharanjeet 
Closing the ticket as old and non-relevant.
In case of troubles you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
