### ISSUE TITLE
Unexpected Signature

### ISSUE THREAD

**Issue by aces2808** [QuickBlox/quickblox-android-sdk#473]
Hi,

I'm currently using a different approach in integrating to QB, I have an API gateway to control the sequence of all of my request, currently I was able to create a session token with the following the example:

HMAC-SHA
application_id=22&auth_key=wJHd4cQSxpQGWx5&nonce=33432&timestamp=1326966962

As for the user token, I followed the format
application_id=22&auth_key=wJHd4cQSxpQGWx5&nonce=33432&timestamp=1326966962&user[login]=amigo30&user[password]=amigo30pass

And I keep on getting the unexpected signature. I'm using java

here is the sequence I made:

User endpoint : https://[url]/session.json
application_id=X&auth_key=XXXXXXXX&nonce=70513&timestamp=1509694081&user[login]=User1&user[password]=pass1&signature=530d1bc856dc436482cc90ece7309cde4678e1ea
{Content-Type=[application/json], QuickBlox-REST-API-Version=[0.1.1]}
{"application_id":"X","auth_key":"XXXXXXXX","timestamp":"1509694081","nonce":"57475","signature":"530d1bc856dc436482cc90ece7309cde4678e1ea","user":{"login":"User1","password":"pass1"}}
{"errors":{"base":["Unexpected signature"]}}

Do I have to encode the parameters for user and password?

**Comment by tatanka987** [comment]
Yes, you should encode all parameters. What string do you use for generation signature? Additionally check timestamp parameter (time and time zone should be correct).

**Comment by alexanderkoqb** [comment]
Whatup @aces2808 
Since it's been a while and no answer was provided so far the ticket is being closed.
You can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
