### ISSUE TITLE
Connection closed due to inactivity server

### ISSUE THREAD

**Issue by naguchennai** [QuickBlox/quickblox-android-sdk#474]
Android sdk-chat:3.4.1 . Following code not work its keep disconection 

`      QBChatService.setDebugEnabled(true); // enable chat logging
        QBChatService.setDefaultPacketReplyTimeout(10000);
        QBChatService.ConfigurationBuilder chatServiceConfigurationBuilder = new QBChatService.ConfigurationBuilder();
        chatServiceConfigurationBuilder.setSocketTimeout(6000000); //Sets chat socket's read timeout in seconds
        chatServiceConfigurationBuilder.setKeepAlive(true); //Sets connection socket's keepAlive option.
        chatServiceConfigurationBuilder.setUseTls(true); //Sets the TLS security mode used when making the connection. By default TLS is disabled.
        QBChatService.setConfigurationBuilder(chatServiceConfigurationBuilder);`

So after my all work quickblox use less SDK?

**Comment by Sharanjeet** [comment]
Thanks for the reply. Now what should i have to do now...As i am stuck in
between.

**Comment by RomanPronin** [comment]
@naguchennai, try to set QBChatService.setDefaultConnectionTimeout(0); // 0 - means connection won't be disconnected.

**Comment by naguchennai** [comment]
Same error
W/AbstractXMPPConnection: Connection closed due to inactivity server\
when send mesg 
 D/QBASDK: Can't parse the 'date_sent' value null: Invalid double: "null"

**Comment by histone** [comment]
I have found the same issue:
W/AbstractXMPPConnection: Connection closed due to inactivity server
Can you help?

**Comment by alexanderkoqb** [comment]
Hey @naguchennai 
Since it's been a while and if you're still being experiencing analogous troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
