### ISSUE TITLE
UserInfo is null over a session

### ISSUE THREAD

**Issue by somyatuteja** [QuickBlox/quickblox-android-sdk#475]
I am using the quickblox for Android 23 API . I want to include user info from one caller to another, just before the call is established. 
For that I have used the 'userinfo' part of QBRTCSession and put in a key value pair. But for the other end, its giving  null value for 'userinfo'. Could anyone please suggest the possible reason and suggest a solution?

The session id is same in both the calls.

**Comment by RomanPronin** [comment]
What version Quickblox Android SDK do you use? In the latest versions of the SDK, it works fine.

**Comment by somyatuteja** [comment]
Hey, i am using the version 3.3.1

**Comment by RomanPronin** [comment]
@somyatuteja, you should set UserInfo when do currentSession.startCall(userInfo). (in sample BaseConversationFragment class)

**Comment by alexanderkoqb** [comment]
Whatup @somyatuteja 
Since it's been a while and no answer was provided so far the ticket is being closed.
You can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
