### ISSUE TITLE
How to get user avatar image in messages or when calling.

### ISSUE THREAD

**Issue by petergayduchik** [QuickBlox/quickblox-android-sdk#477]
Not issue, but question.
Hi guys, im trying to get user avatar image but i cant understand how to do this.
Its possible to get avatar img by user id if i know ? 
Or its should configuring some how from backend panel ? Cant find anything :(

**Comment by RomanPronin** [comment]
Hi, as an option, you can load user avatar using content just like [here](https://quickblox.com/developers/SimpleSample-users-android#Update_profile_picture_.28avatar.29).
Or you can storage url with avatar in QBUser custom data: `qbUser.setCustomData(qbFile.getPublicUrl());`
