### ISSUE TITLE
How to get QBRTCAudioTrack buffer

### ISSUE THREAD

**Issue by jwzhuang** [QuickBlox/quickblox-android-sdk#478]
I want to draw waveform.
How can I get remote QBRTCAudioTrack buffer in android?

**Comment by RomanPronin** [comment]
Hi, @jwzhuang. For this purpose, you can use [WebRTC Stats reporting](https://quickblox.com/developers/Sample-webrtc-android#WebRTC_Stats_reporting).

**Comment by jwzhuang** [comment]
@RomanPronin I have tried QBRTCStatsReport, but not work.
onStatsReportUpdate not called

**Comment by jwzhuang** [comment]
Thank you @RomanPronin , I got it.
