### ISSUE TITLE
how to retrieve only contacts that are using quickblox?

### ISSUE THREAD

**Issue by el-gabry** [QuickBlox/quickblox-android-sdk#479]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by tatanka987** [comment]
You need collect all phone numbers and request users from QB server by they. As example you can see this [test branch ](https://github.com/QuickBlox/q-municate-android/blob/feature/QMUN-2037/Q-municate_app/src/main/java/com/quickblox/q_municate/utils/helpers/FriendListServiceManager.java#L71). But pay attention, this is not released branch and it can contain some bugs.

**Comment by alexanderkoqb** [comment]
Whatup @el-gabry 
Since it's been a while and no answer was provided so far the ticket is being closed.
You can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
