### ISSUE TITLE
Online status in Private chat Dialog

### ISSUE THREAD

**Issue by diaz9557** [QuickBlox/quickblox-android-sdk#480]
I am using Quick Blox android Sdk for Chat application . There are 3 types of Dilogs private, public group and private group. The problem is i can not find any solution to get online status of Opponent in Private Dialog.

QBRoster class is responsible for online/offline status of users . but Its not working for private dialog.  Please provide a solution for this problem,

**Comment by RomanPronin** [comment]
@diaz9557, you can use [LastActivity](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Last_activity) feature - 0 if user is online.

**Comment by diaz9557** [comment]
`long lastUserActivity = QBChatService.getInstance().getLastUserActivity(targetUser.getId())`

getLastUserActivity() method is not available .
I am using V 3.3.1.

**Comment by RomanPronin** [comment]
This feature was added in version 3.3.3. So, update it.

**Comment by diaz9557** [comment]
Ok I have Tried the method you have mentioned. And below is the output -
1. When Opponent is Login and currently chatting
onlineStatusPrivateChat: 3
onlineStatusPrivateChat: 4
2. When Opponent is Log Out .
onlineStatusPrivateChat: 3034
onlineStatusPrivateChat: 3035

As you said 0 value indicate online , well i am never getting 0 . For me its making sense as the numbers are miliseconds . I am using a Background service to maintain session which suppose to run in background all of the time . So  even i am not using app getLastUserActivity(23789) returning me the last activity below 100. 
still the problem remains as it is . In this case the Opponent will be visible Online for all time . Do you have any suggestion on that? Thx

**Comment by RomanPronin** [comment]
I've just checked getLastUserActivity(), and I've got value 0 for online user.
If user is logged in Chat (chatService.isLoggedIn()), he is online. So, as an option, if this user is not in chat window, do chatService.logout().
And you can use groupChatDialog with only two occupants to make successful requestOnlineUsers().
As for [QBRoster](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Contact_list), with QBRosterListener you can listen changing of the presence of a user (user becomes online/offline).

**Comment by alexanderkoqb** [comment]
Whatup @diaz9557 
Since it's been a while and no more comments concerning the matter were provided so far, thus the issue is being closed.
You can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
