### ISSUE TITLE
Getting group list 

### ISSUE THREAD

**Issue by firojandev** [QuickBlox/quickblox-android-sdk#481]
Hello,

I am using quickblox android SDK 3.3.5.  I want to display group list what is created by me and in which group I joined. 

So, How can I get group list ?

Please help.

**Comment by firojandev** [comment]
Solution found from Quickblox documentation 
--------------------------------------------------------------
QBRequestGetBuilder qbRequestGetBuilder = new QBRequestGetBuilder();
        qbRequestGetBuilder.setLimit(100);
        QBRestChatService.getChatDialogs(null, qbRequestGetBuilder).performAsync(
                new QBEntityCallback<ArrayList<QBChatDialog>>() {
                    @Override
                    public void onSuccess(ArrayList<QBChatDialog> result, Bundle params) {
                       
                        for (QBChatDialog qbChatDialog:result){
                            if (qbChatDialog.getType().toString().equals("GROUP")){
                               // do here
                            }
                        }

                 
                        //notify adapter
                        groupsListAdapter.updateData(groupsList);

                    }

                    @Override
                    public void onError(QBResponseException responseException) {
                        Glog.logMsg("QBResponseException","error:"+responseException.toString());
                    }
                });

**Comment by diaz9557** [comment]
If your problem is resolved the pls close the issue

**Comment by tatanka987** [comment]
QuickBlox API don't have ability for getting dialogs by "uaser_id", more detail about filters [there](https://quickblox.com/developers/Chat#Retrieve_dialogs).
