### ISSUE TITLE
Last message sent not getting deleted from API QBRestChatService.getChatDialogs

### ISSUE THREAD

**Issue by karan23** [QuickBlox/quickblox-android-sdk#484]
I am making an app in which I have integerated QuickBlox. When we delete the last message from the chat and then calling API QBRestChatService.getChatDialogs still showing last message sent as the deleted message in qbDialog. how can I handle this?

**Comment by tatanka987** [comment]
If you delete message with parameter force=true, it message will deleted fully and field 'last_message' of dialog will updated, if you delete message with parameter force=false, it message will deleted only for current user and field 'last_message' of dialog won't be updated.

**Comment by alexanderkoqb** [comment]
Whatup @karan23 
Since it's been a while and no more comments concerning the matter were provided so far, thus the issue is being closed.
You can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
