### ISSUE TITLE
Bluetooth support for QB android?

### ISSUE THREAD

**Issue by dhaval-zaptech** [QuickBlox/quickblox-android-sdk#485]
New Query

Does QB android sdk supports Bluetooth audio devices???
I have tried with the latest version till date 3.5.0, but with no success.

When can this support be available for android sdk?
for iOS sdk it was back in march 2016 update ver 2.2
https://quickblox.com/blog/ios-webrtc-video-chat-sdk-2-2-with-bluetooth-support/

Till then is there any workaround to achieve this functionality?

Thanks in advance...!!!

**Comment by RomanPronin** [comment]
Hi, @dhaval-zaptech! We haven't yet added bluetooth support to SDK. But you can find all you need in this test [sample branch](https://github.com/QuickBlox/quickblox-android-sdk/tree/feature/QBANDRSDK-Bluetooth).

**Comment by alexanderkoqb** [comment]
Hi @dhaval-zaptech 
Let me know whether this information is still relevant.

**Comment by vadimkhmyrovqb** [comment]
@dhaval-zaptech Hi, to use Bluetooth functionality, please use solution from this commit: 

https://github.com/QuickBlox/quickblox-android-sdk/commit/0bf433d5f477a9cc3800ac1c8c24cb87d2653ed1
