### ISSUE TITLE
OnHangUpSend on IOS

### ISSUE THREAD

**Issue by petergayduchik** [QuickBlox/quickblox-android-sdk#486]
Hi Guys, its not issue , question 
i found from android side method 
session.onHangUpSend(peerConection)
Main thing its after group call - one dude pick up and we want stop calling to other guys.
For android this method work very good
But we cant found something for IOS. Can u guys help  ?

**Comment by RomanPronin** [comment]
@petergayduchik , you better create a issue on [IOS tracker](https://github.com/QuickBlox/quickblox-ios-sdk/issues)

**Comment by alexanderkoqb** [comment]
Hey @petergayduchik 
Closing the ticket as not having any relation to Android.
Best!
