### ISSUE TITLE
Android : Fatal Signal Exception 6 and 11 at Video call

### ISSUE THREAD

**Issue by iosgnanavel** [QuickBlox/quickblox-android-sdk#487]
**libc: Fatal signal 6 (SIGABRT) at 0x00007fdf (code=-6), thread 8172 (signaling_threa)**
**libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 15605 (signaling_threa)**

**This Exception occurs at the user in  video calling when the user goes background and come again means app crashing.**
 **# Note:** Logs show above two errors

**Comment by tatanka987** [comment]
this crash reproduces on our sample? please provide more information about this issue: full log, detail steps to reproduce, info about devices, on which you tested, etc.

**Comment by alexanderkoqb** [comment]
Hey @iosgnanavel 
Since it's been a while and if you're still being experiencing analogous troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
