### ISSUE TITLE
Queue message on client 

### ISSUE THREAD

**Issue by sannysinghs** [QuickBlox/quickblox-android-sdk#488]
Is there a way to queue message when dialog is not joined or connected to quickblox. So far i have done the similar queue mechanism on my end and send all queue message once dialog is rejoined. I am curious is there built in support to improve my current implementation . Thanks

**Comment by tatanka987** [comment]
QuickBlox Android SDK doesn't have functionality for delayed sending messages.

**Comment by alexanderkoqb** [comment]
Hey @sannysinghs 

Closing the issue as solved.
