### ISSUE TITLE
About QBRoster RosterLoadedListener

### ISSUE THREAD

**Issue by jwzhuang** [QuickBlox/quickblox-android-sdk#490]
I find Roster have addRosterLoadedListener method
but can not set RosterLoadedListener with QBRoster

**Comment by tatanka987** [comment]
Why do you need this listener? What functionality do you want to get?

**Comment by jwzhuang** [comment]
QBRoster.getEntries()

If before loaded call QBRoster.getEntries() will get empty list, i need know when to call QBRoster.getEntries()

**Comment by alexanderkoqb** [comment]
Sup @jwzhuang 
Still relevant?
