### ISSUE TITLE
SampleChat: Group dialog not updating (Last message and unread message count) on DilogsActivity

### ISSUE THREAD

**Issue by Shahjahan786** [QuickBlox/quickblox-android-sdk#491]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*
Android 8.1

**Did this work before?**
Yes some time it works but mostly AllDialogsMessageListener.processMessage method is not called.
This happened with only group dialog.

**Expected behavior**
Group dialog should be updated like private dialog

**Actual behavior**

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**
Group dialog not updating (Last message and unread message count) on DilogsActivity

**Any others comments?**

**Comment by kishorejethava** [comment]
Same issue. Is there any solution?

**Comment by tatanka987** [comment]
@kishorejethava  did you do any changes in sample?

**Comment by kishorejethava** [comment]
Resolved!!
comment this line
` chatDialog.leave()`
Don't leave the group when you leave the chat screen.

**Comment by RomanPronin** [comment]
Seems resolved now, so can be closed.
