### ISSUE TITLE
Not getting message read callback 

### ISSUE THREAD

**Issue by diaz9557** [QuickBlox/quickblox-android-sdk#493]
Hi guys ,
       I am using quickblox sdk with following dependencies . Problem is i am not getting status of read message at the send end . And when i reload chat the message is already read . but i first place callback not getting fire.

` compile 'com.quickblox:quickblox-android-sdk-videochat-webrtc:3.3.3@aar'
    compile 'com.quickblox:quickblox-android-sdk-content:3.3.3@aar'
    compile('com.quickblox:quickblox-android-sdk-chat:3.3.3@aar') {
        transitive = true
    }`

Chatmessage is markable already .
`chatMessage.setMarkable(true);`

`messageStatusListener=new QBMessageStatusListener() {
            @Override
            public void processMessageDelivered(String messageId, String dialogId, Integer userId) {
              // Getting called on delivery
            }

            @Override
            public void processMessageRead(String messageId, String dialogId, Integer userId) {
                // Not Getting called on delivery
            }
        };`

On the receiver end i am sending the Read status to sender .

`public void markMessageRead(String dialogId, String messageId) {

        StringifyArrayList<String> messagesIDs = new StringifyArrayList<>();

        messagesIDs.add(messageId);

        QBRestChatService.markMessagesAsRead(dialogId, messagesIDs).performAsync(new 
QBEntityCallback<Void>() {

            @Override
            public void onSuccess(Void aVoid, Bundle bundle) {
                Log.e("Message","Read");
            }

            @Override
            public void onError(QBResponseException e) {

                Log.e("Message","Read failure");

            }

        });
    }`

markMessageRead runs with success but i am not getting callback on sender end . Please let me know whats the issue ?

**Comment by tatanka987** [comment]
it is expected behavior, you mark messages as read via REST, in this case server doesn't sent notification to sender, you should mark messages as read via CHAT for notify sender about reading, for it use:
```
QBChatDialog chatDialog = ...;
QBChatMessage chatMessage = ...;
                    
chatDialog.readMessage(chatMessage);
```

**Comment by diaz9557** [comment]
Thx . I have one more question .
`chatDialog.readMessage(chatMessage);`

Is this a asynchronous call or we have to call it asynchronously(On a new thread).

**Comment by tatanka987** [comment]
you can use asynchronous variant of this method chatDialog.readMessage(chatMessage, callback);

**Comment by diaz9557** [comment]
Thx for your support .Closing the issue now .
