### ISSUE TITLE
File Uploading issue :  W/System.err: java.net.SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by Shahjahan786** [QuickBlox/quickblox-android-sdk#499]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*
Android 8.1

**Did this work before?**
Some time files are uploading sometime raise exception

**Expected behavior**
File should upload successfully

**Actual behavior**
Some time files are uploading sometime raise exception W/System.err: java.net.SocketTimeoutException: timeout
**Logs**
*(please, use github [gist](https://gist.github®.com/))*

https://gist.github.com/Shahjahan786/00739c428362e500be099ce82b4b25d3
**Steps to reproduce the behavior**

**Any others comments?**

**Comment by RomanPronin** [comment]
Hi @Shahjahan786. Try to increase connect and read timeouts:
`      QBHttpConnectionConfig.setConnectTimeout(60*1000);` 
 `     QBHttpConnectionConfig.setReadTimeout(60*1000);`
