### ISSUE TITLE
Unread messages count issue:

### ISSUE THREAD

**Issue by Shahjahan786** [QuickBlox/quickblox-android-sdk#503]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*
Android 8.1

**Did this work before?**
No

**Expected behavior**
When I open chat window unread message count for dialog should be zero.

**Actual behavior**

Unread messages count issue when there are more than 99 unread messages count,
after opening chat window and coming back to dialogs window unread message count remains 78 always 

**Logs**
*(please, use github [gist](https://gist.github.com/))*
https://gist.github.com/Shahjahan786/e713ed0a17a82b2396be782169fc9502

**Steps to reproduce the behavior**
1. Open dialogs activity on device 1 with user1
2. open chat window for user1 on device2 with user2, 
3. send more than 99 messages. on device1 it will show all unread message count correctly for user2. 4 user1 opens chat window (user2's dialog) and comes back to dialog activity it still shows 78 unread messages

**Any others comments?**

**Comment by tatanka987** [comment]
to fix this issue replace [this code](https://github.com/QuickBlox/quickblox-android-sdk/blob/master/sample-chat/src/main/java/com/quickblox/sample/chat/utils/chat/ChatHelper.java#L238-L243)  like there:
```
QBMessageGetBuilder messageGetBuilder = new QBMessageGetBuilder();
messageGetBuilder.setSkip(skipPagination);
messageGetBuilder.setLimit(CHAT_HISTORY_ITEMS_PER_PAGE);
messageGetBuilder.sortDesc(CHAT_HISTORY_ITEMS_SORT_FIELD);
messageGetBuilder.markAsRead(false);

QBRestChatService.getDialogMessages(dialog, messageGetBuilder).performAsync(
```

**Comment by Shahjahan786** [comment]
Thanks issue resolved
