### ISSUE TITLE
how to get user presence (online/offline) without QBRoster in private chat dialog

### ISSUE THREAD

**Issue by Shahjahan786** [QuickBlox/quickblox-android-sdk#506]
how to get user presence (online/offline) without QBRoster in private chat dialog

**Comment by RomanPronin** [comment]
You have several options: [ping user](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Ping_a_user) or use getLastUserActivity: 
`long lastUserActivity = QBChatService.getInstance().getLastUserActivity(targetUser.getId());` 
if lastUserActivity equals 0, user is online.

**Comment by Shahjahan786** [comment]
But how to get it in real time? Like typing status

**Comment by RomanPronin** [comment]
QBRoster is a answer. Why don't you want to use it? With QBRosterListener you can listen changing of the presence of a user (user becomes online/offline).

**Comment by Shahjahan786** [comment]
Because in my app a user can chat with users who are on chat server and in user's phone contact like whatsapp. I don't want friend request like process

**Comment by RomanPronin** [comment]
So, I can advise you to use [System notifications](https://quickblox.com/developers/Android_XMPP_Chat_Sample#System_notifications), and send system message to other user about your state.

**Comment by Shahjahan786** [comment]
I think like in group dialog there is participant listener same should be for private dialog

**Comment by RomanPronin** [comment]
QBChatDialogParticipantListener is only for group dialog, but you can use group dialog with only two occupants.

**Comment by Shahjahan786** [comment]
Can you add QBChatDialogParticipantListener to private dialog in next release?

**Comment by RomanPronin** [comment]
No. Main purpose of this ParticipantListener is a suitable way to know when the list of occupants should be re-loaded due to any changes. You have several other options I advised you.

**Comment by Shahjahan786** [comment]
Okay thanks. I will try system notification for this
