### ISSUE TITLE
Help !! Push Notification turns from private 1-1 chat into a public notification

### ISSUE THREAD

**Issue by kyrloseshak** [QuickBlox/quickblox-android-sdk#510]
I'm using quickblox and it has great features like push notification , but when i set private chat i want to setup push notification from i user to one another .. lately push notification that send from single user to another from private chat turns to  become a public notification 

please help me to fix it fast 

here is my code for subscribtion : 

 private  void intialPushNotification()
    {
        QBSettings.getInstance().init(getApplicationContext(), CustomObjectCommom.APP_ID,CustomObjectCommom.AUTH_KEY,CustomObjectCommom.AUTH_SECRET);
        QBSettings.getInstance().setAccountKey(CustomObjectCommom.ACCOUNT_KEY);
        QBSettings.getInstance().setStoringMehanism(StoringMechanism.UNSECURED);
        QBSettings.getInstance().setLogLevel(LogLevel.DEBUG);
        QBSettings.getInstance().setZone(ServiceZone.PRODUCTION);

        if (EmulatorDetector.isEmulator())
        {
            QBSettings.getInstance().setEnablePushNotification(false); //true by default

        }
        else
        {
            QBSettings.getInstance().setSubscribePushStrategy(SubscribePushStrategy.ALWAYS);
            QBSettings.getInstance().setEnablePushNotification(true); //true by default
            QBChatService.getInstance().setUseStreamManagement(true);

            user = getSharedPreferences(MY_PREFS_NAME,
                    MODE_PRIVATE).getString(CustomObjectCommom.PROFILE_USER_NAME,null);
            password = getSharedPreferences(MY_PREFS_NAME,
                    MODE_PRIVATE).getString(CustomObjectCommom.PROFILE_PASSWORD,null);
            QBUser qbUser = new QBUser(user,password);

            QBAuth.createSession(qbUser).performAsync(new QBEntityCallback<QBSession>() {
                @Override
                public void onSuccess(QBSession session, Bundle params) {

                    googlePlayServicesHelper = new GooglePlayServicesHelper(ChatMessageActivity.this);
                  
                    try {

                            SubscribeService.subscribeToPushes(ChatMessageActivity.this, true);
                            QBPushManager.getInstance().addListener(new QBPushManager.QBSubscribeListener() {
                                @Override
                                public void onSubscriptionCreated() {
                                    Log.d(TAG, "Subscribed to push notifications");
                                }

                                @Override
                                public void onSubscriptionError(Exception e, int i) {
                                    Log.d(TAG, "Failed to subscribe to push notifications: " + e.toString());
                                }

                                @Override
                                public void onSubscriptionDeleted(boolean b) {
                                    Log.d(TAG, "Subscription deleted to push notifications");
                                }
                            });
                        }
                    catch (Exception e) {
                        Log.d(TAG, e.toString());
                    }
          

                }

                @Override
                public void onError(QBResponseException errors) {

                }
            });
        }

    }

and my set notification method : 

 private void  sendNotification(String message )
    {
        if(EmulatorDetector.isEmulator())
        {
        }
        else
        {
            if (userID!=0)
            {
                QBEvent event = new QBEvent();
                event.setEnvironment(QBEnvironment.DEVELOPMENT);
                event.setUserId(userID);
                event.setNotificationType(QBNotificationType.PUSH);
                event.setPushType(QBPushType.GCM);
                HashMap<String, String> data = new HashMap<String, String>();
                data.put("data.message", message);
                // data.put("data.type", senderName);
                event.setMessage(message);

                QBPushNotifications.createEvent(event).performAsync(new QBEntityCallback<QBEvent>() {
                    @Override
                    public void onSuccess(QBEvent qbEvent, Bundle args) {
                        // sent
                    }

                    @Override
                    public void onError(QBResponseException errors) {

                    }
                });
            }

        }

    }

where is the problem and why this happening ???

**Comment by RomanPronin** [comment]
Hi, @kyrloseshak! To send Push Notification to particular users you should use the next method -event.setUserIds(), not setUserId(). For ex:
`StringifyArrayList<Integer> userIds = new StringifyArrayList<Integer>();`
`userIds.add(53779);`
`event.setUserIds(userIds);`

**Comment by alexanderkoqb** [comment]
Hey @kyrloseshak 
Since it's been a while and if you're still being experiencing analogous troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
