### ISSUE TITLE
Getting System message multiple times

### ISSUE THREAD

**Issue by diaz9557** [QuickBlox/quickblox-android-sdk#513]
I am using `QBSystemMessagesManager` for sending SystemMessage to participants of a private group.

        `public void sendSystemMessage(QBSystemMessagesManager systemMessagesManager,                     QBChatDialog dialog, QBChatMessage systemMessageCreatingDialog) { 
            try {
               for (final Integer recipientId : dialog.getOccupants()) {
                 if (!recipientId.equals(QBChatService.getInstance().getUser().getId())) {
                    systemMessageCreatingDialog.setRecipientId(recipientId);
                     systemMessagesManager.sendSystemMessage(systemMessageCreatingDialog, new QBEntityCallback<Void>() {
                           @Override
                         public void onSuccess(Void aVoid, Bundle bundle) {
                             Log.e("SystemMessage"+recipientId.intValue(),"Success");
                         }
                         @Override
                         public void onError(QBResponseException e) {
                             e.printStackTrace();
                             Log.e("SystemMessage"+recipientId.intValue(),"Failed");
                         }
                      });
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }` 

In current scenario the group consist total 19 participants including creator . So if i am sending a system message to all participants with above code its sends message to each participants excluding sender, Logs shows fine. 
On participants end i am getting multiple callback of same system message . In this particular scenario 17 times .
Am i doing something wrong ? Please have a look into this issue. Its also happening in IOS sdk .

**Comment by RomanPronin** [comment]
In your QBSystemMessageListener you've got the same system message several times, right? Is this behavior reproduced in sample chat?

**Comment by diaz9557** [comment]
Yeah right . I have followed the sample chat in my application . But i do not know if its producing there also or not. Can you please look into issue and let me know if i am missing something or this is a SDK issue .

**Comment by RomanPronin** [comment]
In sample-chat this behavior is not reproducible, it's all ok. Your piece of code looks fine. So, look carefully what the difference is between your code and sample, maybe something wrong in your implementation of adding QBSystemMessageListener.

**Comment by RomanPronin** [comment]
Long time inactivity.
