### ISSUE TITLE
Updating a  QBMessage returning last mesage from dialog incomplete

### ISSUE THREAD

**Issue by diaz9557** [QuickBlox/quickblox-android-sdk#518]
Hi.
I am using following dependencies .

`compile 'com.quickblox:quickblox-android-sdk-videochat-webrtc:3.3.3@aar'
 compile 'com.quickblox:quickblox-android-sdk-content:3.3.3@aar'
 compile('com.quickblox:quickblox-android-sdk-chat:3.3.3@aar') {
        transitive = true
    }`

When i am updating last message in a dialog . Now on loading dialog list 'dialog.getLastMessage()' returning incomplete message (with ...). Please look into issue and let us know whats the issue, message update api is below. Thanks for support .

    `QBMessageUpdateBuilder  messageUpdateBuilder = new QBMessageUpdateBuilder();
        messageUpdateBuilder.updateText(newBody)
                .markDelivered()
                .markRead();
        QBRestChatService.updateMessage(qbChatMessage.getId(),qbChatDialog.getDialogId(),
                messageUpdateBuilder).performAsync(new QBEntityCallback<Void>() {
            @Override
            public void onSuccess(Void aVoid, Bundle bundle) {
               
            }
            @Override
            public void onError(QBResponseException e) {
            }
        });`

**Comment by tatanka987** [comment]
This is bug on backend, it was fixed in test branch and is checking now. Later it will be deployed to shared server (oriented date is February).

**Comment by A2DNEW** [comment]
@tatanka987 can you help me ? :( https://github.com/QuickBlox/quickblox-android-sdk/issues/517

**Comment by diaz9557** [comment]
Thanks @tatanka987 . Please let us know when changes reflect on shared server.
Thanks for Support . 
Regards Diaz

**Comment by tatanka987** [comment]
@diaz9557 QuickBlox doesn't have limits to QBChatMessage's body, but QBChatDialog's field shrinks to 27 symbols.

**Comment by diaz9557** [comment]
Hi tatanka987 Thx for quick reply . As you said QBChatDialog's field shrinks to 27 symbols.
This makes too difficult to handle chat list for us . See we are using JSON String for some types of messages. The thing that makes us to use JSON is that `qbChatDialog.getLastMessage()` returns body only  not `QbChatMessage` so we are unable to distinguish between message types . Hope you got the point .

In our group module we have several scenario where we need to distinguish some messages from the normal chat message like Participants added to group, Participant left the group, Group subject changed and group Icon changed .  So we figured out that we will use JSON String to distinguish the message type .
I know we can also do this with `QbChatMessage.setProperty()` but the problem is when we load `QbChtDialogList` we do not get `QbChatMessage` as last message we only get Message body in `QBChatDialog` object. To overcome this problem we used JSON . We have read and follow the documentation there were no limit on   
`qbChatDialog.getLastMessage()` , this is why  we made the decision .

Now as you said QBChatDialog's field shrinks to 27 symbols which is 27 character max . In this way JSON String will be truncated and we will not able to parse it . This will cause a huge problem in our Chat module. We are running out of time as this is our target and we need to deliver it at the end of this week.Hope you can understand our situation.
Please suggest a workaround we have already implemented the whole chat module with above model.

**Comment by diaz9557** [comment]
@tatanka987  hope you are doing great . If you read  the problem above, please suggest a workaround . As we are on tight deadline which is already passed. So we need to fix this immediately. As you can see, we can not compromised with  QBChatDialog's last message 27 symbols . So solution can be it we get whole message body in last message field. Please look into issue and let us know if there is a work around .
Thanks for support
Regards
Diaz

**Comment by tatanka987** [comment]
you can get last message for concrete dialog:
```
        QBChatDialog chatDialog = ...;

        QBRequestGetBuilder requestGetBuilder = new QBRequestGetBuilder();
        requestGetBuilder.sortDesc("date_sent");
        requestGetBuilder.setLimit(1);

        QBChatMessage lastMessage = QBRestChatService.getDialogMessages(chatDialog, requestGetBuilder).perform().get(0);
```

or you can get message by date sent:
```
        QBRequestGetBuilder requestGetBuilder = new QBRequestGetBuilder();
        requestGetBuilder.addRule("date_sent", QueryRule.EQ, chatDialog.getLastMessageDateSent());

        QBChatMessage lastMessage = QBRestChatService.getDialogMessages(chatDialog, requestGetBuilder).perform().get(0);
```

**Comment by diaz9557** [comment]
First of all Thanks for reading the whole problem .
We already know that we can get any message for a concrete dialog . But when we load list of dialog with following code .

> public void getDialogs() {
          QBRequestGetBuilder requestBuilder = new QBRequestGetBuilder();
          requestBuilder.setLimit(ChatHelper.DIALOG_ITEMS_PER_PAGE);
           requestBuilder.setSkip(skipPagination);
          requestBuilder.in("type", "2", "3");
           requestBuilder.sortDesc("last_message_date_sent");
           requestPerformer = QBRestChatService.getChatDialogs(null, requestBuilder);
           requestPerformer.performAsync(new QBEntityCallback<ArrayList<QBChatDialog>>() {
            @Override
            public void onSuccess(ArrayList<QBChatDialog> result, Bundle bundle) {
            }
            @Override
            public void onError(QBResponseException responseException) {
            }
        });
    }


Lets say we get 50 dialog in first call . Its a huge hustle to get lastmessage for each dialog individually.
 I think the only that will help us is that QbChatDialog last message field returns the complete message body . 
So Please let us know does  QBChatDialog's last message shrinks to 27 symbols from now on or we can expect that it will return whole body in future too .

**Comment by tatanka987** [comment]
I talked with our backend team and they said me if you used Enterprise plan you would change this parameter (from 27 to your value) on own server. On shared server we can't change this parameter.

**Comment by YatinKwikard** [comment]
@diaz9557 This is not good i think as you have to redo all the implementation i just started the implementation of chatting module in my project and faced same problem.I thought Quickblox backend can easily handle this problem but after reading above reply i think i should start searching for other chatting sdk.
@tatanka987 if this issue can't be solved then i would seriously do not recommend Quickblox sdk to anyone.

**Comment by tatanka987** [comment]
Field 'last_message' intended for displaying last message for dialog in dialogs list. It is just subtitle and that's all. Which additional information do you need for displaying last message in your cases? Please specify your needs which we can use for internal discussions about this question.

**Comment by YatinKwikard** [comment]
@tatanka987 Please remove either the last message limit or change the last message field return type to be QBChatMessage instead of text.

**Comment by tatanka987** [comment]
I understood your wants. But you didn't specify needs for additional parameters. Please provide your examples.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/ios-chat-messaging#retrieve-chat-history](https://docs.quickblox.com/docs/ios-chat-messaging#retrieve-chat-history)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
