### ISSUE TITLE
Push notification from Javascript to all platforms

### ISSUE THREAD

**Issue by pramodwadkar** [QuickBlox/quickblox-android-sdk#52]
Hi,
I am trying to send push notification from Javascript and could not find documentation for following methods. 
QB.messages
QB.messages.tokens
QB.messages.subscriptions
QB.messages.events
It will be really helpful if you provide some documentation regarding the same .

**Comment by geohelou** [comment]
Hi,
I did exactly the same and QB.messages.events.create responds with this json object:
{ event: 
   { active: true,
     application_id: 18113,
     created_at: '2015-01-12T19:01:29Z',
     date: null,
     end_date: null,
     event_type: 'one_shot',
     id: 1806723,
     message: 'data.message=SStsb3ZlK00lMjZNJTI3cyUyMStFc3BlY2lhbGx5K3JlZCtvbmUlMjE=',
     name: null,
     occured_count: 0,
     period: null,
     updated_at: '2015-01-12T19:01:29Z',
     user_id: 2185263,
     notification_channel: { name: 'gcm' },
     subscribers_selector: 
      { environment: 'production',
        tags_query: null,
        user_ids: [Object] } } }
However, when I check the admin panel for the messages queue, it remains empty.
Could u please help ?

**Comment by vrodge** [comment]
Hi,
 am trying to send push notification from Javascript but getting following error.
"  { code: 422, status: "error", message: "Unprocessable Entity", detail: "{"errors":{"base":["No recipients. At least one user should be subscribed for GCM (Android Push) (through SDK or REST API)"]}}" } ".

Please provide me proper solution. my code is givin below...

<html>
<head>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<script src="require.js"></script>	
	

</head>
	<body>
<script>
require(["quickblox"],function(quickblox){
quickblox.init("xxxxx", "xxxxxxxxxxxxxx", "xxxxxxxxxxxxxx");
var params = {
			environment: "development",
			platform: "android",
			udid: "**************"
		};
quickblox.createSession(function(err, response) {
  if (err) {
				console.log(err);
				alert("error1")
			} else {
				console.log(response);
				var params1 = {login: 'xxxxxx', password: 'xxxxxx'}; 
				quickblox.login(params1, function(err, result) {
					if(err)
					{
						console.log(err);							
					}
					else
					{
						console.log(result);
                        quickblox.messages.tokens.create(params, function (err, response) {
								if (err) {
									console.log(err);
								} else {
									console.log(response);
									var params2 = {notification_channels: "GCM"};
                                    quickblox.messages.subscriptions.create(params2, function (err, response) {
                                    if (err) 
                                    {
                                            console.log('subscriptions'+err);
                                    } 
                                    else
                                    {
                                        console.log(response);
                                        var params3 = {
                                        notification_type: "push",
                                        environment: "development",
                                        users: {
                                                    ids: "xxxxxxxx"
                                        },
                                        message: "payload=eyJhcHMiOnsic291bmQiOiJkZWZhdWx0IiwiYWxlcnQiOiJZb3UgaGF2ZSBqdXN0IHJlY2VpdmVkIGEgbmV3IG1lc3NhZ2UgZnJvbSBZdWxpYSBTeWRvcmVua28uIn0sIngiOnsiZGF0YSI6IntcInR5cGVcIjpcIm1lc3NhZ2VcIixcImZyb21fbmFtZVwiOlwiWXVsaWEgU3lkb3JlbmtvXCIsXCJmcm9tX2lkXCI6XCI4NTc1MTFcIixcImZyb21fZmFjZWJvb2tcIjpcIjEwMDAwMDM0OTA4MjYwM1wifSJ9fQ==",
                                        push_type: "gcm"
                                    };
        quickblox.messages.events.create(params3, function (err, response) {
			if (err) {
				console.log(err);
			} else {
				console.log('sadkasdf'+response);
			}
		});
                                    }
                        });

		// now available to send push notifications to
		

		
								}
							});		
					}
				});
				
			}
});

});
</script>
		<p id="demo" onclick="myFunction()">Click me to change my text color.</p>
	</body>

</html>

**Comment by soulfly** [comment]
@vrodge to what user you are sending a push? iOS/Android?

**Comment by vrodge** [comment]
Android

**Comment by sagargohad7** [comment]
Hi,
I am new to quickblox push notification, I am also facing same problem to sending push to android user. I get response as below.
/*
Array [  ]

Object { code: 422, status: "error", message: "Unprocessable Entity", detail: "{"errors":{"base":["No recipients. At least one user should be subscribed for GCM (Android Push) (through SDK or REST API)"]}}" }.
*/
Please help me to solve this problem. 
Thanx in advance....

**Comment by soulfly** [comment]
Please post your js code how you do it

**Comment by sagargohad7** [comment]
@soulfly 

<html>
<head>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<script src="require.js"></script>	
	

</head>
	<body>
<script>
require(["quickblox"],function(quickblox){
quickblox.init("appId", "authKey", "authSecret");
var params = {
			environment: "development",
			platform: "android",
			udid: "udid"
		};
quickblox.createSession(function(err, response) {
  if (err) {
				console.log(err);
				
			} else {
				console.log(response);
				var params1 = {login: 'xxxxxxxxx', password: 'xxxxxxxx'}; 
				quickblox.login(params1, function(err, result) {
					if(err)
					{
						console.log(err);							
					}
					else
					{
						console.log(result);
                        quickblox.messages.tokens.create(params, function (err, response) {
								if (err) {
									console.log(err);
								} else {
									console.log(response);
									var params2 = {notification_channels: "GCM"};
                                    quickblox.messages.subscriptions.create(params2, function (err, response) {
                                    if (err) 
                                    {
                                            console.log('subscriptions'+err);
                                    } 
                                    else
                                    {
                                        console.log(response);
                                        var params3 = {
                                        notification_type: "push",
                                        environment: "development",
                                        users: {
                                                    ids: "6596976"
                                        },
                                        message: "payload=eyJhcHMiOnsic291bmQiOiJkZWZhdWx0IiwiYWxlcnQiOiJZb3UgaGF2ZSBqdXN0IHJlY2VpdmVkIGEgbmV3IG1lc3NhZ2UgZnJvbSBZdWxpYSBTeWRvcmVua28uIn0sIngiOnsiZGF0YSI6IntcInR5cGVcIjpcIm1lc3NhZ2VcIixcImZyb21fbmFtZVwiOlwiWXVsaWEgU3lkb3JlbmtvXCIsXCJmcm9tX2lkXCI6XCI4NTc1MTFcIixcImZyb21fZmFjZWJvb2tcIjpcIjEwMDAwMDM0OTA4MjYwM1wifSJ9fQ==",
                                        push_type: "gcm"
                                    };
        quickblox.messages.events.create(params3, function (err, response) {
			if (err) {
				console.log(err);
			} else {
				console.log('Response'+response);
			}
		});
                                    }
                        });

		
		

		
								}
							});		
					}
				});
				
			}
});

});
</script>
		
	</body>

</html>

Please give any solution.
thank you.

**Comment by soulfly** [comment]
@sagargohad7 
Please post your js code how you send a push

**Comment by sagargohad7** [comment]
/*
<html>
<head>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<script src="require.js"></script>	
	

</head>
	<body>
<script>
require(["quickblox"],function(quickblox){
quickblox.init("appId", "authKey", "authSecret");
var params = {
			environment: "development",
			platform: "android",
			udid: "udid"
		};
quickblox.createSession(function(err, response) {
  if (err) {
				console.log(err);
				
			} else {
				console.log(response);
				var params1 = {login: 'xxxxxxxxx', password: 'xxxxxxxx'}; 
				quickblox.login(params1, function(err, result) {
					if(err)
					{
						console.log(err);							
					}
					else
					{
						console.log(result);
                        quickblox.messages.tokens.create(params, function (err, response) {
								if (err) {
									console.log(err);
								} else {
									console.log(response);
									var params2 = {notification_channels: "GCM"};
                                    quickblox.messages.subscriptions.create(params2, function (err, response) {
                                    if (err) 
                                    {
                                            console.log('subscriptions'+err);
                                    } 
                                    else
                                    {
                                        console.log(response);
                                        var params3 = {
                                        notification_type: "push",
                                        environment: "development",
                                        users: {
                                                    ids: "ids"
                                        },
                                        message: "payload=eyJhcHMiOnsic291bmQiOiJkZWZhdWx0IiwiYWxlcnQiOiJZb3UgaGF2ZSBqdXN0IHJlY2VpdmVkIGEgbmV3IG1lc3NhZ2UgZnJvbSBZdWxpYSBTeWRvcmVua28uIn0sIngiOnsiZGF0YSI6IntcInR5cGVcIjpcIm1lc3NhZ2VcIixcImZyb21fbmFtZVwiOlwiWXVsaWEgU3lkb3JlbmtvXCIsXCJmcm9tX2lkXCI6XCI4NTc1MTFcIixcImZyb21fZmFjZWJvb2tcIjpcIjEwMDAwMDM0OTA4MjYwM1wifSJ9fQ==",
                                        push_type: "gcm"
                                    };
        quickblox.messages.events.create(params3, function (err, response) {
			if (err) {
				console.log(err);
			} else {
				console.log('Response'+response);
			}
		});
                                    }
                        });
								}
							});		
					}
				});
				
			}
});

});
</script>
		
		
	</body>

</html>

*/

Please give any solution.
Thank you

**Comment by soulfly** [comment]
*No recipients. At least one user should be subscribed for GCM (Android Push) (through SDK or REST API)* means that you didn't subscribe a user to pushes

you have to call *subscriptions.create* before and check that it works well, no errors

Which platforms do you use? only Web? is it web app or mobile?

**Comment by sagargohad7** [comment]
I call  subscriptions.create  but it gives me empty array[ ] in response and i already subscribe 3 users.
here is my subscription code and response.

/*
quickblox.messages.subscriptions.create(params2, function (err, response) {
                                            if (err)
                                            {
                                                console.log(err);
                                            }
                                            else {

                                                console.log(response);
                                                var params3 = {
                                                    notification_type: "push",
                                                    environment: "development",
                                                    user: {
                                                        ids: 'XXXXXXX'
                                                    },
                                                    message: "payload=hello from js",
                                                    push_type: "GCM"
                                                };
                                                quickblox.messages.events.create(params3, function (err, response) {
                                                    if (err) {
                                                        console.log(err);
                                                    } else {
                                                        console.log(response);
                                                    }
                                                });
                                            }

                                        });
*/

Response:
/*
Array [  ]
*/

please give any solution,
Thank you.

**Comment by soulfly** [comment]
An empty array it's ok, it means that you are already subscribetd to this particular device

**Comment by sagargohad7** [comment]
But after that it gives me following error
/*
Object { code: 422, status: "error", message: "Unprocessable Entity", detail: "{"errors":{"base":["No recipients. At least one user should be subscribed for GCM (Android Push) (through SDK or REST API)"]}}" } 
*/
what should i have to do ?

**Comment by sagargohad7** [comment]
hi sir,
i am little bit confuse about,
  which ids should i have to use for  "message.create.event"  whether to use subscription id or user Id
when i used  "subscription Id"  then it gives me following error ,
/*
Object { code: 422, status: "error", message: "Unprocessable Entity", detail: "{"errors":{"base":["No recipients. At least one user should be subscribed for GCM (Android Push) (through SDK or REST API)"]}}" } sample.html:57
*/
and when i used  "Users Id"  then it gives following response,
/*
Object { event: Object }
*/

please give any solution.  

thank you

**Comment by sunilkmrnishad** [comment]
Hi Sir ,

I'm facing same issue in android.

As per QB doc https://quickblox.com/developers/SimpleSample-messages_users-android#Giving_a_user_a_Push_Notification_subscription


        QBSubscription subscription = new QBSubscription();
        subscription.setEnvironment(QBEnvironment.PRODUCTION);
        //
        String deviceId;
        final TelephonyManager mTelephony = (TelephonyManager) mContext.getSystemService(
                Context.TELEPHONY_SERVICE);
        if (mTelephony.getDeviceId() != null) {
            deviceId = mTelephony.getDeviceId(); //*** use for mobiles
        } else {
            deviceId = Settings.Secure.getString(mContext.getContentResolver(),
                    Settings.Secure.ANDROID_ID); //*** use for tablets
        }
        subscription.setDeviceUdid(deviceId);
        //
        subscription.setRegistrationID(registrationID);
        subscription.setId(ChatHelper.getCurrentUser().getId());
        subscription.setNotificationChannel(QBNotificationChannel.GCM);


        
        QBPushNotifications.createSubscription(subscription).performAsync(new QBEntityCallback<ArrayList<QBSubscription>>() {

            @Override
            public void onSuccess(ArrayList<QBSubscription> qbSubscriptions, Bundle bundle) {
                Log.i("createSubscription success");
            }

            @Override
            public void onError(QBResponseException e) {
                Log.i("createSubscription fail");
            }
        });

**Here i'm getting success**

But when i'm sending push




 StringifyArrayList<Integer> userIds = new StringifyArrayList<>();
        userIds.add(recipientId);

        QBEvent event = new QBEvent();
        event.setUserIds(userIds);
        event.setEnvironment(QBEnvironment.PRODUCTION);
        event.setNotificationType(QBNotificationType.PUSH);
        event.setPushType(QBPushType.GCM);
        event.setMessage(message);

        QBPushNotifications.createEvent(event).performAsync(new QBEntityCallback<QBEvent>() {
            @Override
            public void onSuccess(QBEvent qbEvent, Bundle args) {
                Log.i("push sent");
            }

            @Override
            public void onError(QBResponseException errors) {
                Log.i("push fail");
            }
        });

 facing issue  base No recipients. At least one user should be subscribed for 'gcm' (through SDK or REST API) in android

Please help
