### ISSUE TITLE
Api initialization asynchornous

### ISSUE THREAD

**Issue by RoudyK** [QuickBlox/quickblox-android-sdk#521]
Is there any way currently to initialize the SDK asynchronously? It takes quite some time to initialize sometimes and it blocks the UI Thread and gives the app a few seconds delay when opening.

**Comment by RomanPronin** [comment]
Hi, @RoudyK. You can always use AsyncTask, or just set `QBSettings.getInstance().setStoringMehanism(StoringMechanism.UNSECURED);`
It will be much faster without encryption mechanism. More info [Manage session storage](https://quickblox.com/developers/Android#Manage_session_storage).

**Comment by RomanPronin** [comment]
Any updates?

**Comment by RoudyK** [comment]
@RomanPronin Hey, we were already using an AsyncTask and that caused A LOT of problems when using the quickblox SDK (Especially the SubscribeService throwing infinite exceptions even with the releases that had fixes for it). We already are using UNSECURED storing mechanism.

**Comment by RomanPronin** [comment]
@RoudyK, it would be very helpful if you post some logs with SubscribeService infinite exceptions to find out the causes. As for initializing SDK, especially with UNSECURED mechanism, as I know, it takes less than a second in most cases.

**Comment by RoudyK** [comment]
@RomanPronin The SubscribeService no longer throws any exception when not using AsyncTask. The delays is a few seconds and on older devices so I guess we can live with it for now. Thank you
