### ISSUE TITLE
Call not connect to Other QBUser

### ISSUE THREAD

**Issue by KailashChavda** [QuickBlox/quickblox-android-sdk#524]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Android, QuickBlox 3.4.1)*

**Always show error : QBASDK: Can't parse the 'date_sent' value null: For input string: "null"**

How to update "date_sent" key value?

**Comment by tatanka987** [comment]
It is not error, just notification. About your problem - please add more details (steps to reproduce, logs (from both sides), etc.) to help us localize your  problem.

**Comment by KailashChavda** [comment]
01-23 14:54:59.982 15307-15307/com.ieltsspeaking D/QBASDK: Data : User : Offline
01-23 14:54:59.984 15307-15307/com.ieltsspeaking D/QBASDK: =========================================================
                                                           === REQUEST ==== 6fa4f996-159f-4484-9309-cec51ce8809c ===
                                                           REQUEST
                                                               GET https://api.quickblox.com/users.json
                                                           HEADERS
                                                               QuickBlox-REST-API-Version=0.1.1
                                                               QB-SDK=Android 3.4.1
                                                               QB-Token=7d4bf3d4a3406e51a2f83e7823628d1794010195
                                                           PARAMETERS
                                                               filter[]=number id in 41362288
                                                           INLINE
                                                               GET https://api.quickblox.com/users.json?filter[]=number+id+in+41362288
01-23 14:55:01.901 15307-15307/com.ieltsspeaking D/QBASDK: *********************************************************
                                                           *** RESPONSE *** 6fa4f996-159f-4484-9309-cec51ce8809c ***
                                                           STATUS : 200 
                                                           HEADERS
                                                               X-Runtime=0.022897
                                                               Cache-Control=max-age=0, private, must-revalidate
                                                               QuickBlox-REST-API-Version=0.1.1
                                                               X-Android-Selected-Protocol=http/1.1
                                                               Set-Cookie=_mkra_ctxt=8e7c6c423173cce85b3f6dd2ec9c4ff0--200; path=/; max-age=5; HttpOnly; secure
                                                               QB-Token-ExpirationDate=2018-01-23 11:24:49 +0000
                                                               Status=200 OK
                                                               X-Request-Id=97402a53-441b-49bf-8580-f3a9c8891aa4
                                                               X-Android-Response-Source=NETWORK 200
                                                               Connection=Close
                                                               X-Android-Sent-Millis=1516699500933
                                                               Content-Type=application/json; charset=utf-8
                                                               Date=Tue, 23 Jan 2018 09:25:02 GMT
                                                               X-Content-Type-Options=nosniff
                                                               Content-Length=469
                                                               ETag=W/"d8e8c15389ead7140d379744b4478e4e"
                                                               Server=openresty/1.9.15.1
                                                               Strict-Transport-Security=max-age=31536000max-age=15768000;
                                                               X-XSS-Protection=1; mode=block
                                                               X-Frame-Options=SAMEORIGIN
                                                               X-Android-Received-Millis=1516699501898
                                                               Access-Control-Allow-Origin=*
                                                           BODY
                                                               '{"current_page":1,"per_page":10,"total_entries":1,"items":[{"user":{"id":41362288,"owner_id":70748,"full_name":"navi","email":null,"login":"00000000-63ea-1d37-0570-a3695571b97f","phone":null,"website":null,"created_at":"2018-01-20T06:08:43Z","updated_at":"2018-01-23T09:20:40Z","last_request_at":"2018-01-23T09:20:40Z","external_user_id":null,"facebook_id":null,"twitter_id":null,"blob_id":null,"custom_data":null,"twitter_digits_id":null,"user_tags":"IELTSSDEVAPP"}}]}'
01-23 14:55:01.918 15307-15307/com.ieltsspeaking D/QBASDK: Data : User : Online
01-23 14:55:01.932 15307-15307/com.ieltsspeaking D/QBASDK: =========================================================
                                                           === REQUEST ==== f5aa08d7-9b32-4d15-a3c8-d66706b3fdd6 ===
                                                           REQUEST
                                                               POST https://api.quickblox.com/events.json
                                                           HEADERS
                                                               QuickBlox-REST-API-Version=0.1.1
                                                               QB-SDK=Android 3.4.1
                                                               QB-Token=7d4bf3d4a3406e51a2f83e7823628d1794010195
                                                           PARAMETERS
                                                               event[notification_type]=push
                                                               event[environment]=development
                                                               event[user][ids]=41362288
                                                               event[message]=MjEzMTI5NjQ5NA==
                                                           INLINE
                                                               POST https://api.quickblox.com/events.json?event[notification_type]=push&event[environment]=development&event[user][ids]=41362288&event[message]=MjEzMTI5NjQ5NA%3D%3D
01-23 14:55:02.170 15307-15526/com.ieltsspeaking D/QBASDK: Can't parse the 'date_sent' value null: For input string: "null"
01-23 14:55:03.455 15307-15526/com.ieltsspeaking D/QBASDK: Can't parse the 'date_sent' value null: For input string: "null"
01-23 14:55:03.482 15307-15307/com.ieltsspeaking D/QBASDK: *********************************************************
                                                           *** RESPONSE *** f5aa08d7-9b32-4d15-a3c8-d66706b3fdd6 ***
                                                           STATUS : 422 
                                                           HEADERS
                                                               X-Runtime=0.080794
                                                               Cache-Control=no-cache
                                                               QuickBlox-REST-API-Version=0.1.1
                                                               X-Android-Selected-Protocol=http/1.1
                                                               Set-Cookie=_mkra_ctxt=f08cecde54fd60c76afcf29f9aa8d2aa--422; path=/; max-age=5; HttpOnly; secure
                                                               QB-Token-ExpirationDate=2018-01-23 11:24:49 +0000
                                                               Status=422 Unprocessable Entity
                                                               X-Request-Id=c9649dd6-7811-456f-bfd1-801e086d5451
                                                               X-Android-Response-Source=NETWORK 422
                                                               Connection=Close
                                                               X-Android-Sent-Millis=1516699502671
                                                               Content-Type=application/json; charset=utf-8
                                                               Date=Tue, 23 Jan 2018 09:25:04 GMT
                                                               X-Content-Type-Options=nosniff
                                                               Content-Length=45
                                                               Server=nginx/1.8.1
                                                               Strict-Transport-Security=max-age=31536000
                                                               X-XSS-Protection=1; mode=block
                                                               X-Frame-Options=SAMEORIGIN
                                                               X-Android-Received-Millis=1516699503476
                                                               Access-Control-Allow-Origin=*
                                                           BODY
                                                               '{"errors":["No one can receive the message"]}'
01-23 14:55:07.172 15307-15526/com.ieltsspeaking D/QBASDK: Can't parse the 'date_sent' value null: For input string: "null"
01-23 14:55:08.454 15307-15526/com.ieltsspeaking D/QBASDK: Can't parse the 'date_sent' value null: For input string: "null"
01-23 14:55:12.172 15307-15526/com.ieltsspeaking D/QBASDK: Can't parse the 'date_sent' value null: For input string: "null"
01-23 14:55:13.454 15307-15526/com.ieltsspeaking D/QBASDK: Can't parse the 'date_sent' value null: For input string: "null"
01-23 14:55:17.171 15307-15526/com.ieltsspeaking D/QBASDK: Can't parse the 'date_sent' value null: For input string: "null"
01-23 14:55:18.454 15307-15526/com.ieltsspeaking D/QBASDK: Can't parse the 'date_sent' value null: For input string: "null"

**Comment by tatanka987** [comment]
in logs I can see user 41362288 not subscribed to pushes, it means hi wont get background call. For better understand please provide full logs from both devices (caller and receiver) from start app to getting error. Use [Gist](https://gist.github.com/) for posting logs. Logs must contain Chat logs (call QBChatService.setDebugEnabled(true) before login to the chat).

**Comment by KailashChavda** [comment]
Hi,

According to log it's says that at sender side date_sent value got "null",
But In code I check there is no key set for it,

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/2.17.10](https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/2.17.10)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)
[https://docs.quickblox.com/docs/code-samples#video-calling-samples](https://docs.quickblox.com/docs/code-samples#video-calling-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
