### ISSUE TITLE
Delivery status not updated when a user logs in.

### ISSUE THREAD

**Issue by RoudyK** [QuickBlox/quickblox-android-sdk#525]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
- Android SDK
- IOS SDK (I understand that this is the android sdk github but just letting you know it's not only on android devices)

**Did this work before?**
- This is newly added

**Expected behavior**
- When the user logs in, all the messages that were "undelivered" to him should be marked as delivered
and all the users that are chatting with this user should be notified through the status listener in status manager.

**Actual behavior**
- If both users are logged in, the messages are being delivered successfully. 
- If one of the users is logged out and the other user is logged in, the message will not be marked as delivered (This is correct so far). But when the logged out user logs back in, the message remains "undelivered".

**Logs**
- No logs to view since the message delivery is not being received anyway.

**Steps to reproduce the behavior**
- Log in user A.
- Log in user B.
- A talks to B. B is not reading
- A receives delivery status successfully
- B logs out.
- A talks to B. B is not in the app
- A doesn't receive delivery status ( Expected )
- B logs back in
- A still doesn't receive delivery status
- B reads the messages (readMessage in QBChatDialog)
- A receives read status (Expected)

**Any others comments?**
- **All messages are markable = true**

**Comment by tatanka987** [comment]
Did user B mark delivered messages as 'delivered' on step 8 (```chatDialog.deliverMessage(message);```)? When user B loaded messages from server they are marked as 'delivered' but server doesn't send this information to sender in realtime.

**Comment by RoudyK** [comment]
@tatanka987 The problem is that when user B logs back in and retrieves the chat messages. They become read. Or is that not the case ? Whenever I load messages from a dialog and retrieve the dialog again, the next request will return that the unreadCount is zero because the previous already called them. Does retrieving messages in Quickblox automatically makes the messages read/delivered?

**Comment by tatanka987** [comment]
This is another case,  if you want user B fetch messages from server without marking as read, you need add one more parameter to request:
```
        QBMessageGetBuilder messageGetBuilder = new QBMessageGetBuilder();
        ...
        messageGetBuilder.markAsRead(false);

        QBRestChatService.getDialogMessages(dialog, messageGetBuilder).perform();
```

**Comment by RoudyK** [comment]
@tatanka987 i see, i will give that a try. But that requires I load all the messages on all dialogs and mark all undelivered messages delivered. What's the cost of doing so ?

**Comment by javieritis** [comment]
`    public static void markAllMessagedAsDelivered(String idChatDialog) {
        QBMessageUpdateBuilder qbMessageUpdateBuilder = new QBMessageUpdateBuilder();
        qbMessageUpdateBuilder.markDelivered();

        CustomQBRestChatService.markMessagesAsDelivered(idChatDialog, qbMessageUpdateBuilder).performAsync(new QBEntityCallback<Void>() {
            @Override
            public void onSuccess(Void aVoid, Bundle bundle) {
                Log.d(TAG, "onSuccess markAllMessagedAsDelivered");
            }

            @Override
            public void onError(QBResponseException e) {
                Log.e(TAG, "" + e);
            }
        });
    }

    public static class CustomQueryUpdateMessage extends QueryAbsMessage {
        private String dialogId;
        private QBMessageUpdateBuilder messageUpdateBuilder;

        public CustomQueryUpdateMessage(String dialogId, QBMessageUpdateBuilder messageUpdateBuilder) {
            this.dialogId = dialogId;
            this.messageUpdateBuilder = messageUpdateBuilder;
        }

        protected void setParams(RestRequest request) {
            Map<String, Object> parametersMap = request.getParameters();
            this.messageUpdateBuilder.fillParametersMap(parametersMap);
            if (!TextUtils.isEmpty(this.dialogId)) {
                parametersMap.put("chat_dialog_id", this.dialogId);
            }

            parametersMap.put("delivered", 1);
        }

        public String getUrl() {
            String relateDomain = super.getRelateDomain();
            return this.buildQueryUrl(relateDomain);
        }

        protected void setMethod(RestRequest request) {
            request.setMethod(RestMethod.PUT);
        }
    }

    public static class CustomQBRestChatService extends BaseService {

        private CustomQBRestChatService() {
        }

        public static Performer<Void> markMessagesAsDelivered(String dialogId, QBMessageUpdateBuilder messageUpdateBuilder) {
            return new CustomQueryUpdateMessage(dialogId, messageUpdateBuilder);
        }
    }
 }
`


I tried to call the endpoint manually when user login/access the app.
https://imgur.com/hkJTecE

and the result:
https://imgur.com/RX2s1Cf

and in my QBMessageStatusListener dont receive any movement. :man_facepalming: .
Quickblox backend dont notify the endpoint and is impossible.
