### ISSUE TITLE
Re-Login issues: sending old password in session call

### ISSUE THREAD

**Issue by Shahjahan786** [QuickBlox/quickblox-android-sdk#529]
**ON FRESH APP LAUNCH**

a) App make an authentication call to our api server after successful authentication call I get an access_token
b) Server makes a password reset call to QuickBlox and set access_token for the user
c) App send sign in call to QuickBlox with access_token as a password
call is like POST https://apinayapay.quickblox.com//login.json?login=aliali&password=2a9363acdba2494984069ca4abcfc184

**ON APP RELAUNCH**

a) App make an authentication call to our api server after successful authentication call I get an access_token
b) Server again makes a password reset call to QuickBlox and set access_token for the user
c) App send sign in call to QuickBlox with access_token as a password
call is like POST https://apinayapay.quickblox.com//session.json?application_id=[deleted]&auth_key=[deleted]&nonce=-2141328434&timestamp=1517285035&user[login]=aliali&user[password]=2a9363acdba2494984069ca4abcfc184&signature=[deleted]

NOTE: OLD PASSWORD IS USED ALL TIMES like 2a9363acdba2494984069ca4abcfc184
**Logs**
*(please, use github [gist](https://gist.github.com/))*
https://gist.github.com/Shahjahan786/57c7dff106283846bf8e15b5c90822da

Following is the code snippet:

QBUsers.signIn(user).performAsync(new QbEntityCallbackTwoTypeWrapper(callback) {
@Override
public void onSuccess(QBUser qbUser, Bundle args) {
user.setId(qbUser.getId());
user.setFullName(qbUser.getFullName());
user.setPhone(qbUser.getPhone());
loginToChat(user, new QbEntityCallbackWrapper<>(callback));
AppUtils.logDebug("CHAT_LOGIN[success]", "Pass:"+user.getPassword());
}

@Override
public void onError(QBResponseException error) {
super.onError(error);
error.printStackTrace();
AppUtils.logDebug("CHAT_LOGIN[failure]", "Pass:"+user.getPassword());
}
});

**Comment by tatanka987** [comment]
@Shahjahan786 for your case better to use QBAuth.createSession(qbUser) instead of QBUsers.signIn(user) it will create new session with actual user data all times.

**Comment by Shahjahan786** [comment]
Thanks @tatanka987, I changed my code and now it's working,

But the issue is when I receive authentication server (upon successful authentication my api server changes password on  QuickBlox for that user) I make QuickBlox auth call and some time it fails and I need to retry.

Is there any delay in changing password on QuickBlox? (when my api server hits a password reset callon QuickBlox it returns success but when I make  auth call it gives exception [401 unauthorised])

    public void login(final QBUser user, final QBEntityCallback<Void> callback) {

        QBAuth.createSession().performAsync(new QBEntityCallback<QBSession>() {
            @Override
            public void onSuccess(QBSession qbSession, Bundle bundle) {
                qbSignIn(user, callback);
            }

            @Override
            public void onError(QBResponseException e) {
                e.printStackTrace();
                callback.onError(e);
            }
        });

        AppUtils.logDebug("CHAT_LOGIN", QBChatService.getInstance().isLoggedIn()+"");

    }

    private void qbSignIn(final QBUser user, final QBEntityCallback<Void> callback) {

        AppUtils.logDebug("CHAT_LOGIN","Retry "+loginRetry);
            QBUsers.signIn(user).performAsync(new QbEntityCallbackTwoTypeWrapper<QBUser, Void>(callback) {
                @Override
                public void onSuccess(QBUser qbUser, Bundle args) {
                    user.setId(qbUser.getId());
                    user.setFullName(qbUser.getFullName());
                    user.setPhone(qbUser.getPhone());
                    loginToChat(user, new QbEntityCallbackWrapper<>(callback));
                    AppUtils.logDebug("CHAT_LOGIN[success]", "Pass:"+user.getPassword());
                    loginRetry = 5;
                }

                @Override
                public void onError(QBResponseException error) {

                    loginRetry--;

                    if(loginRetry > 0){
                        qbSignIn(user, callback);
                    }else{
                        super.onError(error);
                    }

                    error.printStackTrace();
                    AppUtils.logDebug("CHAT_LOGIN[failure]", "Pass:"+user.getPassword());
                }
            });
    }

    public void loginToChat(final QBUser user, final QBEntityCallback<Void> callback) {
        if (qbChatService.isLoggedIn()) {
            callback.onSuccess(null, null);
            return;
        }

        qbChatService.login(user, callback);
    }

**Comment by tatanka987** [comment]
As I saw before, for your case use ```QBAuth.createSession(qbUser)```  instead of ```QBUsers.signIn(user)```, but you do ```QBUsers.signIn(user)``` in your method qbSignIn(...). Why? If you need ```userId``` in this method you can call:
```
int userId = QBSessionManager.getInstance().getSessionParameters().getUserId();
```

**Comment by Shahjahan786** [comment]
I Changed my code but same thing happens it always gives 401

public void login(final QBUser user, final QBEntityCallback<Void> callback) {

        QBAuth.createSession(user).performAsync(new QBEntityCallback<QBSession>() {
            @Override
            public void onSuccess(QBSession qbSession, Bundle bundle) {
                int userId = QBSessionManager.getInstance().getSessionParameters().getUserId();
                user.setId(userId);
                loginToChat(user, new QbEntityCallbackWrapper<>(callback));
            }

            @Override
            public void onError(QBResponseException e) {
                e.printStackTrace();
                callback.onError(e);
            }
        });

        AppUtils.logDebug("CHAT_LOGIN", QBChatService.getInstance().isLoggedIn()+"");

    }


> **LOGS**

01-31 10:19:31.976 5217-5217/com.nayapay.app D/QBASDK: =========================================================
                                                       === REQUEST ==== b9c9a24e-6b0e-4b17-9d4d-a9f8e6427370 ===
                                                       REQUEST
                                                           POST https://apinayapay.quickblox.com//session.json
                                                       HEADERS
                                                           QuickBlox-REST-API-Version=0.1.1
                                                           QB-SDK=Android 3.5.0
                                                           QB-Token=6f03bc33369cd8216f6c5e53bed7b50328000010
                                                       PARAMETERS
                                                           application_id=16
                                                           auth_key=Z9wAMYn42S4gzxr
                                                           nonce=-2027324099
                                                           timestamp=1517393971
                                                           user[login]=shahjahan
                                                           user[password]=ea8efa8274ba4407ac55ea2362b299d9
                                                           signature=7df81cdc9c7d648b342ff282359edbcec0147bf2
                                                       INLINE
                                                           POST https://apinayapay.quickblox.com//session.json?application_id=16&auth_key=Z9wAMYn42S4gzxr&nonce=-2027324099&timestamp=1517393971&user[login]=shahjahan&user[password]=ea8efa8274ba4407ac55ea2362b299d9&signature=7df81cdc9c7d648b342ff282359edbcec0147bf2
01-31 10:19:32.594 5217-5217/com.nayapay.app D/QBASDK: *********************************************************
                                                       *** RESPONSE *** b9c9a24e-6b0e-4b17-9d4d-a9f8e6427370 ***
                                                       STATUS : 401 
                                                       HEADERS
                                                           Status=401 Unauthorized
                                                           Transfer-Encoding=chunked
                                                           Server=nginx/1.12.1
                                                           Access-Control-Allow-Origin=*
                                                           X-Request-Id=13369d4e-4032-4fc6-8e09-dedf7065416f
                                                           X-Content-Type-Options=nosniff
                                                           X-Runtime=0.015801
                                                           WWW-Authenticate=OAuth realm=auth
                                                           Connection=close
                                                           X-Android-Received-Millis=1517393972592
                                                           Date=Wed, 31 Jan 2018 10:19:32 GMT
                                                           QuickBlox-REST-API-Version=0.1.1
                                                           X-Frame-Options=SAMEORIGIN
                                                           X-Android-Selected-Protocol=http/1.1
                                                           Strict-Transport-Security=max-age=31536000
                                                           Cache-Control=no-cache
                                                           X-Android-Response-Source=NETWORK 401
                                                           Set-Cookie=_mkra_ctxt=2b9463f65b75d90e802d3304bc1d5c6f--401; path=/; max-age=5; HttpOnly; secure
                                                           X-Android-Sent-Millis=1517393972285
                                                           X-XSS-Protection=1; mode=block
                                                           QB-Token-ExpirationDate=2018-01-31 12:19:32 UTC
                                                           Content-Type=application/json; charset=utf-8
                                                       BODY
                                                           '{"errors":["Unauthorized"]}'
01-31 10:19:47.393 5217-5217/com.nayapay.app D/QBASDK: =========================================================
                                                       === REQUEST ==== 9946404c-2e39-4de8-bfdb-120d2c31280c ===
                                                       REQUEST
                                                           POST https://apinayapay.quickblox.com//session.json
                                                       HEADERS
                                                           QuickBlox-REST-API-Version=0.1.1
                                                           QB-SDK=Android 3.5.0
                                                           QB-Token=6f03bc33369cd8216f6c5e53bed7b50328000010
                                                       PARAMETERS
                                                           application_id=16
                                                           auth_key=Z9wAMYn42S4gzxr
                                                           nonce=-1606050927
                                                           timestamp=1517393987
                                                           user[login]=shahjahan
                                                           user[password]=24aaf7faabf34eb093581705ecd76a52
                                                           signature=557105f3cf5c583aafc5623a65cb9b8ee563af3c
                                                       INLINE
                                                           POST https://apinayapay.quickblox.com//session.json?application_id=16&auth_key=Z9wAMYn42S4gzxr&nonce=-1606050927&timestamp=1517393987&user[login]=shahjahan&user[password]=24aaf7faabf34eb093581705ecd76a52&signature=557105f3cf5c583aafc5623a65cb9b8ee563af3c
01-31 10:19:48.016 5217-5217/com.nayapay.app D/QBASDK: *********************************************************
                                                       *** RESPONSE *** 9946404c-2e39-4de8-bfdb-120d2c31280c ***
                                                       STATUS : 401 
                                                       HEADERS
                                                           Status=401 Unauthorized
                                                           Transfer-Encoding=chunked
                                                           Server=nginx/1.12.1
                                                           Access-Control-Allow-Origin=*
                                                           X-Request-Id=4eaa7d3d-ba0f-478d-b947-092ed6b47ed4
                                                           X-Content-Type-Options=nosniff
                                                           X-Runtime=0.015524
                                                           WWW-Authenticate=OAuth realm=auth
                                                           Connection=close
                                                           X-Android-Received-Millis=1517393988014
                                                           Date=Wed, 31 Jan 2018 10:19:48 GMT
                                                           QuickBlox-REST-API-Version=0.1.1
                                                           X-Frame-Options=SAMEORIGIN
                                                           X-Android-Selected-Protocol=http/1.1
                                                           Strict-Transport-Security=max-age=31536000
                                                           Cache-Control=no-cache
                                                           X-Android-Response-Source=NETWORK 401
                                                           Set-Cookie=_mkra_ctxt=e2801641c4d6b235b7a61ea424fc6387--401; path=/; max-age=5; HttpOnly; secure
                                                           X-Android-Sent-Millis=1517393987712
                                                           X-XSS-Protection=1; mode=block
                                                           QB-Token-ExpirationDate=2018-01-31 12:19:48 UTC
                                                           Content-Type=application/json; charset=utf-8
                                                       BODY
                                                           '{"errors":["Unauthorized"]}'
01-31 10:20:02.263 5217-5217/com.nayapay.app D/QBASDK: =========================================================
                                                       === REQUEST ==== a004d8d3-363b-4cbc-9fa9-2d282f580334 ===
                                                       REQUEST
                                                           POST https://apinayapay.quickblox.com//session.json
                                                       HEADERS
                                                           QuickBlox-REST-API-Version=0.1.1
                                                           QB-SDK=Android 3.5.0
                                                           QB-Token=6f03bc33369cd8216f6c5e53bed7b50328000010
                                                       PARAMETERS
                                                           application_id=16
                                                           auth_key=Z9wAMYn42S4gzxr
                                                           nonce=1783752548
                                                           timestamp=1517394002
                                                           user[login]=shahjahan
                                                           user[password]=d3fffe9f357746459c2735f8796440a4
                                                           signature=f31362ee2223774832bcb73999043d65c2249f02
                                                       INLINE
                                                           POST https://apinayapay.quickblox.com//session.json?application_id=16&auth_key=Z9wAMYn42S4gzxr&nonce=1783752548&timestamp=1517394002&user[login]=shahjahan&user[password]=d3fffe9f357746459c2735f8796440a4&signature=f31362ee2223774832bcb73999043d65c2249f02
01-31 10:20:02.891 5217-5217/com.nayapay.app D/QBASDK: *********************************************************
                                                       *** RESPONSE *** a004d8d3-363b-4cbc-9fa9-2d282f580334 ***
                                                       STATUS : 401 
                                                       HEADERS
                                                           Status=401 Unauthorized
                                                           Transfer-Encoding=chunked
                                                           Server=nginx/1.12.1
                                                           Access-Control-Allow-Origin=*
                                                           X-Request-Id=cc49c682-6824-4693-85f1-f39e8d5eb971
                                                           X-Content-Type-Options=nosniff
                                                           X-Runtime=0.016828
                                                           WWW-Authenticate=OAuth realm=auth
                                                           Connection=close
                                                           X-Android-Received-Millis=1517394002889
                                                           Date=Wed, 31 Jan 2018 10:20:03 GMT
                                                           QuickBlox-REST-API-Version=0.1.1
                                                           X-Frame-Options=SAMEORIGIN
                                                           X-Android-Selected-Protocol=http/1.1
                                                           Strict-Transport-Security=max-age=31536000
                                                           Cache-Control=no-cache
                                                           X-Android-Response-Source=NETWORK 401
                                                           Set-Cookie=_mkra_ctxt=3e1e5883fd5042956c4d86c2d2986ffd--401; path=/; max-age=5; HttpOnly; secure
                                                           X-Android-Sent-Millis=1517394002578
                                                           X-XSS-Protection=1; mode=block
                                                           QB-Token-ExpirationDate=2018-01-31 12:20:03 UTC
                                                           Content-Type=application/json; charset=utf-8
                                                       BODY
                                                           '{"errors":["Unauthorized"]}'
01-31 10:20:12.360 5217-5217/com.nayapay.app D/QBASDK: =========================================================
                                                       === REQUEST ==== 5bf4dd85-c850-466d-8d37-e68580ca3e91 ===
                                                       REQUEST
                                                           POST https://apinayapay.quickblox.com//session.json
                                                       HEADERS
                                                           QuickBlox-REST-API-Version=0.1.1
                                                           QB-SDK=Android 3.5.0
                                                           QB-Token=6f03bc33369cd8216f6c5e53bed7b50328000010
                                                       PARAMETERS
                                                           application_id=16
                                                           auth_key=Z9wAMYn42S4gzxr
                                                           nonce=902279573
                                                           timestamp=1517394012
                                                           user[login]=shahjahan
                                                           user[password]=52eeb16ebb1b4a368b65ce5ee3805d96
                                                           signature=e04550d199c75bbaed7b8a085a7ee94be57076d4
                                                       INLINE
                                                           POST https://apinayapay.quickblox.com//session.json?application_id=16&auth_key=Z9wAMYn42S4gzxr&nonce=902279573&timestamp=1517394012&user[login]=shahjahan&user[password]=52eeb16ebb1b4a368b65ce5ee3805d96&signature=e04550d199c75bbaed7b8a085a7ee94be57076d4
01-31 10:20:12.976 5217-5217/com.nayapay.app D/QBASDK: *********************************************************
                                                       *** RESPONSE *** 5bf4dd85-c850-466d-8d37-e68580ca3e91 ***
                                                       STATUS : 401 
                                                       HEADERS
                                                           Status=401 Unauthorized
                                                           Transfer-Encoding=chunked
                                                           Server=nginx/1.12.1
                                                           Access-Control-Allow-Origin=*
                                                           X-Request-Id=74540954-7474-4944-a29f-1b5335e28f19
                                                           X-Content-Type-Options=nosniff
                                                           X-Runtime=0.019242
                                                           WWW-Authenticate=OAuth realm=auth
                                                           Connection=close
                                                           X-Android-Received-Millis=1517394012974
                                                           Date=Wed, 31 Jan 2018 10:20:13 GMT
                                                           QuickBlox-REST-API-Version=0.1.1
                                                           X-Frame-Options=SAMEORIGIN
                                                           X-Android-Selected-Protocol=http/1.1
                                                           Strict-Transport-Security=max-age=31536000
                                                           Cache-Control=no-cache
                                                           X-Android-Response-Source=NETWORK 401
                                                           Set-Cookie=_mkra_ctxt=70703a77a8fabcea086c3a5b642a0ef1--401; path=/; max-age=5; HttpOnly; secure
                                                           X-Android-Sent-Millis=1517394012668
                                                           X-XSS-Protection=1; mode=block
                                                           QB-Token-ExpirationDate=2018-01-31 12:20:13 UTC
                                                           Content-Type=application/json; charset=utf-8
                                                       BODY
                                                           '{"errors":["Unauthorized"]}'

**Comment by tatanka987** [comment]
are you sure that passwords are correct? can you check it without our SDK, for example if use  https://hurl.quickblox.com/ for sending raw request?

**Comment by Shahjahan786** [comment]
Yes I'm sure passwords are correct [I send the password as I receive it from server - api server changes quickblox user password on every authentication call]. We checked login call [After changing Quickblox user password] on our api server it is successful every time. 


And also QBUsers.signIn(user) method is working after creating session with QBAuth.createSession() [without user]. but some time it also returns 401 so I make retry QBUsers.signIn(user)  again and it works.

**Comment by tatanka987** [comment]
Your case is specific and we strongly recommend use QBAuth.createSession(qbUser) instead of QBUsers.signIn(user), on the server they have same behavior.

**Comment by Shahjahan786** [comment]
And in my case I can't user QBAuth.createSession(qbUser) because it always gives 401 as I have provided you logs and also cods snippet

**Comment by tatanka987** [comment]
401 error code means login or password incorrect, try compare passwords that you get from your server and passwords that you put to requests (in QB logs). For the server doesn't matter type of create session with user (QBUsers.signIn(user) or QBAuth.createSession(qbUser)) but on client-side method QBAuth.createSession(qbUser) every time puts new user's data to SDK, it is more useful for your case.

**Comment by Shahjahan786** [comment]
I have compared passwords on server and also QB request logs THEY ARE SAME ALWAYS

I create  **QBAuth.createSession()** Application session without user first and then call **QBUsers.signIn(user)** it's successful but sometimes it also gives 401 so retry method call with 
**SAME PASSWORD** and it succeeds on 1st, 2nd or 3rd retry. but QBAuth.createSession(qbUser) always gives 401 in my case.

**Comment by tatanka987** [comment]
Today I wrote tests and tried reproduce your issue, but unsuccessfully.  I propose move this conversation to our support. Please, collect full log, which will contains all steps to reproduce your issue (with old passwords, new password, with your attempts use createSession and signIn etc.) we will try help you.

**Comment by haris15** [comment]
do you find any solution for that ?

**Comment by techradiusopc** [comment]
@Shahjahan786  do you find any solution for that ?

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-authentication](https://docs.quickblox.com/docs/android-authentication)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
