### ISSUE TITLE
No recipients. At least one user should be subscribed for 'gcm' (through SDK or REST API)

### ISSUE THREAD

**Issue by prographo** [QuickBlox/quickblox-android-sdk#532]
Platform Android. 

When I try to send Push from QuickBlox it says:
`No recipients. At least one user should be subscribed for 'gcm' (through SDK or REST API)`

From the log it looks like the app is registering
```
02-01 11:39:47.256 5346-5346 D/TEST_debug: Created session, now connecting to chat
02-01 11:39:47.265 5346-5532/ D/QBASDK: connect to chat via new connection
02-01 11:39:47.266 5346-5346/ D/QBASDK: QBSessionListener onSessionCreated: WITH USER
02-01 11:39:47.275 5346-5346/ D/QBASDK: QBSessionListener onSessionUpdated
02-01 11:39:47.285 5346-5346/ D/QBASDK: SubscribeService: SubscribeService created
02-01 11:39:47.290 5346-5629/ D/QBASDK: SubscribeService: onHandleIntent start: register to pushes
02-01 11:39:47.301 5346-5629/ D/QBASDK: SubscribeService: subscribed already
02-01 11:39:47.302 5346-5629/ D/QBASDK: SubscribeService: onHandleIntent start: register to pushes
02-01 11:39:47.302 5346-5629/ D/QBASDK: SubscribeService: subscribed already

```
I want to use FCM. 

From gradle:
```
def qbSdkVersion = '3.3.4'  
def fbSdkVersion = '11.8.0' 
dependencies {
...
    compile 'com.android.support:support-v4:25.2.0' // was v4:23.+
    compile "com.android.support:multidex:1.0.2" // was 1.0.0
    compile "com.quickblox:quickblox-android-sdk-core:$qbSdkVersion@aar"
    compile("com.quickblox:quickblox-android-sdk-chat:$qbSdkVersion@aar") {
        transitive = true
    }
    compile "com.quickblox:quickblox-android-sdk-content:$qbSdkVersion@aar"
    compile "com.quickblox:quickblox-android-sdk-messages:$qbSdkVersion@aar"
    compile "com.quickblox:quickblox-android-sdk-customobjects:$qbSdkVersion@aar"
    compile "com.quickblox:quickblox-android-sdk-location:$qbSdkVersion@aar"
    compile "com.quickblox:quickblox-android-sdk-videochat-webrtc:$qbSdkVersion@aar"

    compile 'com.facebook.android:facebook-android-sdk:4.22.1'

    compile "com.google.android.gms:play-services:$fbSdkVersion"
    compile "com.google.android.gms:play-services-gcm:$fbSdkVersion" 
    compile "com.google.firebase:firebase-messaging:$fbSdkVersion" 
    compile "com.google.firebase:firebase-core:$fbSdkVersion"  
...
apply plugin: 'com.google.gms.google-services'
```

I have included the google-services.json into the app top level directory

From Manifest file:
```
        <meta-data android:name="com.quickblox.messages.TYPE" android:value="FCM" />
        <meta-data android:name="com.quickblox.messages.SENDER_ID" android:value="@string/firebase_sender_id" />
        <meta-data android:name="com.quickblox.messages.QB_ENVIRONMENT" android:value="PRODUCTION" />

<service
            android:name="com.quickblox.messages.services.fcm.QBFcmPushListenerService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

        <service
            android:name="com.quickblox.messages.services.fcm.QBFcmPushInstanceIDService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>
```

The QB settings have the Firebase legacy server key for Dev and Production.

How do I debug this?? How can I narrow down to what the problem is?

**Comment by tatanka987** [comment]
1) check subscription for users in admin panel;
2) check subscription's environment where you send push (in your case it must be 'Live', because client subscribes to PRODUCTION environment);
3) if steps 1 and 2 didn't help, try remove app from device and install it again and check steps 1-2 again, collect logs and provide us for better understanding your issue. You can use [Gist](https://gist.github.com/) to post logs.

**Comment by prographo** [comment]
Thanks for getting back.

When I uninstalled and reinstalled, it registered with QB. 

It got the push no problem.

I am seeing this in logcat:
```
02-01 17:49:03.104 2883-2883/? I/Finsky: [1] com.google.android.finsky.ar.a.a(33): Selecting account [2f5_toafYnvcwIFymHyiTKuDdOg] for package com.xxx.xxx. overriding=[true]
02-01 17:49:03.105 2883-2883/? I/Finsky: [1] com.google.android.finsky.f.a.<init>(62): com.xxx.xxx is installed but certificate mistmatch
```

When I tap on the notification it does not open the app - I think that is to do with these messages in the log. I guess when I deploy from Android Studio it is not signing the apk with my release key, but some internal key.

**Comment by prographo** [comment]
Actually, even when I build it with the release key; tapping on the notification DOES NOT bring the app to the foreground.

Any clue why?

**Comment by prographo** [comment]
Also there is no sound/buzz as with other notifications.

**Comment by tatanka987** [comment]
QuickBlox Android SDK doesn't provide any work with notifications, you should himself realize work with notifications. Try review your code to found issues.

**Comment by faizanprogrammer** [comment]
can you tell me in sender id which value you typed ? it was project id or sender id which is placed in cloud message tab in firebase 
https://github.com/QuickBlox/quickblox-android-sdk/issues/538 also help me on this issue
Thanks

**Comment by tatanka987** [comment]
sender id means Sender ID from your firebase developer console from tab CLOUD MESSAGING, please see screenshot https://gyazo.com/0eb24e5e9b9958c2931b61a9d0636012

**Comment by Semafu** [comment]
@prographo put an intent in the notification, something like this:

```
                // Create notification

                final NotificationManager mNotificationManager =
                        (NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);

                NotificationCompat.Builder mBuilder =
                        new NotificationCompat.Builder(MyApplication.getAppContext())
                                .setSmallIcon(R.drawable.icon)
                                .setContentTitle(message)
                                .setContentText(message)
                                .setTicker(message);

                // Create pending intent, mention the Activity which needs to be
                //triggered when user clicks on notification

                PendingIntent contentIntent = PendingIntent.getActivity(context, 0,
                        new Intent(context, MainActivity.class), PendingIntent.FLAG_UPDATE_CURRENT );

                mBuilder.setContentIntent(contentIntent);

                mNotificationManager.notify(10, mBuilder.build());
```

**Comment by faizanprogrammer** [comment]
Thanks for answering i have solved my issue and now its working fine

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tatanka987** [comment]
issue was solved

**Comment by manojkraftly** [comment]
Any one can help me to resolve push issue iOS - Android?

**Comment by tatanka987** [comment]
@manojkraftly please create new issue and describe your problem more detailed (with steps to reproduce and logs)

**Comment by manojkraftly** [comment]
I have already mentioned full details in same ticket & paste log file there.
Please let me know if you need any other info then i will provide you here.
