### ISSUE TITLE
Load ChatHistory error

### ISSUE THREAD

**Issue by Shahjahan786** [QuickBlox/quickblox-android-sdk#537]
02-08 11:33:11.572 11281-11281/com.nayapay.app D/ChatHelper: Last read message time: 1517925045
02-08 11:33:11.573 11281-11281/com.nayapay.app D/QBASDK: =========================================================
                                                         === REQUEST ==== 5826ba85-4880-48a0-91d7-10818f7ad4f5 ===
                                                         REQUEST
                                                             GET https://apinayapay.quickblox.com//chat/Message.json
                                                         HEADERS
                                                             QuickBlox-REST-API-Version=0.1.1
                                                             QB-SDK=Android 3.5.0
                                                             QB-Token=37fd30bc2fd4dcf2731533f59df96053a6000010
                                                         PARAMETERS
                                                             sort_desc=date_sent
                                                             date_sent[gt]=1517925045
                                                             limit=100
                                                             chat_dialog_id=5a793a74876ca97ab56128f8
                                                         INLINE
                                                             GET https://apinayapay.quickblox.com//chat/Message.json?sort_desc=date_sent&date_sent[gt]=1517925045&limit=100&chat_dialog_id=5a793a74876ca97ab56128f8

02-08 11:33:12.249 11281-11281/com.nayapay.app D/QBASDK: *********************************************************
                                                         *** RESPONSE *** 5826ba85-4880-48a0-91d7-10818f7ad4f5 ***
                                                         STATUS : 500 
                                                         HEADERS
                                                             Status=500 Internal Server Error
                                                             Server=nginx/1.12.1
                                                             X-Request-Id=e50beea7-93f8-4093-a54a-ec49462f5fa8
                                                             X-Runtime=0.025288
                                                             Connection=close
                                                             X-Android-Received-Millis=1518089592217
                                                             Date=Thu, 08 Feb 2018 11:33:13 GMT
                                                             X-Android-Selected-Protocol=http/1.1
                                                             Strict-Transport-Security=max-age=31536000
                                                             X-Android-Response-Source=NETWORK 500
                                                             X-Android-Sent-Millis=1518089591863
                                                             Content-Length=48
                                                             Content-Type=application/json; charset=utf-8
                                                         BODY
                                                             '{"status":"500","error":"Internal Server Error"}'
02-08 11:33:12.275 11281-11281/com.nayapay.app E/ChatMessagesActivity: loadChatHistoryOnError We're sorry, but something went wrong. We've been notified about this issue and we'll take a look at it shortly.,Internal Server Error

**Comment by tatanka987** [comment]
looks like your issue related with server error, please contact our support team, provide this error and specify time zone for time from logs

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-chat-messaging#retrieve-chat-history](https://docs.quickblox.com/docs/android-chat-messaging#retrieve-chat-history)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
