### ISSUE TITLE
Can't start Quickblox Android SDK in my Project.

### ISSUE THREAD

**Issue by sheikhrashid** [QuickBlox/quickblox-android-sdk#545]
I have followed the official Quickblox guide, added everything, but don't know what is going wrong. I am receiving this error:

`Error:(40, 0) Could not find method сompile() for arguments [com.quickblox:quickblox-android-sdk-customobjects:3.7.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
`

**Comment by tatanka987** [comment]
which version of Gradle plugin do you use? Please provide us 'dependencies' part of your build.gradle file (module level). For connection Quickblox Android SDK need use:
Gradle 2: 
compile "com.quickblox:quickblox-android-sdk-chat:3.7.0"

Gradle 3:
implementation "com.quickblox:quickblox-android-sdk-chat:3.7.0"

**Comment by sheikhrashid** [comment]
There was an extreme strange thing. I can't believe. Check this: http://prntscr.com/iezwqs 

When I copy the compile line from here: https://github.com/QuickBlox/quickblox-android-sdk-releases
It doesn't work. It doesn't even find the **compile** text (as given in screenshot)

When I manually type the whole line, it started working.
