### ISSUE TITLE
Chat disconnects when app goes into background

### ISSUE THREAD

**Issue by prographo** [QuickBlox/quickblox-android-sdk#548]
SDK 3.3.0 Android

When the app goes into background the Chat disconnects. Is there a way to PREVENT this from happening? 

I want to detect if they receive message while app in background and generate local push.

**Comment by prographo** [comment]
My bad, chat was on UI thread, which is closed when app moves to background.

**Comment by ParryPatel021** [comment]
Hey, how did you resolve these issues?
Could you please explain it? OR it would be great if have some code snippets to address it.
