### ISSUE TITLE
getRegisteredUsersFromAddressBook is not working well

### ISSUE THREAD

**Issue by sheikhrashid** [QuickBlox/quickblox-android-sdk#549]
As Quickblox has updated their SDK with this method: **getRegisteredUsersFromAddressBook**

But I am facing a problem. I have registered the user on **Quickblox** through **Firebase verification**. 
Issue is, we are not getting the numbers matched exactly. 

**For Example:**
- user registered with login number **923209445751**
- address book have number **03209445751** or +**923209445751**

In this case, it is not returning the contact. 

==========================
On the other hand, **if both numbers are exactly same**, then it returns the contact.
How to solve this issue

**Comment by tatanka987** [comment]
new firebase user will be saved with phone number 923209445751 (in international format without '+'), you add contact to address book himself and you set phone himself, if you save contact with phone  '03209445751' but user register by phone '923209445751' you wont get notification from our server. If you save address book contact with phone '+923209445751' you should get user registered with phone '923209445751' for request getRegisteredUsersFromAddressBook

**Comment by sheikhrashid** [comment]
Then you should consider this fix in the next update. Otherwise, we can't get Registered users if the contact is not saved in international format in User's phone. 

I just gave an example of Pakistan. There can be a lot of countries, where users save the number in their format.

**Comment by tatanka987** [comment]
For correct work this feature you should save phone number in Address book in international format.
