### ISSUE TITLE
"Connection failed. Please check your internet connection" in QBContent

### ISSUE THREAD

**Issue by sheikhrashid** [QuickBlox/quickblox-android-sdk#551]
I have successfully implemented quickblox, registered user, get users. But when I try to upload the file in **QBContent**. It gives me QBResponseException with message **Connection failed. Please check your internet connection** 

here is the gist: https://gist.github.com/sheikhrashid/4af9ca6601b44fffbc9acd2df2966d94

My internet connection is working perfect.

What's the issue?

**Comment by tatanka987** [comment]
in logs I can see FileNotFoundException: ..... (Permission denied) did you provide permissions to read/write external storage in your AndroidManifest.xml? You can read about app permissions in Android documentation, for example [there](https://developer.android.com/guide/topics/permissions/index.html)

**Comment by sheikhrashid** [comment]
Crap, I was missing Runtime Permission. 
Issue resolved.

Thanks Quickblox Support
