### ISSUE TITLE
videochat no response  

### ISSUE THREAD

**Issue by ideav5** [QuickBlox/quickblox-android-sdk#554]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by tatanka987** [comment]
more details - more success ))) so, provide more information about your issue (steps to reproduce, full log from both sides (caller and receiver) etc. which will help us localize your issue).

**Comment by ideav5** [comment]
this demo  --> sample-videochat-webrtc videochat no response   you  can try it

**Comment by tatanka987** [comment]
Did you do any changes in code? If yes, please specify they and provide us full log as I asked before from both devices (caller and receiver).

**Comment by ideav5** [comment]
no ,I didn't change any code,3.6.0 is  ok  ,but 3.7.0 no response

**Comment by tatanka987** [comment]
I need logs

**Comment by RomanPronin** [comment]
Long time inactivity.
