### ISSUE TITLE
Need Info: does Quickblox support End-toEnd Encryption for chat like WhatsApp?

### ISSUE THREAD

**Issue by Shahjahan786** [QuickBlox/quickblox-android-sdk#555]
We want the chat between user A and User B be encrypted and secure like WhatsApp. 
Does this feature is currently supported by QuickBlox?

**Comment by tatanka987** [comment]
now QuickBlox Android SDK doesn't support encryption, but you can realize it on app side. Note: in this case you should realize same encryption mechanism for all platform (Android, iOS, web).
