### ISSUE TITLE
You cannot call create unless the parent is saved

### ISSUE THREAD

**Issue by Ahmadsawalhajo** [QuickBlox/quickblox-android-sdk#559]
Please  this issue happen with me when i make sign up so what is the solution 
is this my code .......
  final QBUser user = new QBUser("ahmad", "123456789");
        user.setExternalId("3056478");
        user.setFullName("Javfhfck Bold");
//        user.setPhone("+18904567812");
        StringifyArrayList<String> tags = new StringifyArrayList<String>();
        tags.add("car");
        tags.add("man");
        user.setTags(tags);
//        user.setWebsite("www.mysite.com");

        QBUsers.signUp(user).performAsync(new QBEntityCallback<QBUser>() {
            @Override
            public void onSuccess(QBUser user, Bundle args) {
                Log.e("onSuccess", "");
            }

            @Override
            public void onError(QBResponseException errors) {
                Log.e("onSuccess", errors.getMessage());
            }
        });

**Comment by RomanPronin** [comment]
I suppose you use the externalId or login which have already been taken.
