### ISSUE TITLE
How to Update GroupChat Dialog's Custom Data?

### ISSUE THREAD

**Issue by sheikhrashid** [QuickBlox/quickblox-android-sdk#565]
Hello,
Can I update GroupChat Dialog's Custom data? 

Only Found this in Documentation:
_**User can update group chat dialog name, add new occupants or leave this group chat**_

Thanks, 
Rashid

**Comment by sheikhrashid** [comment]
Can you tell me how can I copy the **ChatDialog's custom Data** to a New one, so I can update it. 

I am using this code right now: 
`QBDialogCustomData customData = new QBDialogCustomData(MyQBKeys.myClassName);
                qbChatDialog.copyFieldsTo(customData);
                customData.putString(MyQBKeys.gameStatus, MyQBKeys.COMPLETED);
                qbChatDialog.setCustomData(customData);`

But receiving this error:
https://gist.github.com/sheikhrashid/0bf0f10ff4370e8418a99f453cdf4410

**Comment by tatanka987** [comment]
for example, you have dialog with custom data, which you want to update, first get old custom data:
`QBDialogCustomData qbDialogCustomData = chatDialog.getCustomData();`

then update needed field:
`qbDialogCustomData.putString(MyQBKeys.gameStatus, MyQBKeys.COMPLETED);`

then set updated custom data to dialog:
`chatDialog.setCustomData(qbDialogCustomData);`

then update dialog with updated custom data:
`QBRestChatService.updateGroupChatDialog(chatDialog, null).perform();`

**Comment by sheikhrashid** [comment]
Thanks much. Please have a look of this issue as well sir. 
https://github.com/QuickBlox/quickblox-android-sdk/issues/562
