### ISSUE TITLE
how to get status user online/offline:

### ISSUE THREAD

**Issue by holu15795** [QuickBlox/quickblox-android-sdk#566]
i want get status user. 

Firstly: I using QBChatService.getInstance().getLastUserActivity but it is not realtime.

The second: i using Contact list. my code:
QBRoster chatRoster = QBChatService.getInstance().getRoster();
QBPresence presence = chatRoster.getPresence(idFriends);
if (presence.getType() == QBPresence.Type.online) {
    Log.d(TAG,"user online");
}else{
    Log.d(TAG,"user offline");
}

 it is always offline.
 Thx.

**Comment by RomanPronin** [comment]
Hi, @holu15795. Does the user have subscription to the contact's presence information?

**Comment by RomanPronin** [comment]
Long time inactivity.

**Comment by rishabhtech1994** [comment]
Can you please Let me know more about implementing about the online and offline status of a User in Android.
