### ISSUE TITLE
Android Release 3.7.0 and 3.8.0 not building successfully

### ISSUE THREAD

**Issue by xpressmobtech** [QuickBlox/quickblox-android-sdk#570]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)

**Environment details**
*(Operating system, browser information, SDK version)*

android studio 3.0.1 , gradle 4.1,min sdk 21 ,target sdk 27

**Did this work before?**

yes worked with 3.6.0 but stopped working at 3.7.0 and 3.8.0

**Expected behavior**

Build successfully like 3.6.0 version

**Actual behavior**

App build finishing with error.

**Logs**
*(please, use github [gist](https://gist.github.com/))*

#1
Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\xpress\.gradle\caches\transforms-1\files-1.1\google-webrtc-1.0.21217.aar\15fc535b954f743a2ad94480d58c9732\jars\classes.jar

#2 

Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing org/webrtc/VideoEncoderWrapper.class

#3 

Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)

#4 

Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\xpress\.gradle\caches\transforms-1\files-1.1\google-webrtc-1.0.21217.aar\15fc535b954f743a2ad94480d58c9732\jars\classes.jar

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by RomanPronin** [comment]
Hi, @xpressmobtech. Starting from 3.7.0 videochat-webrtc module migrated to Java version 1.8. So, add in your build.gradle module next lines:
`    compileOptions {`
   `     sourceCompatibility JavaVersion.VERSION_1_8`
    `    targetCompatibility JavaVersion.VERSION_1_8`
 `   }`

**Comment by xpressmobtech** [comment]
Thanks! Your solution worked perfectly.
