### ISSUE TITLE
No response received within reply timeout. Timeout was 5000ms (~5s)

### ISSUE THREAD

**Issue by kishorejethava** [QuickBlox/quickblox-android-sdk#571]
Getting time out exception when try set privacy list. can you please help me!!

`org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). Used filter: IQReplyFilter: iqAndIdFilter (AndFilter: (OrFilter: (IQTypeFilter: type=error, IQTypeFilter: type=result), StanzaIdFilter: id=7xMb4-52)), : fromFilter (OrFilter: (FromMatchesFilter (full): null, FromMatchesFilter (bare): 43736263-66505@chat.quickblox.com, FromMatchesFilter (full): chat.quickblox.com)).
`

Here is the code to set privacy list

       // set listener
        val privacyListListener = object : QBPrivacyListListener {
            override fun setPrivacyList(listName: String?, listItem: MutableList<QBPrivacyListItem>?) {
                Log.i(TAG,"Privacy listName:"+listName +" listItem:"+listItem.toString())
            }

            override fun updatedPrivacyList(listName: String?) {
                Log.i(TAG,"Privacy listName:"+listName)
            }
        };

        val privacyListsManager = QBChatService.getInstance().privacyListsManager
        privacyListsManager.addPrivacyListListener(privacyListListener)

        var lists : List<QBPrivacyList>? = null;
        try {
            lists = privacyListsManager.privacyLists
        } catch (e : SmackException.NotConnectedException ) {
            e.printStackTrace()
        } catch (e : XMPPException.XMPPErrorException) {
            e.printStackTrace()
        } catch (e : SmackException.NoResponseException) {  // got exception here
            e.printStackTrace()
        }

        val list =  QBPrivacyList()
        list.name = "public";

        val listPrivacyListItem = ArrayList<QBPrivacyListItem>()
        val qbPrivacyListItem = QBPrivacyListItem()
        qbPrivacyListItem.type = QBPrivacyListItem.Type.USER_ID
        qbPrivacyListItem.valueForType = profileModel!!.user!!.qbId
        qbPrivacyListItem.isMutualBlock = true

        listPrivacyListItem.add(qbPrivacyListItem);

        list.items = listPrivacyListItem;

        try {
            privacyListsManager.setPrivacyList(list)
        } catch (e : SmackException.NotConnectedException) {
            e.printStackTrace()
        } catch (e : XMPPException.XMPPErrorException ) {
            e.printStackTrace()
        } catch (e : SmackException.NoResponseException) { // got exception here
            e.printStackTrace()
        }
    }

**Comment by RomanPronin** [comment]
Hi, @kishorejethava, try to increase reply timeout just like this - `QBChatService.setDefaultPacketReplyTimeout(30000);`
