### ISSUE TITLE
Android Notifciations stops work

### ISSUE THREAD

**Issue by petergayduchik** [QuickBlox/quickblox-android-sdk#579]
***Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)***
[https://github.com/QuickBlox/quickblox-android-sdk/issues/431](https://github.com/QuickBlox/quickblox-android-sdk/issues/431)

Environment details
*(Operating system, browser information, SDK version)*
Android 
QuickBlox sdk 3.3.4

Did this work before?
yes

Hello again. Today or maybe yesterday push notification stops work. I cant understand what happened and i dont know how to test its work or not. 

I have used test data from firebase test push notification and my device received correctly any push notification. From Admin quickblox i cant receive anything. 
First answer : 
in production/development key - what i should put ?
Api Key
Server Api Key 
 or what ?

Second: On IOS PUSH works. Why its again stopped on android. Did you have any problem with server ? I cant fix this and i dont know its my problem or no. 

Im still using manual subscription with GCM. Becouse SDK Documentation still not updated and FCM is imposible to integrate. Everything old and everything not working . One way which i did with manual sub and GCM is was work last time in Friday 06 April 2018

**UPD**
I check you sample notification app . And there are method never called 
check screenshot pls. This is never called. But app tell me notification is coming .
[http://prntscr.com/j3shpg](http://prntscr.com/j3shpg)

few logs:

[http://prntscr.com/j3sibu](http://prntscr.com/j3sibu)
 [http://prntscr.com/j3siwu](http://prntscr.com/j3siwu)

Please help me . My client very angry

**Comment by RomanPronin** [comment]
I've just checked pushes and it works fine. Maybe there was some delaying on server side.
BTW on your screen logs I see MessagesActivity/Receiving event new-push-event.

**Comment by RomanPronin** [comment]
Do you mean showNotification()? If your app is in foreground it will not be shown, only in background look [here](https://github.com/QuickBlox/quickblox-android-sdk/blob/30cd66b63dc79cb15957c7b5d28bf67f938118c4/sample-core/src/main/java/com/quickblox/sample/core/gcm/CoreGcmPushListenerService.java#L9)

**Comment by petergayduchik** [comment]
1)I add Legacy Server Key from firebases to admin panel(Quickblox)
In section Production/Development
2)I have code which was work before.
3) I can send via PostMethod (firebase post request to send push) and i can use test notification from firebase console - PUSH WORKS
4) I can send via QuickbloxAdmin panel - PUSH NOT WORK!!! Just no info .. anything.
5) What i missing? How to detect problem ?????? 
i have all settings. And using manual subscription. In logs i see - subscription successful. 
from google json file - current_key  empty.
What can be wrong ? Its was work in friday or suturday.

**Comment by RomanPronin** [comment]
Firstly, if you subscribed to "DEVELOPMENT" environment (<meta-data android:name="com.quickblox.messages.QB_ENVIRONMENT" android:value="DEVELOPMENT" />) you should send push from admin panel Environment "Testing".
Secondly, after you sent message from admin panel (like [here](https://quickblox.com/developers/SimpleSample-messages_users-android#Send_Push_Notifications_from_Admin_panel) )you can always look at "Queue" tab in admin panel and download "Download detailed log" for your message, and see all info about push message state.
As for add Legacy Server Key, you can use just "Server Key", not legacy.
Also as you can see nothing has changed on our side, cause push in our sample works fine.
Maybe you've missed something, so compare your code with sample push notification or look at implementation [FcmPushListenerService](https://github.com/QuickBlox/q-municate-android/blob/62976920e8d200d3a402d87f14029f3b5693ca39/Q-municate_app/src/main/java/com/quickblox/q_municate/fcm/FcmPushListenerService.java#L14) (declaring service in [manifest](https://github.com/QuickBlox/q-municate-android/blob/3d55f03305764aba9f2b03d5e6a2d6bb6b72f125/Q-municate_app/src/main/AndroidManifest.xml#L203) )in Q-mun project.

**Comment by petergayduchik** [comment]
@RomanPronin 
1) here my user before subscription
http://prntscr.com/j46ria
2) here my user after subscription
http://prntscr.com/j46s2k
3) and here after i test push notification 
im using production - test push (LIVE) to all users  or by TAG
http://prntscr.com/j46syx
my subscription removed. What can be wrong ? Also i did not receive push in logs.

**Comment by petergayduchik** [comment]
@RomanPronin  ? :(

**Comment by RomanPronin** [comment]
As for subscription removing, likely you did SubscribeService.unSubscribeFromPushes(), or something like that, i.e. removed the subscription by yourself.
And from log I see "InvalidRegistration" error, that can meaning mismatch between the sender ID you are registering with and the API key.

**Comment by petergayduchik** [comment]
@RomanPronin how i can do this SubscribeService.unSubscribeFromPushes() if unsubscription right after i sent test notification in admin panel ?

**Comment by RomanPronin** [comment]
@petergayduchik Just for clarification, you say your user's push subscription deleted right after you send test push to all users or by TAG?
Can you check this case with several user with the same TAG? Are subscriptions deleted in all users?

**Comment by RomanPronin** [comment]
So, you do subscribe to pushes manually? Why don't you use Auto subscription feature?

**Comment by petergayduchik** [comment]
@RomanPronin i cant make auto subscription. Its not working. I was tried empty project. No subscription created in qb admin panel. Only after manual. :(

**Comment by petergayduchik** [comment]
@RomanPronin 
Auto subscription
Android manifest
http://prntscr.com/j4r5t2

codes:

http://prntscr.com/j4r6ia

No subscription in admin panel
and callback never called. 

For manual: 

http://prntscr.com/j4r71e
and this way was work in friday 6 apr 2018.

**Comment by RomanPronin** [comment]
Maybe something wrong with your registrationID.

Anyway, I highly recommend you to try again to set auto subscription.
QBSettings.getInstance().setEnablePushNotification(true); it is just a global setting to enable or disable Delivering pushes.
Subscription callback will be called after you login to REST (QBUsers.signIn();)
So, show logs after you make it.

**Comment by petergayduchik** [comment]
registrationID what is it ?

**Comment by RomanPronin** [comment]
registrationID - ID for application on GCM service. You set subscription.setRegistrationID(registrationID); what kind of registrationID do you set?
I say again, use auto subscription. It works perfectly.

**Comment by petergayduchik** [comment]
Omg finnaly i did it 
deviceId - changed on TelephonyManager
and api request to get registrationId and finnaly i receive push But its work only in manual subscription. 
I have no idea why its was work before. And why its stopped work in friday.
