### ISSUE TITLE
Error when sent message to group

### ISSUE THREAD

**Issue by tatdat10** [QuickBlox/quickblox-android-sdk#58]
Hi,
After lost network connection, i call function to login again, but when sent message to group, i have error message as below:

01-07 20:50:39.879: D/SMACK(6016): SENT (1): <message id='54ad39af535843b62910307d' to='18172_54ab92c3535c12c70102525c@muc.chat.quickblox.com' type='groupchat'><body>uuu</body><extraParams xmlns='jabber:client'><dialog_id>54ab92c3535c12c70102525c</dialog_id><date_sent>1420638639</date_sent><save_to_history>1</save_to_history></extraParams></message>

01-07 20:50:40.220: D/SMACK(6016): RCV (1): <message xmlns="jabber:client" type="error" id="54ad39af535843b62910307d" to="2162459-18172@chat.quickblox.com/356489057728094" from="18172_54ab92c3535c12c70102525c@muc.chat.quickblox.com"><body>uuu</body><extraParams xmlns="jabber:client"><dialog_id>54ab92c3535c12c70102525c</dialog_id><date_sent>1420638639</date_sent><save_to_history>1</save_to_history></extraParams><error type="auth" code="403"><forbidden xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></message>

Please show me where is the problem with the error message: error type="auth" code="403" forbidden xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" error".
 Thanks for your support.

The error in logcat:
01-08 00:11:57.577: E/XMPPConnection(23031): Exception in packet listener
01-08 00:11:57.577: E/XMPPConnection(23031): java.lang.NumberFormatException: Invalid int: "18172_54ab92c3535c12c70102525c@muc.chat.quickblox.com"
01-08 00:11:57.577: E/XMPPConnection(23031): 	at java.lang.Integer.invalidInt(Integer.java:137)
01-08 00:11:57.577: E/XMPPConnection(23031): 	at java.lang.Integer.parse(Integer.java:374)
01-08 00:11:57.577: E/XMPPConnection(23031): 	at java.lang.Integer.parseInt(Integer.java:365)
01-08 00:11:57.577: E/XMPPConnection(23031): 	at java.lang.Integer.parseInt(Integer.java:331)
01-08 00:11:57.577: E/XMPPConnection(23031): 	at com.quickblox.chat.utils.Utils.parseUserId(Utils.java:37)
01-08 00:11:57.577: E/XMPPConnection(23031): 	at com.quickblox.chat.QBPrivateChatManager.processIncomingPacket(QBPrivateChatManager.java:153)
01-08 00:11:57.577: E/XMPPConnection(23031): 	at com.quickblox.chat.QBPrivateChatManager$2.processPacket(QBPrivateChatManager.java:63)
01-08 00:11:57.577: E/XMPPConnection(23031): 	at org.jivesoftware.smack.XMPPConnection$ListenerWrapper.notifyListener(XMPPConnection.java:1233)
01-08 00:11:57.577: E/XMPPConnection(23031): 	at org.jivesoftware.smack.XMPPConnection$ListenerNotification.run(XMPPConnection.java:1143)
01-08 00:11:57.577: E/XMPPConnection(23031): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
01-08 00:11:57.577: E/XMPPConnection(23031): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-08 00:11:57.577: E/XMPPConnection(23031): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
01-08 00:11:57.577: E/XMPPConnection(23031): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
01-08 00:11:57.577: E/XMPPConnection(23031): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-08 00:11:57.577: E/XMPPConnection(23031): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-08 00:11:57.577: E/XMPPConnection(23031): 	at java.lang.Thread.run(Thread.java:841)

**Comment by soulfly** [comment]
After lost connection you must re-join all joined rooms

**Comment by tatdat10** [comment]
Hi soulfly,
As your suggestion, after reconnection successfull, i call function to rejoin all dialog but this issue is still happen. Thanks for your support.

private class ChatConnectionListener implements ConnectionListener {

        @Override
        public void connected(XMPPConnection connection) {
        	xmppConnection = connection;
        	ErrorUtils.logError("Refresh", "QBChatRestHelper=>connected()");
        }

        @Override
        public void authenticated(XMPPConnection connection) {
        	xmppConnection = connection;
        	ErrorUtils.logError("Refresh", "QBChatRestHelper=>authenticated()");
        }

        @Override
        public void connectionClosed() {
        	ErrorUtils.logError("Refresh", "QBChatRestHelper=>connectionClosed()");            
        }

        @Override
        public void connectionClosedOnError(Exception e) {
        	ErrorUtils.logError("Refresh", "QBChatRestHelper=>connectionClosedOnError()" + e.getMessage());
        }

        @Override
        public void reconnectingIn(int seconds) {
        	ErrorUtils.logError("Refresh", "QBChatRestHelper=>reconnectingIn(" + seconds + ")");            
        }

        @Override
        public void reconnectionSuccessful() {
        	ErrorUtils.logError("Refresh", "QBChatRestHelper=>reconnectionSuccessful");
        	LoadAndJoindAllDialogs();
        }

        @Override
        public void reconnectionFailed(Exception error) {
        	ErrorUtils.logError("Refresh", "QBChatRestHelper=>reconnectionFailed() " + error.getMessage());            
        }
    }

**Comment by soulfly** [comment]
Thanks, could you also post more SMACK logs like this before this crash 

01-07 20:50:39.879: D/SMACK(6016): SENT (1): uuu54ab92c3535c12c70102525c14206386391
01-07 20:50:40.220: D/SMACK(6016): RCV (1): uuu54ab92c3535c12c70102525c14206386391

**Comment by tatdat10** [comment]
I already updated the Quickblox SDK to latest version 2.1 and still have this issue. Please see more info in the log file: http://pastebin.com/2gZW9FWG
Thanks.
