### ISSUE TITLE
Doubts with the subscription to the push notifications

### ISSUE THREAD

**Issue by javieritis** [QuickBlox/quickblox-android-sdk#584]
In my personal project, i have OneSignal for push for the basic notifications of the application and Quickblox (3.7.0) for internal messaging.

I'm currently doing something wrong and I can not find a way to resolve the error, because both Quickblox and OneSignal give me a TOO_MANY_REGISTRATIONS error.

I would like someone to help me establish the subscription for the quickblox push.

I'm using real mobiles, not emulators.

My method to subscribe notifications and disable notifications when user logout un mi app.

https://i.imgur.com/bIssgGB.png
Right now I call the "subscribeToNotificationsPush" method after "QBChatService.getInstance (). Login" returns "onSuccess" ......
https://i.imgur.com/CPE3Yso.png

right now, because of a failure of mine it makes me
error: TOO_MANY_REGISTRATIONS

and I have 2 phones that do not receive push from Quickblox or OneSignal.

I would like someone to help me establish the code well and solve the error I have.

thanks you!!

**Comment by RomanPronin** [comment]
Hi, @javieritis, you should look at TOO_MANY_REGISTRATIONS [stackOverFlow answer](https://stackoverflow.com/questions/47529977/firebase-token-error-too-many-registrations?rq=1)

**Comment by javieritis** [comment]
@RomanPronin 
This post does not solve anything, I want to find a solution, not restore the image of the mobile.

Could you help me solve the error? I would like to see the correct code to automatically subscribe a device to push notifications.

**Comment by RomanPronin** [comment]
The correct code to automatically subscribe a device to push notifications can be found in [sample-pushnotification](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-pushnotifications) or in [sample-chat](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-chat).
Also, if you do SubscribeService.subscribeToPushes(), you should set QBSettings.getInstance().setSubscribePushStrategy(SubscribePushStrategy.MANUAL)

**Comment by javieritis** [comment]
What is the difference between manual and automatic?
it is best that a user when opening the app, subscribe automatically, no?

What do you recommend me??

**Comment by javieritis** [comment]
this documentations is confused
https://i.imgur.com/GGR1uDU.png

**Comment by RomanPronin** [comment]
The best way is when user make login to REST (QBUsers.signIn()) and right after that do subscribe to push - this is behavior by default if SubscribePushStrategy.ALWAYS
And right before user make signOut, do unsubscribe.

**Comment by javieritis** [comment]
ok, i will try this form.

Do you know how to solve the error? too_many_registrations

**Comment by javieritis** [comment]
thanks, now works fine! 😉
