### ISSUE TITLE
Localview placed below opponent view after onRemoteVideoTrackReceive

### ISSUE THREAD

**Issue by A2DNEW** [QuickBlox/quickblox-android-sdk#586]
I use Quickblox for video calls

Everything is good, but after onRemoteVideoTrackReceive, localview placed below opponentview. as a result, user not view itself video and only view opponent view

My code :

```
@Override
    public void onLocalVideoTrackReceive(BaseSession baseSession, QBRTCVideoTrack qbrtcVideoTrack) {
        Log.i("errorCheck","inVideo 999");
        localVideoTrack = qbrtcVideoTrack;

        mediaStreamManager = baseSession.getMediaStreamManager();
        qbrtcVideoTrack.addRenderer(new VideoRenderer(localView));
    }

    @Override
    public void onRemoteVideoTrackReceive(BaseSession baseSession, QBRTCVideoTrack qbrtcVideoTrack, Integer integer) {
        Log.i("errorCheck","inVideo 888");

        Log.i("errorCheck","inVideo 888 = "+localVideoTrack);

        mediaStreamManager = baseSession.getMediaStreamManager();
        qbrtcVideoTrack.addRenderer(new VideoRenderer(opponentView));

        localVideoTrack.removeRenderer(localVideoTrack.getRenderer());
        localVideoTrack.addRenderer(new VideoRenderer(localView));
        localView.setScalingType(RendererCommon.ScalingType.SCALE_ASPECT_FILL);
        localView.setMirror(true);
        localView.requestLayout();
    }
```

**Comment by RomanPronin** [comment]
I can assume that your opponentView surface view's surface is placed on top of localview cause this parameter - opponentView.setZOrderMediaOverlay(true).

**Comment by A2DNEW** [comment]
No i dont use `opponentView.setZOrderMediaOverlay(true)` anywhere
But i add `localView.setZOrderMediaOverlay(true)` and work for me
Thank you

**Comment by RomanPronin** [comment]
Resolved

**Comment by mechaadi** [comment]
@A2DNEW can you please send me the code for implementing video chat using Quickblox?
Its gonna save my lot of time, please?

**Comment by mechaadi** [comment]
@RomanPronin can you please send me a simple code for implementation of video chat using quickblox?
I am trying my best but not able to follow official docs, I am confused by the steps, if you can send me then it would be great for me.
