### ISSUE TITLE
create session error in quickblox 

### ISSUE THREAD

**Issue by PrithvirajChauhan** [QuickBlox/quickblox-android-sdk#59]
I put my app credential in sample chat demo but every time i get create session error 

01-08 03:20:53.909: D/QBASDK(828): *********************************************************
01-08 03:20:53.909: D/QBASDK(828): *** RESPONSE *** c227fce3-fe0b-4547-b37b-484acb9c23bf ***
01-08 03:20:53.909: D/QBASDK(828): STATUS : 401 
01-08 03:20:53.909: D/QBASDK(828): HEADERS
01-08 03:20:53.909: D/QBASDK(828):     Access-Control-Allow-Origin=*
01-08 03:20:53.909: D/QBASDK(828):     Cache-Control=no-cache
01-08 03:20:53.909: D/QBASDK(828):     Connection=keep-alive
01-08 03:20:53.909: D/QBASDK(828):     Content-Type=application/json; charset=utf-8
01-08 03:20:53.909: D/QBASDK(828):     Date=Thu, 08 Jan 2015 11:20:50 GMT
01-08 03:20:53.909: D/QBASDK(828):     QuickBlox-REST-API-Version=0.1.1
01-08 03:20:53.909: D/QBASDK(828):     Server=nginx/1.0.15
01-08 03:20:53.909: D/QBASDK(828):     Status=401 Unauthorized
01-08 03:20:53.909: D/QBASDK(828):     Transfer-Encoding=chunked
01-08 03:20:53.909: D/QBASDK(828):     X-Rack-Cache=invalidate, pass
01-08 03:20:53.909: D/QBASDK(828):     X-Request-Id=b93a2ea7496ec0ef9ad6291559e6c1b1
01-08 03:20:53.909: D/QBASDK(828):     X-Runtime=0.012184
01-08 03:20:53.909: D/QBASDK(828):     X-UA-Compatible=IE=Edge,chrome=1
01-08 03:20:53.909: D/QBASDK(828): BODY
01-08 03:20:53.909: D/QBASDK(828):     '{"errors":["Unauthorized"]}'

**Comment by soulfly** [comment]
Unauthorized means that your user's login and pass are wrong

You have to use the valid user's credentials to login

**Comment by PrithvirajChauhan** [comment]
Thank you for reply can you tell am doing right or wrong
1) I have to signup user
2) I have to create session using that session
3)After than i can successfully login my user

**Comment by PrithvirajChauhan** [comment]
Ok I am doing it totally wrong i solved the issue right flow is for new app
QBChatService.setDebugEnabled(true);
		QBSettings.getInstance().fastConfigInit(APP_ID, AUTH_KEY, AUTH_SECRET);
		if (!QBChatService.isInitialized()) {
			QBChatService.init(this);
		}
QBChatService		chatService = QBChatService.getInstance();
QBUser	user = new QBUser();
		user.setLogin(USER_LOGIN);
		user.setPassword(USER_PASSWORD);
1) First i have to create session like below code
public void CreateSession(){
		QBAuth.createSession( new QBEntityCallbackImpl<QBSession>(){
			@Override
			public void onSuccess(QBSession session, Bundle args) {

				// save current user
				//
				user.setId(session.getUserId());
				((ApplicationSingleton)getApplication()).setCurrentUser(user);

				// SignupUserto Chat
				//
				SignupUser(user);
			}

			@Override
			public void onError(List<String> errors) {
				AlertDialog.Builder dialog = new AlertDialog.Builder(SplashActivity.this);
				dialog.setMessage("create session errors: " + errors).create().show();
			}
		});
	}
2) If i don't have any user  then
private void SignupUser(final QBUser user) {
		// TODO Auto-generated method stub
		QBUsers.signUp(user,new QBEntityCallback<QBUser>() {
			@Override
			public void onSuccess(QBUser arg0, Bundle arg1) {
				// TODO Auto-generated method stub
                                // Login to that user
				loginToChat(user);
			}
			@Override
			public void onSuccess() {}
			@Override
			public void onError(List<String> arg0) {}
		});

	}
3) After login to that user
private void loginToChat(final QBUser user){

		chatService.login(user, new QBEntityCallbackImpl() {
			@Override
			public void onSuccess() {
				// Start sending presences
				try {
chatService.startAutoSendPresence(AUTO_PRESENCE_INTERVAL_IN_SECONDS);
				} catch (SmackException.NotLoggedInException e) {
					e.printStackTrace();
				}
			}
			@Override
			public void onError(List errors) {}
		});
	}

**Comment by manasikaranjkar** [comment]
i am getting same error...all my credentials are okay still the error.pls help

**Comment by samarth220194** [comment]
Please help me also .Well If i am logging in to the chat application then where i have to put my user login and password.

**Comment by RomanPronin** [comment]
Here is link how to do it  http://quickblox.com/developers/Android_XMPP_Chat_Sample#Login_to_Chat

**Comment by naisargparmar** [comment]
I am facing the same problem. While I have used the same code with new application credential, which is working well. Also I have created new QuickBlox account and created new Application, with this, working perfectly.
