### ISSUE TITLE
chatDialog.initForChat(QBChatService.getInstance()); blocks UI for about more than 15 seconds if Device is connected to a wifi/data but no internet is available

### ISSUE THREAD

**Issue by Shahjahan786** [QuickBlox/quickblox-android-sdk#599]
chatDialog.initForChat(QBChatService.getInstance()); blocks UI(Showing black screen) for about more than 15 seconds if Device is connected to a wifi/3g but no internet is available.

06-01 11:42:00.147 32002-32002/com.my.app D/ChatMessagesActivity: initForChat[start]1527835320147
06-01 11:42:00.148 32002-32002/com.my.app D/ChatMessagesActivity: initForChat[end]1527835320148
    initForChat[tim took]1 ms
06-01 11:42:06.347 32002-32002/com.my.app D/ChatMessagesActivity: initForChat[start]1527835326347
06-01 11:42:06.348 32002-32002/com.my.app D/ChatMessagesActivity: initForChat[end]1527835326348
    initForChat[tim took]1 ms
06-01 11:42:12.623 32002-32002/com.my.app D/ChatMessagesActivity: initForChat[start]1527835332623
06-01 11:42:47.248 32002-32002/com.my.app D/ChatMessagesActivity: initForChat[end]1527835367248
    initForChat[tim took]34625 ms
06-01 11:43:52.851 32002-32002/com.my.app D/ChatMessagesActivity: initForChat[start]1527835432851
06-01 11:44:27.348 32002-32002/com.my.app D/ChatMessagesActivity: initForChat[end]1527835467348
    initForChat[tim took]34497 ms
06-01 11:45:58.698 32002-32002/com.my.app D/ChatMessagesActivity: initForChat[start]1527835558698
06-01 11:46:07.444 32002-32002/com.my.app D/ChatMessagesActivity: initForChat[end]1527835567444
06-01 11:46:07.445 32002-32002/com.my.app D/ChatMessagesActivity: initForChat[tim took]8746 ms

**Comment by Shahjahan786** [comment]
Is there anyone to update on this?

**Comment by soulfly** [comment]
Hi @Shahjahan786 
I'm Igor, CTO, left the company, 
so not sure what is going on now with the product...

**Comment by Shahjahan786** [comment]
Thanks @soulfly for your quick response, Is there anyone to whom I may contact about this?

**Comment by RoudyK** [comment]
@soulfly What do you mean?

**Comment by RoudyK** [comment]
@soulfly Apologies, misunderstood.

**Comment by soulfly** [comment]
@RoudyK  no worries, man 🍺

**Comment by vadimkhmyrovqb** [comment]
@Shahjahan786 We do not support cases of internet loss. At the moment, to avoid the problem you described, some additional logic needs to be implemented client-side.
