### ISSUE TITLE
Unable to find user in quickblox

### ISSUE THREAD

**Issue by PrithvirajChauhan** [QuickBlox/quickblox-android-sdk#60]
I am successfully integrated quickblox in my application i have two user in app when after login  i try to fetch  users i got blank array do i have to do subscribe ans subscribed to user  like we do  using asmack  in quickblox ?

**Comment by soulfly** [comment]
No you don't

Which request do you use to get users?

**Comment by PrithvirajChauhan** [comment]
QBRequestGetBuilder customObjectRequestBuilder = new QBRequestGetBuilder();
        customObjectRequestBuilder.setPagesLimit(100);

        QBChatService.getChatDialogs(null, customObjectRequestBuilder, new QBEntityCallbackImpl<ArrayList<QBDialog>>() {
            @Override
            public void onSuccess(final ArrayList<QBDialog> dialogs, Bundle args) {
                // collect all occupants ids
                //
                List<Integer> usersIDs = new ArrayList<Integer>();
                for(QBDialog dialog : dialogs){
                    usersIDs.addAll(dialog.getOccupants());
                }

                // Get all occupants info
                //
                QBPagedRequestBuilder requestBuilder = new QBPagedRequestBuilder();
                requestBuilder.setPage(1);
                requestBuilder.setPerPage(usersIDs.size());
                //
                QBUsers.getUsersByIDs(usersIDs, requestBuilder, new QBEntityCallbackImpl<ArrayList<QBUser>>() {
                    @Override
                    public void onSuccess(ArrayList<QBUser> users, Bundle params) {

                        // Save users
                        //
                        ((ApplicationSingleton)getApplication()).setDialogsUsers(users);

                        // build list view
                        //
                        buildListView(dialogs);
                    }

                    @Override
                    public void onError(List<String> errors) {
                        AlertDialog.Builder dialog = new AlertDialog.Builder(DialogsActivity.this);
                        dialog.setMessage("get occupants errors: " + errors).create().show();
                    }

                });
            }

            @Override
            public void onError(List<String> errors) {
                AlertDialog.Builder dialog = new AlertDialog.Builder(DialogsActivity.this);
                dialog.setMessage("get dialogs errors: " + errors).create().show();
            }
        });
    }

**Comment by soulfly** [comment]
What is in usersIDs?

Do you have users with these ids in admin panel?

**Comment by PrithvirajChauhan** [comment]
Yes i  have ,2183733 is my UserId

**Comment by soulfly** [comment]
Ok, then please send logs of this request from Logcat

**Comment by mahfuzislam14** [comment]
i integrate the quickblox successfully in my android app.but i am not able to see the list of users.why?

**Comment by tatanka987** [comment]
@mahfuzislam14 check in admin panel permission to retrieve users via API, for it go to Home -> app name -> Users -> Users Settings ([see screenshot](https://gyazo.com/35a188d0eef1f64fcd12adc4091bedd1)) and tick mark on item 'Allow to retrieve other user's info'.

**Comment by mahfuzislam14** [comment]
i did it earlier but i am still not able to see the user list it is still hidden

**Comment by tatanka987** [comment]
@mahfuzislam14  please provide us log with request and response for getting users

**Comment by mahfuzislam14** [comment]
sir,i can retrieve any user,work with user,can login,able to create chat dialog all is work really fine.but my problem is that i cannot see the list of the user of my app in the admin panel.

**Comment by tatanka987** [comment]
did you check APP_ID in your mobile app and in admin panel? they are same? try create user manually in admin panel and found it in mobile app, it is working?

**Comment by mahfuzislam14** [comment]
yes,sir.my APP_ID is same,i can create user manually and  use it.as i said earlier in my comment all are working fine but i cannot see my user list it is hidden in my admin panel.one another problem is arrive today whenever i create any chat dialog with any user it is all the time create the dialog with the same user.
