### ISSUE TITLE
QuickBlox Application status - API call count

### ISSUE THREAD

**Issue by vineeshtp** [QuickBlox/quickblox-android-sdk#612]
Hi

Let me know How quickblox calculating the All API count in Application status section, Which is used to draw the graph.
For 2 days it shows around 10,000 api calls. I haven't used this much much of api calls.
If any documentation available, please let me know.

**Environment details**
*(Operating system, browser information, SDK version)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by vineeshtp** [comment]
Any updates. please

**Comment by alexanderkoqb** [comment]
Hi @vineeshtp. QB is alive and running! Reddis server counts the API calls. If you have a lot of users then do not get too surprised that API call limit is reached.

**Comment by vadimkhmyrovqb** [comment]
@vineeshtp is this issue still relevant? If yes, please submit a ticket on our portal and we will be glad to assist: https://assist.quickblox.com/index.php?/Tickets/Submit
