### ISSUE TITLE
Security Alert Google Play Developer Console

### ISSUE THREAD

**Issue by woutergoossens** [QuickBlox/quickblox-android-sdk#62]
I recently updated my Android application with the QuickBlox SDK and now I saw this Security Alert in the Google Play Developer Console.

When I run the command I get:
OpenSSL 1.0.1e 11 Feb 2013

Can you confirm that you are using this version and if possible can you update the OpenSSL?

Thanks!

Your app is statically linking against a version of OpenSSL that has multiple security vulnerabilities. You should update OpenSSL as soon as possible.
The vulnerabilities were addressed in OpenSSL versions beginning with 1.0.1h, 1.0.0m, and 0.9.8za. To confirm your OpenSSL version, you can do a grep via ("$ unzip -p YourApp.apk | strings | grep "OpenSSL""). For more information about the vulnerability, please consult http://www.openssl.org/news/secadv_20140605.txt.
To confirm that you've upgraded correctly, upload the updated version to the Developer Console and check back after five hours.
Please note, while it's unclear whether these specific issues affect your application, applications with vulnerabilities that expose users to risk of compromise may be considered "dangerous products" and subject to removal from Google Play.

**Comment by soulfly** [comment]
Please try our latest Android SDK

http://quickblox.com/developers/Android#Download_Android_SDK

**Comment by histone** [comment]
@soulfly, did you people fixed it?
