### ISSUE TITLE
Not able to send Chat from Adapterclass

### ISSUE THREAD

**Issue by PrithvirajChauhan** [QuickBlox/quickblox-android-sdk#63]
Hello , I successfully integrate single chat and its work like a charm. now my question is when i try to send some message from my Adapter class like i want to resend some message  chat object gets null. 
what should i do now

**Comment by soulfly** [comment]
Can you provide some code to better understand your issue

**Comment by PrithvirajChauhan** [comment]
package app.alumnikonnect.utils;


import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.apache.http.NameValuePair;
import org.jivesoftware.smack.Chat;
import org.jivesoftware.smack.ChatManager;
import org.jivesoftware.smack.ConnectionListener;
import org.jivesoftware.smack.MessageListener;
import org.jivesoftware.smack.PacketListener;
import org.jivesoftware.smack.SmackException;
import org.jivesoftware.smack.XMPPConnection;
import org.jivesoftware.smack.XMPPException;

import android.app.Dialog;
import android.content.Context;
import android.graphics.Bitmap;
import android.os.Bundle;
import android.os.Handler;
import android.support.v4.app.Fragment;
import android.util.Log;
import android.view.KeyEvent;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.view.animation.Animation;
import android.view.inputmethod.InputMethodManager;
import android.widget.BaseAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.ListView;
import android.widget.TextView;
import app.aluminikonnect.xmpp.PresencePacketListener;
import app.aluminikonnect.xmpp.PrivateChatManagerImpl;
import app.aluminikonnect.xmpp.XmppBuddies;
import app.aluminikonnect.xmpp.XmppConnectionChangeListener;
import app.aluminikonnect.xmpp.XmppDeliveryReceipts;
import app.alumnikonnect.asyntask.Communicator;
import app.alumnikonnect.classpar.Loginparameter.Chat_Single_Message;
import app.alumnikonnect.classpar.Loginparameter.GroupChat_;
import app.alumnikonnect.database.Database;
import app.alumnikonnect.ui.R;

import com.andinrajesh.emojicon.EmojiPopup;
import com.nostra13.universalimageloader.core.DisplayImageOptions;
import com.nostra13.universalimageloader.core.ImageLoader;
import com.quickblox.chat.model.QBChatMessage;
import com.quickblox.chat.model.QBDialog;

public class MyClass extends Fragment implements OnClickListener {

	View rootView;
	Communicator communicator;
	static ListView lstvw;
	final static String TAG = "GB.XmppConnection";

	private static Handler mHandler = new Handler();


	EditText userTypedMessage;
	Button sendButton;
	String imgicon_strng;
	ImageView imgvw_mgrpicon;
	ImageLoader imageLoader;
	public boolean islong=false;
	Animation anim,anim1;
	public static int clickedRowID = -1;
	public static int clickedRowIDdelete = -1;

	Bitmap bitmap = null;
	static ArrayList<Chat_Single_Message> arrayList_chat=new ArrayList<Chat_Single_Message>();
	Chat_Single_Message chat_Single_Message;
	EmojiPopup popup;
	Button emojiButton;
	TextView txt_mgname,txt_slogan;
	public static TextView txt_membersgname;
	ImageView emoticonsButton;
	ImageView imgvwsend;
	Dialog dialogchooser;
	public static final int PICK_IMAGE = 1;

	public static String TOCHATUSERNAME = "";

	static Database database;
	static AwesomeAdapterSingle 	adapter;
	static Context activitycontext;

	static String str_sdcardpath ;
	Thread thread=null;
	MessageListener messageListener;
	boolean isresult=false;

	Chat newChat;
	ChatManager chatmanager;
	//Variable to check message send succesfully
	String hassend="0";

	// Indicates the current state of the service (disconnected/connecting/connected)
	public static final int DISCONNECTED = 1;
	public static final int CONNECTING = 2;
	public static final int CONNECTED = 3;
	// A "transient" state - will only be DISCONNECTING *during* a call to stop()
	public static final int DISCONNECTING = 4;
	// This state means we are waiting for a retry attempt etc.
	// mostly because a connection went down
	public static final int WAITING_TO_CONNECT = 5;
	// We are waiting for a valid data connection
	public static final int WAITING_FOR_NETWORK = 6;

	PresencePacketListener listener;

	
	private final String PROPERTY_SAVE_TO_HISTORY = "save_to_history";
	public  ArrayList<GroupChat_> groupChat_s=new ArrayList<GroupChat_>();

	private app.aluminikonnect.xmpp.ChatManager chat;
	//int i=0;
	@Override
	public View onCreateView(LayoutInflater inflater, ViewGroup container,
			Bundle savedInstanceState) {
		// TODO Auto-generated method stub
		rootView = inflater.inflate(R.layout.simple_chat, container, false);  
		rootView.setFocusableInTouchMode(true);
		rootView.requestFocus();
		activitycontext=getActivity();
		//	Integer opponentID = ((ApplicationSingleton)activitycontext).getOpponentIDForPrivateDialog(dialog);
		chat = new PrivateChatManagerImpl(MyClass.this, 12345,getActivity());		
		rootView.setOnKeyListener(new View.OnKeyListener() {
			@Override
			public boolean onKey(View v, int keyCode, KeyEvent event) {
				Log.i("Tag", "keyCode: " + keyCode);
				if (keyCode == KeyEvent.KEYCODE_BACK) {
					Log.i("Tag", "onKey Back listener is working!!!");
					XmppUtils.issingleChatcall=false;
					return true;
				} else {
					return false;
				}
			}
		});
		return rootView;
	}
	

	public static void setListAdapter() {
		mHandler.post(new Runnable() {
			public void run() {
				arrayList_chat=database.GetAllSingleChatData("12345");	
				MyClass chatGroupFragment=new MyClass();
				adapter = chatGroupFragment.new  AwesomeAdapterSingle(arrayList_chat,activitycontext);
				adapter.notifyDataSetChanged();
				lstvw.setAdapter(adapter);
			}
		});
	}
	private void setlistiners() {
		// TODO Auto-generated method stub
		sendButton.setOnClickListener(this);
		imgvwsend.setOnClickListener(this);
		
	}

	private void initconrols() {
		// TODO Auto-generated method stub

		userTypedMessage=(EditText)rootView.findViewById(R.id.userMessageBox);
		emoticonsButton = (ImageView) rootView.findViewById(R.id.emoticons_button);
		imgvwsend=(ImageView)rootView.findViewById(R.id.imgvwsend);
		txt_mgname=(TextView)rootView.findViewById(R.id.txt_mgname);
		txt_slogan=(TextView)rootView.findViewById(R.id.txt_slogan);
		emojiButton=(Button)rootView.findViewById(R.id.emojiButton);
		txt_membersgname=(TextView)rootView.findViewById(R.id.txt_membersgname);


		imgvw_mgrpicon=(ImageView)rootView.findViewById(R.id.imgvw_mgrpicon);
		txt_mgname.setText(getArguments().getString("name", null)+" ");
		txt_slogan.setText(getArguments().getString("seen", null)+" ");
		options = new DisplayImageOptions.Builder()
		.showStubImage(R.drawable.ic_launcher)
		.showImageForEmptyUri(R.drawable.ic_launcher)
		.cacheInMemory().cacheOnDisc().build();
		imageLoader = ImageLoader.getInstance();
		sendButton=(Button)rootView.findViewById(R.id.sendButton);
		lstvw=(ListView)rootView.findViewById(R.id.lstvw);
	}


	
	private void SendChat(String convertjson, String isupdate) {
		// TODO Auto-generated method stub		
		try {
			QBChatMessage chatMessage = new QBChatMessage();
			chatMessage.setBody(convertjson);
			chatMessage.setProperty(PROPERTY_SAVE_TO_HISTORY, "1");
			hassend="1";
			userTypedMessage.setText("");
			chat.sendMessage(chatMessage);
		} catch (XMPPException e) {
			Log.e(TAG, "failed to send a message", e);
			hassend="0";
			userTypedMessage.setText("");
		} catch (SmackException sme){
			Log.e(TAG, "failed to send a message", sme);
			hassend="0";
			userTypedMessage.setText("");
		}
	}





	@Override
	public void onClick(View v) {
		// TODO Auto-generated method stub
		InputMethodManager imm = (InputMethodManager) getActivity().getSystemService(Context.INPUT_METHOD_SERVICE);
		switch (v.getId()) {		
		case R.id.sendButton:
			String convertjson = "";
			imm.hideSoftInputFromWindow(getView().getWindowToken(), 0);
			SendChat(convertjson," ");
			break;
	
		default:
			break;
		}
	}
	/**
	 * 
	 * 
	 * @author PruthviChauhan
	 *
	 */
	public class AwesomeAdapterSingle extends BaseAdapter{
		private Context mContext;
		private ArrayList<Chat_Single_Message> mMessages;
		String date_match="";
		Communicator communicator;
		com.sromku.simple.fb.example.imageloader.ImageLoader _imageLoader;
		//Progress bar variables
		int myProgress=0;

		public AwesomeAdapterSingle(ArrayList<Chat_Single_Message> arrayList_chat, Context activitycontext) {
			super();
			this.mContext = activitycontext;
			this.mMessages = arrayList_chat;
			communicator=new Communicator();
			_imageLoader=new com.sromku.simple.fb.example.imageloader.ImageLoader(mContext);
			
		}
		@Override
		public int getCount() {
			return mMessages.size();
		}
		@Override
		public Object getItem(int position) {		
			return mMessages.get(position);
		} 
		@Override
		public View getView(final int position, View convertView, ViewGroup parent) {
			final Chat_Single_Message message = (Chat_Single_Message) this.getItem(position);

			final ViewHolder1 holder;
			final Handler handler=new Handler();
			if(convertView == null)
			{
				holder = new ViewHolder1();
				convertView = LayoutInflater.from(mContext).inflate(R.layout.sms_row, parent, false);
				holder.view1=(View)convertView.findViewById(R.id.view1);
				holder.message = (TextView) convertView.findViewById(R.id.message_text);	
				holder.imgvmsg=(ImageView)convertView.findViewById(R.id.imgvmsg);
					convertView.setTag(holder);
			}
			else
				holder = (ViewHolder1) convertView.getTag();

			
			holder.message.setOnClickListener(new OnClickListener() {
				@Override
				public void onClick(View v) {
					// TODO Auto-generated method stub
					try {
						QBChatMessage chatMessage = new QBChatMessage();
						chatMessage.setBody("Message");
						chatMessage.setProperty(PROPERTY_SAVE_TO_HISTORY, "1");
						chat.sendMessage(chatMessage);
						arrayList_chat=database.GetAllSingleChatData("12345");	
						adapter.notifyDataSetChanged();
						setListAdapter();
					} catch (XMPPException e) {		
						hassend="0";
						
						Log.e(TAG, "failed to send a message", e);
					} catch (SmackException sme){
						Log.e(TAG, "failed to send a message", sme);
						hassend="0";
						userTypedMessage.setText("");
						Log.e(TAG, "failed to send a message", sme);
					}
				}
			});
			return convertView;
		}
		// Send like unlike data From Group Chat
		// O for Unlike 1 For Like
		protected void SetLikeUnlike(final int i, List<NameValuePair> nameValuePairs, final TextView message_unlike_count, final int count, final String chatid) {}
		private  class ViewHolder1
		{
			TextView message;
			TextView message_unlike_count,message_date;		
			ImageView imgvmsg;
			View view1;
		}

		@Override
		public long getItemId(int position) {
			//Unimplemented, because we aren't using Sqlite.
			return position;
		}

	}
}
