### ISSUE TITLE
IOS not receiving push Notification

### ISSUE THREAD

**Issue by avik1990** [QuickBlox/quickblox-android-sdk#634]
private void sendChatMessage(String text, QBAttachment attachment) {
        QBChatMessage chatMessage = new QBChatMessage();
        if (attachment != null) {
            chatMessage.addAttachment(attachment);
        } else {
            chatMessage.setBody(text);
        }
        chatMessage.setSaveToHistory(true);
        chatMessage.setDateSent(System.currentTimeMillis() / 1000);
        //chatMessage.setSenderId(qbChatDialog.getLastMessageUserId());
        chatMessage.setDeliveredIds(Collections.singleton(qbChatDialog.getLastMessageUserId()));
        chatMessage.setReadIds(Collections.singleton(qbChatDialog.getLastMessageUserId()));
        chatMessage.setMarkable(true);
        boolean sendToDialog = true; //set true to send this message to the chat or false to create it.
        if (!QBDialogType.PRIVATE.equals(qbChatDialog.getType()) && !qbChatDialog.isJoined()) {
            Toaster.shortToast("You're still joining a group chat, please wait a bit");
            return;
        }

        try {
            qbChatDialog.sendMessage(chatMessage);

            if (QBDialogType.PRIVATE.equals(qbChatDialog.getType())) {
                showMessage(chatMessage);
            }

            if (attachment != null) {
                attachmentPreviewAdapter.remove(attachment);
            } else {
                messageEditText.setText("");
            }

            Integer opponentId = qbChatDialog.getRecipientId();
            QBUser user = QbUsersHolder.getInstance().getUserById(opponentId);

            StringifyArrayList<Integer> userIds = new StringifyArrayList<>();
            userIds.add(opponentId);

            QBEvent event = new QBEvent();
            event.setUserIds(userIds);
            event.setEnvironment(QBEnvironment.DEVELOPMENT);
            event.setNotificationType(QBNotificationType.PUSH);
            event.setPushType(QBPushType.GCM);

            HashMap<String, Object> data = new HashMap<>();
            data.put("data.message", loggedUserFullname + " says " + chatMessage.getBody());
            data.put("data.userName", loggedUserFullname);
            data.put("data.type", "QBPushMessage");
            data.put("data.userId", loggedUseRID);
            data.put("data.notificationType", "QBPushMessage");
            data.put("data.dialogId", qbChatDialog.getDialogId().toString());
            data.put("data.ios_badge", "1");

            event.setMessage(data);
           /* try {
                event.setMessage(data);
            } catch (Exception e) {
                e.printStackTrace();
            }*/

           // String pushMsg = new Gson().toJson(event);
            //Log.d("PushMessage", pushMsg);

            /*QuickBloxChatPushModel chatPushModel = new QuickBloxChatPushModel();
            chatPushModel.setDialog_header("" + loggedUserFullname);
            chatPushModel.setDialog_type(QuickBloxChatPushModel.PUSH_EVENT_DIALOG_TYPE_PRIVATE);
            chatPushModel.setDialog_id(qbChatDialog.getDialogId());
            chatPushModel.setMessage(loggedUserFullname + ": " + text);

            String pushMsg = new Gson().toJson(chatPushModel);*/
            // event.setMessage(data);
            QBPushNotifications.createEvent(event).performAsync(new QBEntityCallback<QBEvent>() {
                @Override
                public void onSuccess(QBEvent qbEvent, Bundle args) {
                    // sent
                    //Toast.makeText(ChatActivity.this, qbEvent.getGSMMessage(), Toast.LENGTH_SHORT).show();
                    //CreateMessage(chatMessage, sendToDialog);
                }

                @Override
                public void onError(QBResponseException errors) {
                    //Toast.makeText(ChatActivity.this, errors.getMessage(), Toast.LENGTH_SHORT).show();
                    //CreateMessage(chatMessage, sendToDialog);
                }
            });
        } catch (SmackException.NotConnectedException e) {
            Log.w(TAG, e);
            Toaster.shortToast("Can't send a message, You are not connected to chat");
        }
    }

**Comment by avik1990** [comment]
Android - Android
Ios - Android
Push is working but from Android to IOS the push is not working

**Comment by tempersitu** [comment]
@avik1990 You didn't send notification to ios, you only sent to android. try below code(it's kotlin and convert to java if you need). 

private fun sendIOSNotification(dialog: QBChatDialog, message: String) {
        try{
            val userIds = StringifyArrayList<Int>()
            dialog.occupants.filter { it.toString() != qbUser?.id?.toString() }.forEach {
                userIds.add(it)
            }

            val event: QBEvent = QBEvent()
            event.userIds = userIds
            event.environment = if (BuildConfig.FLAVOR == "prod") {
                QBEnvironment.PRODUCTION
            } else {
                QBEnvironment.DEVELOPMENT
            }
            event.notificationType = QBNotificationType.PUSH
            event.pushType = QBPushType.APNS

            val data = HashMap<String, Any>()
            val apsData = HashMap<String, Any>()
            apsData.put("alert", "${MemberManager.user?.name}: $message")
            apsData.put("sound", "default")
            data.put("aps", apsData)
            data.put("dialog_id", dialog.dialogId)
            data.put("type", "chat_dialog")


            event.setMessage(data)

            QBPushNotifications.createEvent(event).performAsync(object : QBEntityCallback<QBEvent> {
                override fun onError(p0: QBResponseException?) {
                    log("send message ios notification fail")
                    log("${p0?.message}")
                }

                override fun onSuccess(p0: QBEvent?, p1: Bundle?) {
                    log("send message ios notification success")
                }
            })
        }catch (e:Exception){
            e.printStackTrace()
        }
    }

    private fun sendAndroidNotification(dialog: QBChatDialog, message: String) {
        try{
            val userIds = StringifyArrayList<Int>()
            dialog.occupants.filter { it.toString() != qbUser?.id?.toString() }.forEach {
                userIds.add(it)
            }

            val event: QBEvent = QBEvent()
            event.userIds = userIds
            event.environment = if (BuildConfig.FLAVOR == "prod") {
                QBEnvironment.PRODUCTION
            } else {
                QBEnvironment.DEVELOPMENT
            }
            event.notificationType = QBNotificationType.PUSH
            event.pushType = QBPushType.GCM

            val map: HashMap<String, Any> = HashMap()
            map.put("data.message", "${MemberManager.user?.name}: $message")
            map.put("data.dialog_id", dialog.dialogId)
            map.put("data.type", "chat_dialog")

            event.setMessage(map)

            QBPushNotifications.createEvent(event).performAsync(object : QBEntityCallback<QBEvent> {
                override fun onError(p0: QBResponseException?) {
                    log("send message android notification fail")
                    log("${p0?.message}")
                }

                override fun onSuccess(p0: QBEvent?, p1: Bundle?) {
                    log("send message android notification success")
                }
            })
        }catch (e:Exception){
            e.printStackTrace()
        }
    }

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-push-notifications](https://docs.quickblox.com/docs/android-push-notifications)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
