### ISSUE TITLE
VideoChatWebRTC - delay in sending messages

### ISSUE THREAD

**Issue by ZaLeXemre** [QuickBlox/quickblox-android-sdk#64]
I am trying to implement the videochat module to my ongoing android project. I have reviewed based my code on the sample provided on github and also read the documentation on your site.

Login activity : http://pastebin.com/6vjrq6UD
Videochat activity : http://pastebin.com/DqTHztJK
Testing on 2 xperia z2 physical devices ( A - device 1, B-device 2)

A calls B, the call message is not sent to B by asmack till the call is timed out (callTimer in the sample app) on A site. After timeout B receives the call message but, of course, when B accepts the call nothing happens. 

I hope you can answer or at least interact with this question.

p.s = do we have to change the user and credentials in pc_config.txt :

{'iceServers': [{'url': 'stun:stun.l.google.com:19302'}, {'url': 'turn:turnserver.quickblox.com:3478?transport=udp',
                                 'username': 'user',
                                 'credential': 'user'},
                                {'url': 'turn:turnserver.quickblox.com:3478?transport=tcp',
                                  'username': 'user',
                                  'credential': 'user'}]};

**Comment by tatanka987** [comment]
Use latest version of QuickBlox Android SDK https://quickblox.com/developers/Android
Closed for long inactivity.
