### ISSUE TITLE
Issues when updating API version from 2.0 to 2.1

### ISSUE THREAD

**Issue by JoCodes** [QuickBlox/quickblox-android-sdk#65]
Hi Team, 

I had upgraded APIs from 2.0 to 2.1 .Some issues I m facing currently , like 

QBChatHistoryMessage , QBMessage are not available? 
WIth what classes I should use instead of the above mentioned ? 

 Can u please confirm this?. Also, would appreciate if can let me know if the typing status of the opponent/members available for GroupChat in 2.1 as like its already there for the PrivateChat in 2.0?

**Comment by soulfly** [comment]
Look at changelog http://quickblox.com/developers/Android#Framework_changelog

- Removed classes QBMessage and QBChatHistoryMessage. Now QBChatMessage must be used anywhere.

**Comment by JoCodes** [comment]
Thanks Soulfly
