### ISSUE TITLE
VP9 support for Android SDK?

### ISSUE THREAD

**Issue by EsiAB** [QuickBlox/quickblox-android-sdk#657]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by EsiAB** [comment]
Does Android SDK for QuickBlox have vp9 support?

**Comment by IgorChernobayQB** [comment]
HI @EsiAB ,
Yes, Android SDK supports VP9 for video call.
You can use this constant QBRTCMediaConfig.VideoCodec to enable a VP9.

**Comment by EsiAB** [comment]
Thank you for your answer. My another question is that if QuickBlox support SVC? @IgorChernobayQB

**Comment by IgorChernobayQB** [comment]
Hi @EsiAB,

We support SVC as this technology has been implemented in VP8, VP9.

**Comment by EsiAB** [comment]
Hi @IgorChernobayQB,

Thank you for your reply. I have a few more questions related to SVC and VP9 technology implemented on QuickBlox. These are as follows.

- Is it enabled by default or do we need to modify some setting to get it activated and if it is how?
- How can i test SVC? Is there any way to select different frame rates and resolutions?

**Comment by vadimkhmyrovqb** [comment]
@EsiAB This behavior is codec-related and not specific to Quickblox functionality. We use SVC-compatible codecs as-is. Regarding your second question, we do not have a specific sample to test how SVC works.
