### ISSUE TITLE
 Program type already present: android.support.v4.media.MediaBrowserCompat$CustomActionCallback

### ISSUE THREAD

**Issue by Edgar1012** [QuickBlox/quickblox-android-sdk#659]
Hi am updated to latest sdk version of qbSdkVersion - 3.9.0
After updating am facing issue not able to build the file  . its showing me always . 
  Program type already present: android.support.v4.media.MediaBrowserCompat$CustomActionCallback

**Comment by vadimkhmyrovqb** [comment]
HI @Edgar1012 this issue is related to AndroidX support in your project.

To solve this problem, you should add these lines below in gradle.properties file:

android.useAndroidX=true
android.enableJetifier=true

**Comment by Drumering** [comment]
Hi @vadimkhmyrovqb , how are you?

After i do your above suggestion, i have new errors:

[TAG] Failed to resolve variable '${project.groupId}'

Can you help me?
