### ISSUE TITLE
getOnlineUsers list returning 0 most of the times

### ISSUE THREAD

**Issue by JoCodes** [QuickBlox/quickblox-android-sdk#66]
Hi , 

When trying to get the online users in a groupchat room , its returning with zero list. But sometimes its working fine too. Code snippet used are as below.

 ArrayList<Integer>(groupChatManager.getGroupChat(roomJid).getOnlineUsers());

Thanks

**Comment by soulfly** [comment]
No updates here, so closing

if you have more concrete steps to reproduce then please post and reopen
