### ISSUE TITLE
fabric api key issue while creating singed apk

### ISSUE THREAD

**Issue by nomicool** [QuickBlox/quickblox-android-sdk#661]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**
while configuring standard gradle generating singed apk it show error for fabric api but there is no where given to add api key also kindly help me with this

**Comment by nomicool** [comment]
This erro occur during making signed apk   

Execution failed for task ':Q-municate_app:fabricGenerateResourcesStandardRelease'.> Crashlytics Developer Tools error.
--

**Comment by vadimkhmyrovqb** [comment]
Hi @nomicool 

First, you need to make sure that Fabric plugin is integrated in your IDE, you can check this guide: https://examples.javacodegeeks.com/android/android-fabric-crashlytics-integration/

After this is done, please check this guide in our documentation: https://quickblox.com/developers/Q-municate#Q-municate_Android

You need to configure "gradle.properties" and make sure that the following values match the ones you got from Fabric: _devFabricApiKey, prodFabricApiKey_.

**Comment by nomicool** [comment]
as you can see i have atatched screenshot no where asking to add these Fabric: devFabricApiKey, prodFabricApiKey. keys
![Screenshot (23)](https://user-images.githubusercontent.com/25566185/55090600-3b03c300-50d1-11e9-92d3-5c3938165a28.png)

**Comment by vadimkhmyrovqb** [comment]
@nomicool have you tried adding these values in gradle.properties?

**Comment by nomicool** [comment]
as i told you gradle.properties is not appaering in android studio but when i mannualy open root folder i see that file i edited that file but nothing work. Kindly help me with this.

**Comment by vadimkhmyrovqb** [comment]
@nomicool it looks like you might have misconfigured the project. The values devFabricApiKey, prodFabricApiKey are taken from "gradle.properties" that should have been edited on project setup.
Please check this guide for more information: https://quickblox.com/developers/Q-municate#Q-municate_Android
