### ISSUE TITLE
Error while send message in Groupchat

### ISSUE THREAD

**Issue by JoCodes** [QuickBlox/quickblox-android-sdk#67]
HI, 

Throwing IllegalStateException while trying to send message to the created GroupDialog. 9 out of 10 occassions I face this issue while sometimes it works fine too.

code snippet:
 
        groupChat = groupChatManager.getGroupChat(roomJId); // roomJid and groupChat are not null.
        
        try {
            groupChat.sendMessage(chatMessage);// chatMessage is properly created and checked.
        } catch (XMPPException e) {
          
        } catch (SmackException.NotConnectedException e) {
           
        } catch (IllegalStateException e) {
          // exception thrown here
        }

**Comment by soulfly** [comment]
What is the error message of this exception? There should be a text description

**Comment by soulfly** [comment]
Looks like it's "You have not joined chat room"

so you have to join room before send messages

**Comment by Zephyer7673** [comment]
@soulfly , I am also having this error but, i am already owner of group, and i try to remove user from group dialog, is there any solution for this ?
