### ISSUE TITLE
Continue Video/Voice Call Session #675

### ISSUE THREAD

**Issue by Sukhwal** [QuickBlox/quickblox-android-sdk#693]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by alexparvus1** [comment]
Please clarify your problem if you still have some. Thanks
