### ISSUE TITLE
Cant create private dialog by userID

### ISSUE THREAD

**Issue by nbayaman** [QuickBlox/quickblox-android-sdk#70]
Hello!

I have set integer opponentId and try to get dialog object:

```
Integer opponentId = 2273049; 
QBDialog dialog = privateChatManager.createDialog(opponentId);
```
and then I'm  getting following debug message:

```
W/System.err﹕ java.lang.NullPointerException: Attempt to invoke virtual method 'com.quickblox.chat.model.QBDialog com.quickblox.chat.QBPrivateChatManager.createDialog(int)' on a null object reference
```
But opponentId is not null..

Are there any more requirements? What do i miss? Any help is appreciated.

**Comment by soulfly** [comment]
Looks like privateChatManager is null, you have to login to chat and then get privateChatManager

**Comment by Robbypatel1357** [comment]
yes GroupChatmanager is null then how to solve it?

**Comment by PrinceMasalawala** [comment]
How Can I Display My Private Chat
