### ISSUE TITLE
Manage periodic ping in javascript SDK

### ISSUE THREAD

**Issue by arpit87** [QuickBlox/quickblox-android-sdk#701]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*
-

**Environment details**
*(Operating system, browser information, SDK version)*
SDK 2.12.7 Javascript

**Did this work before?**
Yes , but long before

**Expected behavior**
Periodic pings/presence to be sent to server.Either manually or automatically

**Actual behavior**
Only 1 presence sent right after login
**Logs**
*(please, use github [gist](https://gist.github.com/))*
-

**Steps to reproduce the behavior**
-

**Any others comments?**
-

**Comment by alexparvus1** [comment]
If your question about JavaScript functionality - You can ask your question in section Javascript - https://github.com/QuickBlox/quickblox-javascript-sdk
