### ISSUE TITLE
Program type already present: android.support.v4.media.MediaBrowserCompat$CustomActionCallback

### ISSUE THREAD

**Issue by Drumering** [QuickBlox/quickblox-android-sdk#702]
**Environment details**
*(Kubuntu 18.04, Android Studio 3.6.1, SDK Quickblox version 3.9.2)*

**Expected behavior**

When importing the dependencies in build.gradle app-level, the app should work normally

**Actual behavior**

When importing the dependency  "com.quickblox:quickblox-android-sdk-messages:3.9.2", i get the error described in title this issue

**Steps to reproduce the behavior**

After including reference to SDK repository in your project-level build.gradle file at the root directory and import the dependency implementation "com.quickblox:quickblox-android-sdk-messages:3.9.2" then make a project.

- [A gif to demonstrate the error](https://imgur.com/EaEsVwx)
 - The sync gradle it's OK, but the make project and start app doesn't wortk

**Any others comments?**

Only this dependency returns one error, the others are normal.

**Comment by alexparvus1** [comment]
Case 1:
Please Add the following in your gradle.properties file:
```
android.useAndroidX = true
android.enableJetifier = false
```

Case 2 (if above doesn't work)
Android studio -> Navigate -> Class
Check include non-project classes
Copy full classpath android.support.v4.media.MediaBrowserCompat
See where it is used. You may need to remove, one of them.

Case 3 
Seems that one of your existing dependencies already has "support.v4" You may exclude this library by using:
```
implementation ('com.example.example:package:1.0.0') {
      exclude group: 'com.android.support', module:'support-v4'
}
```


If it still not working, please show your build.gradle (application level)

**Comment by Drumering** [comment]
So, I realized I need to migrate the application to use androidX. This way a new error appears:

`[TAG] Failed to resolve variable '${project.version}'`

Followed by:

```
Could not resolve all files for configuration ':app:debugAnnotationProcessorClasspath'.
> Failed to transform file 'dagger-compiler-2.8.jar' to match attributes {artifactType=processed-jar} using transform JetifyTransform
   > Failed to transform '/home/anderson/.gradle/caches/modules-2/files-2.1/com.google.dagger/dagger-compiler/2.8/f8e76f27907d495d16760ffb58e37b3f30859bf/dagger-compiler-2.8.jar' using Jetifier. Reason: The type does not support '.' as package separator! Received 'java.lang.Object;Ljava.lang.Class'.. (Run with --stacktrace for more details.) To disable Jetifier, set android.enableJetifier=false in your gradle.properties file.
```

P.S. Can't disable Jetifier.

Can you help me?

**Comment by alexparvus1** [comment]
I give you "Case 1" In the first message...
Try ->  `android.enableJetifier = false`  in your gradle.properties file

**Comment by QB-nikolay-zolotarov** [comment]
@Drumering Hello

This is Nikolay from QuickBlox support.

Please let me know if you had a chance to check the previous reply and try the provided solution.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Comment by Drumering** [comment]
Hi there! Yes, I was able to solve my problem following the @alexparvus1  's tips. Thanks a lot! I'll close this issue.
