### ISSUE TITLE
import com.quickblox.sample.chat.java.BuildConfig;

### ISSUE THREAD

**Issue by sarkar2003** [QuickBlox/quickblox-android-sdk#704]
import com.quickblox.sample.chat.java.BuildConfig;****
cant resolve symbol BuildConfig

**Comment by alexparvus1** [comment]
Make sure your file is importing the right BuildConfig class. 
And if you copying all code from the Sample, it may try to link the wrong buildConfig. 
Make sure your import it's like this **com.project.app.BuildConfig**.

**Comment by QB-nikolay-zolotarov** [comment]
@sarkar2003  Hello

This is Nikolay from QuickBlox support.

Please let me know if you had a chance to check the previous reply and try the provided solution.

If there is no reply within 5 business days, the issue will be closed as outdated.
