### ISSUE TITLE
Crash :- libjingle_peerconnection_so.so 

### ISSUE THREAD

**Issue by janakspaceo** [QuickBlox/quickblox-android-sdk#706]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*
-Galaxy C9 Pro

**Crash**
Found crash with ** libjingle_peerconnection_so.so **

Crashed: Thread #1
SIGSEGV 0x000000000000001e

Crashed: Thread: SIGSEGV  0x000000000000001e
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()

**Comment by alexparvus1** [comment]
Please clarify your problem or explain what did you mean at : 
```
...
at (Missing)()
at (Missing)()
at (Missing)()
at (Missing)()
...
```

**Comment by janakspaceo** [comment]
Hello alex,
this is the exact log i am getting on crash, i don't know what is this "missing" here

**Comment by alexparvus1** [comment]
As we know - Libjingle is a part of the WebRTC codebase. 
Maybe you need to check your proguard-rules.pro file?

**Comment by QB-nikolay-zolotarov** [comment]
Hello

This is Nikolay from QuickBlox support.

Please let me know if you had a chance to check the previous reply and try the provided suggestion.

Also, please let us know if the issue is still relevant.

If there is no reply within 5 business days, the issue will be closed as outdated.
