### ISSUE TITLE
QBAuth.createSessionByEmail broken: base Unexpected signature

### ISSUE THREAD

**Issue by Wirwing** [QuickBlox/quickblox-android-sdk#71]
I'm using quickblox-android-sdk-core-2.1.jar and quickblox-android-sdk-chat-2.1.jar.

After configuring QBSettings with my keys and initializing QBChatService, calling QBAuth.createSessionByEmail with a user with his email and password setted throws "base Unexpected signature" exception.

Here's the request log:

=========================================================
    === REQUEST ==== a4630a7b-6f3d-4e09-8c0f-f1656394fd03 ===
    REQUEST
    POST https://api.quickblox.com/session.json
    HEADERS
    QuickBlox-REST-API-Version=0.1.1
    QB-SDK=Android 2.1
    PARAMETERS
    application_id=XXXXX
    auth_key=XXXXXXXX
    nonce=-XXXXXXX
    timestamp=1424988363
    user[email]=irving.cf@gmail.com
    user[password]=YYYYY
    signature=XXXXXXXXXXXXXXXXXXXXXXXX
    INLINE
    POST https://api.quickblox.com/session.json?application_id=XXXXXX&auth_key=XXXXXXXXX&nonce=-XXXXXXX&timestamp=1424988363&user[email]=irving.cf%40gmail.com&user[password]=YYYYY&signature=XXXXXXXXXXXXXXXXXXXXXXXX
=========================================================

Here's the response:

*********************************************************
    *** RESPONSE *** a4630a7b-6f3d-4e09-8c0f-f1656394fd03 ***
    STATUS : 422
    HEADERS
    Access-Control-Allow-Origin=*
    Cache-Control=no-cache
    Connection=keep-alive
    Content-Type=application/json; charset=utf-8
    Date=Thu, 26 Feb 2015 22:06:04 GMT
    QuickBlox-REST-API-Version=0.1.1
    Server=nginx/1.0.15
    Status=422 Unprocessable Entity
    Transfer-Encoding=chunked
    X-Rack-Cache=invalidate, pass
    X-Request-Id=dc99064197ead270bc16d6642fceb5d5
    X-Runtime=0.007870
    X-UA-Compatible=IE=Edge,chrome=1
    BODY
    '{"errors":{"base":["Unexpected signature"]}}'
*********************************************************

However, calling QBAuth.createSession (with the same user, setting its Login atribute) works flawlessly.

**Comment by soulfly** [comment]
Try to use SDK 2.2.2
http://quickblox.com/developers/Android#Framework_changelog

We did some fixes for this issue
