### ISSUE TITLE
Reset Password not working

### ISSUE THREAD

**Issue by sohaibkhaa** [QuickBlox/quickblox-android-sdk#710]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Android, browser information, SDK version 3.9.2)*

**Did this work before?**
not

**Expected behavior**

**Actual behavior**

**Logs**
https://gist.github.com/sohaibkhaa/a6071235b01cbcffc96de345139cf374

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by alexparvus1** [comment]
To reset User's password you should use:
```
QBUsers.resetPassword(qbUser.getEmail()).performAsync(new QBEntityCallback<Void>() {
    @Override
    public void onSuccess(Void aVoid, Bundle bundle) {

    }

    @Override
    public void onError(QBResponseException e) {

    }
});
```
But make sure, that this User's **e-mail** is confirmed by another identity provider like Firebase or Facebook.

**Comment by sohaibkhaa** [comment]
i have enabled that option but now when i log in it's giving error that email not confirmed.
How to confirm email now? i have searched but nothing not even in quickblox documentation

**Comment by alexparvus1** [comment]
@sohaibkhaa you should create new user, or enter e-mail for your user, and than confirm it

**Comment by sohaibkhaa** [comment]
> @sohaibkhaa you should create new user, or enter e-mail for your user, and then confirm it

Sir i have created new user but still not getting confirmation email..
is there any specific method to send confirmation email or quickblox automatically sends it?

**Comment by QB-nikolay-zolotarov** [comment]
@sohaibkhaa Hello,

This is Nikolay from QuickBlox support.

We are sorry for the delayed reply.

Unfortunately, email notifications are disabled on the Cloud server.

You may use such functionality with our Enterprise plans. 

If you are interested in it, please [contact sales](https://quickblox.com/enterprise/#get-enterprise).

If there is no reply within 5 business days, the issue will be closed as outdated.
