### ISSUE TITLE
How remove a user from conference video call android

### ISSUE THREAD

**Issue by mjhaghparast** [QuickBlox/quickblox-android-sdk#712]
hi
i want create a video conference with multi users and remove a user from my conferance call
how do this work with android?????

**Comment by alexparvus1** [comment]
You can use SystemMessagesManager with System Messages here.
How to work with System Messages you can find in Chat Sample (https://github.com/QuickBlox/quickblox-android-sdk/blob/master/sample-chat-java/)

How to handle System Messages you can find for example there - https://github.com/QuickBlox/quickblox-android-sdk/blob/master/sample-chat-java/app/src/main/java/com/quickblox/sample/chat/java/ui/activity/ChatInfoActivity.java

To know how to create and send custom System Message you can find there - https://github.com/QuickBlox/quickblox-android-sdk/blob/master/sample-chat-java/app/src/main/java/com/quickblox/sample/chat/java/managers/DialogsManager.java

You may use System Message as an additional signaling message to send to opponents you need to remove from the call.

For example:
```
systemMessagesManager = QBChatService.getInstance().getSystemMessagesManager();
.....
QBChatMessage qbChatMessage = new QBChatMessage();
qbChatMessage.setDateSent(System.currentTimeMillis() / 1000);
qbChatMessage.setSaveToHistory(false);
qbChatMessage.setMarkable(false);

qbChatMessage.setRecipientId(opponentID); // Your opponent you want to remove from call
qbChatMessage.setProperty("property_need_hangup_call", "1"); // Your custom parameter for "removing" this user from your call

try {
systemMessagesManager.sendSystemMessage(qbChatMessage);
} catch (SmackException.NotConnectedException e) {
// your application does not connected to chat server
}
```

And when you need to receive System Messages:
```
private class SystemMessagesListener implements QBSystemMessageListener {
        @Override
        public void processMessage(QBChatMessage qbChatMessage) {
            // You need hangup current call there
        }

        @Override
        public void processError(QBChatException e, QBChatMessage qbChatMessage) {
            
        }
}
```
