### ISSUE TITLE
No one to recieve the Message

### ISSUE THREAD

**Issue by adi4472** [QuickBlox/quickblox-android-sdk#716]
I am using QuickBlox calling service when I call for the first time everything works normally but when I call the second time I get the error No one to receive the message. Any help will be appreciated

**Comment by alexparvus1** [comment]
Give us some steps and some logs please.

**Comment by QB-nikolay-zolotarov** [comment]
@adi4472 The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.
