### ISSUE TITLE
Voice issue on audio video call

### ISSUE THREAD

**Issue by sawattoo** [QuickBlox/quickblox-android-sdk#72]
I am facing a problem when ever i tried to call audio or video calls. i cant listen  other user voice. and same with him.. some time on one side i listen voice which is so much broke. pl z help me to get ride of this.

**Comment by soulfly** [comment]
Try our latest version of WebRTC Android
http://quickblox.com/developers/Sample-webrtc-android

**Comment by ntanduc2288** [comment]
Still facing this issue (version 2.4)

**Comment by priyaljain** [comment]
audio call  is not working when app is in backgroung or on other activty in androdi

**Comment by Ajayiosdeveloper** [comment]
i am using QuickBloxWebRTC in iOS. i am also not able to hear any voice in audio call after accepting the call.Can anyone tell the solution for this.

**Comment by vikasgothi** [comment]
i am using QuickBloxWebRTC in android but it's not working for me .
Please can any one help me for this.
I need a demo for the same .
