### ISSUE TITLE
onError (No one can receive the message)

### ISSUE THREAD

**Issue by pumatus** [QuickBlox/quickblox-android-sdk#720]
QBPushNotifications.createEvent(qbEvent).performAsync(object : QBEntityCallback<QBEvent> {
        override fun onSuccess(qbEvent: QBEvent?, bundle: Bundle?) {
            // Event Created
            Log.e("sendPushMessage --- ", "成功")
        }

        override fun onError(e: QBResponseException?) {
            Log.e("sendPushMessage --- ", "失败 " + e!!.message)
        }
    })

**Comment by alexparvus1** [comment]
This error means that NONE of the QBEvent "receivers" has QBEvent Subscription (for example PushNotification subscription).

Example. If you create QBEvent like this:
```
StringifyArrayList<Integer> userIds = new StringifyArrayList<>(qbChatDialog.getOccupants());

// Send Push: create QuickBlox Push Notification Event
QBEvent qbEvent = new QBEvent();
qbEvent.setNotificationType(QBNotificationType.PUSH);
qbEvent.setEnvironment(QBEnvironment.DEVELOPMENT);
qbEvent.setMessage(outMessage);
qbEvent.setUserIds(userIds);

QBPushNotifications.createEvent(qbEvent).performAsync(new QBEntityCallback<QBEvent>() {
    @Override
    public void onSuccess(QBEvent qbEvent, Bundle bundle) {
    
    }

    @Override
    public void onError(QBResponseException e) {

    }
});
```
    
And if you got an error message "No one can receive the message" - it means that NONE of `qbChatDialog.getOccupants()` has Subscription. (You may check these subscriptions in Quickblox Admin Panel)
