### ISSUE TITLE
Flutter GitHub Repo

### ISSUE THREAD

**Issue by Significantinfotech2020** [QuickBlox/quickblox-android-sdk#729]
Hello QuickBlox Support Team,

I just want to know, when will you launch flutter github repo for flutter chat app functionality?

**Comment by QB-maksym-pidhorbunskyi** [comment]
Hello,

By now we do not have the exact date when Flutter GitHub repository will be launched.

New versions of QuickBlox Flutter SDK will be released on pub.dev: https://pub.dev/packages/quickblox_sdk/versions

**Comment by alexparvus1** [comment]
There is the Quickblox flutter SDK https://github.com/QuickBlox/quickblox-flutter-sdk
