### ISSUE TITLE
connect two users who are not registered on the quickblox site

### ISSUE THREAD

**Issue by veronikawilliams1** [QuickBlox/quickblox-android-sdk#732]
Hello,
I make app quickblox.sample.videochat.
Can the quickblox.sample.videochat.java application connect two users who are **_not registered with my application on the quickblox site_**? (But on the other hand, for example, they are listed in `Firebase` or my `SQLite`)

Thanks!

**Comment by veronikawilliams1** [comment]
### please answer who knows :)

**Comment by alexparvus1** [comment]
If you want to directly connect two nor registered in QuickBlox users using QuickBlox - you should create application with your own registration or using our "Custom Identity Provider" https://docs.quickblox.com/docs/android-authentication#custom-identity-provider.
And you can find the solution with registration (for example by phone number) using Firebase.
All these features you can find there - https://docs.quickblox.com/docs/android-authentication

**Comment by QB-nikolay-zolotarov** [comment]
Hello @veronikawilliams1 

This is Nikolay from QuickBlox support.

Please let me know if you had a chance to check the previous reply and resolve the issue.

If there is no reply within 5 business days, the issue will be closed as outdated.
