### ISSUE TITLE
Support for Huawei Mobile Services Push Kit

### ISSUE THREAD

**Issue by abusuioc** [QuickBlox/quickblox-android-sdk#735]
Let me start by thanking you guys for creating this useful SDK.

As you well know, because of the [US trade ban](https://en.wikipedia.org/wiki/China%E2%80%93United_States_trade_war) , the new and upcoming Huawei devices powered by Android cannot anymore use Google Play Services (GMS). As a response to that, Huawei developed its own alternative to GMS - called Huawei Mobile Services (HMS). As part of the HMS offering, the [Push Kit](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/service-introduction-0000001050040060) offers support for push notifications on HMS devices with the same features you're used from FCM.

It would be fantastic if the SDK would fully run on HMS devices as well - currently it cannot, mostly because of the dependency on FCM (which in turn depends on GMS). The effort to integrate the HMS Push Kit (client & server side) should be one man-week. I'd gladly support your quest with relevant documentation and code samples should you decide to start this journey and have your product available on HMS. This way, your customers can continue using your SDK on the increasing number of new HMS devices.

**Comment by alexparvus1** [comment]
Thank you very much we are working on it.

**Comment by alexparvus1** [comment]
@abusuioc are you a Huawei Mobile Service representative or are you a free developer? 
In any case, we are always open to communication and mutual assistance.

**Comment by abusuioc** [comment]
@alexparvus1 sure, let me know what you need / how I can help you. We can continue here, or if you want to use a different channel, write me at adrian.busuioc@huawei.com

**Comment by alexparvus1** [comment]
Hello Nate!
This man answered me that he is working on Huawei! Got it! :) His e-mail -
adrian.busuioc@huawei.com

ср, 16 дек. 2020 г. в 11:46, abusuioc <notifications@github.com>:

**Comment by faizan-196** [comment]
Hi, any update? Is QuickBlox support Huawei or not?

**Comment by QB-nikolay-zolotarov** [comment]
Hello,

This is Nikolay from QuickBlox support.

QuickBlox supports only FCM service for the work of Push Notification functionality on the Android platform.
You could use QuickBlox Android SDK for the correct work of key functionalities except Push Notification for HUAWEI devices.
