### ISSUE TITLE
Hashmap<> issue 

### ISSUE THREAD

**Issue by prashant21497** [QuickBlox/quickblox-android-sdk#737]
![Screenshot (39)](https://user-images.githubusercontent.com/35329291/103441144-f035b880-4c71-11eb-8b47-d69732616a8f.png)
Hello Guys,

i found HashMap<> error in CallActivity

 @Override
    public void onRejectCurrentSession() {
        callService.rejectCurrentSession(new HashMap<>());
    }

 public void hangUpCurrentSession() {
        callService.stopRingtone();
        if (!callService.hangUpCurrentSession(new HashMap<>())) {
            CallService.stop(this);
            finish();
        }
    }

-------------------------------------------------------------------------------

BaseConversationFragment

 @Override
    public void onStart() {
        super.onStart();
        if (conversationFragmentCallback != null) {
            if (isIncomingCall) {
                conversationFragmentCallback.acceptCall(new HashMap<>());
            } else {
                conversationFragmentCallback.startCall(new HashMap<>());
            }
        }
    }

-------------------------------------------------------------------------------------

VideoConversationFragment

    @Override
    protected void initFields() {
        super.initFields();
        localViewOnClickListener = new LocalViewOnClickListener();
        amountOpponents = opponents.size();
        allOpponents = Collections.synchronizedList(new ArrayList<>(opponents.size()));  ///<--- this line error
        allOpponents.addAll(opponents);
        timerCallText = getActivity().findViewById(R.id.timer_call);

        isPeerToPeerCall = opponents.size() == 1;
    }

----------------------------------------------------------------------------
 CallService

private class ConnectionListenerImpl extends AbstractConnectionListener {
        @Override
        public void connectionClosedOnError(Exception e) {
            SharedPreferences sharedPref = PreferenceManager.getDefaultSharedPreferences(getApplicationContext());
            int reconnectHangUpTimeMillis = SettingsUtil.getPreferenceInt(sharedPref,
                    getApplicationContext(), R.string.pref_disconnect_time_interval_key,
                    R.string.pref_disconnect_time_interval_default_value) * 1000;
            expirationReconnectionTime = System.currentTimeMillis() + reconnectHangUpTimeMillis;
        }

        @Override
        public void reconnectionSuccessful() {

        }

        @Override
        public void reconnectingIn(int seconds) {
            Log.i(TAG, "reconnectingIn " + seconds);
            if (!isCallState && expirationReconnectionTime < System.currentTimeMillis()) {
                hangUpCurrentSession(new HashMap<>());
            }
        }
    }

  @Override
        public void onReceiveHangUpFromUser(QBRTCSession session, Integer userID, Map<String, String> map) {
            stopRingtone();
            if (session == WebRtcSessionManager.getInstance(getApplicationContext()).getCurrentSession()) {
                Log.d(TAG, "Initiator HangUp the Call");
                if (userID.equals(session.getCallerID()) && currentSession != null) {
                    currentSession.hangUp(new HashMap<>());
                }

                QBUser participant = QbUsersDbManager.getInstance(getApplicationContext()).getUserById(userID);
                String participantName = participant != null ? participant.getFullName() : userID.toString();
                ToastUtils.shortToast("User " + participantName + " " + getString(R.string.text_status_hang_up) + " conversation");
            }
        }

 @Override
        public void onCameraFreezed(String s) {
            ToastUtils.shortToast("Camera Freezed");
            hangUpCurrentSession(new HashMap<>());
        }

in above all methods hashmap<> display error any one can help me . Thank you in advance/
![Screenshot (36)](https://user-images.githubusercontent.com/35329291/103441044-1dce3200-4c71-11eb-9d50-ad81c9442344.png)
![Screenshot (37)](https://user-images.githubusercontent.com/35329291/103441045-1eff5f00-4c71-11eb-9fc2-a9f323c34fc3.png)
![Screenshot (39)](https://user-images.githubusercontent.com/35329291/103441171-18251c00-4c72-11eb-8ca5-72b86a1d5f74.png)

**Comment by alexparvus1** [comment]
@prashant21497 Hello! As you can see - this "new HashMap<>()" - this is just the argument that you can add as a parameter for signaling message if you want to customize it. So if your Android Studio markets these part of the code as error - you can parameterize this HashMap as - new HashMap<String, String>()

About the line : 
`allOpponents = Collections.synchronizedList(new ArrayList<>(opponents.size())); 
we just create the new ArrayList with initial capacity there. And there are no errors in this line. Isn't it?

**Comment by QB-nikolay-zolotarov** [comment]
Hello @prashant21497 

This is Nikolay from QuickBlox support.

Please let me know if you had a chance to check the previous reply and try the provided solution.

If there is no reply within 5 business days, the issue will be closed as outdated.
