### ISSUE TITLE
device id getting null while sending push notifications

### ISSUE THREAD

**Issue by SuryaChundawat** [QuickBlox/quickblox-android-sdk#738]
Hi All, 

Getting an issue with quickblox push notifications. I have successfully integrated chat functionality and it's working great. But push notification functionality is not working. I am able to send push from the app its showing delivered in the portal but when I am looking in logs its showing below (i manage to show some of my logs)
{"notification":{"id":3811111,"badge":null,"device_token":null,"sound":"default","alert":null,
"uri":null,"priority":10,"url_args":null,"category":null,"content_available":false,"dry_run":false,"mutable_content":false,"notification":null,"thread_id":null,"type":"Rpush::Client::Redis::Fcm::Notification","event_id":3511111,"event_date":"2021-01-02T06:34:29+00:00"},"log":[{"device_token":null,"delivered_at":"2021-01-02T06:34:30+00:00","failed_at":null,"error_code":null,"error_description":null}]}

Please help where I am wrong
I asked the same on StackOverflow 
https://stackoverflow.com/questions/65447617/quickblox-push-notification-integration-in-android

**Comment by alexparvus1** [comment]
It seems that you already receive the push but your BroadcastReceiver didn't do anything to show the notification for the user.
Please check how you make your receiver.
I have an example for you: https://github.com/QuickBlox/quickblox-android-sdk/blob/master/sample-chat-java/app/src/main/java/com/quickblox/sample/chat/java/fcm/PushListenerService.java

I answered also on StackOverflow.

**Comment by QB-nikolay-zolotarov** [comment]
Hello @SuryaChundawat 

This is Nikolay from QuickBlox support.

Please let me know if you had a chance to check the previous reply and try the provided solution.

If there is no reply within 5 business days, the issue will be closed as outdated.
