### ISSUE TITLE
javax.net.ssl.SSLPeerUnverifiedException: No peer certificate   (on android 2.x)

### ISSUE THREAD

**Issue by aratj** [QuickBlox/quickblox-android-sdk#74]
04-05 06:28:01.020: W/System.err(517): javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
04-05 06:28:01.020: W/System.err(517): 	at org.apache.harmony.xnet.provider.jsse.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:258)
04-05 06:28:01.020: W/System.err(517): 	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:93)
04-05 06:28:01.020: W/System.err(517): 	at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:381)
04-05 06:28:01.020: W/System.err(517): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:164)
04-05 06:28:01.020: W/System.err(517): 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
04-05 06:28:01.020: W/System.err(517): 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
04-05 06:28:01.020: W/System.err(517): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:359)
04-05 06:28:01.020: W/System.err(517): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
04-05 06:28:01.020: W/System.err(517): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
04-05 06:28:01.020: W/System.err(517): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
04-05 06:28:01.020: W/System.err(517): 	at com.quickblox.core.server.HttpExecutor.execute(HttpExecutor.java:28)
04-05 06:28:01.020: W/System.err(517): 	at com.quickblox.core.server.HttpRequestRunnable.run(HttpRequestRunnable.java:73)
04-05 06:28:01.020: W/System.err(517): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:444)
04-05 06:28:01.020: W/System.err(517): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
04-05 06:28:01.020: W/System.err(517): 	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
04-05 06:28:01.020: W/System.err(517): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
04-05 06:28:01.020: W/System.err(517): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
04-05 06:28:01.020: W/System.err(517): 	at java.lang.Thread.run(Thread.java:1019)

**Comment by soulfly** [comment]
Hey, 

what is that? do you have the repro steps?

**Comment by aratj** [comment]
Давай на русском. )

Просто пытаюсь создать сессию и такая ошибка.

В общем есть такой косяк, при попытке обратиться к HTTPS на 2.х ведроиде.
android javax.net.ssl.SSLPeerUnverifiedException: No peer certificate

И если не ошибаюсь, то в предыдущей версии SDK такого не было.

**Comment by soulfly** [comment]
Все версии 2.1, 2.2, 2.3?

**Comment by aratj** [comment]
точно вопросизводится на 2.3.5 и 2.3.7

**Comment by aratj** [comment]
погуглил, судя по SO, ошибка появляется только на 2.3.х девайсах.
