### ISSUE TITLE
SASLError using PLAIN: not-authorized

### ISSUE THREAD

**Issue by saurav2210-1996** [QuickBlox/quickblox-android-sdk#748]
In Android app integrated and working fine but when we update openfire now old register user get "SASLError using PLAIN: not-authorized" error but when i create new user it is working fine.

why this happen ?

**Comment by alexparvus1** [comment]
Please provide us a more readable description of your issue. Because we have no idea about how you are using Openfire etc., and when and where did you get your error.

**Comment by saurav2210-1996** [comment]
Thanks for reply but i found issue now working fine.
Thanks

**Comment by saurav2210-1996** [comment]
Thanks for reply but i found issue now working fine.
Thanks
