### ISSUE TITLE
rtcClient.getSession("sessionId").isActive throw NullPointException

### ISSUE THREAD

**Issue by hasan5151** [QuickBlox/quickblox-android-sdk#752]
rtcClient.getSession("sessionId").isActive throw NullPointException

**Comment by alexparvus1** [comment]
It seems that there are no session found with this Session ID.

**Comment by QB-nikolay-zolotarov** [comment]
Hello @hasan5151 

This is Nikolay from QuickBlox support.

Please let me know if you had a chance to check the previous reply and if the issue is still relevant.

If there is no reply within 5 business days, the issue will be closed as outdated.
