### ISSUE TITLE
Email Verification and Password Reset is not working

### ISSUE THREAD

**Issue by Ahmadpashaquarterpi** [QuickBlox/quickblox-android-sdk#764]
Hi,
I am working on a chatting app but I am facing a problem while verifying email.
When I receive the email and open the link to verify. but it does not verify email but instead open an raw html page as follows:

<!DOCTYPE html>
<html lang='en'>
<head>
<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<style>
  body {
    background-color: #eaf0f0;
    font-family: "Open Sans", Arial;
  }
  .text-center {
    text-align: center;
  }
  header {padding-top: 68px;}
  h1 {
    padding-top: 71px;
    font-size: 32px;
    color: #444444;
  }
  p {
    padding-top: 24px;
    font-size: 12px;
    font-weight: normal;
    color: #666666;
  }
  h1, p {font-weight: normal; }
  p a {
    color: #666666;
    text-decoration: underline;
  }
</style>
</head>
<body>
<style>
  body {background-color: #eaf0f0;}
      header {padding-top: 68px;}
      h1 {
        padding-top: 71px;
        font-size: 32px;
        color: #444444;
      }
      p {
        padding-top: 24px;
        font-size: 12px;
        font-weight: normal;
        color: #666666;
      }
      h1, p {font-weight: normal; }
      p a {
        color: #666666;
        text-decoration: underline;
      }
</style>
<div class='container text-center'>
<h1>
Sorry, we can`t find your registration info, please, check the link or fill the form again
</h1>
</div>
</body>
</html>

and when I try to reset password, I receive the mail, but when that link is opened, following line is shown only:

{"code":null,"message":"Resource not found"}

**Comment by Ahmadpashaquarterpi** [comment]
@QB-nikolay-zolotarov  Thanks for reply,

I am working on a App, and I want to get email verified.

I am using the following link template to get the email verified in the greeting email. But there is nothing related to email when I click the link just some raw html tags are shown on screen.

https://api.quickblox.com/confirm_email?token=#{user.get_confirmation_token}

similarly, I have also implemented password reset mail template, and used the suggested link format as follows:

https://api.quickblox.com/password_reset?token=#{user.get_reset_password_token}

but when I click this link to get password reset, following line is written on the webpage only:

{"code":null,"message":"Resource not found"}

Plus, All these links were working before.

**Comment by QB-nikolay-zolotarov** [comment]
Hello Ahmad,

Thank you for getting back to me.

Unfortunately, email notifications are disabled for the Cloud server.

You may use such functionality with our Enterprise plans. 

Also, you will need to check the required checkboxes in the Admin Dashboard on your Enterprise instance.
[https://admin.quickblox.com/apps/YOUR_APP_ID/service/users/email-settings](https://admin.quickblox.com/apps/YOUR_APP_ID/service/users/email-settings)
![image](https://user-images.githubusercontent.com/88783425/129360043-d9aac35d-990e-48dd-9d61-ec3c70955f86.png)

**Comment by Ahmadpashaquarterpi** [comment]
Ok
Thank you @QB-nikolay-zolotarov
