### ISSUE TITLE
Upload file error on Android 11

### ISSUE THREAD

**Issue by arusyakhov** [QuickBlox/quickblox-android-sdk#765]
After targeting Android SDK version 30, I cannot upload files from Documents and Downloads in Quickblox

**Environment details**
*(Operating system, browser information, SDK version)*
Operating System: Android
SDK Version: 3.9.10

**Did this work before?**
With target sdk version 29 it worked

**Expected behavior**
Quickblox client should be able to upload files from Documents folder

**Actual behavior**
Quickblox client isn't able to upload files from Documents folder. 
Everything is done as in sample. I call QBContent.uploadFileTask, passing a File argument (file path - /storage/emulated/0/Documents/demofile_1710.pdf), I get the following error com.quickblox.core.exception.QBResponseException: Connection failed. Please check your internet connection.

**Any others comments?**
This is an urgent issue, as Google requires the app target sdk versions to be updated to 30

**Comment by QB-nikolay-zolotarov** [comment]
Hello,

This is Nikolay from QuickBlox support.

We are aware of the change in the target SDK version from 29 to 30.
This is a known issue. We are planning to update the SDK before November.

Please use the target SDK version 29 so far.

Please follow our Github for updates: https://github.com/QuickBlox/
