### ISSUE TITLE
Incoming call is not working when my mobile's screen is OFF.

### ISSUE THREAD

**Issue by arbaz07** [QuickBlox/quickblox-android-sdk#767]
Is this possible on QuickBlox ?

**Did this work before?**
NO

**Comment by QB-nikolay-zolotarov** [comment]
Hello Arbaz,

This is Nikolay from QuickBlox support.

You need to configure push notifications for your application to receive calls in the non-running states using this guide: 
[Configuration of chat and video push notifications](https://help.quickblox.com/article/268-configuration-of-chat-and-video-push-notifications)

Please be notified that managing and configuring push notifications in the background mode or killed state is not a part of QuickBlox SDK's and the implementation is up to the client side.
