### ISSUE TITLE
How can i do search on dialog by name in android

### ISSUE THREAD

**Issue by sagarbhojaviya** [QuickBlox/quickblox-android-sdk#768]
i am using  ChatHelper.getDialogs()

**Comment by ishaforenkoqb** [comment]
You're referring to helper class of sample app. Create a new method in this class that will do search in dialogs.

Check out SDK documentation https://docs.quickblox.com/docs/android-chat-dialogs#search-operators

You can use `ctn(field, searchValue)` method of `QBRequestGetBuilder` to specify search string.

`
String field = "name";
String searchValue = "some_group_name";
QBDialogType type = QBDialogType.GROUP;

QBRequestGetBuilder requestBuilder = new QBRequestGetBuilder();
requestBuilder.ctn(field, searchValue);

QBRestChatService.getChatDialogs(type, requestBuilder).performAsync(new QBEntityCallback<ArrayList<QBChatDialog>>() {
    @Override
    public void onSuccess(ArrayList<QBChatDialog> result, Bundle params) {
      
    }

    @Override
    public void onError(QBResponseException responseException) {

    }
});
`

**Comment by sagarbhojaviya** [comment]
Thanks for your quick support
