### ISSUE TITLE
Sample chat example- Receive chat messages not working 

### ISSUE THREAD

**Issue by legolas14** [QuickBlox/quickblox-android-sdk#77]
Hi,

I am trying sample chat example in geny motion.  I am able to send a chat message to a user but not able to receive the message from the other end.   I am able to see in the logcat - SMACK message received.  But not able to see it in the dialog. 

I.e control is not coming to 

    @Override
    public void processMessage(QBPrivateChat chat, QBChatMessage message) {
        Log.w(TAG, "new incoming message: " + message);
        chatActivity.showMessage(message);
    }

Can someone kindly help.

**Comment by legolas14** [comment]
I get the following in logcat log- But the control is not reaching the above mentioned function nor I am getting the chat in the dialog box. 

04-11 10:13:59.118    1311-1331/com.quickblox.sample.chat D/SMACK﹕ RCV (0): <presence xmlns="jabber:client" id="E97OL-3" to="2752076-<app-id>@chat.quickblox.com" from="2752076-<app_id>@chat.quickblox.com/7dcbabcd8044030"/>
04-11 10:14:03.062    1311-1331/com.quickblox.sample.chat D/SMACK﹕ RCV (0): <message type="chat" xmlns="jabber:client" id="purple21ce253" to="2752076-<app_id>@chat.quickblox.com/7dcbabcd8044030" from="2752083-<app-id>@chat.quickblox.com/><active xmlns="http://jabber.org/protocol/chatstates"/><body>hello</body></message>

**Comment by soulfly** [comment]
How did you add that listener? Please show whole code

**Comment by legolas14** [comment]
Hi ,

Please find the code 

""" 
private void initViews() {
        messagesContainer = (ListView) findViewById(R.id.messagesContainer);
        messageEditText = (EditText) findViewById(R.id.messageEdit);
        sendButton = (Button) findViewById(R.id.chatSendButton);

        TextView meLabel = (TextView) findViewById(R.id.meLabel);
        TextView companionLabel = (TextView) findViewById(R.id.companionLabel);
        RelativeLayout container = (RelativeLayout) findViewById(R.id.container);
        progressBar = (ProgressBar) findViewById(R.id.progressBar);

        Intent intent = getIntent();

        // Get chat dialog
        //
        dialog = (QBDialog)intent.getSerializableExtra(EXTRA_DIALOG);

        mode = (Mode) intent.getSerializableExtra(EXTRA_MODE);
        switch (mode) {
            case GROUP:
                chat = new GroupChatManagerImpl(this);
                container.removeView(meLabel);
                container.removeView(companionLabel);

                // Join group chat
                //
                progressBar.setVisibility(View.VISIBLE);
                //
                ((GroupChatManagerImpl) chat).joinGroupChat(dialog, new QBEntityCallbackImpl() {
                    @Override
                    public void onSuccess() {

                        // Load Chat history
                        //
                        loadChatHistory();
                    }

                    @Override
                    public void onError(List list) {
                        AlertDialog.Builder dialog = new AlertDialog.Builder(ChatActivity.this);
                        dialog.setMessage("error when join group chat: " + list.toString()).create().show();
                    }
                });

                break;
            case PRIVATE:
                Integer opponentID = ((ApplicationSingleton)getApplication()).getOpponentIDForPrivateDialog(dialog);

                chat = new PrivateChatManagerImpl(this, opponentID);

                companionLabel.setText(((ApplicationSingleton)getApplication()).getDialogsUsers().get(opponentID).getLogin());

                // Load CHat history
                //
                loadChatHistory();
                break;
        }

        sendButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                String messageText = messageEditText.getText().toString();
                if (TextUtils.isEmpty(messageText)) {
                    return;
                }

                // Send chat message
                //
                QBChatMessage chatMessage = new QBChatMessage();
                chatMessage.setBody(messageText);
                chatMessage.setProperty(PROPERTY_SAVE_TO_HISTORY, "1");
                chatMessage.setDateSent(new Date().getTime()/1000);

                try {
                    chat.sendMessage(chatMessage);
                } catch (XMPPException e) {
                    Log.e(TAG, "failed to send a message", e);
                } catch (SmackException sme){
                    Log.e(TAG, "failed to send a message", sme);
                }

                messageEditText.setText("");

                if(mode == Mode.PRIVATE) {
                    showMessage(chatMessage);
                }
            }
        });
    }
"""


'''public class PrivateChatManagerImpl extends QBMessageListenerImpl<QBPrivateChat> implements ChatManager, QBPrivateChatManagerListener {

    private static final String TAG = "PrivateChatManagerImpl";

    private ChatActivity chatActivity;

    private QBPrivateChatManager privateChatManager;
    private QBPrivateChat privateChat;

    public PrivateChatManagerImpl(ChatActivity chatActivity, Integer opponentID) {
        this.chatActivity = chatActivity;

        privateChatManager = QBChatService.getInstance().getPrivateChatManager();

        privateChatManager.addPrivateChatManagerListener(this);

        // init private chat
        //
        privateChat = privateChatManager.getChat(opponentID);
        if (privateChat == null) {
            privateChat = privateChatManager.createChat(opponentID, this);
        }else{
            privateChat.addMessageListener(this);
        }
    }

    @Override
    public void sendMessage(QBChatMessage message) throws XMPPException, SmackException.NotConnectedException {
        privateChat.sendMessage(message);
    }

    @Override
    public void release() {
        Log.w(TAG, "release private chat");
        privateChat.removeMessageListener(this);
        privateChatManager.removePrivateChatManagerListener(this);
    }

    @Override
    public void processMessage(QBPrivateChat chat, QBChatMessage message) {
        Log.w(TAG, "new incoming message: " + message);
        chatActivity.showMessage(message);
    }

    @Override
    public void processError(QBPrivateChat chat, QBChatException error, QBChatMessage originChatMessage){

    }

    @Override
    public void chatCreated(QBPrivateChat incomingPrivateChat, boolean createdLocally) {
        if(!createdLocally){
            privateChat = incomingPrivateChat;
            privateChat.addMessageListener(PrivateChatManagerImpl.this);
        }

        Log.w(TAG, "private chat created: " + incomingPrivateChat.getParticipant() + ", createdLocally:" + createdLocally);
    }
}'''

**Comment by vivdub** [comment]
I am having similar issue, but its not showing in log also.
Have you fixed yours ?

**Comment by legolas14** [comment]
Yes, my issue was I was using Pidgen (Chat client) to try and chat with Geny Motion for which it does not work. 
If you are having a similar environment try using geny motion on both ends or try between two phones.

**Comment by vivdub** [comment]
Yes I resolved it yesterday, it was same issue, looks like it doesn't works good with 3rd part XMPP clients.

**Comment by legolas14** [comment]
Great!  I spent almost a week trying to figure this out :)

**Comment by vivdub** [comment]
I spent complete day, and no one mentioned this thing anywhere, it should be easily searchable, since every one will face this issue.
Well thanks for answering, at least it should have been resolved today after you answered it.

**Comment by Robbypatel1357** [comment]
hey hi i have still problem chat message not send on server

**Comment by Shadowstep33** [comment]
Just for anyone after me, I was having this problem and it seems I do not receive messages broadcast by myself. I do receive messages from other users, albeit somewhat slowly....

I am using the javascript SDK though, not sure if that affects the underlying way these notifications function. If not intentional behavior I can open an issue over there.
