### ISSUE TITLE
Listview in not showing

### ISSUE THREAD

**Issue by harshpatel0909** [QuickBlox/quickblox-android-sdk#779]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by harshpatel0909** [comment]
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/coordinator_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    tools:context=".Activities.ChatDialogsActivity">


    <ListView
        android:id="@+id/listDialogsChats"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

    </ListView>

ListView is not Showing  please help me sdk versions are 31.

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/chatdialog_adduser"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|right"
        android:layout_marginStart="@dimen/_16sdp"
        android:layout_marginTop="@dimen/_16sdp"
        android:layout_marginEnd="@dimen/_16sdp"
        android:layout_marginBottom="@dimen/_16sdp"
        android:backgroundTint="@color/back_c"
        android:src="@drawable/ic_add"
        app:layout_anchor="@id/listDialogsChats"
        app:layout_anchorGravity="bottom|right|end">

    </com.google.android.material.floatingactionbutton.FloatingActionButton>


</androidx.coordinatorlayout.widget.CoordinatorLayout>###

**Comment by QB-nikolay-zolotarov** [comment]
@harshpatel0909 Hello, this is Nikolay from QuickBlox support. 

Unfortunately, the request is not clear enough. Please rephrase it and provide more detailed information about the issue, the error message. Also, please provide steps to reproduce the issue.

In addition, please provide us with full logs. You can enable them using the documentation:
https://docs.quickblox.com/docs/android-setup#enable-logging
