### ISSUE TITLE
Possible Bug: Sample Chat Application not showing received message on chat dialog.

### ISSUE THREAD

**Issue by chowbene1986** [QuickBlox/quickblox-android-sdk#78]
I am trying to load the sample chat application to understand the private chat functionality using quickblox. I have 2 users - gamma and theta.

Gamma is logged into pidgin xmpp client and theta in the virtual device running quickblox.
The message from virtual box reaches the pidgin client, however the reply from pidgin client does not show up in the dialog window for Gamma. 

LOG CAT For Send
----------------------------
```04-12 13:28:26.979    1813-1813/com.quickblox.sample.chat W/PrivateChatManagerImpl﹕ Sending Message:QBChatMessage{id=552aab3a25d7916474d98462, sender_id=null, recipient_id=null, body=I am Gamma!, properties={save_to_history=1}, attachments=null, dialogId=null, dateSent=1428859706, read=false}
04-12 13:28:26.981    1813-1838/com.quickblox.sample.chat D/SMACK﹕ SENT (0): <message id='552aab3a25d7916474d98462' to='xxxxxx-xxxxxx@chat.quickblox.com' type='chat'><body>I am Gamma!</body><extraParams xmlns='jabber:client'><date_sent>1428859706</date_sent><save_to_history>1</save_to_history></extraParams></message>
04-12 13:28:26.995    1813-1813/com.quickblox.sample.chat E/sCube﹕ Add Rx Message to View```

LOG CAT For Receive
--------------------------------
```04-12 13:22:15.781    1813-1838/com.quickblox.sample.chat D/SMACK﹕ SENT (0): <presence id='0Ikcm-9'></presence>
04-12 13:22:15.860    1813-1839/com.quickblox.sample.chat D/SMACK﹕ RCV (0): <presence xmlns="jabber:client" id="0Ikcm-9" to="xxxxxx-xxxxx@chat.quickblox.com" from="2810865-21405@chat.quickblox.com/952902c1fc047dca"/>
04-12 13:22:16.517    1813-1839/com.quickblox.sample.chat D/SMACK﹕ RCV (0): <message type="chat" xmlns="jabber:client" id="purple6bff82a3" to="xxxxx-xxxxx@chat.quickblox.com/952902c1fc047dca" from="xxxxxx-xxxxxx@chat.quickblox.com/tigase-216622"><active xmlns="http://jabber.org/protocol/chatstates"/><body>I am Theta !</body></message>```


The control never comes to this function:
---------------------------------------------------------
@Override
        public void processMessage (QBPrivateChat chat, QBChatMessage message){
            Log.w(TAG, "new incoming message: " + message);
            chatActivity.showMessage(message);
        }

Please find attached image for chat dialogs-
![quickblox_chat_not_rx](https://cloud.githubusercontent.com/assets/11913589/7106736/a22db314-e100-11e4-8f5f-8900fa5e126d.JPG)

Please help me as I am stuck debugging from last few days. Thanks a lot in advance for any help offered to solve this issue.

**Comment by soulfly** [comment]
What is inside this callback?

        // Get 1-1 chat manager and listener
        //
        privateChatManager = chatService.getPrivateChatManager();
        //
        privateChatManagerListener = new QBPrivateChatManagerListener() {
            @Override
            public void chatCreated(final QBPrivateChat privateChat, final boolean createdLocally) {
                if(!createdLocally){
                    Log.i(TAG, "adding message listener to new chat");
                    privateChat.addMessageListener(privateChatMessageListener);
                    privateChat.addIsTypingListener(privateChatIsTypingListener);
                }

                log("Private chat created: " + privateChat + ", createdLocally: " + createdLocally);
            }
        };
        privateChatManager.addPrivateChatManagerListener(privateChatManagerListener);

**Comment by chowbene1986** [comment]
Hello,

The sample code I picked has the following code- 
``` java

public class PrivateChatManagerImpl extends QBMessageListenerImpl<QBPrivateChat> implements ChatManager, QBPrivateChatManagerListener {

    private static final String TAG = "PrivateChatManagerImpl";

    private ChatActivity chatActivity;

    private QBPrivateChatManager privateChatManager;
    private QBPrivateChat privateChat;

    public PrivateChatManagerImpl(ChatActivity chatActivity, Integer opponentID) {
        this.chatActivity = chatActivity;

        privateChatManager = QBChatService.getInstance().getPrivateChatManager();

        privateChatManager.addPrivateChatManagerListener(this);

        // init private chat
        //
        privateChat = privateChatManager.getChat(opponentID);
        Log.w(TAG, "Created pvt chat manager");

        if (privateChat == null) {
            Log.w(TAG, "pvt chat is NULL");
            privateChat = privateChatManager.createChat(opponentID, this);
            //privateChat.addMessageListener(this);
        } else {
            privateChat.addMessageListener(this);
        }
    }

        @Override
        public void sendMessage (QBChatMessage message)throws
        XMPPException, SmackException.NotConnectedException {
            Log.w(TAG,"Sending Message:"+message.toString());
            privateChat.sendMessage(message);
        }

        @Override
        public void release () {
            Log.w(TAG, "release private chat");
            privateChat.removeMessageListener(this);
            privateChatManager.removePrivateChatManagerListener(this);
        }

        @Override
        public void processMessage (QBPrivateChat chat, QBChatMessage message){
            Log.w(TAG, "new incoming message: " + message);
            chatActivity.showMessage(message);
        }

        @Override
        public void processError (QBPrivateChat chat, QBChatException error, QBChatMessage
        originChatMessage){

        }

        @Override
        public void chatCreated (QBPrivateChat incomingPrivateChat,boolean createdLocally){
            if (!createdLocally) {
                privateChat = incomingPrivateChat;
                privateChat.addMessageListener(PrivateChatManagerImpl.this);
            }

            Log.w(TAG, "private chat created: " + incomingPrivateChat.getParticipant() + ", createdLocally:" + createdLocally);
        }
}
```

**Comment by soulfly** [comment]
Looks correct

Did you try this between 2 android devices?

**Comment by chowbene1986** [comment]
No I did not try between 2 android devices. I have always tried b/w virtual device and xmpp client . I will try it and update.

**Comment by chowbene1986** [comment]
Hello,

I tested the following-
1. Between two android devices. - WORKED 
2. Between two virtual devices on Geny Motion - WORKED
3. Between Android Device and XMPP Client (Pidgin) - DID NOT WORK
4. Between Virtual Device and XMPP Client - DID NOT WORK.

Not sure why 3 & 4 did not work. However my requirement was #1 and #2  , glad it worked.
Thanks for the advise.

**Comment by chowbene1986** [comment]
One more Question-

Virtual Device(Genymotion) to Android Device did not work ? Can you possibly help me with this as it will help my testing.

**Comment by soulfly** [comment]
Fixed an issue with Whitespace characters

so now it works between Android SDK and desktop clients

This is done in development branch
https://github.com/QuickBlox/quickblox-android-sdk/tree/development

will be in our next release

**Comment by chowbene1986** [comment]
Thanks a lot for the fix !!

**Comment by guffyWave** [comment]
Even I am facing the same issue.But you may be interested in the following listener 

        QBMessageStatusListener   messageStatusListener = new QBMessageStatusListener() {
            @Override
            public void processMessageDelivered(final String messageId, String dialogId, Integer userId) {
                Log.d(TAG, "processMessageDelivered: Message DELIVERED : message ID " + messageId);
            }

            @Override
            public void processMessageRead(final String messageId, String dialogId, Integer userId) {
                Log.d(TAG, "processMessageRead: Message READ : message ID " + messageId);
            }
        };
        messageStatusesManager.addMessageStatusListener(messageStatusListener);

Please also check  mesage sent status by
        
          try{
                //blah blah
                 yourchatservice.sendMessage(chatMessage);
          } catch (XMPPException e) {
            Log.e(TAG, "Failed to send a message", e);
          } catch (SmackException sme) {
              Log.e(TAG, "Failed to send a message", sme);
           } catch (Exception e) {
              Log.e(TAG, "Failed to send a message", e);
          }


My objective was resolved by above as I do have SENT,DELIVERED and READ status.

**Comment by turkovsky** [comment]
I have the similar problem
fun observeIncomingMessages(dialog: QBChatDialog? = null): Flowable<ObservableMessage> {
        return Flowable.create({ emitter ->
            val listener = object : QBChatDialogMessageListener {
                override fun processMessage(dialogId: String, message: QBChatMessage, senderId: Int) {
                    emitter.onNext(Triple(dialogId, message, senderId))
                    toLog("processMessage ${message.body} -> ${message.id}")
                }

                override fun processError(dialogId: String, error: QBChatException?, message: QBChatMessage, senderId: Int) {
                    emitter.onError(error ?: UnknownException())
                }
            }
            val action: Action =
                    if (dialog == null) {
                        chatService.incomingMessagesManager.addDialogMessageListener(listener)
                        Action { chatService.incomingMessagesManager.removeDialogMessageListrener(listener) }
                    } else {
                        dialog.addMessageListener(listener)
                        Action { dialog.removeMessageListrener(listener) }
                    }
            emitter.setDisposable(Disposables.fromAction(action))
        }, BUFFER)
    }

Listener doesn't work when type of dialog is PRIVATE.
With GROUP works correctly
