### ISSUE TITLE
Unexpected signature in session api

### ISSUE THREAD

**Issue by sagarbhojaviya** [QuickBlox/quickblox-android-sdk#782]
I am using android sdk version 3.9.13

When i login first time in quickblox it give me success response of session api.
But getting Unexpected signature error after 1 day login with credential

Ay one can help me in this?

How can i manage this things?

=========================================================
=== REQUEST ==== 4e45a91d-6f31-4f88-b1d9-e76b1a07b661 ===
REQUEST
POST https://api.quickblox.com/session.json
HEADERS
QuickBlox-REST-API-Version=0.1.1
QB-SDK=Android 3.9.13
QB-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdHlwZSI6ImFwcGxpY2F0aW9uIiwiYXBwbGljYXRpb25faWQiOjkzNjAwLCJpYXQiOjE2NDY2NTE2NTQwMTYwMDl9.i7_VY07e6htqid50YrPXxZ5ePPhslbJd7dHqokrYWT--EbwKuJ9sGBVNaH3nxA0hV-V-_26tZg1ddetXWfuepQ
PARAMETERS
application_id=*****
auth_key=*****
nonce=-1569037671
timestamp=1646819225
mailto:user[email]=[test1@yopmail.com](mailto:test1@yopmail.com)
mailto:user[login]=test1@yopmail.com1
user[password]=quickblox
signature=4384d66f3a5eda5be544a2d661f33cb226f969e9
INLINE
POST [https://api.quickblox.com/session.json?application_id=****&auth_key=*****&nonce=-1569037671&timestamp=1646819225&user[email]=test1%40yopmail.com&user[login]=test1%40yopmail.com1&user[password]=quickblox&signature=4384d66f3a5eda5be544a2d661f33cb226f969e9](https://api.quickblox.com/session.json?application_id=****&auth_key=*****&nonce=-1569037671&timestamp=1646819225&user%5Bemail%5D=test1%40yopmail.com&user%5Blogin%5D=test1%40yopmail.com1&user%5Bpassword%5D=quickblox&signature=4384d66f3a5eda5be544a2d661f33cb226f969e9)
2022-03-09 15:17:06.537 12568-16052/com.justice D/QBASDK: *********************************************************
** RESPONSE ** 4e45a91d-6f31-4f88-b1d9-e76b1a07b661 ***
STATUS : 422
HEADERS
x-request-id=FtqtXICN6m2OUEwz5Z0k
X-Android-Selected-Protocol=http/1.1
Server=nginx
Connection=close
X-Android-Response-Source=NETWORK 422
X-Android-Sent-Millis=1646819226228
cache-control=max-age=0, private, must-revalidate
Content-Length=44
X-Android-Received-Millis=1646819226535
Date=Wed, 09 Mar 2022 09:47:06 GMT
Content-Type=application/json; charset=utf-8
BODY
'{"errors":{"base":["Unexpected signature"]}}'`

**Comment by QB-nikolay-zolotarov** [comment]
Hello,

This is Nikolay from QuickBlox support.

The issue is that you use email, login, and password to log in to the application.

Please use login and password or email and password.

**Comment by sagarbhojaviya** [comment]
above changes working fine
