### ISSUE TITLE
Audio/Video call connection issue (Not calling onReceiveNewSession method when call coming)

### ISSUE THREAD

**Issue by sagarbhojaviya** [QuickBlox/quickblox-android-sdk#784]
I've integrated qb android sdk 3.9.14 to my project. I get issue with call connection.

**Environment details**
(Operating system, browser information, SDK version)
Operating System: Android
SDK Version: 3.9.14

**Did this work before?**
Yes, December 2021

**Expected behavior**
When one qb client calls another, the other doesn't get call

**Actual behavior**
When one qb client calls another, the other should receive a video call

**Logs**
[log.txt](https://github.com/QuickBlox/quickblox-android-sdk/files/8380125/log.txt)

**Steps to reproduce the behavior**
Call with one client to another. The other client is logged into qb. He sometimes doesn't get call because QBRTCClientSessionCallbacksImpl -> onReceiveNewSession callback doesn't get called.

**Any others comments?**
Usually the call connection works well. But in some unexpected cases, the other client doesn't get call because QBRTCClientSessionCallbacksImpl -> onReceiveNewSession callback doesn't get called.

I have attached also logs of client, who didn't receive call and client who made call. Please note the logs are taken after each other on the same device.

**Comment by QB-nikolay-zolotarov** [comment]
Hello @sagarbhojaviya 

This is Nikolay from QuickBlox support.

Please try reproducing the issue on our samples:
https://docs.quickblox.com/docs/code-samples#video-calling-samples

If it is not reproduced, you can compare the sample with your custom code to identify the issue.
