### ISSUE TITLE
Corner Radius in QBRTCSurfaceView

### ISSUE THREAD

**Issue by yash-m-hanj** [QuickBlox/quickblox-android-sdk#788]
hello i need to give radius in my QBRTCSurfaceView (local) but i won't be able to do that thing i tried with cardview but it is not working .. looking for help

**Comment by QB-nikolay-zolotarov** [comment]
@yash-m-hanj Hello, this is Nikolay from QuickBlox support.
We do not have any instructions on how to implement the described functionality.
The implementation of this UI view is up to the client-side.
Let's continue the conversation in the ticketing portal as you already opened a ticket.
