### ISSUE TITLE
Private chat Notification receiving  for all the users 

### ISSUE THREAD

**Issue by mathayan321** [QuickBlox/quickblox-android-sdk#796]
val userIds1 = StringifyArrayList<Int>()

        for (user in userIds1!!) {
            userIds1.add(opponentId)
        }

        val event = QBEvent()
        event.userIds = userIds1
        event.environment = QBEnvironment.DEVELOPMENT
        event.notificationType = QBNotificationType.PUSH
        event.pushType = QBPushType.GCM
        val customData = HashMap<String, Any>()
        customData["data.message"] = text.toString()
        customData["data.title"] = currentUser.fullName
        customData["data.notification_id"] = 11

        event.setMessage(customData)

        QBPushNotifications.createEvent(event).performAsync(object : QBEntityCallback<QBEvent> {
            override fun onSuccess(qbEvent: QBEvent?, bundle: Bundle?) {
                Log.e("QB_notification","send")
                Log.e("CustomerData", Gson().toJson(qbEvent))
            }
            override fun onError(e: QBResponseException?) {
                Log.e("PN_error", e?.message.toString())
            }
        })
        
        the above is the code i am using but notification receiving for all the user, please guide us to fix this issues

**Comment by mathayan321** [comment]
What is the issues Completed

**Comment by kirillTolmachev** [comment]
@mathayan321 
I have re-opened the issue.

@vdovbnya-qb 
Please check the code and write an answer.

**Comment by vdovbnya-qb** [comment]
@mathayan321 
You create a list and try to iterate over it but the list is empty

`val userIds1 = StringifyArrayList()

    for (user in userIds1!!) {
        userIds1.add(opponentId)
    }`
    
 Try to add  opponentId to the list without a loop
 
 `val userIds1 = StringifyArrayList()
  
    userIds1.add(opponentId)
  
    val event = QBEvent()
    event.userIds = userIds1
    event.environment = QBEnvironment.DEVELOPMENT
    event.notificationType = QBNotificationType.PUSH
    event.pushType = QBPushType.GCM
    val customData = HashMap<String, Any>()
    customData["data.message"] = text.toString()
    customData["data.title"] = currentUser.fullName
    customData["data.notification_id"] = 11

    event.setMessage(customData)

    QBPushNotifications.createEvent(event).performAsync(object : QBEntityCallback<QBEvent> {
        override fun onSuccess(qbEvent: QBEvent?, bundle: Bundle?) {
            Log.e("QB_notification","send")
            Log.e("CustomerData", Gson().toJson(qbEvent))
        }
        override fun onError(e: QBResponseException?) {
            Log.e("PN_error", e?.message.toString())
        }
    })`
