### ISSUE TITLE
Whats the dependency to be mentioned in build.gradle of my app for my app to reference Quickblox chat?

### ISSUE THREAD

**Issue by gayathri-nair03** [QuickBlox/quickblox-android-sdk#80]

**Comment by soulfly** [comment]
Look at this gradle file

https://github.com/QuickBlox/quickblox-android-sdk/blob/master/sample-chat/build.gradle

**Comment by gayathri-nair03** [comment]
What is this - 
compile files(rootProject.core_jar_path, rootProject.chat_jar_path)? What is the core_jar_path, chat_jar_path? New to Studio.

**Comment by soulfly** [comment]
Look at parent gradle file

https://github.com/QuickBlox/quickblox-android-sdk/blob/master/build.gradle
