### ISSUE TITLE
Cannot upload document files on Quickblox android

### ISSUE THREAD

**Issue by ravikumarneo** [QuickBlox/quickblox-android-sdk#805]
Connection failed. Please check your internet connection.

**Comment by sshaforenkoqb** [comment]
@ravikumarneo Please provide additional details.

**Comment by ravikumarneo** [comment]
using uploadFileTask method.
image and .mp4 files are being uploaded sucessfully, but .pdf, docs file uploading throw Error.

**Comment by ravikumarneo** [comment]
Error Message is:
 Connection failed, Please check your internet connection
 
 but this is not helping in guessing the issue.

**Comment by sshaforenkoqb** [comment]
Are you reproducing this issue using your own code or using the QuickBlox chat sample?

**Comment by quangnguyen-agilityio** [comment]
@sshaforenkoqb I have got the same problem. Uploading an image is successful but it's failed with a .pdf file. 
I am following the documentation (https://docs.quickblox.com/docs/android-content#upload-file) to implement upload files. There are no additional things.

**Comment by vdovbnya-qb** [comment]
Hi @ravikumarneo @quangnguyen-agilityio 
To investigate this issue, need to provide additional information:

1. The version of QuickBlox Android SDK you are using
2. The size of the file you are trying to upload
3. Provide logs of REST-requests for file upload.

Also, try to reproduce this issue on our chat samples:
https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-chat-kotlin
https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-chat-java
