### ISSUE TITLE
Push subscription

### ISSUE THREAD

**Issue by jeetbv** [QuickBlox/quickblox-android-sdk#808]
Hello There,
I have downloaded the sample code of the video calling SDK.

1. We have a starter plan 
2. Now, I have added all the required things. like app key, id, etc
3. Now, try to register with the email and display name, creating the user but the push token is not created in the quick box dashboard. 
So, my question is that at the time of login/register subscription push is created, and it is required for the calling? 
4. I test the application on two different phones. ( Samsung and one plus OS-12 and 13 )
    - Call connect on background, foreground 
    - Call not connect when the applicaiton is killed by the user.

**Comment by jeetbv** [comment]
Issue 2 :
1. "The call service is ready to call service is ready" this notification tray is not displayed in the native android project but when I try this with the flutter SDK it's showing. so if this tray no comes, "The call service is ready to call service is ready"

**Comment by sshaforenkoqb** [comment]
Hello @jeetbv,
have you configured Firebase project, API Key, and added it to the QuickBlox dashboard as described [here](https://docs.quickblox.com/docs/android-push-notifications#configure-firebase-project-and-api-key)? 

> I have downloaded the sample code of the video calling SDK.
Just to clarify, you have downloaded [simple sample](https://github.com/QuickBlox/quickblox-flutter-samples/tree/master/simple_sample) for flutter, right?

**Comment by jeetbv** [comment]
We are using this but some issue regarding the calls , so we are move into the separate native SDK code for the android as well the iOS.

for android we are using this SDK - https://github.com/QuickBlox/quickblox-android-sdk -

**Comment by sshaforenkoqb** [comment]
Ok, got it, so to configure Push notifications please go through [this](https://docs.quickblox.com/docs/android-push-notifications#configure-firebase-project-and-api-key) and [this](https://docs.quickblox.com/docs/android-push-notifications#add-firebase-to-your-project) documentation.
Subscription required to receive push notifications that will wake up the application if it in the background or killed state to receive a call.

**Comment by jeetbv** [comment]
But when I run the application and login/register it. it's not creating the push subscription in the quick box dashboard.

**Comment by sshaforenkoqb** [comment]
If you haven't added API key to the dashboard and haven't added Firebase to your project subscription won't be created.

**Comment by jeetbv** [comment]
We already added the API key.

**Comment by sshaforenkoqb** [comment]
And configured your application according to [this](https://docs.quickblox.com/docs/android-push-notifications#add-firebase-to-your-project) instruction?

**Comment by jeetbv** [comment]
Yes. we have followed the official document for the setup and integration.

**Comment by jeetbv** [comment]
After the login 
--------------------------------

E/MainActivity( 4357): Checking Permissions
E/MainActivity( 4357): Android Overlay Permission NOT Granted
V/OplusZoomWindowDecorViewHelper( 4357): setLastReportedMergedConfiguration mZoomDisplayHeight: 2400 getDecorView.263962605
D/SurfaceComposerClient( 4357): VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
D/App     ( 4357): Session Updated
I/Quality ( 4357): Skipped: false 4 cost 74.03001 refreshRate 0 processName com.human.quest.human_quest
D/App     ( 4357): ===SubscriptionCreated
I/flutter ( 4357): PAYLOADING:____
I/flutter ( 4357): connect_chat errorPlatformException(Client is already logged in, null, null, null)
I/flutter ( 4357): connect_chat
D/BaseClient.( 4357): Create QBRTCClient INSTANCE
D/BaseClient.( 4357): init Task Executor
D/BaseClient.LooperExecutor( 4357): Create looper executor on thread: 2 for QBRTCClient
D/BaseClient.LooperExecutor( 4357): Request Looper start. On QBRTCClient
D/BaseClient.LooperExecutor( 4357): Looper thread started.
D/BaseClient.LooperExecutor( 4357): Looper thread started on thread.1007
D/BaseClient.( 4357):  Added session CALLBACK listenercom.quickblox.quickblox_sdk.webrtc.WebRTCCallService$SessionEventListener@5de1a737



This log comes after i give the permission of the overlay. 
----------------------------------

-D/LoginService( 4357): ---------Service onCreate()
D/LoginService( 4357): ---------Service started
D/LoginService( 4357): ---------Service started after
D/LoginService( 4357): ---------Get USEr
E/SettingsUtil( 4357): answerTimeInterval = 60
E/SettingsUtil( 4357): disconnectTimeInterval = 10
E/SettingsUtil( 4357): dialingTimeInterval = 5
D/BaseClient.( 4357):  Added session CALLBACK WebRtcSessionManager@cebb5fe

**Comment by sshaforenkoqb** [comment]
Hello @jeetbv,
Let's move our conversation to the support portal https://help.quickblox.com(There is a link to submit a ticket) because we'll require you to share with us some sensitive information. 
1. Could you please clarify, are you using Android SDK in your flutter application with your own bridge?
2. Also could you please enable logs inside sdk(https://docs.quickblox.com/docs/android-setup#enable-logging) and share them with us:
```
QBSettings.getInstance().setLogLevel(LogLevel.DEBUG);
QBChatService.setDebugEnabled(true);
QBRTCConfig.setDebugEnabled(true);
```
