### ISSUE TITLE
Can't create handler inside thread that has not called looper prepare - this exception is thrown when loginToChat(user) method is called in my fragment

### ISSUE THREAD

**Issue by gayathri-nair03** [QuickBlox/quickblox-android-sdk#81]

**Comment by JoCodes** [comment]
Can you post the code block which causes the error?

**Comment by gayathri-nair03** [comment]
package com.locon.housing.chat;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Context;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.FragmentActivity;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.ListView;
import android.widget.ProgressBar;

import com.locon.housing.MainActivity;
import com.locon.housing.MainApplication;
import com.locon.housing.R;
import com.locon.housing.core.BaseFragment;
import com.quickblox.auth.QBAuth;
import com.quickblox.auth.model.QBSession;
import com.quickblox.chat.QBChatService;
import com.quickblox.chat.model.QBDialog;
import com.quickblox.chat.model.QBDialogType;
import com.quickblox.core.QBEntityCallbackImpl;
import com.quickblox.core.QBSettings;
import com.quickblox.core.request.QBPagedRequestBuilder;
import com.quickblox.core.request.QBRequestGetBuilder;
import com.quickblox.users.QBUsers;
import com.quickblox.users.model.QBUser;

import org.jivesoftware.smack.SmackException;

import java.util.ArrayList;
import java.util.List;

/**
 Created by gayathri_nair on 27/04/15.
 */
public class ChatLauncherFragment extends BaseFragment {

    //Updated-ones
    private static final String APP_ID = "22637";
    private static final String AUTH_KEY = "yp3q94wArvAYVus";
    private static final String AUTH_SECRET = "gVyhQJ8svFGP6pX";

    //Initial-ones
    //        private static final String APP_ID = "92";
    //        private static final String AUTH_KEY = "wJHdOcQSxXQGWx5";
    //        private static final String AUTH_SECRET = "BTFsj7Rtt27DAmT";

    private static final String USER_LOGIN = "igorquickblox";
    private static final String USER_PASSWORD = "igorquickblox";
    private static final int AUTO_PRESENCE_INTERVAL_IN_SECONDS = 30;
    private static final String EXTRA_DIALOG = "dialog";
    private static final String EXTRA_MODE = "mode";
    private FragmentActivity activityContext;
    private QBChatService chatService;
    private ListView dialogsListView;
    private ProgressBar progressBar;

    private static enum Mode {PRIVATE, GROUP}

    public static ChatLauncherFragment newInstance() {
        ChatLauncherFragment fragment = new ChatLauncherFragment();
        return fragment;
    }

    @Override public String getName() {
        return "ChatLauncherFragment";
    }

    @Override public void onClick(View v) {

    }

    @Override public void onAttach(Activity activity) {
        super.onAttach(activity);
        activityContext = (FragmentActivity) activity;
    }

    @Override public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container,
            @Nullable Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.dummy, null);
        dialogsListView = (ListView) rootView.findViewById(R.id.roomsList);
        progressBar = (ProgressBar) rootView.findViewById(R.id.progressBar);

        QBChatService.setDebugEnabled(true);
        QBSettings.getInstance().fastConfigInit(APP_ID, AUTH_KEY, AUTH_SECRET);
        if (!QBChatService.isInitialized()) {
            QBChatService.init(activityContext);
        }
        chatService = QBChatService.getInstance();

        final QBUser user = new QBUser();
        user.setLogin(USER_LOGIN);
        user.setPassword(USER_PASSWORD);

        QBAuth.createSession(user, new QBEntityCallbackImpl<QBSession>() {
            @Override
            public void onSuccess(QBSession session, Bundle args) {
                user.setId(session.getUserId());
                ((MainApplication) activityContext.getApplication()).setCurrentUser(user);

                // login to Chat
                loginToChat(user);
            }

            @Override
            public void onError(List<String> errors) {
                //                AlertDialog.Builder dialog = new AlertDialog.Builder(activityContext);
                //                dialog.setMessage("create session errors: " + errors).create().show();
            }
        });
        return rootView;
    }

    private void loginToChat(final QBUser user) {

        chatService.login(user, new QBEntityCallbackImpl() {
            @Override
            public void onSuccess() {

                // Start sending presences
                try {
                    chatService.startAutoSendPresence(AUTO_PRESENCE_INTERVAL_IN_SECONDS);
                } catch (SmackException.NotLoggedInException e) {
                    e.printStackTrace();
                }

                continueOnSuccess();

            }

            @Override
            public void onError(List errors) {
                AlertDialog.Builder dialog = new AlertDialog.Builder(activityContext);
                dialog.setMessage("chat login errors: " + errors).create().show();
            }
        });
    }

    private void continueOnSuccess() {
        QBRequestGetBuilder customObjectRequestBuilder = new QBRequestGetBuilder();
        customObjectRequestBuilder.setPagesLimit(100);

        QBChatService.getChatDialogs(null, customObjectRequestBuilder,
                                     new QBEntityCallbackImpl<ArrayList<QBDialog>>() {
                                         @Override
                                         public void onSuccess(final ArrayList<QBDialog> dialogs,
                                                 Bundle args) {

                                             // collect all occupants ids
                                             //
                                             List<Integer> usersIDs = new ArrayList<Integer>();
                                             for (QBDialog dialog : dialogs) {
                                                 usersIDs.addAll(dialog.getOccupants());
                                             }

                                             // Get all occupants info
                                             //
                                             QBPagedRequestBuilder requestBuilder = new QBPagedRequestBuilder();
                                             requestBuilder.setPage(1);
                                             requestBuilder.setPerPage(usersIDs.size());
                                             //
                                             QBUsers.getUsersByIDs(usersIDs, requestBuilder,
                                                                   new QBEntityCallbackImpl<ArrayList<QBUser>>() {
                                                                       @Override
                                                                       public void onSuccess(
                                                                               ArrayList<QBUser> users,
                                                                               Bundle params) {

                                                                           // Save users
                                                                           //
                                                                           ((MainApplication) activityContext
                                                                                   .getApplication())
                                                                                   .setDialogsUsers(
                                                                                           users);

                                                                           // build list view
                                                                           //
                                                                           buildListView(dialogs);
                                                                       }

                                                                       @Override
                                                                       public void onError(
                                                                               List<String> errors) {
                                                                           AlertDialog.Builder dialog = new AlertDialog.Builder(
                                                                                   activityContext);
                                                                           dialog.setMessage(
                                                                                   "get occupants errors: " +
                                                                                   errors).create()
                                                                                 .show();
                                                                       }

                                                                   });
                                         }

                                         @Override
                                         public void onError(List<String> errors) {
                                             AlertDialog.Builder dialog = new AlertDialog.Builder(
                                                     activityContext);
                                             dialog.setMessage("get dialogs errors: " + errors)
                                                   .create().show();
                                         }
                                     });
    }

    void buildListView(List<QBDialog> dialogs) {
        final DialogsAdapter adapter = new DialogsAdapter(dialogs, activityContext);
        dialogsListView.setAdapter(adapter);

        progressBar.setVisibility(View.GONE);

        // choose dialog
        dialogsListView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                QBDialog selectedDialog = (QBDialog) adapter.getItem(position);

                Bundle bundle = new Bundle();
                bundle.putSerializable(EXTRA_DIALOG, (QBDialog) adapter.getItem(position));

                // group
                if (selectedDialog.getType().equals(QBDialogType.GROUP)) {
                    bundle.putSerializable(EXTRA_MODE, Mode.GROUP);

                    // private
                } else {
                    bundle.putSerializable(EXTRA_MODE, Mode.PRIVATE);
                }

                // Open chat activity
                //
                start(activityContext, bundle);
            }
        });
    }

    private void start(Context context, Bundle bundle) {
        ((MainActivity) activityContext)
                .loadFragmentInDefaultLayout(ChatWindowFragment.newInstance());
    }

}

**Comment by gayathri-nair03** [comment]
In your chat code, you have started DialogsActivity from Splash activity, whereas in mine I have included that list view in my fragment's layout itself. The difference in both codes is yours is part of activity whereas mines part of a fragment. On debugging, I found that the code lands on the call to loginToChat(user) and then lands up in the onError() callback. The exception is the one i stated above - Can't create handler inside thread that has not called looper prepare . Please assist

**Comment by soulfly** [comment]
Method 
   chatService.login(user, new QBEntityCallbackImpl()

should be called on the main thread

If you are in a background thread then call sync method chatService.login(user)

**Comment by parthivikky** [comment]
I am facing this issue. Please help me to fix it.
