### ISSUE TITLE
Send Location and Contacts in Chat

### ISSUE THREAD

**Issue by AqeelAaqi** [QuickBlox/quickblox-android-sdk#816]
Hi All,
 I want to send locations and contacts in chat like WhatsApp how can I achieve this? also please share piece of code of this logic . 

Thanks in Advance

**Comment by vdovbnya-qb** [comment]
Hi @AqeelAaqi 
You can use custom objects to send locations and contacts in chat.
Find information on how to implement this in our documentation via the links:

https://docs.quickblox.com/docs/android-chat-messaging#send-message-with-extra-data
https://docs.quickblox.com/docs/android-custom-objects

**Comment by AqeelAaqi** [comment]
> Hi @AqeelAaqi You can use custom objects to send locations and contacts in chat. Find information on how to implement this in our documentation via the links:
> 
> https://docs.quickblox.com/docs/android-chat-messaging#send-message-with-extra-data https://docs.quickblox.com/docs/android-custom-objects

i want to show with different views can this is possible like if location is send in extra data then i wanna show a map image like whatsapp

**Comment by QB-maksym-pidhorbunskyi** [comment]
Hello @AqeelAaqi This is Maksym from QuickBlox support.
We don't have ready-to-use code snippet with UI elements that you can add to your apps, but you can achieve the required functionality using the SDK features from the links above.
So the implementation of the described features is up to the client side.
If you want us to add the features to your apps, we can offer our professional services at an addtional cost.
If you are interested, please let us know.

**Comment by AqeelAaqi** [comment]
> Hello @AqeelAaqi This is Maksym from QuickBlox support. We don't have ready-to-use code snippet with UI elements that you can add to your apps, but you can achieve the required functionality using the SDK features from the links above. So the implementation of the described features is up to the client side. If you want us to add the features to your apps, we can offer our professional services at an addtional cost. If you are interested, please let us know.

let me try 1st if am having trouble then i'll let you know.

thanks for your reply

**Comment by AqeelAaqi** [comment]
I've resolved both send location and contacts in chat myself, thanks
