### ISSUE TITLE
Dialog Name As my Contact Name

### ISSUE THREAD

**Issue by AqeelAaqi** [QuickBlox/quickblox-android-sdk#818]
Hi all,

I want my private dialogs name as a number saved in my contacts but I get the name of the user at the time of registering kindly help.

is there any solution or any help, please...

**Comment by vdovbnya-qb** [comment]
Hi @AqeelAaqi 

When creating a dialog, you can pass it a custom parameter with a number.
Here is the link to the documentation: https://docs.quickblox.com/docs/android-chat-dialogs#create-dialog-with-custom-parameters

If you have any further questions, please contact us again.
Thanks!

**Comment by vdovbnya-qb** [comment]
Hi @AqeelAaqi
You can add information about current users and your opponent to a custom parameter of dialog.
After that, get the dialog take custom parameters from it, and display the necessary information

You can also set a custom date for the user upon creation and receive the necessary information from him.
You can see more details here:
https://docs.quickblox.com/docs/android-users#create-user
https://docs.quickblox.com/reference/create-user
