### ISSUE TITLE
Could not download chat-message-adapter-2.0.aar

### ISSUE THREAD

**Issue by yogeshkaharmis** [QuickBlox/quickblox-android-sdk#819]
hello guys
my project work find before some day but today I open and run the project I got below error

Could not download chat-message-adapter-2.0.aar

searching many but I am not find any solution.
I am using below SDK

implementation 'com.quickblox:quickblox-android-sdk-videochat-webrtc:3.8.1'
implementation 'com.quickblox:quickblox-android-sdk-chat:3.9.11'
implementation "com.quickblox:quickblox-android-sdk-content:3.9.11"
implementation "com.quickblox:chat-message-adapter:2.0"
implementation "com.quickblox:quickblox-android-sdk-messages:3.9.11"

Please help me.
Thanks in advance

**Comment by kirillTolmachev** [comment]
Hello @yogeshkaharmis 
Unfortunately, the **message adapter** is a very old project and it was updated more than 6 years ago. We strongly don't recommend to use it. 
The **chat-message-adapter-2.0.aar** is still available. You can check it by the link.
https://github.com/QuickBlox/quickblox-android-sdk-releases/blob/3.9.11/com/quickblox/chat-message-adapter/2.0/chat-message-adapter-2.0.aar
Maybe the error message contains some other details.

**Comment by yogeshkaharmis** [comment]
@kirillTolmachev 
I am using documentation but SDK is not connect to project please give me sample project for chat SDK because in project chat SDK is not download and time out error showing.
