### ISSUE TITLE
Is there a way to retrieve a dialog by id?

### ISSUE THREAD

**Issue by gandalf14** [QuickBlox/quickblox-android-sdk#85]
I see that we can set a dialog id by using:
[dialog].setName([dialogId])

Is it possible to then retrieve a dialog by its id? I am not finding an API for that.
Please let me know. Thanks!

**Comment by soulfly** [comment]
Yes, there is a way

http://quickblox.com/developers/Android_XMPP_Chat_Sample#Filters

use '_id' filter

**Comment by gandalf14** [comment]
That works. Thanks!
