### ISSUE TITLE
WebRTC rejectCall method bug

### ISSUE THREAD

**Issue by enginegl** [QuickBlox/quickblox-android-sdk#87]
Parameter 'userInfo' is never used.

    public void rejectCall(Map<String, String> userInfo)
      {
        if (this.state.ordinal() > QBRTCSessionState.QB_RTC_SESSION_ACTIVE.ordinal()) {
          return;
        }
        stopCallTimer();
    
        this.state = QBRTCSessionState.QB_RTC_SESSION_REJECTED;
        for (Integer opponentID : this.channels.keySet())
        {
          QBChatMessage rejectCallMessage = this.signalChannel.sendRejectCallToOpponent(getCallerID(), this.sessionDescription.getUserInfo());
          QBRTCClient.getInstance().sendMessage(rejectCallMessage, opponentID);
          ((QBPeerChannel)this.channels.get(opponentID)).reject();
        }
      }

**Comment by soulfly** [comment]
This is fixed in development branch
https://github.com/QuickBlox/quickblox-android-sdk/tree/development

will be released to master soom
