### ISSUE TITLE
Not able to receive incoming messages

### ISSUE THREAD

**Issue by vivdub** [QuickBlox/quickblox-android-sdk#89]
I have integrated private chat, its able to send message, but I am not able to receive messages, the listener doesn't get called.
I am using pidgin from other end to send the message.
Here is the code.

//===================================================
public class ChatFragment extends Fragment{

    private EditText msg;
    private Button send;
    private int oppId = -1;
    private QBMessageListener<QBPrivateChat> privateChatMessageListener;
    private QBPrivateChatManagerListener privateChatManagerListener;
    private QBPrivateChatManager privateChatManager;

    //===============================
    public void setOpponentId(int id){oppId=id;}

    //===============================
    @Override
    public View onCreateView(LayoutInflater inf, ViewGroup vg, Bundle b){
        View v = inf.inflate(R.layout.chat,null);
        v.setLayoutParams(new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
        msg = (EditText)v.findViewById(R.id.msg);
        send = (Button)v.findViewById(R.id.send);
        createChat();
        send.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if(!msg.getText().toString().trim().equals(""))
                    sendMessage(msg.getText().toString().trim());
            }
        });
        return v;
    }

    //===============================
    private void createChat(){
        if(oppId!=-1){
            privateChatManager = QBChatService.getInstance().getPrivateChatManager();
            privateChatMessageListener = new QBMessageListener<QBPrivateChat>() {
                @Override
                public void processMessage(QBPrivateChat privateChat, final QBChatMessage chatMessage) {

                }

                @Override
                public void processError(QBPrivateChat privateChat, QBChatException error, QBChatMessage originMessage){

                }

                @Override
                public void processMessageDelivered(QBPrivateChat privateChat, String messageID){

                }

                @Override
                public void processMessageRead(QBPrivateChat privateChat, String messageID){

                }
            };

            privateChatManagerListener = new QBPrivateChatManagerListener() {
                @Override
                public void chatCreated(final QBPrivateChat privateChat, final boolean createdLocally) {
                    if(!createdLocally){
                        privateChat.addMessageListener(privateChatMessageListener);
                    }
                }
            };
            QBChatService.getInstance().getPrivateChatManager().addPrivateChatManagerListener(privateChatManagerListener);
        }
    }

    //===============================
    private void sendMessage(String cmsg){
        if(oppId==-1) return;
        try {
            QBChatMessage chatMessage = new QBChatMessage();
            chatMessage.setBody(cmsg);
            chatMessage.setProperty("save_to_history", "1"); // Save a message to history

            QBPrivateChat privateChat = privateChatManager.getChat(oppId);
            if (privateChat == null) {
                privateChat = privateChatManager.createChat(oppId, privateChatMessageListener);
            }
            privateChat.sendMessage(chatMessage);
            msg.setText("");
        } catch (XMPPException e) {
            e.printStackTrace();
        } catch (SmackException.NotConnectedException e) {
            e.printStackTrace();
        }
    }
}

**Comment by soulfly** [comment]
The issue is probably with that you use pidgin client

can you post a log from Android where you receive a message from pidgin

**Comment by vivdub** [comment]
Yes the issue was this only, confirmed here:
https://github.com/QuickBlox/quickblox-android-sdk/issues/77

**Comment by hishamMuneer** [comment]
@soulfly Receiving the same error while chatting 1-1 with android devices. Specially 1 user is not able to send the messages, rest of the users can send me the message easily. Getting ResourceBindingNotOfferedException at the time of signing in. 

Steps to recreate this issue is like this: While signing in from user 1 if user 2 keeps sending some messages to me continously, I get ResourceBindingNotOfferedException and next time I login, I can't receive any message from user 2.
