### ISSUE TITLE
how to use Quickblox android SDK with android studio.

### ISSUE THREAD

**Issue by vinaytumbemane** [QuickBlox/quickblox-android-sdk#92]
How to Integrate quickblox android sdk with android studio. i want to Establish Video communication using WebRTC. 
Is it library file?

**Comment by soulfly** [comment]
Just Import project to android studio, or open build.gradle file from Android Studio

**Comment by vinaytumbemane** [comment]
Error:SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

Above error I am getting.

I copied "quickblox-android-sdk-master" extracted file to my Android work space. 
I opened Android studio.
menu > Import project > selected path to sample-videochat-webrtc-new > ok
I built the app with above error. says Gradle project sync failed. because of above error.

Can you guide me on this issue? Help will be appreciated.

**Comment by vinaytumbemane** [comment]
Should I import whole quickblox-android-sdk-master file?

**Comment by soulfly** [comment]
You have to update a file local.properties

and change ANDROID_HOME. Just set the location of Android SDK on your computer

**Comment by vinaytumbemane** [comment]
I settings I am unable to select use default gradle wrapper(not configured for current project)

**Comment by vinaytumbemane** [comment]
I imported complete SDK file not just sample file and Sample-webrtc-android is working.

**Comment by luzzato** [comment]
Hi team,
Have you finished q-municate with the new version(..2.2.5 jar files)?
Now I am seeing the q-municate made with new version(in your branch), but the project is broken.
What's wrong here?

**Comment by soulfly** [comment]
Yes, it's on master branch

https://github.com/QuickBlox/q-municate-android

**Comment by coolsky0725** [comment]
Oh, I have same problem. How to fix this bug ? Please let me know about that

**Comment by purushottam34** [comment]
I need help to import quick blox in ur application can any one give the complete step to import the sample chat....... 
Thank u

**Comment by Fideas** [comment]
@purushottam34 instead of importing just the chat sample import the whole project to Android Studio. The issue here is that in the build.gradle for the sample-chat module the compileSdkVersion and minSdkVersion are defined in terms of a variable that is part of the containing project. If you import just the chat sample the containing project, and thus the aforementioned variable, won't exist and you will see the error that has been commented here. 
Another solution is to provide your own values for those properties.

**Comment by rohitroyrr8** [comment]
i want to connect to the quickblox , but getting error while adding dependency

**Comment by tatanka987** [comment]
@rohitroyrr8 what error do you get? In your case you have to connect only chat dependency 
compile 'com.quickblox:quickblox-android-sdk-chat:3.3.0'
other transitive dependencies will be connected automatically

**Comment by ritusharma4** [comment]
How to add quickblox android sdk in my existing project?

**Comment by Bhagat1** [comment]
how to integrate video calling sdk in our app without all skd integration in android studio

**Comment by tatanka987** [comment]
@Bhagat1 your question not related with current issue, please create new issue with your problem and explain what do you mean "without all skd integration"
