### ISSUE TITLE
Quickblox Login

### ISSUE THREAD

**Issue by joyalReji** [QuickBlox/quickblox-android-sdk#94]
When trying to login in Quickblox  , in certain networks it gets connected soon but in some cases it doesn’t get connected at all. Is this a network issue or is there any issues related to proxy??

Showing Log as : Connecting to chat.....

**Comment by soulfly** [comment]
Do you have kind of proxy settings there?

**Comment by joyalReji** [comment]
Hi,
 Really I am not aware of it. Did the quickblox is trying to connect with
any port number? May it stuck with our settings(firewall setting).

**Comment by joyalReji** [comment]
Chattings application like whatsapp, hike, snapchat etc are working properly in our wifi network, If i tried with the sample app for the Quickblox one to one chat application from github and run in our network it showing Error like: Please check your internet connection (Alert will pop up), but other applications are working fine.

I

**Comment by soulfly** [comment]
Other REST API work ok?

it's just Chat issue?

**Comment by joyalReji** [comment]
So how can I resolve this issue. I need to connect quickblox in all
networks like other chat application

**Comment by soulfly** [comment]
Do other modules work?

Users, Content for example

**Comment by joyalReji** [comment]
Here Iam stuck in login itself?? They how can it  is possible to try users,
content  etc..  Issue is only happening in some networks, and remaning all
functionalities of chat works for me..

**Comment by soulfly** [comment]
Can you post here which 'login code' doesn;t work

**Comment by joyalReji** [comment]
Yeah, The code which which i tried to login Quickblox

user = new QBUser();
user.setLogin(SystemUtils.USER_LOGIN);
user.setPassword(SystemUtils.USER_PASSWORD);

        QBAuth.createSession(user, new QBEntityCallbackImpl<QBSession>() {
            @Override
            public void onSuccess(QBSession session, Bundle args) {

                user.setId(session.getUserId());
             
                chatService.login(user, new QBEntityCallbackImpl() {
                    @Override
                    public void onSuccess() {

                        // Start sending presences
                       
                        try {
                            chatService.startAutoSendPresence(AUTO_PRESENCE_INTERVAL_IN_SECONDS);
                        } catch (SmackException.NotLoggedInException e) {
                            e.printStackTrace();
                        }
                       
       			
                    }

                    @Override
                    public void onError(List errors) {
                    	
                    	Log.e("Quickblox login error", "Error:"+errors);              	
                    
                    	
            }

            @Override
            public void onError(List<String> errors) {
            	
            	Log.e("createSession Error ","Error"+errors);
            	
            	
        });


Here, createSession got Sucess and try to  chatService.login().. Here it takes to much time and getting error as " Connection failed. Please check your internet connection " in onError().

I checked the internet connection, that is there and other app is also working fine.

**Comment by soulfly** [comment]
Thanks you

can you also post log from start to error

**Comment by joyalReji** [comment]
06-22 17:41:10.441: D/QBASDK(28428): =========================================================
06-22 17:41:10.441: D/QBASDK(28428): === REQUEST ==== 174d03cf-b2b6-4a71-aef9-2d87cd7c1891 ===
06-22 17:41:10.441: D/QBASDK(28428): REQUEST
06-22 17:41:10.441: D/QBASDK(28428):     POST https://api.quickblox.com/session.json
06-22 17:41:10.441: D/QBASDK(28428): HEADERS
06-22 17:41:10.441: D/QBASDK(28428):     QuickBlox-REST-API-Version=0.1.1
06-22 17:41:10.441: D/QBASDK(28428):     
QB-SDK=Android 2.2.4
06-22 17:41:10.441: D/QBASDK(28428): PARAMETERS
06-22 17:41:10.441: D/QBASDK(28428):     application_id=23119
06-22 17:41:10.441: D/QBASDK(28428):     auth_key=PgYNyVxGKQdKWVj
06-22 17:41:10.441: D/QBASDK(28428):     nonce=66786529
06-22 17:41:10.441: D/QBASDK(28428):     timestamp=1434975070
06-22 17:41:10.441: D/QBASDK(28428):     user[login]=app_196
06-22 17:41:10.441: D/QBASDK(28428):     user[password]=app_196123
06-22 17:41:10.441: D/QBASDK(28428):     signature=233215b3fc9d2fe613fe54dcbe523255056b031e
06-22 17:41:10.441: D/QBASDK(28428): INLINE
06-22 17:41:10.441: D/QBASDK(28428):     POST https://api.quickblox.com/session.json?application_id=23119&auth_key=PgYNyVxGKQdKWVj&nonce=66786529&timestamp=1434975070&user[login]=app_196&user[password]=app_196123&signature=233215b3fc9d2fe613fe54dcbe523255056b031e
06-22 17:41:12.542: D/QBASDK(28428): *********************************************************
06-22 17:41:12.542: D/QBASDK(28428): *** RESPONSE *** 174d03cf-b2b6-4a71-aef9-2d87cd7c1891 ***
06-22 17:41:12.542: D/QBASDK(28428): STATUS : 201 
06-22 17:41:12.542: D/QBASDK(28428): HEADERS
06-22 17:41:12.542: D/QBASDK(28428):     Access-Control-Allow-Origin=*
06-22 17:41:12.542: D/QBASDK(28428):     Cache-Control=max-age=0, private, must-revalidate
06-22 17:41:12.542: D/QBASDK(28428):     Connection=keep-alive
06-22 17:41:12.542: D/QBASDK(28428):     Content-Type=application/json; charset=utf-8
06-22 17:41:12.542: D/QBASDK(28428):     Date=Mon, 22 Jun 2015 12:11:12 GMT
06-22 17:41:12.542: D/QBASDK(28428):     ETag="953581dcbe64ba889a35ce0900ea0039"
06-22 17:41:12.542: D/QBASDK(28428):     QB-Token-ExpirationDate=2015-06-22 14:11:12 UTC
06-22 17:41:12.542: D/QBASDK(28428):     QuickBlox-REST-API-Version=0.1.1
06-22 17:41:12.542: D/QBASDK(28428):     Server=nginx/1.0.15
06-22 17:41:12.542: D/QBASDK(28428):     Status=201 Created
06-22 17:41:12.542: D/QBASDK(28428):     Transfer-Encoding=chunked
06-22 17:41:12.542: D/QBASDK(28428):     X-Rack-Cache=invalidate, pass
06-22 17:41:12.542: D/QBASDK(28428):     X-Request-Id=efe67fa618f24f12f66cc301d417349e
06-22 17:41:12.542: D/QBASDK(28428):     X-Runtime=0.040565
06-22 17:41:12.542: D/QBASDK(28428):     X-UA-Compatible=IE=Edge,chrome=1
06-22 17:41:12.542: D/QBASDK(28428): BODY
06-22 17:41:12.542: D/QBASDK(28428):     '{"session":{"_id":"5587fb60535c12de3b0014f9","application_id":23119,"created_at":"2015-06-22T12:11:12Z","device_id":0,"nonce":66786529,"token":"b92e87375604e2b1b1694dad4bf93d6912cb39ae","ts":1434975070,"updated_at":"2015-06-22T12:11:12Z","user_id":3651518,"id":43637}}'
06-22 17:41:12.590: E/createSession(28428): sucess
06-22 17:41:12.592: D/QBASDK(28428): Connecting to chat..
06-22 17:42:15.814: E/QuickBLOX LOGIN(28428): ERROR:[Connection failed. Please check your internet connection.]

**Comment by soulfly** [comment]
Can you try to do 
  
   telnet chat.quickblox.com 5222

and also 

    traceroute chat.quickblox.com

from terminal on you PC

**Comment by joyalReji** [comment]
I tried and i got like this


    # telnet chat.quickblox.com 5222
    Trying 54.243.229.130...

      You have new mail in /var/spool/mail/root
      [root@station254 wkhtml]# traceroute chat.quickblox.com
         traceroute to chat.quickblox.com (54.243.229.130), 30 hops max, 40 byte packets
       1  192.168.1.3 (192.168.1.3)  0.217 ms  0.205 ms  0.173 ms
 2  * * *
 3  * * *
 4  * * *
 5  * * *
 6  * * *
 7  * * *
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
You have new mail in /var/spool/mail/root

**Comment by soulfly** [comment]
So this is something with your local network (home/office network or provider)

Maybe port 5222  is closed on your router, you should check this first  

This is what I got

     $ telnet chat.quickblox.com 5222
     Trying 54.243.229.130...
     Connected to chat.quickblox.com.
     Escape character is '^]'.

**Comment by joyalReji** [comment]
How  can i manage this issue. May be the app users may try to connect in open WiFi in Restaurants,Hotels, Libraries,Offices etc.. If the port 5222 is not opened in network means, quickblox will not connect.  How this can be manage in all networks.

**Comment by joyalReji** [comment]
IS there any solution to get the quickblox in all networks??

**Comment by guimellon** [comment]
Did you guys figure out hor to solve this problems?

**Comment by joyalReji** [comment]
Yes... just open the port which the quickblox needed..


Happy Coding...

Thank you,

**Comment by himangipatel** [comment]
hello,

I am facing the same issue

com.quickblox.core.exception.QBResponseException: Connection failed. Please check your internet connection.

when trying to sign in user to quickblox. It is almost working fine with most of all devices but issue is still arrive in some devices.

is there any solution?
