### ISSUE TITLE
Audio call crash on eclipse ide.

### ISSUE THREAD

**Issue by dimitrireef** [QuickBlox/quickblox-android-sdk#97]
Audio call crash before call activity started.  

06-24 10:28:11.336: D/RTCClient(30532): Create new session
06-24 10:28:11.336: D/dalvikvm(30532): Trying to load lib /data/app-lib/packagename-3/libjingle_peerconnection_so.so 0x42a22eb0
06-24 10:28:11.341: D/dalvikvm(30532): Added shared lib /data/app-lib/packagename-3/libjingle_peerconnection_so.so 0x42a22eb0
06-24 10:28:11.341: D/EglBase(30532): SDK version: 19
06-24 10:28:11.346: D/*WEBRTCN*(30532): SetRenderAndroidVM
06-24 10:28:11.346: E/rtc(30532): #
06-24 10:28:11.346: E/rtc(30532): # Fatal error in ../../talk/app/webrtc/java/jni/jni_helpers.cc, line 267
06-24 10:28:11.346: E/rtc(30532): # Check failed: ret
06-24 10:28:11.346: E/rtc(30532): # 
06-24 10:28:11.346: E/rtc(30532): #
06-24 10:28:11.346: D/dalvikvm(30532): [SWE] ### S.LSI JIT optimization list BEGIN ###
06-24 10:28:11.346: D/dalvikvm(30532): [SWE] ### S.LSI JIT optimization list END ###
06-24 10:28:11.346: A/libc(30532): Fatal signal 6 (SIGABRT) at 0x00007744 (code=-6), thread 30532 (packagename)

**Comment by BogatovEvgeniy** [comment]
Looks like you use old jar file of quickblox chat module. Try to use latest jars from updated samples project (https://github.com/QuickBlox/quickblox-android-sdk/tree/master/jars)

**Comment by dimitrireef** [comment]
Project already use latest 2.25 jar i migrated from 2.0 to 2.25, all the jars are updated jars. Still facing this issue.

**Comment by dimitrireef** [comment]
@BogatovEvgeniy  my mistake.  The create session method used in application was old.  The latest jar recognise the create session method but video call webRTC sample don't.  By implementing new session style method, audio call works successfully. Thank you. I close the issue.
