### ISSUE TITLE
Android Video WebRTC

### ISSUE THREAD

**Issue by sms81** [QuickBlox/quickblox-android-sdk#98]
hi, when i added the sample video webrtc and just changed the app parameters in the costs.java file
I ran the app and the first layout appears normaly but when choosing any user the app gives me error when login check test users login and password. So I tried modifying the user lists in Dataholder.java and adding me and a user that I added in the users tab in my app and then when choosing a user a load opponents appear but it keeps loading forever.any solution?

**Comment by mnesarco** [comment]
Hi, your users must have the tag "webrtcusers". You can add tags to users in Quickblox admin panel.
